### ISSUE TITLE
Flutter not recognizing cocoapods inside Android Studio 4.1

### ISSUE THREAD

**Issue by taracell** [flutter/flutter-intellij#4981] opened 2020-10-19 17:34 UTC
I cannot run any flutter development application inside Android Studio 4.1 stable on iOS using flutter and am not sure if it is an issue with Android Studio or the Flutter plugin.  I am using macOS Catalina Version 10.15.7

I am able to build app within Xcode 12.0.1. 

When I try it states: 
```
Launching lib/main.dart on iPhone 11 Pro in debug mode...
Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
To install:
  sudo gem install cocoapods

CocoaPods not installed or not in valid state.
Error launching application on iPhone 11 Pro.
```
With that said I re-installed cocoapods using the following commands:
```
sudo gem uninstall cocoapods
sudo gem install cocoapods -v 1.7.5
pod setup
sudo gem install cocoapods 
```
//to get latest version 1.9.3

The cocoapods were still not recognized after these commands.  
I uninstalled and re-installed Android Studio.  
This did not change the outcome.  
I also tried the --pre version of cocoapods. No change.  

ran these commands:
```
sudo gem update
sudo gem clean cocoapods

pod --version 
1.10.0.rc.1

sudo gem --version 
3.0.3

gem list cocoapods      

*** LOCAL GEMS ***

cocoapods (1.10.0.rc.1)
cocoapods-core (1.10.0.rc.1, 1.9.3, 1.7.5)
cocoapods-deintegrate (1.0.4)
cocoapods-downloader (1.4.0)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.1.0)
cocoapods-trunk (1.5.0)
cocoapods-try (1.2.0)
```

Android studio 4.1 has known issue of not recognizing Dart and Flutter plugins as noted: https://github.com/flutter/flutter/issues/67986

Running flutter doctor using button inside Android Studio on screen within the pubspec.yaml file produces the following:
```
/Users/tara/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-US)
    • Flutter version 1.22.2 at /Users/tara/flutter
    • Framework revision 84f3d28555 (4 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tara/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin installed
    • Dart plugin version 202.7319.5

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554                        • android-x86 • Android 11 (API 30) (emulator)
    • iPhone 11 Pro (mobile)      • B0415B3C-2E75-4FA5-85E4-425082E20A87 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    ! Error: Tara’s iPhone is not connected. Xcode will continue when Tara’s iPhone is connected. (code -13)

! Doctor found issues in 2 categories.
Process finished with exit code 0
```
Running flutter doctor from terminal outside Android Studio produces the following: 
```
Taras-Mac:~ tara$ flutter doctor -v

[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-US)
    • Flutter version 1.22.2 at /Users/tara/flutter
    • Framework revision 84f3d28555 (4 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tara/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin installed
    • Dart plugin version 202.7319.5

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554                        • android-x86 • Android 11 (API 30) (emulator)
    • iPhone 11 Pro (mobile)      • B0415B3C-2E75-4FA5-85E4-425082E20A87 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    ! Error: Tara’s iPhone is not connected. Xcode will continue when Tara’s iPhone is connected. (code -13)
```

**Comment by stevemessick** [comment] 2020-10-20 16:52
@devoncarew @helin24 @jacob314 
Could someone who has Xcode 12 take a look at this one? I can't install 12 yet.

**Comment by helin24** [comment] 2020-10-20 19:52
I can't replicate this problem with Android Studio 4.1, although it seems I have XCode 12.0 (not sure if that's likely to cause a difference).

I do see a few issues in flutter about cocoapods not being detected from IDEs, e.g. https://github.com/flutter/flutter/issues/57433. One suggestion is this could be a PATH issue, so perhaps @taracell could try these steps and report back:
1. Does this fix work? https://github.com/flutter/flutter/issues/14630#issuecomment-448886939
2. What are the result of `echo $PATH` inside Android Studio's terminal and outside?

**Comment by taracell** [comment] 2020-10-20 20:56
Hello I ran this within Android Studio Terminal with the same results.
```
tara@Taras-Mac app % sudo gem install cocoapods -n /usr/local/bin
Password:
Fetching cocoapods-core-1.10.0.gem
Fetching cocoapods-1.10.0.gem
Successfully installed cocoapods-core-1.10.0
Successfully installed cocoapods-1.10.0
Parsing documentation for cocoapods-core-1.10.0
Installing ri documentation for cocoapods-core-1.10.0
Parsing documentation for cocoapods-1.10.0
Installing ri documentation for cocoapods-1.10.0
Done installing documentation for cocoapods-core, cocoapods after 4 seconds
2 gems installed
tara@Taras-Mac app % echo $PATH
/usr/local/opt/openjdk/bin:/Users/tara/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Apple/usr/bin:/Users/tara/flutter/bin
tara@Taras-Mac whats_the_dish % gem list cocoapods                          

*** LOCAL GEMS ***

cocoapods (1.10.0, 1.10.0.rc.1)
cocoapods-core (1.10.0, 1.10.0.rc.1, 1.9.3, 1.7.5)
cocoapods-deintegrate (1.0.4)
cocoapods-downloader (1.4.0)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.1.0)
cocoapods-trunk (1.5.0)
cocoapods-try (1.2.0)
tara@Taras-Mac app % sudo gem --version                          
3.0.3
tara@Taras-Mac app % pod --version                          
1.10.0
tara@Taras-Mac app % sudo gem clean cocoapods               
Cleaning up installed gems...
Attempting to uninstall cocoapods-1.10.0.rc.1
Successfully uninstalled cocoapods-1.10.0.rc.1
Clean up complete
tara@Taras-Mac app % gem list cocoapods      

*** LOCAL GEMS ***

cocoapods (1.10.0)
cocoapods-core (1.10.0, 1.10.0.rc.1, 1.9.3, 1.7.5)
cocoapods-deintegrate (1.0.4)
cocoapods-downloader (1.4.0)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.1.0)
cocoapods-trunk (1.5.0)
cocoapods-try (1.2.0)
tara@Taras-Mac app % pod setup
Setup completed
tara@Taras-Mac app % echo $PATH                                  
/usr/local/opt/openjdk/bin:/Users/tara/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Apple/usr/bin:/Users/tara/flutter/bin
tara@Taras-Mac whats_the_dish % 
```
Next: Pressed invalidate caches/restart

Goto Pubspec.yaml and pressed flutter doctor within Android studio presents
```
/Users/tara/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-US)
    • Flutter version 1.22.2 at /Users/tara/flutter
    • Framework revision 84f3d28555 (5 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tara/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin installed
    • Dart plugin version 202.7319.5

[!] Connected device
    ! Error: Tara’s iPhone is not connected. Xcode will continue when Tara’s iPhone is connected. (code -13)

! Doctor found issues in 3 categories.
Process finished with exit code 0
```
Outside Android Studio Terminal provides: 
```
tara@Taras-Mac ~ % flutter doctor -v
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-US)
    • Flutter version 1.22.2 at /Users/tara/flutter
    • Framework revision 84f3d28555 (5 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tara/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin installed
    • Dart plugin version 202.7319.5

[!] Connected device
    ! Error: Tara’s iPhone is busy: Waiting for Device. Xcode will continue when
      Tara’s iPhone is finished. (code -10)

! Doctor found issues in 2 categories.
tara@Taras-Mac ~ % echo $PATH
/usr/local/opt/openjdk/bin:/Users/tara/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Apple/usr/bin:/Users/tara/flutter/bin
```
Outside the Android Studio application flutter doctor is picking up the cocoapods I just installed within the Android Studio application, so it doesn't seem to have anything to do with the path.

**Comment by helin24** [comment] 2020-10-20 23:53
@taracell thanks for executing those steps, but now I have a few more:
- Does running `flutter doctor -v` in the Android Studio terminal give the same results for cocoapods as pressing the doctor button? (It probably will, but just in case)
- Run `which pod` in your Android Studio terminal and in your regular outside terminal

Basically I'm trying to understand if there are environment differences in/out of Android Studio. I'm not very familiar with how cocoapods is installed, so let me know if you have other information that may suggest environment differences.
- Are you using rvm? If so, are you on the same version of ruby in both places?
- You ran `pod --version` and `gem --version` in Android Studio, do you get the same results in the outside terminal?

**Comment by taracell** [comment] 2020-10-21 00:31
@helin24 
runs as prescribed in the steps:
Within Android Studio Terminal shows same results as outside terminal:
```
tara@Taras-Mac app % flutter doctor -v
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-US)
    • Flutter version 1.22.2 at /Users/tara/flutter
    • Framework revision 84f3d28555 (5 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tara/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

 
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin installed
    • Dart plugin version 202.7319.5

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)
    ! Error: Tara’s iPhone is not connected. Xcode will continue when Tara’s iPhone is connected. (code -13)

! Doctor found issues in 1 category.
tara@Taras-Mac app % which pod
/usr/local/bin/pod
tara@Taras-Mac app % which gem
/usr/bin/gem
tara@Taras-Mac app % gem --version
3.0.3
tara@Taras-Mac app % ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

```
Yes ruby and gem versions are the same results as outside Android Studio Terminal:
```
tara@Taras-Mac ~ % ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
tara@Taras-Mac ~ % gem --version
3.0.3
```
However, When I use the run button inside Android terminal connected to an iOS simulator it gives me this: 
```
Launching lib/main.dart on iPhone 11 Pro in debug mode...
Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
To install:
  sudo gem install cocoapods

CocoaPods not installed or not in valid state.
Error launching application on iPhone 11 Pro.
```

**Comment by helin24** [comment] 2020-10-22 16:27
@taracell thanks for this additional info! It looks like there's a problem with the Android Studio terminal. Can you send a screenshot of how you access the terminal where you did not have rvm and rbenv? I'm not sure what you meant by 

> the run button inside Android terminal connected to an iOS simulator

and what that terminal looked like.

**Comment by taracell** [comment] 2020-10-23 01:25
This is how I am accessing terminal through Android Studio by pressing terminal at the bottom of the screen:
![image](https://user-images.githubusercontent.com/48975214/96945845-a7080200-1493-11eb-97f9-cddf57708e40.png)
After starting up an iOS simulator I press the run button at the top of the screen depicted by the green play arrow icon.  It also happens when pressing the debug icon.
![image](https://user-images.githubusercontent.com/48975214/96945955-ecc4ca80-1493-11eb-88dc-374bf7c9b0da.png)

**Comment by taracell** [comment] 2020-10-23 04:05
I am going to see if updating to canary improves this.

**Comment by helin24** [comment] 2020-10-23 16:46
@taracell Let me make sure I'm understanding correctly.

So you first checked `which rvm` and `which rbenv` in Android studio and saw that it matched what you get in your external terminal, i.e. within:
![Screen Shot 2020-10-23 at 9 36 15 AM](https://user-images.githubusercontent.com/6379305/97030152-3f919700-1513-11eb-927a-a68437911899.png)

Then you ran your app configuration with `--verbose` in additional arguments, and that's where you see cocoapods errors, i.e. here:
![Screen Shot 2020-10-23 at 9 44 32 AM](https://user-images.githubusercontent.com/6379305/97030936-643a3e80-1514-11eb-8a38-9e228d593e73.png)

And finally you change back to the terminal and check `which rvm` and `which rbenv` again, they are not found (back to the first image)

Is that accurate, or is the last terminal somewhere else?

**Comment by taracell** [comment] 2020-10-23 17:03
@helin24 I never had rvm or rbenv to begin with.  They are not on my computer.  In all places on my computer in and out of Android Studio terminal it says not found.  
In Studio 4.1:

```
tara@Taras-Mac app % which rvm
rvm not found
tara@Taras-Mac whats_the_dish % which rbenv
rbenv not found
```
Outside Studio:
```
tara@Taras-Mac ~ % which rvm
rvm not found
tara@Taras-Mac ~ % which rbenv
rbenv not found
```
The other assumptions are correct.  Yes, I only used Android Studio.

**Comment by helin24** [comment] 2020-10-23 17:39
Ah great, thanks for clarifying. I'll look into how the flutter doctor button differs more.

**Comment by taracell** [comment] 2020-12-13 00:08
I'm still having this issue with Android studio. Any fixes on the horizon?

**Comment by helin24** [comment] 2020-12-15 16:41
@taracell very sorry, I lost track of this issue. I realize I hadn't asked before, are you able to build your app with `fluter run` on the command line?

**Comment by taracell** [comment] 2020-12-16 23:37
@helin24 yes the app works and runs in iOS simulator through the command line from Android studio terminal.
```
tara@Taras-Mac whats_the_dish % flutter run

Launching lib/main.dart on iPhone 11 Pro in debug mode...
 
Running pod install...                                              6.2s
Running Xcode build...                                                  
[Firebase/Crashlytics] Version 4.6.2                             
 └─Compiling, linking and signing...                        89.3s
Xcode build done.                                           175.0s
[Firebase/Crashlytics] Version 4.6.2
Waiting for iPhone 11 Pro to report its views...                     4ms
Syncing files to device iPhone 11 Pro...                           560ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on iPhone 11 Pro is available at: http://127.0.0.1:61812/Lm4uvRDtbDg=/
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (os/kern) invalid argument
```

**Comment by helin24** [comment] 2020-12-21 23:52
@taracell our best guess is that there's something going on with your local settings somehow, outside of the plugin, but we're not sure how to debug. You may want to try using VS code instead, which has many of the same functions (https://flutter.dev/docs/development/tools/vs-code). If that also fails to run apps, there may be something else going on.

**Comment by hoonji** [comment] 2020-12-27 09:12
Opening Android Studio from the terminal worked for me: `open /Applications/Android\ Studio.app`

The issue is caused by PATH is not being set correctly when opening Android Studio from GUI - in particular it does not seem to include /usr/local/bin, which is why the `which pod` command is not found during `flutter run`.

Originally mentioned here: https://github.com/flutter/flutter/issues/54962#issuecomment-672578610

**Comment by kkhan** [comment] 2021-01-03 16:09
I was having this same issue (on Android Studio 4.1) only whenever I was adding any location related package. After trying everything for 2 days I reluctantly downloaded latest beta versions of Android Studio i.e. 4.2 Beta 2 and to my surprise it just worked.

**Comment by helin24** [comment] 2021-01-05 19:13
@hoonji thanks for the suggestion and the link!

Closing this as it's not a flutter issue.

**Closed by helin24** 2021-01-05 19:13 UTC

**Comment by aymangithub** [comment] 2021-08-28 21:46
> On my system I use .zsh. Setting up .zprofile did not fix the problem. Creating a symbolic link from .bash_profile to .zprofile did fix my issue.
> 
> ```shell
> ln -s .zprofile .bash_profile
> ```

could you please write the steps ?

**Comment by dspells** [comment] 2021-08-28 23:39
> > On my system I use .zsh. Setting up .zprofile did not fix the problem. Creating a symbolic link from .bash_profile to .zprofile did fix my issue.
> > ```shell
> > ln -s .zprofile .bash_profile
> > ```
> 
> could you please write the steps ?

Since 'flutter doctor -v' works properly from your terminal window that means that your environment variables are setup properly when running from a terminal window.

If you have changed the "Terminal > General > Shells open with" preference to a specified "Command" then you may want to set that as the default shell for your whole system. You can do that running "chsh -s <comand>". For me I had to do "chsh -s /bin/zsh" so that the whole whole os knows what your default shell is. Closing and opening Android Studio then running "Tools > Flutter > Flutter Doctor" will tell you if that worked of course.

If you did not change your default shell or that did not work for you then you will have to do some more digging to find out where your current shell is getting the bulk of it's environment variables from.

If you execute a ps -al in your "Terminal" window one of the running processes should be a shell (like zsh, Fish, sh, Tcsh, Ksh, Ash, Dash, bash). More than likely you are running zsh, bash or sh on Mac OS X. You must find out where all your variables are coming from for that type of shell.

If you are running 'bash' that means that some or all of your variables are in another file besides .bash_profile
See https://tldp.org/LDP/Bash-Beginners-Guide/html/chap_03.html to find out the different configuration files. Most people end up putting their variables in .bashrc or .bash_profile. Then you must either copy those variables into .bash_profile

I was using .zshenv for all my variables which is probably not a good practice. So I then moved the file using 'mv .zshenv .zprofile'
I then created a symbolic using 'ln -s .zprofile .bash_profile' as described above.

Doing this has the advantage of having my variables setup properly whether I am running 'zsh' as my shell or if the 'shebang' line forces a script to use bash.

I hope this information is helpful.

The overarching goal is to help the plugin to find your environment variables from the default system shell environment while not messing up any customizations you may have made.

**Comment by stevemessick** [comment] 2021-08-30 14:38
Excellent write-up @dspells, thanks! There is one more thing to remember. Whenever you change .zprofile or .bash_profile you need to log out and log back in. Otherwise, the change won't be processed by the operating system.

**Comment by ikarelin** [comment] 2022-01-27 21:06
You don't need to logout to use new .bash_profile
Just run "source ~/.bash_profile" and you are ready to go

**Comment by stevemessick** [comment] 2022-01-27 21:38
@ikarelin That won't update the settings used by the IDE.

**Comment by jhatch28** [comment] 2022-05-01 20:20
Here's how you solve it. You need to set system-wide path using `launchctl` 
https://stackoverflow.com/a/3756686/1451443

**Comment by AlexanderThiele** [comment] 2022-05-02 06:53
just leaving my 2 cents: I updated Android Studio to 2021.1.1 Patch 3 which fixed the issue for me.

**Comment by umitmutluu** [comment] 2024-02-15 21:05
First, the iOS project 
delete symliks, pods and podfile.lock folders.
then delete the pubspec.lock folder
then come to the home directory and paste this command
`flutter clean && flutter pub get && cd ios/ && pod deintegrate && pod install --repo-update`
in the podfile of the package you are using, for example
platform :ios, make sure it is compatible with '14.5'
