### ISSUE TITLE
Flutter Outline says "Nothing to show" with new versions of everything

### ISSUE THREAD

**Issue by gazialankus** [flutter/flutter-intellij#1827] opened 2018-02-25 16:50 UTC
## Steps to Reproduce

1. Turn on "Enable Flutter Outline view" in Settings > Languages & Frameworks > Flutter.
2. Restart IntelliJ.
3. Create a new Flutter project. 
4. Flutter Outline stays as "Nothing to show" with no content.

I understand that other people have this working. Is there any way I can provide a log file to help diagnose the issue?

## Version info

I tried both with the dev and the master channels. 

λ flutter doctor -v
[√] Flutter (Channel master, v0.1.6-pre.7, on Microsoft Windows [Version 10.0.16299.192], locale en-US)
    • Flutter version 0.1.6-pre.7 at C:\Installs\Flutter\flutter
    • Framework revision c3bbcb6f91 (23 hours ago), 2018-02-24 09:28:58 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\Installs\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = D:\Installs\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • Flutter plugin version 22.0.2
    • Dart plugin version 173.4548.30

[!] VS Code (version 1.17.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by devoncarew** [comment] 2018-02-25 18:12
Thanks for reporting! Your flutter sdk is recent enough to contain the changes to support the outline view, so I'm assuming this is a windows issue. We'll do some investigation here.

**Comment by devoncarew** [comment] 2018-02-25 18:33
@scheglov, it looks like we're not showing content for the outline view on windows. Perhaps a path issue, in the Flutter plugin or on the analysis server side?

**Comment by slightfoot** [comment] 2018-02-25 18:55
I can confirm this is also an issue for myself.
```
Windows 10 x64
IntelliJ IDEA 2017.3.4 #IC-173.4548.28
-
Flutter 0.1.6-pre.6 • channel master • https://github.com/flutter/flutter.git
Framework • revision 1f3eb5034f (2 days ago) • 2018-02-23 18:35:40 -0800
Engine • revision ead227f118
Tools • Dart 2.0.0-dev.28.0.flutter-0b4f01f759
```

**Comment by scheglov** [comment] 2018-02-26 21:52
This should be fixed with https://github.com/flutter/flutter-intellij/commit/b595ba9bc1c2c47d3fddda9272057b92d34e8c59

It is not part of any build yet AFAIK.

**Closed by scheglov** 2018-02-26 21:52 UTC
Labels: bug, flutter-preview, ❖ platform-windows

**Comment by devoncarew** [comment] 2018-02-27 02:40
This has been published as M22.1.

**Comment by slightfoot** [comment] 2018-02-27 15:08
For visitors to this ticket: You can download the Flutter Plugin directly from here: https://plugins.jetbrains.com/plugin/9212-flutter

Make sure you download the version that matches your Intellij Build Number as found in the "Help > About" section.

**Comment by devoncarew** [comment] 2018-02-27 15:16
@slightfoot, thanks for verifying!

> You can download the Flutter Plugin directly from here

You're generally going to be better off installing from the plugins preference page - that'll make sure that IntelliJ keeps up with updates.

**Comment by nag0121** [comment] 2018-05-02 06:27
hello guys how about me i have been using flutter in android studio...
Flutter channels:
* beta
  dev
  master

this is how my flutter channel looks like and not showing flutter out line(windows)

**Comment by gazialankus** [comment] 2018-05-02 06:38
@nag0121 possible issues that come to mind: 

- Your Flutter version may be old. Try `flutter upgrade`
- Your Flutter plugin may be old. Try Help->Check for Updates... in IntelliJ

If these don't work, please post the output of `flutter doctor -v` and we'll figure it out.

**Comment by kDaqqa** [comment] 2020-03-18 09:16
**I got this solve:** 
Open a terminal/command window and type flutter channel. You'll see that you are in the alpha channel, which is actually abandoned. You need to be in the dev channel, but for some reason switching from alpha to dev does not work. Do this:

_flutter channel master
flutter doctor
flutter channel dev
flutter doctor
flutter channel_

This should tell you that you are in dev channel. Now restart and try again.

**Comment by Axxxx** [comment] 2020-03-23 13:52
> **I got this solve:**
> Open a terminal/command window and type flutter channel. You'll see that you are in the alpha channel, which is actually abandoned. You need to be in the dev channel, but for some reason switching from alpha to dev does not work. Do this:
> 
> _flutter channel master flutter doctor flutter channel dev flutter doctor flutter channel_
> 
> This should tell you that you are in dev channel. Now restart and try again.

Thanks It 'Worked' for me

**Comment by harikirank** [comment] 2020-03-24 16:25
> flutter channel

flutter channel dev
Switching to flutter channel 'dev'...
git: From https://github.com/flutter/flutter
git:    e6b0f5f23..58cad787d  dev        -> origin/dev
git:    8c0b43bda..af5194dbf  master     -> origin/master
git:  * [new branch]          remove-implements-function -> origin/remove-implements-function
git:  * [new branch]          revert-47667-refresh_indicator_perf -> origin/revert-47667-refresh_indicator_perf
git:  * [new tag]             v1.16.2    -> v1.16.2
git: error: unable to create file bin/flutter: Permission denied
git: D  bin/flutter
git: Branch 'dev' set up to track remote branch 'dev' from 'origin'.
git: Switched to a new branch 'dev'

//It got messed up 
flutter channel 
bash: /c/src/flutter/bin/flutter: No such file or directory

//what should I do now?

**Comment by FunckyFizz** [comment] 2020-03-27 10:16
Hi guys,

Unfortunately this is happening to me as well and I've tried upgrading Flutter under tools.

Does anyone know of a known fix for this?

I'm using Pop OS 18.04.
![image](https://user-images.githubusercontent.com/62399911/77745825-e2cd0d00-7013-11ea-86a8-c9eae4908fd2.png)

**Comment by saadalti** [comment] 2020-03-29 10:38
> **I got this solve:**
> Open a terminal/command window and type flutter channel. You'll see that you are in the alpha channel, which is actually abandoned. You need to be in the dev channel, but for some reason switching from alpha to dev does not work. Do this:
> 
> _flutter channel master flutter doctor flutter channel dev flutter doctor flutter channel_
> 
> This should tell you that you are in dev channel. Now restart and try again.

Works like charm thanks!

**Comment by AruArshad** [comment] 2020-04-02 07:32
> **I got this solve:**
> Open a terminal/command window and type flutter channel. You'll see that you are in the alpha channel, which is actually abandoned. You need to be in the dev channel, but for some reason switching from alpha to dev does not work. Do this:
> 
> _flutter channel master flutter doctor flutter channel dev flutter doctor flutter channel_
> 
> This should tell you that you are in dev channel. Now restart and try again.

Thanks man!

**Comment by shariar41** [comment] 2020-04-02 17:19
click to red dart analysis server button hopefully it will work

<img width="643" alt="Screenshot 2020-04-02 23 13 02" src="https://user-images.githubusercontent.com/12062225/78278798-65842980-7538-11ea-9598-41b63128ad5d.png">

**Comment by ZulqarnainGithub** [comment] 2020-04-03 11:17
> **I got this solve:**
> Open a terminal/command window and type flutter channel. You'll see that you are in the alpha channel, which is actually abandoned. You need to be in the dev channel, but for some reason switching from alpha to dev does not work. Do this:
> 
> _flutter channel master flutter doctor flutter channel dev flutter doctor flutter channel_
> 
> This should tell you that you are in dev channel. Now restart and try again.

this worked for me thanks alot mate!

**Comment by leandrog7** [comment] 2020-04-05 15:59
It often happens for me, but when I STOP it suddenly works. Then I RUN again and it is still ok.

**Comment by TheBrown** [comment] 2020-04-13 16:29
> click to red dart analysis server button hopefully it will work
> 
> <img alt="Screenshot 2020-04-02 23 13 02" width="643" src="https://user-images.githubusercontent.com/12062225/78278798-65842980-7538-11ea-9598-41b63128ad5d.png">

Thank you

**Comment by naeem43khan** [comment] 2020-04-24 06:39
make sure your code is not a mess.

**Comment by ssinha2103** [comment] 2020-04-30 15:58
> **I got this solve:**
> Open a terminal/command window and type flutter channel. You'll see that you are in the alpha channel, which is actually abandoned. You need to be in the dev channel, but for some reason switching from alpha to dev does not work. Do this:
> 
> _flutter channel master flutter doctor flutter channel dev flutter doctor flutter channel_
> 
> This should tell you that you are in dev channel. Now restart and try again.

In my case the app was in stable channel, from there I shifted to master version.

Its working now.

**Comment by al3sha** [comment] 2020-04-30 23:34
> I got this solve:
> Open a terminal/command window and type flutter channel. You'll see that you are in the alpha channel, which is actually abandoned. You need to be in the dev channel, but for some reason switching from alpha to dev does not work. Do this:
> 
> flutter channel master flutter doctor flutter channel dev flutter doctor flutter channel
> 
> This should tell you that you are in dev channel. Now restart and try again.
> 

I also had to change my channel - good fix. Many mahalos.

**Comment by ssinha2103** [comment] 2020-05-04 17:16
Move the mouse to any widget and Press Ctrl and click on that widget ,

after this step, your FLutter Outline will be enabled

**Comment by UsabilitySpace** [comment] 2020-05-11 18:47
> Move the mouse to any widget and Press Ctrl and click on that widget ,
> 
> after this step, your FLutter Outline will be enabled

This worked for me on iMac — thanks. 

But, nevertheless, note that on Macs it is ⌥+Click that should be performed.

**Comment by Anoop-Sudhakar** [comment] 2020-05-19 16:07
> click to red dart analysis server button hopefully it will work
> 
> <img alt="Screenshot 2020-04-02 23 13 02" width="643" src="https://user-images.githubusercontent.com/12062225/78278798-65842980-7538-11ea-9598-41b63128ad5d.png">

Worked for me too

**Comment by Thatogafane** [comment] 2020-07-22 16:16
> > click to red dart analysis server button hopefully it will work
> > <img alt="Screenshot 2020-04-02 23 13 02" width="643" src="https://user-images.githubusercontent.com/12062225/78278798-65842980-7538-11ea-9598-41b63128ad5d.png">
> 
> Thank you

Thank you

**Comment by MrDEV0** [comment] 2020-09-21 10:39
> > click to red dart analysis server button hopefully it will work
> > <img alt="Screenshot 2020-04-02 23 13 02" width="643" src="https://user-images.githubusercontent.com/12062225/78278798-65842980-7538-11ea-9598-41b63128ad5d.png">
> 
> Thank you

This works for me, thank a lot.

**Comment by nav9** [comment] 2024-09-30 16:06
Experiencing this nothing shown in outline issue with Flutter installed just a couple of months ago. The solutions provided above didn't work either. Flutter is disappointing on so many levels. The syntax where the indentation makes it difficult to figure out where a widget starts and ends, not having reliable functions for finding and playing ringtones, not being able to easily access the filesystem, not being able to detect if the screen is locked unless I use some other package which when I use, runs into some version errors of Kotlin, the app pausing if I switch to another app or the phone screen gets locked, a lot of unnecessarily complicated syntax. These are just what I've encountered in a short span of use.   
I hope y'all fix the outline issue.
