### ISSUE TITLE
Missing code completion on _incrementCounter

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#862] opened 2017-03-30 13:49 UTC
Repro steps:

1. Create a new Flutter project in IDEA 2017.1
1. Delete lines 79-81
1. Inside `Center(` type `new Fla` and press Tab and get the expected completion to `new FlatButton(onPressed: null)`
1. While `null` is still selected, type `_`

=> Would expect to be offered a code completion to `_incrementCounter` but no such completion is offered

**Comment by mit-mit** [comment] 2017-04-03 17:59
@devoncarew do you think this is analyzer or IJ? (Or me missing something?)

**Comment by pq** [comment] 2017-05-08 02:45
cc @danrubel

**Comment by pq** [comment] 2017-05-10 17:48
AI(@pq): investigate if this still repros on SDK head.

**Comment by pq** [comment] 2017-05-10 19:05
Confirmed.  On SDK HEAD, still no completions for `_incrementCounter`.

**Comment by pq** [comment] 2017-05-10 19:06
Duplicate of #836.

**Closed by pq** 2017-05-10 19:06 UTC
Labels: completion, topic-editing
