### ISSUE TITLE
Crash on IntelliJ IDEA 2024.1

### ISSUE THREAD

**Issue by AlexBurdu** [flutter/flutter-intellij#7341] opened 2024-04-10 03:31 UTC
## Steps to Reproduce

Randomly crashes on the latest Intellij. I had to disable to plugin to avoid having my workflow from being disrupted.

```
IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.0-15-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 24
Registry:
Non-Bundled Plugins:
  Dart (241.15845)
  Flutter (78.5.1)
Kotlin: 241.14494.240-IJ
Current Desktop: ubuntu:GNOME
```

```
2024-04-10 06:01:20,231 [  16480] SEVERE - #io.flutter.actions.RunProfileFlutterApp - `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.flutter.actions.RunProfileFlutterApp' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.flutter]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.flutter.actions.RunProfileFlutterApp' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.flutter]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
2024-04-10 06:01:20,231 [  16480] SEVERE - #io.flutter.actions.RunReleaseFlutterApp - `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.flutter.actions.RunReleaseFlutterApp' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.flutter]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.flutter.actions.RunReleaseFlutterApp' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.flutter]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
2024-04-10 06:01:20,232 [  16481] SEVERE - #io.flutter.actions.RunProfileFlutterApp - IntelliJ IDEA 2024.1  Build #IU-241.14494.240
2024-04-10 06:01:20,232 [  16481] SEVERE - #io.flutter.actions.RunProfileFlutterApp - JDK: 17.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-04-10 06:01:20,232 [  16481] SEVERE - #io.flutter.actions.RunProfileFlutterApp - OS: Linux
2024-04-10 06:01:20,232 [  16481] SEVERE - #io.flutter.actions.RunProfileFlutterApp - Plugin to blame: Flutter version: 78.5.1
2024-04-10 06:01:20,232 [  16481] SEVERE - #io.flutter.actions.RunReleaseFlutterApp - IntelliJ IDEA 2024.1  Build #IU-241.14494.240
2024-04-10 06:01:20,232 [  16481] SEVERE - #io.flutter.actions.RunReleaseFlutterApp - JDK: 17.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-04-10 06:01:20,232 [  16481] SEVERE - #io.flutter.actions.RunReleaseFlutterApp - OS: Linux
2024-04-10 06:01:20,232 [  16481] SEVERE - #io.flutter.actions.RunReleaseFlutterApp - Plugin to blame: Flutter version: 78.5.1

```

## Version info

```
╰─➤  flutter doctor -v
[!] Flutter (Channel unknown, 3.7.6, on Ubuntu 22.04.4 LTS 6.5.0-15-generic, locale en_US.UTF-8)
    ! Flutter version 3.7.6 on channel unknown at /home/alex/snap/flutter/common/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision 12cb4eb7a0 (1 year, 1 month ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/alex/apps/AndroidSDK
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/alex/apps/AndroidSDK
    • Java binary at: /home/alex/.sdkman/candidates/java/current/bin/java
    • Java version OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (version 2024.1)
    • Android Studio at /home/alex/apps/JetBrains/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
    • IntelliJ at /home/alex/apps/JetBrains/intellij-idea-ultimate-2
    • Flutter plugin version 78.5.1
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • Pixel Fold (mobile) • 192.168.0.154:8888 • android-arm64  • Android 14 (API 34)
    • Linux (desktop)     • linux              • linux-x64      • Ubuntu 22.04.4 LTS 6.5.0-15-generic
    • Chrome (web)        • chrome             • web-javascript • Google Chrome 123.0.6312.105

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

**Comment by jwren** [comment] 2024-04-10 17:24
Thanks! This is a known issue, a duplicate of https://github.com/flutter/flutter-intellij/issues/7330

**Closed by jwren** 2024-04-10 17:24 UTC
