### ISSUE TITLE
Error on installing DevTools

### ISSUE THREAD

**Issue by aliyazdi75** [flutter/flutter-intellij#4894] opened 2020-09-26 09:49 UTC
## What happened

Upgraded to new android studio 4 and can not install DevTools

## Version information

Android Studio `4.0.1` • Flutter plugin `io.flutter 49.0.2` • Dart plugin `193.7547`

Error getting Flutter sdk information.

Android Studio 4.0.1
Build #AI-193.6911.18.40.6626763, built on June 25, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.4.0-48-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: ide.new.welcome.screen.force=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: Dart, org.jetbrains.kotlin, com.bloc.intellij_generator_plugin, com.chrisrm.idea.MaterialThemeUI, com.giancarlocode.built-value-snippets, com.google.services.firebase, com.vladsch.idea.multimarkdown, io.flutter, de.mariushoefler.flutter_enhancement_suite, izhangzhihao.rainbow.brackets

## Exception

null

```
com.teamdev.jxbrowser.browser.UnsupportedRenderingModeException: The current HARDWARE_ACCELERATED rendering mode is not supported
	at com.teamdev.jxbrowser.browser.internal.BrowserSettingsImpl.checkRenderingMode(BrowserSettingsImpl.java:370)
	at com.teamdev.jxbrowser.browser.internal.BrowserSettingsImpl.setTransparentBackgroundEnabled(BrowserSettingsImpl.java:358)
	at com.teamdev.jxbrowser.browser.internal.BrowserSettingsImpl.enableTransparentBackground(BrowserSettingsImpl.java:341)
	at io.flutter.jxbrowser.EmbeddedBrowser.openPanel(EmbeddedBrowser.java:30)
	at io.flutter.devtools.DevToolsInstance.lambda$openPanel$1(DevToolsManager.java:402)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by helin24** [comment] 2020-09-30 23:30
Duplicate of https://github.com/flutter/flutter-intellij/issues/4872

This will be fixed for v50 and should be available through the dev channel currently (see https://github.com/flutter/flutter-intellij/wiki/Dev-Channel).

**Closed by helin24** 2020-09-30 23:30 UTC
