### ISSUE TITLE
Not compatible with IntelliJ 191

### ISSUE THREAD

**Issue by passsy** [flutter/flutter-intellij#3132] opened 2019-01-28 12:41 UTC
The latest version `32.0.3` is not compatible with the new IntelliJ 19.1 which is currently in EAP.

```
IntelliJ IDEA 2019.1 EAP (Ultimate Edition)
Build #IU-191.4212.41, built on January 24, 2019
IntelliJ IDEA EAP User
Expiration date: February 23, 2019
JRE: 1.8.0_152-release-1402-b1 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2
```

**Comment by terrylucas** [comment] 2019-01-28 13:56
Duplicate of #3112

**Closed by terrylucas** 2019-01-28 13:56 UTC
