### ISSUE TITLE
Flutter dev tool not working after update to idea 2021.1

### ISSUE THREAD

**Issue by karabanovbs** [flutter/flutter-intellij#5433] opened 2021-04-23 16:58 UTC
Message: jxbrowser installation failed
IDEA: 211..6693.111
Plugin version: 55.1.4

**Comment by helin24** [comment] 2021-04-27 16:06
This is the workaround we're offering for now while investigating the root cause for https://github.com/flutter/flutter-intellij/issues/5376. There should be a link to open the DevTools inspector in your normal browser below this message; alternatively, you can also turn off embedded DevTools instead in Preferences > Flutter (under Languages and Frameworks) > uncheck "Enable embedding DevTools...".

Let me know if you instead mean that DevTools can't be opened into the browser. For now I'm closing this since I'm tracking with the other issue mentioned above.

**Closed by helin24** 2021-04-27 16:06 UTC
