### ISSUE TITLE
SDK location browser freezes

### ISSUE THREAD

**Issue by Timmmm** [flutter/flutter-intellij#1020] opened 2017-05-14 16:40 UTC
## Steps to Reproduce

1. Start IntelliJ
2. New flutter project.
3. It asks where the SDK is. Click browse.
4. The file browser opens. Spins for a bit without showing any directories and eventually IntelliJ freezes and needs to be killed.

It I just type in the location without browsing it works. Also if I use other file browsers (e.g. File->Open) they seem to work fine.

## Version info

```
[√] Flutter (on Microsoft Windows [Version 10.0.15063], channel alpha)
    • Flutter at C:\Users\Tim\Flutter\flutter
    • Framework revision dc4ca8db83 (3 days ago), 2017-05-11 15:33:29 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\Tim\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Community Edition (version 2017.1)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.1

[√] Connected devices
    • None

```

**Comment by pq** [comment] 2017-05-15 20:20
cc @alexander-doroshko

**Comment by pq** [comment] 2017-05-16 12:59
@alexander-doroshko : does this sound at all familiar?

We're using what looks like standard file browser setup code:

```
    mySdkCombo.addBrowseFolderListener("Select Flutter SDK Path", null, null,
                                       FileChooserDescriptorFactory.createSingleFolderDescriptor(),
                                       TextComponentAccessor.STRING_COMBOBOX_WHOLE_TEXT);
```

**Comment by alexander-doroshko** [comment] 2017-05-16 13:06
Not familiar. Are you able to reproduce it? Did you ever see it in non-flutter dialogs? Make sure that file chooser dialog is not shown under a write action.

**Comment by alexander-doroshko** [comment] 2017-05-16 13:07
Also, ask for logs and see if any errors are there.

**Comment by pq** [comment] 2017-05-16 15:35
@Timmmm: is this consistent?  Does it happen in other places you browse for files?

Also, could you look in your logs and see if anything jumps out at you?

https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

**Comment by Timmmm** [comment] 2017-05-16 20:50
I can't seem to reproduce it any more, but also IntelliJ seems to be remembering the SDK location now and I can't work out how to make it forget Previously it had serious issues remembering the SDK path - of course that might be an unrelated issue.

There are several `threadDumps-freeze` logs that seem to show bad stuff happening. I've attached them all here.
[log.zip](https://github.com/flutter/flutter-intellij/files/1005781/log.zip)

There's a nice 180-line stack trace in there (yeay Java) that seems to suggest it is some deadlock deep inside the file browser dialog, I think when I click cancel.

Could be an IntelliJ issue. If I uninstall the Dart and Flutter plugins, and reinstall them will that reset their settings to a blank state? Might be worth a try if so.

**Comment by devoncarew** [comment] 2017-05-22 15:39
@Timmmm, thanks for the report! I'm closing it out, but if you can get a repro, consider filing a bug against https://youtrack.jetbrains.com/issues.

**Closed by devoncarew** 2017-05-22 15:39 UTC
Labels: bug, dependency: idea-platform, ❖ platform-windows
