### ISSUE TITLE
Implement methods not working

### ISSUE THREAD

**Issue by crtl** [flutter/flutter-intellij#4950] opened 2020-10-06 12:35 UTC
It happens to often that I am not able to implement / override methods.
Its hard to reproduce and in new projects it doesnt happen.

Ive created a demo which reproduces the issue reliable so far.
The project files are deducted from a production project so I had to remove all project specific build and flutter files but the issue itself has no changed during the process and still persists even when android, ios etc. folders are missing.

## Steps to Reproduce

1. `git clone https://github.com/crtl/flutter-intellij-bugs`
2. Open `lib/class.dart`
3. Navigate inside class body of `B` and press `CTRL` + `I` to implement methods.
4. No methods were found to implement

## Version info

```
$ flutter doctor -v
[√]
    • Flutter version 1.23.0-8.0.pre.132 at D:\dev\flutter\sdk
    • Framework revision 5e97eed895 (29 hours ago), 2020-10-05 00:42:50 -0700
    • Engine revision a8d7d97bef
    • Dart version 2.11.0 (build 2.11.0-185.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

```

**Comment by stevemessick** [comment] 2020-10-09 16:27
Thanks for the repo case. If you re-run `flutter create` on the project it will be updated with the current templates and your issue goes away. If you want to fix your production project I'd recommend making a backup first. I think we can close this issue.

cc @alexander-doroshko

**Comment by alexander-doroshko** [comment] 2020-10-09 16:35
Override/Implement methods is a functionality implemented in the Dart plugin. This issue is tracked as https://youtrack.jetbrains.com/issue/WEB-40469. Feel free to vote there to be updated about the progress.

**Closed** 2020-10-09 16:35 UTC
Labels: bug

**Comment by PawelShi** [comment] 2023-04-13 03:09
The problem is the incorrect formation of the Flutter project file from the AndroidStudio environment.
The .iml file is missing the following lines:
```
<sourceFolder url="file://$MODULE_DIR$/lib" isTestSource="false" />
 <sourceFolder url="file://$MODULE_DIR$/test" isTestSource="true" />
```
The complete iml file should look like this:
`<?xml version="1.0" encoding="UTF-8"?>
<module type="JAVA_MODULE" version="4">
  <component name="NewModuleRootManager" inherit-compiler-output="true">
    <exclude-output />
    <content url="file://$MODULE_DIR$">
      <sourceFolder url="file://$MODULE_DIR$/lib" isTestSource="false" />
      <sourceFolder url="file://$MODULE_DIR$/test" isTestSource="true" />
      <excludeFolder url="file://$MODULE_DIR$/.idea" />
      <excludeFolder url="file://$MODULE_DIR$/.pub" />
      <excludeFolder url="file://$MODULE_DIR$/.dart_tool" />
      <excludeFolder url="file://$MODULE_DIR$/build" />
    </content>
    <orderEntry type="sourceFolder" forTests="false" />
    <orderEntry type="library" name="Dart SDK" level="project" />
    <orderEntry type="library" name="Flutter Plugins" level="project" />
    <orderEntry type="library" name="Dart Packages" level="project" />
  </component>
</module>`

If the project is generated using the command line "flitter create .", then it works fine.
