### ISSUE TITLE
Flutter inspector does not jump to the source

### ISSUE THREAD

**Issue by M1chlCZ** [flutter/flutter-intellij#6892] opened 2023-09-05 09:17 UTC
## Steps to Reproduce

Flutter inspector does not jump to the source as it once did. Yes, there is some hover over window with class name + line number, but it makes developing much slower. Was this feature removed, I can't get it to work on Stable release, nor on Canary version of Android studio/Flutter SDK.

As per to reproduce, just open Flutter inspector, click "select widget mode" and click on something in your app. I tried it in debug as well as run mode, no difference.

## Version info

```
[✓] Flutter (Channel beta, 3.14.0-0.2.pre, on macOS 13.5.1 22G90 darwin-arm64, locale cs-CZ)
    • Flutter version 3.14.0-0.2.pre on channel beta at /Users/user/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 123453dc41 (5 days ago), 2023-08-31 13:50:44 -0700
    • Engine revision b93c76ab94
    • Dart version 3.2.0 (build 3.2.0-42.2.beta)
    • DevTools version 2.26.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/user/Library/Android/sdk
    • Java binary at: /Users/user/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Users/user/Applications/Android Studio Iguana 2023.2.1 Canary 1.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/user/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] VS Code (version 1.82.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.
```

**Comment by jacob314** [comment] 2023-09-07 18:14
If this issue can be reproduced, rather than debugging the existing complex logic for it in IntelliJ, we should switch over to the simpler API used by VSCode to listen for tool events to navigate to a line + column.

**Comment by jacob314** [comment] 2023-09-07 18:16
This is a duplicate of https://github.com/flutter/flutter-intellij/issues/6894

**Closed by jacob314** 2023-09-07 18:16 UTC
Labels: bug, P1, inspector
