### ISSUE TITLE
exception occurred after I update the Intlijj IDEA to 2023.2.5

### ISSUE THREAD

**Issue by MohammedAlsharafe** [flutter/flutter-intellij#7099] opened 2023-12-01 17:19 UTC
lease file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2023.2.5` • Flutter plugin `io.flutter 76.3.4` • Dart plugin `232.10248`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.Throwable: Error listening to ToolEvent stream: org.dartlang.vm.service.element.RPCError@501cf0bd
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at io.flutter.vmService.VmServiceWrapper$2.onError(VmServiceWrapper.java:185)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:633)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:422)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:86)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by jwren** [comment] 2023-12-15 19:30
Duplicate of https://github.com/flutter/flutter-intellij/issues/7133

**Closed by jwren** 2023-12-15 19:30 UTC
