### ISSUE TITLE
IDE error when building - md file is included below

### ISSUE THREAD

**Issue by foresourcedev** [flutter/flutter-intellij#5407] opened 2021-04-13 17:17 UTC
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_
Building in debug mode.

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.2.3 20D91 darwin-x64, locale en)
    • Flutter version 1.25.0-8.3.pre at /Users/foresource/flutter
    • Framework revision 5d36f2e7f5 (3 months ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/foresource/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/foresource/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/foresource/Library/Android/sdkv
    • Java binary at: /Users/foresource/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/foresource/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /Users/foresource/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (1 available)
    • iPad Pro (12.9-inch) (4th generation) (mobile) • B6A89569-4594-4D9F-8EB6-3F2BD96FB0AF • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)

• No issues found!

[bug-report.md](https://github.com/flutter/flutter-intellij/files/6305493/bug-report.md)

**Comment by helin24** [comment] 2021-04-13 20:40
Duplicate of https://github.com/flutter/flutter-intellij/issues/5376

**Closed by helin24** 2021-04-13 20:40 UTC
