### ISSUE TITLE
Plugin io.flutter: got unexpected null exception

### ISSUE THREAD

**Issue by dvazar** [flutter/flutter-intellij#7332] opened 2024-04-06 20:21 UTC
## What happened

I do not know what happened. I was just working on my project and this error appeared.

## Version information

IntelliJ IDEA `2024.1` • Flutter plugin `io.flutter 78.5.1` • Dart plugin `241.15845`

Flutter 3.19.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 300451adae (10 days ago) • 2024-03-27 21:54:07 -0500
Engine • revision e76c956498
Tools • Dart 3.3.3 • DevTools 2.31.1

## Exception

null

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.flutter.actions.FlutterPackagesExplorerActionGroup' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.flutter]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**Comment by j-fbriere** [comment] 2024-04-06 21:21
Same here.
Also Same versions:

IntelliJ IDEA 2024.1 • Flutter plugin io.flutter 78.5.1 • Dart plugin 241.15845

Flutter 3.19.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 300451adae (10 days ago) • 2024-03-27 21:54:07 -0500
Engine • revision e76c956498
Tools • Dart 3.3.3 • DevTools 2.31.1

**Comment by helin24** [comment] 2024-04-08 19:34
Duplicate of #7330

**Closed by helin24** 2024-04-08 19:34 UTC
