### ISSUE TITLE
Unable to expand or collapse without "new" keyword

### ISSUE THREAD

**Issue by anderscheow** [flutter/flutter-intellij#3125] opened 2019-01-25 09:54 UTC
Expand or collapse indicator is not shown when "new" keyword is not present.

Without "new" keyword
<img width="283" alt="screenshot 2019-01-25 at 5 52 24 pm" src="https://user-images.githubusercontent.com/11788504/51738423-205d9f80-20ca-11e9-9d8f-37da46435032.png">

With "new" keyword
<img width="295" alt="screenshot 2019-01-25 at 5 51 30 pm" src="https://user-images.githubusercontent.com/11788504/51738446-2d7a8e80-20ca-11e9-9ef2-e72f281845ce.png">

**Comment by terrylucas** [comment] 2019-01-28 14:42
Confirm, this is a general IDE problem, outside of Flutter, any constructor without the optional new keyword that spans more than one line is not collapsible - should be.  I'll reassign.  Thank you.

**Comment by alexander-doroshko** [comment] 2019-01-28 15:03
This is already fixed in 2019.1 (available as EAP). I think we need to backport the fix to earlier branch(es).

**Comment by jwren** [comment] 2019-01-28 17:21
This is a duplicate of https://github.com/flutter/flutter-intellij/issues/2373.

Issue is fixed in the 2019.1 release of the Dart plugin.

**Closed by jwren** 2019-01-28 17:21 UTC
Labels: dependency: dart plugin
