### ISSUE TITLE
Android Studio not detecting imported Flutter Project's Structure

### ISSUE THREAD

**Issue by vishnuagbly** [flutter/flutter-intellij#5562] opened 2021-06-10 11:45 UTC
## Description
In android studio whenever I import a flutter project either from some online version control system or any other source, Android Studio fails to determine any project structure. Following are the screenshots of all sections in the project structure.
![Screenshot (23)_LI](https://user-images.githubusercontent.com/53317018/121519202-0e68c700-ca0f-11eb-8191-787269e964d7.jpg)
![Screenshot (24)](https://user-images.githubusercontent.com/53317018/121519210-10328a80-ca0f-11eb-836e-7f361cb33690.png)
![Screenshot (25)](https://user-images.githubusercontent.com/53317018/121519212-10328a80-ca0f-11eb-88be-0dc580673bcb.png)
![Screenshot (26)](https://user-images.githubusercontent.com/53317018/121519213-10cb2100-ca0f-11eb-8c7d-b5e2e99b6fb5.png)
![Screenshot (27)](https://user-images.githubusercontent.com/53317018/121519215-1163b780-ca0f-11eb-8138-683d05e0f950.png)
![Screenshot (21)](https://user-images.githubusercontent.com/53317018/121519216-1163b780-ca0f-11eb-8306-983271733cc3.png)
![Screenshot (22)](https://user-images.githubusercontent.com/53317018/121519217-11fc4e00-ca0f-11eb-9970-f3a68bf673f7.png)

## Steps to Reproduce

1) Open Android Studio (close any already opened project)
2) Click on "Get from Version Control"
3) Clone a flutter project from GitHub

## Version info

the output of `flutter doctor -v`:
```
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.2.1 at D:\flutter
    • Framework revision 02c026b03c (2 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1
    • Pub download mirror https://pub.dev

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\Android\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\vishnu Agarwal\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.41

• No issues found!
```

**Comment by helin24** [comment] 2021-06-11 16:26
@vishnuagbly I'm not able to reproduce this, though I am using Android Studio 4.1.3 and my project structure interface looks a little different from yours. Can you reproduce this on a later version of Android Studio? We will no longer be updating the plugin for v4.1 going forward anyway.

@stevemessick I'm not sure which parts of this we control in the plugin; do you have other ideas?

**Comment by vishnuagbly** [comment] 2021-06-11 16:46
@helin24 Thanks for your response, I fixed it, I think the repo I was trying to get from Github was flawed as there were gradle files in the root folder, Maybe the project was created by some different version plugin or different IDE and different plugin 🤷‍♂️, whatever the case was, I have recreated the whole project and copied lib files and edited android files according to the repo and it worked for me.

**Comment by helin24** [comment] 2021-06-11 16:48
Okay, I'm glad you found a solution! Closing this issue for now.

**Closed by helin24** 2021-06-11 16:48 UTC
