### ISSUE TITLE
IDE Crash during flutter debug build

### ISSUE THREAD

**Issue by shaizar** [flutter/flutter-intellij#7132] opened 2023-12-11 04:27 UTC
## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2023.3` • Flutter plugin `io.flutter 77.0.1` • Dart plugin `233.11799.172`

Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (12 months ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0

## Exception

null

```
java.lang.Throwable: Error listening to ToolEvent stream: org.dartlang.vm.service.element.RPCError@60bd8c83
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at io.flutter.vmService.VmServiceWrapper$2.onError(VmServiceWrapper.java:185)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:633)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:422)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:86)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by shaizar** [comment] 2023-12-11 04:32
# What Happened

Trying to run debug build of project from IDE

**Comment by jwren** [comment] 2023-12-13 20:46
closing, duplicate of https://github.com/flutter/flutter-intellij/issues/7133

**Closed by jwren** 2023-12-13 20:46 UTC
