### ISSUE TITLE
Documentation references are shown instead of the documentation.

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter-intellij#5670] opened 2021-07-24 17:20 UTC
The documentation is not shown correctly. Instead, we get the documentation **reference**.

For example, I want to know what `TextField.autofillHints` does. When I put the caret on top of some identifier and press `Ctrl-Q`, it should show the documentation. Instead, I get this:

```
{Iterable<String>? autofillHints}  

Type: Iterable<String>?  

{@macro flutter.widgets.editableText.autofillHints} 
{@macro flutter.services.AutofillConfiguration.autofillHints}
```

This basically forces us to search the internet for the documentation, defeating its purpose.

**Comment by stevemessick** [comment] 2021-07-29 22:52
@marcglasberg Are you asking about the documentation for SDK elements referenced in your code? For example
```dart
  var x = TextField();
  x.autofillHints;
```
Then you put the cursor on `autofillHints` and type Ctrl-Q, right?

FWIW On my Mac if I just hover over `autofillHints I get the documentation as expected. Or, if I type Ctrl-J (which is bound to quick documentation on Mac) it shows that same panel.

<img width="715" alt="Screen Shot 2021-07-29 at 3 45 18 PM" src="https://user-images.githubusercontent.com/8518285/127574972-12ddc4af-abfc-486d-9e65-b7ee0fe53e99.png">

**Comment by marcglasberg** [comment] 2021-07-29 23:29
Yes. So it seems the problem is in IntelliJ for Windows.

**Comment by stevemessick** [comment] 2021-07-29 23:29
I just checked this on Windows, and Ctrl-Q does the same as Ctrl-J on Mac.

Please add the output of `flutter doctor -v`. I think we'll need to get @alexander-doroshko involved, as this feature is implemented in the Dart plugin, in `DartDocumentationProvider`. Also, make sure you have the latest version of the Dart plugin. If you already have it, and want to try an experiment, try installing an earlier version.

**Comment by marcglasberg** [comment] 2021-07-29 23:35
@stevemessick Sorry, that's not what I mean.

I mean, if I go to `textfield.dart` file, line 799 (current stable), I have this:

```
  /// {@macro flutter.widgets.editableText.autofillHints}
  /// {@macro flutter.services.AutofillConfiguration.autofillHints}
  final Iterable<String>? autofillHints;
```

Then, if I put my mouse on top of the `autofillHints` and press `Ctrl-Q`, then I don't see the documentation. In other words, the @macro works in the usage, but not in the declaration. It should work everywhere.

**Comment by stevemessick** [comment] 2021-07-29 23:52
Great, thanks for the clarification! I'd suggest creating an issue at https://youtrack.jetbrains.com to make sure it gets proper attention.

I'll leave this open for a few days.

**Comment by marcglasberg** [comment] 2021-07-30 17:01
@stevemessick Sorry, I was under the impression this is a Flutter-IntelliJ-plugin issue. Is it not? What's the criteria for filling an issue here or in https://youtrack.jetbrains.com?

**Comment by stevemessick** [comment] 2021-07-30 17:24
@marcglasberg That's a really good question; I wish it had a simple answer. If you don't know how something is implemented it is hard to know where to file issues. The Flutter plugin adds support for Flutter-specific features, but relies on the Dart plugin for everything specific to the Dart language. The Dart plugin was created by JetBrains, so that's why Dart issues go in the JetBrains issue tracker. However, @alexander-doroshko at JetBrains is also really good at keeping tabs on issues filed here, so issues usually get moved around as needed. It is easy for us to move issues between Github repositories. The two most frequent destinations are `dart-lang/sdk` for Dart analyzer issues and `flutter/fluter` for Flutter SDK issues. It would be nice if there was an easy way to move issues to the JetBrains tracker, too.

The simple approach is to file issues here and let us figure out where they belong. Perhaps @devoncarew would have some insight here.

**Comment by alexander-doroshko** [comment] 2021-08-09 09:12
It seems to work as expected for me in IntelliJ IDEA 2021.2.
![image](https://user-images.githubusercontent.com/4499789/128683795-b3e3b7de-4345-4728-b729-58e07993f0be.png)

**Comment by stevemessick** [comment] 2021-08-09 15:42
Thanks @alexander-doroshko !

@marcglasberg were you using Android Studio or IntelliJ when you observed this problem? If Android Studio then I think the problem has been solved. If IntelliJ then something else is going wrong and you should work with JetBrains to get it fixed.

**Comment by marcglasberg** [comment] 2021-08-09 15:58
I have upgraded since posting this. I am now using **_IntelliJ IDEA 2021.2, #IC-212.4746.92 build on July 28, 2021_**. 

Testing it now the problem is different. I don't understand what's going on. Now I have the documentation in the declaration, but not in the usage, as you can see here: 

**_Usage:_** 

![xxx](https://user-images.githubusercontent.com/13332110/128735486-81137123-eb35-4b42-b69b-67a8e3559bf1.jpg)

**_Declaration:_** 

![yyy](https://user-images.githubusercontent.com/13332110/128736574-7d7861a5-7983-4f2b-a2c4-7d91755d1bc0.jpg)

@stevemessick Do you get the documentation both in the declaration AND in the usage?

**Comment by stevemessick** [comment] 2021-08-09 16:16
> Do you get the documentation both in the declaration AND in the usage?

Yes, @marcglasberg I do. Using IJ 2021.2 with Dart 212.4746.57. I checked usage in the SDK, an old app, and a new NNBD app, and the definition.

**Comment by alexander-doroshko** [comment] 2021-08-09 16:17
The same for me. I do get the documentation both in the declaration and in the usage. Is is possible to share a sample project to reproduce the issue? Flutter SDK version might matter.

**Comment by stevemessick** [comment] 2021-08-16 18:02
@marcglasberg It looks like you are using Flutter v2.2.3, which is old. I suspect the problem is fixed in more recent SDKs.

**Comment by marcglasberg** [comment] 2021-08-16 21:27
@stevemessick I use the current stable, which is now Flutter 2.2.3.

**Comment by stevemessick** [comment] 2021-08-16 23:53
@InMatrix The topic of showing some errors differently than others sounds like a candidate for a UXR study.

**Comment by stevemessick** [comment] 2021-08-16 23:57
@marcglasberg I just double-checked with 2.2.3 and I get the documentation at the definition and uses. Since the behavior changed when you upgraded, I suspect there is something special about your local configuration. I have no idea what it might be, though. (Sorry for the version number confusion earlier.)

Does it work properly if you create a sample Flutter project?

**Closed** 2021-08-24 00:06 UTC
Labels: waiting for customer response
