### ISSUE TITLE
Unable to add all the missing switch cases at once after Dart 3.1

### ISSUE THREAD

**Issue by sandeep-pani** [flutter/flutter-intellij#6876] opened 2023-08-20 15:38 UTC
## Steps to Reproduce

Try the below code.<br>
![image](https://github.com/flutter/flutter-intellij/assets/80412459/67a446fb-0b8b-4f12-b934-5058ef7f0c1e) <br>

Adding missing switch cases only adds one case at a time unlike previous versions of dart sdk, where all the missing switch cases were added at once.<br>
![image](https://github.com/flutter/flutter-intellij/assets/80412459/52b787b5-707b-4f2d-934f-7ce65129631f)<br>

## Version info
```
[√] Flutter (Channel stable, 3.13.0, on Microsoft Windows [Version 10.0.19045.3324], locale en-IN)
    • Flutter version 3.13.0 on channel stable at D:\flutter\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (5 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\sande.LAPTOP-J6ESQUPJ\AppData\Local\Android\Sdk   
    • Platform android-33, build-tools 33.0.2
    • ANDROID_SDK_ROOT = C:\Users\sande.LAPTOP-J6ESQUPJ\AppData\Local\Android\Sdk\extras\google\usb_driver
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.1.3)
    • Visual Studio at D:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32328.378
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Users\sande.LAPTOP-J6ESQUPJ\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\221.5080.210
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3324]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.96
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 115.0.1901.203

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by AlexV525** [comment] 2023-08-21 17:50
Duplicate of #6812

**Closed by AlexV525** 2023-08-21 17:50 UTC
