### ISSUE TITLE
'io.flutter.actions.OpenInAppCodeAction' must override `getActionUpdateThread` and chose EDT or BGT

### ISSUE THREAD

**Issue by HudsonAfonso** [flutter/flutter-intellij#7355] opened 2024-04-16 19:04 UTC
## Version information

IntelliJ IDEA `2024.1` • Flutter plugin `io.flutter 79.0.3` • Dart plugin `241.15845`

Flutter 3.19.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ba39319843 (6 weeks ago) • 2024-03-07 15:22:21 -0600
Engine • revision 2e4ba9c6fb
Tools • Dart 3.3.1 • DevTools 2.31.1

## Exception

null

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.flutter.actions.OpenInAppCodeAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.flutter]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**Comment by bc-lee** [comment] 2024-04-17 02:28
Duplicate of #7331.

**Closed** 2024-04-23 22:23 UTC
