### ISSUE TITLE
project keeps forgetting its flutter, requiring dart to be enabled on startup

### ISSUE THREAD

**Issue by james-lawrence** [flutter/flutter-intellij#2993] opened 2018-12-23 14:38 UTC
## Steps to Reproduce

everytime I restart android studio, i need to manually synchronize gradle and reenable dart support. shouldn't be necessary.

## Version info
```
[✓] Flutter (Channel beta, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at ${HOME}/development/flutter
    • Framework revision 5391447fae (3 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at ${HOME}/Android/Sdk
    • Android NDK at ${HOME}/Android/Sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = ${HOME}/Android/Sdk
    • Java binary at: ${HOME}/development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Android Studio (version 3.2.)
    • Android Studio at ${HOME}/development/android-studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by pq** [comment] 2018-12-25 14:55
I wonder if this is related to #2994?

**Comment by pq** [comment] 2018-12-25 14:56
I think this is likely due to #2994; closing and will follow-up there.

**Comment by stevemessick** [comment] 2019-09-06 16:14
> effectively this looks like the metadata telling android studio that its a flutter/dart application is getting mangled when gradle files are modified.

That's indeed what happens. It happens in the IntelliJ support for Gradle projects, and according to Jetbrains it is working as intended.

There's a work-around embedded in this PR, which should be available in the M40 release:
https://github.com/flutter/flutter-intellij/pull/3850

Further discussion is on this issue at Jetbrains:
https://youtrack.jetbrains.com/issue/WEB-40082

It looks like the "correct" solution might be to define a Dart plugin for Gradle, which knows how to preserve the Dart-specific metadata. I don't think that's going to happen anytime soon. Contributions welcome :)

**Closed by stevemessick** 2019-09-06 16:14 UTC
Labels: bug, topic-daily-work
