### ISSUE TITLE
The devices selector is stuck on "Loading..."

### ISSUE THREAD

**Issue by filiph** [flutter/flutter-intellij#4761] opened 2020-08-13 23:00 UTC
## Steps to Reproduce

This doesn't happen every time, but it happens more often than not. I open a Flutter project in Android Studio and I'm greeted with: 

<img width="254" alt="Screen Shot 2020-08-13 at 3 54 45 PM" src="https://user-images.githubusercontent.com/919717/90194997-55e5de80-dd7d-11ea-90cc-56054920021c.png">

Tapping the selector does nothing to remedy this:

<img width="192" alt="Screen Shot 2020-08-13 at 3 50 19 PM" src="https://user-images.githubusercontent.com/919717/90195047-6bf39f00-dd7d-11ea-90c6-b812e88f0163.png">

This is happening for minutes, if not forever.

The interesting part is that `flutter devices` works on the command line:

```sh
$ flutter devices 
2 connected devices:

Pixel 2 XL (mobile)            • 711KPZK05XXXXX            • android-arm64 •
Android 10 (API 29)
Filip Hracek’s iPhone (mobile) • 00008020-00067128XXXXXXXE • ios           • iOS
13.1.3
```

It seemingly doesn't matter what devices or how many I have connected. I mostly see this with only one device. This time, I have two devices.

## Version info

```sh
$ flutter doctor -v
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.20.1 at /Users/filiph/fvm/versions/stable
    • Framework revision 2ae34518b8 (8 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/filiph/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode_11.5.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • Pixel 2 XL (mobile)            • 711KPZK0XXXXXX            • android-arm64 • Android 10 (API 29)
    • Filip Hracek’s iPhone (mobile) • 00008020-0006XXXXXXX2002E • ios           • iOS 13.1.3

• No issues found!
```

**Comment by stevemessick** [comment] 2020-08-14 19:44
I believe this is fixed in Flutter plugin version 48. Could you update and let us know if the problem is solved?

**Comment by filiph** [comment] 2020-08-17 21:03
Ah, yes, I updated and it seems to work correctly.

Interesting that I had such an old version (45) installed. I thought the plugins auto-update, or at the very least ask to be updated. (On second thought, maybe they do and I just said "no".)

**Comment by stevemessick** [comment] 2020-08-17 21:48
There is an option to control whether it asks you to update. `Appearance & Behavior > System Settings > Updates` -- if that is enabled then it will prompt you to update.

**Closed by stevemessick** 2020-08-17 21:48 UTC
