### ISSUE TITLE
Issue in flutter and Android Studio

### ISSUE THREAD

**Issue by saitharun03** [flutter/flutter-intellij#7121] opened 2023-12-07 17:16 UTC
I am a Flutter developer utilizing Android Studio as my integrated development environment (IDE). After upgrading to the latest versions of Flutter (3.16.3) and Android Studio (Hedgehog | 2023.1.1), I encountered the following error:

"java.lang.IllegalStateException: configureNewProject should be used with new projects only"

This error arises when attempting to open the Android module in Android Studio for editing. Initially, the Android module opens without issues, but subsequent attempts result in the aforementioned error being displayed in the logs.

I've noticed similar posts on GitHub regarding this issue, indicating that I'm not the only one facing this problem. I've also posted the issue on GitHub for further visibility: [GitHub Issue Link](https://github.com/flutter/flutter-intellij/issues/7114).

I've spent the last four days grappling with this problem and haven't found a solution online. Despite reinstalling both Android Studio and Flutter and trying on different devices, the error persists. It seems like an uncommon issue, as I couldn't locate any relevant solutions. If anyone has a solution, please respond.

Thank you.

**Comment by jwren** [comment] 2023-12-13 21:14
Which version of the Flutter Plugin for IJ are you using?  Is this a duplicate of https://github.com/flutter/flutter-intellij/issues/7113 / https://github.com/flutter/flutter-intellij/issues/7115 which is now resolved?  Please update to `77.0+`.

**Comment by novikov-studio** [comment] 2023-12-16 17:33
Got the same error.

- Flutter 3.16.4 
- Android Studio Hedgehog | 2023.1.1
- Flutter Plugin: 77.1.2

**Comment by AdamBridges** [comment] 2023-12-22 18:42
I am also experiencing this issue:
https://github.com/flutter/flutter-intellij/issues/7154#issue-2054378347

**Comment by jorge2antibes** [comment] 2023-12-27 21:16
I'm also experiencing issue #7154

**Closed** 2023-12-28 00:23 UTC
Labels: waiting for customer response

**Comment by moodstubos** [comment] 2024-01-07 19:22
Duplicate of https://github.com/flutter/flutter-intellij/issues/7103.

**Comment by kingrmb** [comment] 2024-03-22 11:24
Android Studio Iguana | 2023.2.1 Patch 1

still have this problem

**Comment by E-sion** [comment] 2024-06-11 15:17
You just need to delete the '.idea' folder to open it.
(android - > .idea)
