### ISSUE TITLE
Device selector doesn't show physical iOS device with iOS 16.4.x

### ISSUE THREAD

**Issue by rivella50** [flutter/flutter-intellij#6751] opened 2023-05-13 20:09 UTC
After upgrading to Xcode 14.3 the device selector doesn't list my physical iOS device with iOS 16.4.1 anymore.
The same also happens on the command line, therefore i suppose that the device's list is populated with a similar command as `/usr/bin/arch -arm64 xcrun xcdevice list`.
Older iOS versions (like 15.7.x) are not targeted of this problems and are listed.

When switching back to Xcode 14.2 the iOS device is listed again and can be used for deployments of Flutter apps.

## Steps to Reproduce

Activate Xcode 14.3, connect a physical iOS device with version 16.4.x and press Refresh in the Flutter Device Selection dropdown, where the iOS device shouldn't appear.

## Version info

[!] Flutter (Channel stable, 3.7.11, on macOS 13.3.1 22E261 darwin-arm64, locale en-CH)
    • Flutter version 3.7.11 on channel stable at /Users/valley/fvm/versions/3.7.11
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.17.7/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/valley/fvm/versions/3.7.11. Consider adding /Users/valley/fvm/versions/3.7.11/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (5 weeks ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/valley/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/valley/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/valley/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 73.1.1
    • Dart plugin version 231.9065

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.92

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by rivella50** [comment] 2023-05-15 15:57
Unfortunately not. I'm trying to get over this issue for 2 weeks now and i don't have a clue what i could try else.
Also when i use a timeout in the call `arch -arm64e xcrun xcdevice list --timeout 20` the iPhone does not appear.

As mentioned when i switch to Xcode 14.2 (by using the Xcodes app, i.e. i have 2 Xcode versions installed) the iPhone appears in the console and also in the device selector, therefore i would say that Xcode 14.3 plays a role here.

**Comment by stevemessick** [comment] 2023-05-15 16:06
I don't think this is an issue that can be fixed by modifying the Flutter plugin. If it helps, it works with my Intel-chip Mac, so perhaps it has something to do with the Apple chip.

**Closed by stevemessick** 2023-05-15 16:06 UTC

**Comment by rivella50** [comment] 2023-05-15 16:39
This could be, yes. Thanks for your feedback.

**Comment by rivella50** [comment] 2023-06-23 07:31
@stevemessick Where can i see which commands the Flutter plugin uses to populate the device selector dropdown?

**Comment by oklimberg** [comment] 2023-08-17 11:44
I am currently also struggling with this issue.
I am using Xcode 14.3.1 on an Intel based Macbook running macOS 13.5 and Flutter 3.10.6
An iPhone SE 2nd gen running iOS  16.6 is correctly recognised, an iPad Pro 1st gen running iOS 16.6 is not..

I dug through the source code and in file xcdevice,dart line 161 you can see Flutter is using `xcrun xcdevice list --timeout 2` to find all connected devices.
I figured out, using `flutter run ... --verbose` would have revealed this as well.

When running the command, having Xcode 14.3 selected via `xcode-select`, the iPad does not show up in the list, when connected. However, when using command `xcrun xcdevice observe --both`, I get notified, whenever I connect or disconnect the iPad.

Selecting Xcode 14.2, the iPad will correctly show up.
```
  {
    "simulator" : false,
    "operatingSystemVersion" : "16.6 (20G75)",
    "interface" : "usb",
    "available" : true,
    "platform" : "com.apple.platform.iphoneos",
    "modelCode" : "iPad6,7",
    "identifier" : "XXX",
    "architecture" : "arm64",
    "modelUTI" : "XXX",
    "modelName" : "iPad Pro (12.9-inch) (Model A1584)",
    "name" : "iPad"
  },
```

Even though iOS 16.6 is not supported by Xcode 14.2, I can use this version to run a Flutter app on my iPad.
Wiping my iPad made no difference using Xcode 14.3.1.
I also downloaded the current Beta (6) of Xcode 15.0 and this issue seems to be fixed within the new Command Line Tools as well.

**Comment by oklimberg** [comment] 2023-08-17 16:20
Thanks for the hint about Beta 5 of Xcode 15.0. I might download that version to check if this version still contains my issue as well. I already checked the release notes of all Xcode 15.0 Betas briefly if they mentioned something related but did not find anything

**Comment by oklimberg** [comment] 2023-08-18 11:54
I just double checked with Beta 5 and Beta 6 again and the issue is still present in both versions. I probably messed up changing the Xcode version yesterday using xcode-select. I field a bug at Apple as well (FB12999487)

**Comment by rivella50** [comment] 2023-08-18 11:56
Ok, let's see if you have more luck. I'm pretty sure that other users also have these problems.
Let me know what they say.
