### ISSUE TITLE
Auto-imports do not follow Dart guidelines

### ISSUE THREAD

**Issue by ShivamArora** [flutter/flutter-intellij#3363] opened 2019-04-09 08:03 UTC
## Steps to Reproduce
1. Create a package within `lib` folder named `my_pkg`.
2. Create a dart file under `my_pkg` named `sample.dart`.
3. Now, when I try to use the `sample.dart` file in my `main.dart` and use auto-import feature to import the file, the file is imported in the following way:
```dart
import 'package:flutter_app/my_pkg/sample.dart';
```
4. The import works fine but it's not following the Usage Guidelines for the Dart language.
5. It should be imported as:
```dart
import 'my_pkg/sample.dart';
```

## What went wrong?
The Flutter Plugin isn't following the guidelines of dart language regarding imports.

You can take a look at the guideline regarding imports within the `lib` package:
[Prefer relative paths when importing libraries within your own packages lib directory](https://www.dartlang.org/guides/language/effective-dart/usage#prefer-relative-paths-when-importing-libraries-within-your-own-packages-lib-directory)

## Version info

Flutter Version:  1.2.1
Flutter Plugin Version: 34.0.1

**Comment by devoncarew** [comment] 2019-04-10 14:23
Thanks for the feedback; I agree with the issue.

**Comment by devoncarew** [comment] 2019-04-10 14:26
Closing as a dupe of https://github.com/dart-lang/sdk/issues/32916.

**Closed by devoncarew** 2019-04-10 14:26 UTC
