### ISSUE TITLE
When I'm missing a closing }, I'm told I'm missing a closing )

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter-intellij#719] opened 2017-02-08 22:53 UTC
(From a UX study)

For this syntax error:

```
    setState(() {
      var x = 1;
    );
```

Notice the missing closing `}`

However, the editor tells me I'm missing a closing `)`:

![screen shot 2017-02-08 at 2 52 05 pm](https://cloud.githubusercontent.com/assets/5479/22761131/49aee20e-ee0e-11e6-9855-8bdd353b1bb8.png)

**Comment by devoncarew** [comment] 2017-02-08 23:24
Can you add the version of the Dart plugin (and the dart sdk version) you're using? Thanks!

**Comment by sethladd** [comment] 2017-02-08 23:32
Sure!

![screen shot 2017-02-08 at 3 32 38 pm](https://cloud.githubusercontent.com/assets/5479/22762362/db74fbe2-ee13-11e6-8833-5e57f428cc1a.png)
![screen shot 2017-02-08 at 3 32 32 pm](https://cloud.githubusercontent.com/assets/5479/22762364/db7519d8-ee13-11e6-9e63-10bae6bea5e1.png)
![screen shot 2017-02-08 at 3 32 13 pm](https://cloud.githubusercontent.com/assets/5479/22762363/db75072c-ee13-11e6-8f94-4be501ae5021.png)

**Comment by devoncarew** [comment] 2017-02-08 23:54
You should update your plugin to the latest; we did have some changes in this area (we no longer report errors from the intellij parser, only from the analyzer).

> However, the editor tells me I'm missing a closing `)`

That message is actually saying `unexpected text ')'`, which I think is correct here (we're are also missing a '}').

**Comment by mit-mit** [comment] 2017-02-09 16:19
Closing working as intended.

Seth, generally please always keep both IJ and both plugins updates, and please help us advocate everyone updating all the time. We are trying to move super fast, which means lots of nice updates :-)

**Closed by mit-mit** 2017-02-09 16:19 UTC

**Comment by sethladd** [comment] 2017-02-09 16:34
I apologize I didn't see the update nag/popup.

**Comment by mit-mit** [comment] 2017-02-09 16:53
Oh, I totally understand (I think the nag dialog isn't quite naggy enough). Just saying that given that we probably need to do a bit of user education.

**Comment by sethladd** [comment] 2017-02-09 16:59
It turns out that for me, I had to update my IntelliJ before I saw the update prompts for the plugins. Once I reinstalled IntelliJ, the plugin update prompts came up.
