### ISSUE TITLE
After latest update: open for editing in android studio does not work anymore

### ISSUE THREAD

**Issue by merlijne77** [flutter/flutter-intellij#7138] opened 2023-12-13 18:29 UTC
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

pressing the button in file mainActivity: open for editing in android studio

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

/home/heidi/snap/flutter/common/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 3.10.2, on Ubuntu 22.04.3 LTS 6.2.0-37-generic, locale nl_NL.UTF-8)
    • Flutter version 3.10.2 on channel stable at /home/heidi/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (7 months ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/heidi/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /snap/android-studio/128/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (version 2023.1)
    • Android Studio at /snap/android-studio/136
    • Flutter plugin version 77.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2022.3)
    • Android Studio at /snap/android-studio/128/android-studio
    • Flutter plugin version 75.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64 • Android 13 (API 33) (emulator)
    • Linux (desktop)                       • linux         • linux-x64   • Ubuntu 22.04.3 LTS 6.2.0-37-generic

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
Process finished with exit code 0

**Comment by gnprice** [comment] 2024-01-04 00:33
Duplicate of #7103 (as well as #7101 and others).

**Closed by gnprice** 2024-01-04 00:33 UTC
