### ISSUE TITLE
flutter run default is hot reload enabled, but Run button in IntelliJ is release mode

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter-intellij#396] opened 2016-11-01 21:29 UTC
We have a conflict. :)

The default semantics of `run` in Flutter is "debug, with hot reload". However, it appears that the Run button in IntelliJ means "release build, no hot reload". I'd like to reconcile the default semantics of Run , for Flutter developers.

Suggestion: the Run button in the plugin triggers the same default semantics as `flutter run`.

The sentence, "to run your app, use `flutter run` or press the Debug icon in the plugin" is a bit confusing. Consider: "to run your app, use `flutter run` or press the Run icon in the plugin".

If we need to release build the app, which I assume is used less often, we could investigate a menu item or addition icons.

**Comment by sethladd** [comment] 2016-11-01 21:36
cc @mit-mit

**Comment by devoncarew** [comment] 2016-11-01 21:37
There's more discussion of this here: https://github.com/flutter/flutter-intellij/issues/362

**Comment by pq** [comment] 2016-11-02 12:10
> If we need to release build the app, which I assume is used less often, we could investigate a menu item or addition icons.

In general, how often do folks do a release build?  Do we have any analytics?

**Comment by lukechurch** [comment] 2016-11-02 13:02
+1 @sethladd 

'debugging' is not a separate activity in modern development workflows, especially ones with a live style of development. 'Releasing' might be.

**Comment by eseidelGoogle** [comment] 2016-11-02 13:14
We don't actually have a separate "release" step yet.  `flutter build ios
--release` is probably the closest we have, but even that doesn't build a
store-releasable ipa I don't think.  We may need to re-think the CLI modes
and how we expose them in the CLI and IDE.  We could for example never
build "release" from the IDE but only --debug and --profile so that we
always have observatory control.  And then have a separate "build an
install release" command in the menus somewhere".  We also could consider
splitting out the command line's run into separate "debug", "profile"
commands.  I guess what I'm saying is we can do a lot of different things
here if someone has a concrete/coherent proposal.

How changeable is IntelliJ's pattern here?  As luke suggests, having a
separate debug/run button is kinda dated to me.  Or certainly having your
default button imply "debug" seems that way to me.  What does AppCode or
AndroidStudio do?  Are those better IntelliJ-based models to follow?

**Comment by mit-mit** [comment] 2016-11-02 13:31
pq wrote:
> In general, how often do folks do a release build? 

The only data point I have is the Aplos team here in AAR. Maybe 'release build' is a misnomer, but they occasionally need to run in --release mode to get a "faster build" that enables gauging performance of scrolling, animations, etc.

**Comment by mit-mit** [comment] 2016-11-02 13:33
RE:
> How changeable is IntelliJ's pattern here?  

I don't think we can remove the standard Run and Debug actions, but not sure if we can add additional ones. I noticed Android Studio has a few additional buttons next the Run/Debug ones. PDX folks what can be customized in the main toolbar up where Run and Debug are?

**Comment by alexander-doroshko** [comment] 2016-11-02 13:49
Quoting my [comment](https://github.com/flutter/flutter-intellij/issues/362#issuecomment-255428129):
> As a rule Run/Debug difference is 'breakpoints do not work' / 'breakpoints work'. No difference in the executed app. The same about Run with Coverage or any other Run (yes, you can add other Run actions by implementing corresponding extension point, but not sure you need) - the app that is executed is the same regardless of the button that you press. I admit that there might be exceptions to the rule but they should be thought over carefully.
Run/debug modes are usually configured at Run Configuration level.

So yes, you can add more buttons. But as for now all runners (i.e. all buttons) are not framework specific. Each button (Run/Debug/Coverage) can start different types of apps. If your plugin is going to contribute another button - it will always be visible in all non-flutter projects as well (as disabled).
May be AppCode and Android Studio have specific runners, but they are technology-targeted IDEs.

**Comment by mit-mit** [comment] 2016-11-02 14:37
Thanks Alexander.

It's getting a bit confusing with discussions both here and in #362, so I am closing this bug as a dupe of #362.

**Closed by mit-mit** 2016-11-02 14:37 UTC
Labels: usability
