### ISSUE TITLE
Auto complete import is ignoring package imports

### ISSUE THREAD

**Issue by farkerhaiku** [flutter/flutter-intellij#4229] opened 2019-12-18 19:48 UTC
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Auto completing or importing any dart class imports using a relative path and ignores package imports already in the file.  This is very hard to explain without showing so I made a quicktime movie here: https://drive.google.com/file/d/18Su81io_M3zSYCK0enYr5F6vtBCZ_KOq/view?usp=sharing

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

~/checkout/flutter_expansion_games (feature/XWD-9527) $ flutter doctor -v
[✓] Flutter (Channel master, v1.13.3-pre.19, on Mac OS X 10.13.6 17G8037, locale en-US)
    • Flutter version 1.13.3-pre.19 at /Users/jason/Applications/flutter
    • Framework revision fa190a8685 (5 days ago), 2019-12-13 13:27:53 -0800
    • Engine revision e0e0ac0a68
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 45db297095)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/jason/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /Users/jason/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    ✗ Flutter requires a minimum Xcode version of 10.2.0.
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.5.3 out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on
        the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

**Comment by magillus** [comment] 2019-12-18 20:07
I have same issue on my Intellij.

**Comment by devoncarew** [comment] 2019-12-18 21:27
I think this is the same issue as https://github.com/dart-lang/sdk/issues/39848.

**Comment by magillus** [comment] 2019-12-18 22:01
I run into same issue also while trying same project on VSCode.

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.13.3-pre.23, on Microsoft Windows [Version 10.0.18362.476], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2017 15.9.18)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
[√] VS Code (version 1.39.2)
[√] VS Code, 32-bit edition (version 1.39.2)
[√] Connected device (4 available)

• No issues found!
```

**Comment by magillus** [comment] 2019-12-18 22:29
Fixed with those steps:
1. Switched to beta and back to master
2. clearing `.packages` `.dart_tool` directory and `pubspec.lock` 

Not sure what fixed this issue

**Comment by devoncarew** [comment] 2019-12-18 22:58
@scheglov, people on flutter master are seeing this issue; is it possible that the new support for .dart_tool/packages_config.json is related?

**Comment by magillus** [comment] 2019-12-18 23:22
I remember I had warning/error about `.dart_tool/packages_config.json` missing before and now as I think after fixing it I saw that issue.

**Comment by scheglov** [comment] 2019-12-19 00:55
I will work with this in https://github.com/dart-lang/sdk/issues/39848.

**Comment by scheglov** [comment] 2019-12-19 01:20
I cannot reproduce using the bleeding edge Dart SDK.

1. I downloaded the ZIP atchive as described on https://flutter.dev/docs/get-started/install/macos
2. Extracted it into `/Users/scheglov/Source/flutter`
3. Ran `flutter precache`
4. Ran `flutter doctor`
5. Ran `flutter update-packages`
6. Now I can open the whole Flutter repo and get completion with `package` URIs.

![image](https://user-images.githubusercontent.com/384794/71136730-8fe4ed80-21ba-11ea-834a-e864b8b2a828.png)

**Comment by devoncarew** [comment] 2019-12-20 17:53
Closing in favor of dart-lang/sdk#39848 - please track progress there.

**Closed by devoncarew** 2019-12-20 17:53 UTC

**Comment by DyaryRaoof** [comment] 2020-01-07 00:22
> Fixed with those steps:
> 
> 1. Switched to beta and back to master
> 2. clearing `.packages` `.dart_tool` directory and `pubspec.lock`
> 
> Not sure what fixed this issue

Thank you , Thank you , Thank you. This bug has been driving me crazy. I tried everything and searched quite a while . you are a life saver @magillus . I really would want to kiss you right now if it wasn't awkward.

**Comment by lFaustus** [comment] 2020-06-28 15:25
> Fixed with those steps:
> 
> 1. Switched to beta and back to master
> 2. clearing `.packages` `.dart_tool` directory and `pubspec.lock`
> 
> Not sure what fixed this issue

Thanks you. I have this problem for a month now after updating to new version of dart and flutter

**Comment by yeahse** [comment] 2020-12-20 12:17
@lFaustus 

hi, I don`t understand "clearing". it means deleting that files?

**Comment by lFaustus** [comment] 2020-12-28 22:10
> @lFaustus
> 
> hi, I don`t understand "clearing". it means deleting that files?

yes, deleting those file/folders
