### ISSUE TITLE
hot restart failed to complete: resume: (105) Isolate must be runnable Isolate must be runnable before this request is made.

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter-intellij#5406] opened 2021-04-13 16:27 UTC
## Steps to Reproduce
1, tap to run button
2, waiting for run success and tap to `flutter attach`
3, tap to hot restart

## Version info

```
[✓] Flutter (Channel unknown, 1.22.2, on macOS 11.2.3 20D91, locale en)
    • Flutter version 1.22.2 at /Users/minhtb2/dev/flutter
    • Framework revision 84f3d28555 (6 months ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2


[✓] Android toolchain - develop for Android devices (Android SDK version
    31.0.0-rc2)
    • Android SDK at /Users/minhtb2/Library/Android/sdk
    • Platform android-S, build-tools 31.0.0-rc2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.7759

[✓] VS Code (version 1.55.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API
      30) (emulator)

! Doctor found issues in 1 category.
```
<img width="366" alt="Screen Shot 2021-04-13 at 23 25 52" src="https://user-images.githubusercontent.com/52562340/114587203-9fd9e800-9caf-11eb-8a06-bbdd5a274223.png">

maybe only occur when open big project, I was test on small project and it work fine

**Comment by tbm98** [comment] 2021-04-13 16:28
it work fine in VSCode

**Comment by helin24** [comment] 2021-04-13 20:38
@tbm98 do you still have this issue if you update your flutter version? https://flutter.dev/docs/development/tools/sdk/upgrading

**Comment by tbm98** [comment] 2021-04-14 02:37
@helin24 I can't test on the latest version because it really big project and I can't migrate immediately

**Comment by tbm98** [comment] 2021-04-14 02:48
I just found a demo repo it lead this bug :D 
will feedback soon

**Comment by tbm98** [comment] 2021-04-14 02:58
@helin24  tap to restart button in debug tab is ok.
but tap to restart button in top bar or in run tab is occur error like this 
<img width="821" alt="Screen Shot 2021-04-14 at 09 55 49" src="https://user-images.githubusercontent.com/52562340/114647710-c62b7200-9d07-11eb-938e-b5693279c3ef.png">
<img width="787" alt="Screen Shot 2021-04-14 at 09 55 40" src="https://user-images.githubusercontent.com/52562340/114647723-c9bef900-9d07-11eb-8a6e-215e07f53db9.png">

dart: 2.12.2
flutter: 2.0.4

**Comment by tbm98** [comment] 2021-04-14 13:53
Seems it works fine when build ios

**Comment by helin24** [comment] 2021-04-14 16:53
Thanks for the additional detail! Are you able to provide access to the demo repo or a pared down version of it so we can reproduce the issue? (have not been able to reproduce with my projects)

**Comment by tbm98** [comment] 2021-04-15 02:37
Here you go [repo](https://github.com/tbm98/flutter_project_example)

**Comment by tbm98** [comment] 2021-04-15 07:25
I see the same issue when run ios. my mistake

**Comment by helin24** [comment] 2021-04-15 19:33
I'm not able to reproduce the problem with Dart 2.12.2 and Flutter 2.0.4. In your initial instructions you mention first pressing the run button and then needing to press flutter attach - is this what you do for the demo repo as well? (and if so, why does pressing flutter run not get you to the state where you have a running app that can be restarted?) I wonder if that could be why we have different outcomes - I was able to press the run (or debug) button and then hot restart once the app started up.

**Comment by tbm98** [comment] 2021-04-16 02:41
@helin24 I click on to `run` button and wait for it builds done, after that I click to `flutter attach` and wait for it attaches done. 
finally, I click again to `restart button` and an error occurs.

**Comment by tbm98** [comment] 2021-04-16 02:43
If you can't reproduce in flutter 2.0.4 vs dart 1.12.2 so can you try it on flutter 1.22.2 and dart 2.10. I think it is a bug from the plugin rather than from flutter because I tested it on VSCode but it works without error.

**Comment by helin24** [comment] 2021-04-16 16:48
Hmm... I actually get an error when I try to flutter run and then attach, so I'm not able to get to the point where hot restart is an option. Are these the two buttons you're using? First the one on the left, then the right one?
<img width="291" alt="Screen Shot 2021-04-16 at 9 44 16 AM" src="https://user-images.githubusercontent.com/6379305/115057218-a2e3fc80-9e98-11eb-810a-1d35bb6b52a0.png">

I'd like to understand why you're using flutter attach rather than using the debug button in the first place (the one to the right of run). Does your project use add to app?

**Comment by tbm98** [comment] 2021-04-19 03:23
> Hmm... I actually get an error when I try to flutter run and then attach, so I'm not able to get to the point where hot restart is an option. Are these the two buttons you're using? First the one on the left, then the right one?

Yes.



> Does your project use add to app?

No



> I'd like to understand why you're using flutter attach rather than using the debug button in the first place (the one to the right of run)

I think run debug by debug button not able to hot reload or hot restart, but I just use it again and see these feature in the bottom bar, from now on I will use it

**Comment by helin24** [comment] 2021-04-19 16:43
Okay great, I'm glad the recommended workflow is working for you now. Closing this issue.

**Closed by helin24** 2021-04-19 16:43 UTC
