### ISSUE TITLE
 `ActionUpdateThread.OLD_EDT` is deprecated

### ISSUE THREAD

**Issue by Reslak** [flutter/flutter-intellij#7390] opened 2024-04-26 07:32 UTC
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Standard Setup, Creating new Flutter Project, all plattforms iOS Swift Android Kotlin. Happened multiple times, main error was flutter not being whitelisted for git, causing flutter not to find git on path.
But this is not the deprecated error detailed below :)

## Version information
IntelliJ IDEA 2024.1 • Flutter plugin io.flutter 79.0.3 • Dart plugin 241.15845

Error getting Flutter sdk information.

Exception
null

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.flutter.actions.FlutterBuildActionGroup' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.flutter]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

**Comment by jwren** [comment] 2024-05-14 19:56
Duplicate of https://github.com/flutter/flutter-intellij/issues/7330

**Closed by jwren** 2024-05-14 19:56 UTC
