### ISSUE TITLE
[Editor] Hierarchy lines of widgets are overflowed randomly

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter-intellij#6606] opened 2023-02-05 06:04 UTC
![image](https://user-images.githubusercontent.com/15884415/216804430-2d57fdbb-fedf-4a10-acd4-7204cb4f60cb.png)

```
[✓] Flutter (Channel stable, 3.3.10, on Microsoft Windows [版本 10.0.22000.1455], locale zh-CN)
    • Flutter version 3.3.10 on channel stable at X:\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (8 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at X:\IDEs\apps\IDEA-U\ch-0\223.8617.56
    • Flutter plugin version 72.0.4
    • Dart plugin version 223.8617.8
```

**Comment by AlexV525** [comment] 2023-02-07 17:19
> Your lines are colored; mine are not (in dark or light mode). How does that happen?

I'm using the *Rainbow Brackets* plugin that will color brackets. Tried to disable it and it doesn't relate to the issue.

> Does this problem occur if you un-check the setting to control IntelliJ indent guides? (`Editor > General > Appearance > Show indent guides`)

This is new, when I unchecked the checkbox and applied, an exception was thrown:
<details>

```
Access is allowed from event dispatch thread only

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false
Current thread: Thread[JobScheduler FJ pool 6/15,4,main] 1360178123
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 350117142
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1067)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1050)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.removeHighlighter(MarkupModelImpl.java:217)
	at com.intellij.openapi.editor.impl.RangeHighlighterImpl.unregisterInTree(RangeHighlighterImpl.java:449)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.dispose(RangeMarkerImpl.java:93)
	at io.flutter.editor.FilteredIndentsHighlightingPass.cleanupHighlighters(FilteredIndentsHighlightingPass.java:310)
	at io.flutter.editor.WidgetIndentsHighlightingPassFactory.createHighlightingPass(WidgetIndentsHighlightingPassFactory.java:218)
	at com.intellij.codeInsight.daemon.impl.TextEditorHighlightingPassRegistrarImpl.instantiatePasses(TextEditorHighlightingPassRegistrarImpl.java:193)
	at com.intellij.codeInsight.daemon.impl.TextEditorBackgroundHighlighter.getPasses(TextEditorBackgroundHighlighter.java:75)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$21(DaemonCodeAnalyzerImpl.java:1055)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:898)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$22(DaemonCodeAnalyzerImpl.java:1045)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.submitInBackground(DaemonCodeAnalyzerImpl.java:1042)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$17(DaemonCodeAnalyzerImpl.java:1012)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

</details>

The problem is gone because no lines will be displayed anymore. But when enabled the issue repro again.

> And, just to be thorough, do you have the Flutter setting enabled? (`Languages and Frameworks > Flutter > Show UI Guides for build methods`)

Yes it's enabled.

**Comment by stevemessick** [comment] 2023-02-07 17:46
It appears that the lines that are displaying incorrectly are controlled by the IntelliJ setting, not the Flutter plugin setting. (Let me know if I misunderstood.)

I'll have to check how those lines are drawn. It seems like it should be done by a plugin, but might be Dart.

**Comment by stevemessick** [comment] 2023-02-09 18:08
This is done by the Dart plugin. I think the incorrect lines are always drawn below a left paren. (If not, then my guess as to how it is drawn is wrong, but it is still in the Dart plugin.) I suspect the code that does this was not updated after the Dart plugin stopped using its own formatter.

I created https://youtrack.jetbrains.com/issue/WEB-59450/Dart-indent-guides-anomaly

**Comment by alexander-doroshko** [comment] 2023-02-09 20:10
The Dart plugin itself doesn't draw any lines in the editor. It might be IntelliJ's feature "Indent guides", which works for all languages (it actually doesn't care about language, it works just with text).

@AlexV525  The video shows flashing code highlighting and jumping indent guides, which stabilize in 1-2 seconds. So, is this issue about flashing or about wrong indent guides that stay for a long time?

I mean, the screenshot from the issue description shows incorrect indent guides, but was this incorrect state stable or it got fixed in 1-2 seconds?

What is your Dart plugin version?

**Comment by AlexV525** [comment] 2023-02-09 20:32
> @AlexV525 The video shows flashing code highlighting and jumping indent guides, which stabilize in 1-2 seconds. So, is this issue about flashing or about wrong indent guides that stay for a long time?
> I mean, the screenshot from the issue description shows incorrect indent guides, but was this incorrect state stable or it got fixed in 1-2 seconds?

The first time I saw this it's under a stable situation, that formats didn't help it corrects the line. By the second time that I was tweaking about settings it can only show during formatting.

> What is your Dart plugin version?

I've added in the top comment.

**Comment by alexander-doroshko** [comment] 2023-02-10 12:50
To investigate stable situation with incorrect indent guides we need to be able to reproduce it. If you find steps to reproduce, please let us know.

Flashing on reformat is probably not so severe as it gets back to correct state in 1-2 seconds. But I agree it's annoying. Is it possible to attach a file, in which this flashing is easy to reproduce?

**Comment by AlexV525** [comment] 2023-02-10 13:43
I'll attach more info if I can repro it easily, thanks.

**Comment by AlexV525** [comment] 2023-02-10 17:05
I think it's file related, I can see multiple overflows in my project, but if I copy the whole file or the text in the file into another one, the line will not overflow.

![image](https://user-images.githubusercontent.com/15884415/218152179-1373c119-7500-4f9c-b4d6-21eeb01f7dcd.png)

**Comment by alexander-doroshko** [comment] 2023-02-10 17:08
Will disabling Rainbow Brackets plugin make any difference?

**Comment by alexander-doroshko** [comment] 2023-02-10 17:10
If not, will disabling `Languages and Frameworks > Flutter > Show UI Guides for build methods` change anything?

**Comment by AlexV525** [comment] 2023-02-10 17:47
Both are not making difference here. The situation is more strange now, every time I open the file, lines are correctly drawn, but after I run format with <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>L</kbd>, the line went across again. Also, the latest one was tested on macOS, and the previous one is on Windows.

**Comment by alexander-doroshko** [comment] 2023-02-10 22:22
Thanks for checking. So, looks like I need a file/project that I could use to reproduce it. If it contains sensitive data, you may attach it to the issue ([https://youtrack.jetbrains.com/issue/WEB-59450](https://youtrack.jetbrains.com/issue/WEB-59450)) as visible to jetbrains-team only.

**Comment by AlexV525** [comment] 2023-02-11 06:51
I'm currently AFK, will attach the project soon as I get back. Thanks!

**Comment by AlexV525** [comment] 2023-02-14 03:42
Now I can reproduce the same file both on Windows and macOS. Sending the project, please refer to `lib/connections/ic/nft/dip_721_service.dart#L61`.

**Comment by AlexV525** [comment] 2023-02-14 03:44
The issue is visible to issue readers, however.

**Comment by AlexV525** [comment] 2023-02-14 05:47
Also see the top comment for the compatible Flutter version, this project hasn't adapted to the latest Flutter yet.

**Closed** 2023-02-23 06:14 UTC
Labels: dependency: dart plugin

**Comment by alexander-doroshko** [comment] 2023-02-23 09:28
Yes, it's not a Flutter plugin problem, no need to track it here. The Flutter plugin has "Show UI Guides for build methods" feature but it's not the problematic one from the screenshot.
