### ISSUE TITLE
Devices Selection stuck at Loading

### ISSUE THREAD

**Issue by varunpvp** [flutter/flutter-intellij#4670] opened 2020-06-28 20:11 UTC
Hello Everyone,

## Steps to Reproduce

I'm unable to see the connected devices in the devices dropdown. It's stuck at loading.

![Screenshot 2020-06-29 at 1 39 29 AM](https://user-images.githubusercontent.com/16759053/85957247-6dbdfa80-b9a9-11ea-923a-b8365fe4261c.png)

But I can see the device when I run `flutter devices`.

command `flutter devices`

```
1 connected device:

RMX1921 • 5c7df826 • android-arm64 • Android 10 (API 29)

```

## Version info

command `flutter doctor -v`

```
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.3 19D76, locale en-IN)
    • Flutter version 1.17.4 at /Users/kinggaming/flutter
    • Framework revision 1ad9baa8b9 (11 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/kinggaming/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0

[✓] Connected device (1 available)
    • RMX1921 • 5c7df826 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

Please, let me know if you need more info from my side.
Thanks in advance.

**Comment by pmutisya** [comment] 2020-06-29 02:26
I have the same issue.  It has been open before, in issues #3892 and #4014.

The problems only exists on intellij plugins. The same project works on Visual Studio Code. FYI, the problem consistently happens on an older (slower) mac mini but never on a new, faster macbook pro, which supports the theory that it is a threading problem.

**Comment by helin24** [comment] 2020-06-30 00:07
Duplicate of https://github.com/flutter/flutter-intellij/issues/4642

**Closed by helin24** 2020-06-30 00:07 UTC

**Comment by tisu2tisu** [comment] 2023-03-03 04:01
i fixed by uninstalling/deleting flutter folder, installing powershell 5.1 cause im using windows 7 SP1 ,then run flutter doctor. and its working now, the device became avaiable
its seems like the problem is , im using windows 7 which is only has powershell Version 2, but in order to upgrade dart, you need powershell 5.0 or 5.1, this is main problem, if dart failed to upgrade, it will became no devices or devices selection stuck at loading in your android studio. i hope its help you guys
