### ISSUE TITLE
Hi,how to add hint after this mark ")" ?

### ISSUE THREAD

**Issue by bladeofgod** [flutter/flutter-intellij#3498] opened 2019-05-17 03:08 UTC
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

i got a hint problem: my hint that the after ")", is disappeared, and i checked the setting of AS,cant restore it . so plz tell me how to fix this problem.
thanks a lot. :)

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by devoncarew** [comment] 2019-05-20 17:44
Hi @bladeofgod, I'm not quite sure what problem you're experiencing; can you elaborate?

**Comment by bladeofgod** [comment] 2019-05-22 04:18
@devoncarew  Thanks for your reply, 
my problem is like this :
 Container(
child: ...
) container // now i dont have this 'container' hint.

;)

**Comment by alexander-doroshko** [comment] 2019-05-22 09:43
https://github.com/flutter/flutter-intellij/issues/3502

**Comment by devoncarew** [comment] 2019-05-22 15:11
Thanks for the report @bladeofgod (and thanks Alex for the help triaging :) ). Marking as a dupe of https://github.com/flutter/flutter-intellij/issues/3502.

**Closed by devoncarew** 2019-05-22 15:11 UTC
