### ISSUE TITLE
Open in DevTools not working on Windows

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter-intellij#3753] opened 2019-08-09 06:28 UTC
I was looking the Flutter Performance window, seeing the Frame times bar graph and once I click the Open in DevTool link, Firefox does open it, but it just can't connect. I tried to open it also on Chrome and it failed was well, Flutter Performance window is working fine though.

**Comment by stevemessick** [comment] 2019-08-09 14:08
@terrylucas might want to investigate.

**Comment by kenzieschmoll** [comment] 2019-08-09 15:17
When you say "it failed", which part of the pipeline are you referring to? 

Did the Chrome browser open at all? Did DevTools launch but hung on the "Loading..." screen? If DevTools did open, can you look at the web page console and see if any errors are visible? Thanks.

Also, at this time, we only support Chrome for DevTools as it is the only browser we test with. Eventually, we will port the devtools app to flutter web, at which point we will be able to test in multiple browsers.

**Comment by feinstein** [comment] 2019-08-09 15:22
I am at my phone now, so I will answer what I can for now.

Both Firefox and Chrome open the website, but show a text box for the Port to connect. Once I type the port printed at the IntelliJ console, the browser shows a message on the lower right corner saying it can't connect with the port. 

I should have provided more info at the time, it was just so late I didn't realize.

On a side note, can't you make the plug-in open in chrome directly if it's installed on the machine? Not the default browser.

**Comment by kenzieschmoll** [comment] 2019-08-09 15:26
Interesting. When you are back at your computer, it would be great if you could report the version of the Flutter IntelliJ plugin you are using. If you are not on the latest version, please update your plugin and see if the issue still occurs.

The Open DevTools button is intended to launch chrome explicitly, and to automatically connect to the URI of your running flutter application. 

If upgrading your flutter intellij plugin does not work, it would be helpful it you could provide the text you are trying to paste into the connect dialog, as well as the preloaded URL of the DevTools page.

**Comment by feinstein** [comment] 2019-08-09 15:34
I believe I have the latest version, since I updated it yesterday, as I wanted the fixes for the guidelines and tests buttons, but I will double check it, maybe the error was before I updated, can't remember tbh.

**Comment by feinstein** [comment] 2019-08-09 17:23
- Flutter plugin version 38.2.4.

- This is the URL it opens in Firefox: 
http://127.0.0.1:43967/?ide=IntelliJ-IDEA&uri=http%3A%2F%2F127.0.0.1%3A52953%2FsGsZVCFrF_s%3D#timeline

- Flutter tool command:
C:\Programacao\Flutter\sdk\flutter\bin\flutter.bat --no-color packages pub global run devtools --machine --port=0
{"method":"server.started","params":{"host":"127.0.0.1","port":43967}}

- No outputs on the Chrome console when I try to load the URL 

- When type port 43967 and click Connect, I get this:

>WebSocket connection to 'ws://localhost:43967/ws' failed: Error during WebSocket handshake: Unexpected response code: 404

  I got a similar console output on Firefox, basically the same intent, but a different message, as those are errors from the browser itself.

![image](https://user-images.githubusercontent.com/8120472/62797126-43253380-bab1-11e9-86ef-4178ff075c9a.png)

**Comment by kenzieschmoll** [comment] 2019-08-09 17:31
Sounds like the issue here is that the link is not opening Chrome by default. Is Firefox set as your default browser? 

The connect issue you are seeing sounds like it is due to inputting the wrong text to the connect dialog. The port number you found is actually the port that DevTools is hosted on, but not the port for connecting to your flutter app. Connecting to your app requires a uri with a security token. This uri is the one that can be seen in the url you reported for firefox: `http%3A%2F%2F127.0.0.1%3A52953%2FsGsZVCFrF_s%3D`

If you paste that into the connect dialog for chrome, it should connect just fine. Optionally, you can also copy the URL you were launched to in Firefox and just open it in Chrome.

**Comment by kenzieschmoll** [comment] 2019-08-09 17:41
We have a tracking issue for this here: https://github.com/flutter/flutter-intellij/issues/3503. Please let us know if the fixes I suggested in my last comment work for you for the time being 👍

**Comment by feinstein** [comment] 2019-08-09 17:42
> Sounds like the issue here is that the link is not opening Chrome by default. Is Firefox set as your default browser?

Yes.

> If you paste that into the connect dialog for chrome, it should connect just fine. 

It doesn't:

![image](https://user-images.githubusercontent.com/8120472/62797853-212cb080-bab3-11e9-8b3e-29a66026bb1b.png)

This is the full URL: http://127.0.0.1:43967/?ide=IntelliJ-IDEA&uri=http%3A%2F%2F127.0.0.1%3A52953%2FsGsZVCFrF_s%3D#timeline

I tried to paste: 

- http%3A%2F%2F127.0.0.1%3A52953%2FsGsZVCFrF_s%3D 

And a decoded versions:

- http://127.0.0.1:52953/sGsZVCFrF_s= 
- http://127.0.0.1:52953/sGsZVCFrF_s=#timeline

It didn't work.

>Optionally, you can also copy the URL you were launched to in Firefox and just open it in Chrome.

Sorry if I didn't made it clear in my last post, but I opened Chrome with the same URL that was sent to Firefox.

**Comment by kenzieschmoll** [comment] 2019-08-09 17:49
It looks like this may be another bug. The content of the timeline page should not be showing if you are not connected to your app. Open a tab to http://127.0.0.1:43967/?ide=IntelliJ-IDEA&uri=http%3A%2F%2F127.0.0.1%3A52953%2FsGsZVCFrF_s%3D#timeline, and if you still see the connect dialog, try switching to different pages of DevTools. 

Also, if you do something in your app right now, do frames draw in the timeline view?

**Comment by feinstein** [comment] 2019-08-09 18:03
> It looks like this may be another bug. 

So reopen this Issue?

>The content of the timeline page should not be showing if you are not connected to your app. Open a tab to http://127.0.0.1:43967/?ide=IntelliJ-IDEA&uri=http%3A%2F%2F127.0.0.1%3A52953%2FsGsZVCFrF_s%3D#timeline, and if you still see the connect dialog, try switching to different pages of DevTools.

I am sorry, but how's this different than what I just did? I sent you a picture of this exact URL opened in a Chrome tab. Anyway, I opened it again in another tab, now I have 2 of them, both the same, equal, with the connect button. My Chrome is also updated as well. Can't you reproduce this? Don't you have any Windows 10 machines for QA? If you want I can share my screen with you.

It looks like all the development is focused on Macs, as it also looks like its the preferred choice among the Flutter team, but I hardly think the majority of Flutter developers around the world code on Macs. I honestly appreciate deeply all the work you guys do, can't stress this enough, but after the Bugs on version 37, I honestly think you guys should do a postmortem and think about improving your Windows QA before a release.

> Also, if you do something in your app right now, do frames draw in the timeline view?

No.

**Comment by kenzieschmoll** [comment] 2019-08-12 17:00
Hi, Michel. I wasn't able to reproduce this issue on Windows 10 with the latest IntelliJ/Flutter-IntelliJ plugin/DevTools setup.

```
IntelliJ IDEA Community Edition (version 2019.2)
Flutter plugin version 38.2.4
DevTools version 0.1.5
Default browser: Firefox
```

1. Run flutter app
2. Open Dart DevTools from run menu![open_devtools](https://user-images.githubusercontent.com/43759233/62882519-e612c300-bce6-11e9-9c47-ab0979b3d849.png)
3. Observe DevTools is launched in FireFox
![Firefox](https://user-images.githubusercontent.com/43759233/62882598-1c504280-bce7-11e9-97e0-1fe96e94a8a8.png)

4a. Copy entire URL into Chrome tab and observe DevTools connects as expected
![Chrome](https://user-images.githubusercontent.com/43759233/62882657-3c800180-bce7-11e9-9d80-fdc32203a1b1.png)
OR
4b. Open a chrome tab to `127.0.0.1:[port number from firefox url]`. Now copy uri parameter from Firefox URL and paste it into the connect dialog in your Chrome tab.
![chrome connect dialog](https://user-images.githubusercontent.com/43759233/62882716-5f121a80-bce7-11e9-88de-b5a715c09a8d.png)

If you follow these steps, you should be able to connect. If you are still having trouble, perhaps there is something off with your local configuration? The only other options I can suggest are to restart IntelliJ and your machine.

**Comment by feinstein** [comment] 2019-08-12 17:06
Hi Kenzie, I am away from my computer right now, could you try it in another way?

Click to Debug your app, then click the Flutter Inspector tab, go to Performance, it will open a new dock window with the performance bar graph showing the screen updates, then there will be a blue text saying to open in DevTools, try this one, this is how I did it. 

Thanks!

**Comment by kenzieschmoll** [comment] 2019-08-12 17:50
All ways to open DevTools from IntelliJ trigger the same code path. I did, however, try the exact way you instructed and I can confirm this also worked as expected. When you get a chance, please try the steps in my previous comment, and then if that still doesn't work, restart IntelliJ, Chrome (which you can do by typing `chrome://restart` in the Chrome URL), and your machine and see if that helps.

**Comment by feinstein** [comment] 2019-08-12 20:31
I restarted my computer, opened IntelliJ and clicked the debug button, then waited my app to lunch. After that I clicked on `See Flutter Performance window` and there I selected Open in DevTools. I did this way because I don't have this dart icon on my Run menu:

![image](https://user-images.githubusercontent.com/8120472/62896112-b2f02400-bd26-11e9-9112-914741c2ec4d.png)

So again, it doesn't work:

![image](https://user-images.githubusercontent.com/8120472/62896023-8d631a80-bd26-11e9-86a8-723f92502f7a.png)

**Comment by kenzieschmoll** [comment] 2019-08-12 23:28
Your DevTools version should be printed in the chrome devtools console (which you can open on Windows by pressing `Control + Shift + J` inside the chrome browser).

But based on your screenshot, it doesn't look like you are on the latest - which should happen automatically when you launch from IntelliJ.

@jacob314 do you have any other ideas here?

**Comment by feinstein** [comment] 2019-08-15 01:09
I opened the Chrome console and there's nothing there. `Control + Shift + J`, loaded, reloaded, etc. nothing. Any other way to check the version?

**Comment by feinstein** [comment] 2019-08-15 03:16
One more thing to add, I found the Open Dart DevTools you mentioned, but here instead:

![image](https://user-images.githubusercontent.com/8120472/63070468-b1bf2280-bef1-11e9-9f1c-8fa3c0639401.png)

And when I click it, IntelliJ triggers this process (There are 2 because I clicked twice):

![image](https://user-images.githubusercontent.com/8120472/63070372-50974f00-bef1-11e9-83ab-bec2eb85231f.png)

I was expecting it to update the DevTools and fix this, but it didn't, same issue persists.

**Comment by helin24** [comment] 2021-05-13 22:20
This should be fixed; feel free to open a new issue if this does not work on Windows (since we've changed this significantly since 2019).

**Closed by helin24** 2021-05-13 22:20 UTC
