### ISSUE TITLE
Newly created flutter project shows broken pub banner

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter-intellij#336] opened 2016-10-19 15:27 UTC
I suspect this will be fixed by https://github.com/flutter/flutter-intellij/issues/271, but in case not I'm filing here.

I'm not even sure the banner is needed, but it shows up and then the buttons don't actually do what you want.
<img width="732" alt="screen shot 2016-10-19 at 8 24 31 am" src="https://cloud.githubusercontent.com/assets/11857803/19525450/cfb2d234-95d5-11e6-9d30-b05063a3fdda.png">

**Comment by pq** [comment] 2016-10-19 16:08
Right.  There are (at least) two issues:

1. the pub banner shows even though we've run pub behind the scenes in `flutter create` --- maybe @alexander-doroshko can chime in on what we might do here...
1. `pub get` doesn't do the right thing for Flutter w/o some massaging --- as you note, this is fixed with #271 and will work as soon as a new Dart plugin is pushed

Thanks!

**Comment by alexander-doroshko** [comment] 2016-10-19 16:15
1. Banner is shown if there's no `.packages` file near `pubspec.yaml` or if `.packages` file is older than pubspec.
1. I guess you want me to cherry-pick that fix to 162 branch and update the Dart plugin?

**Comment by pq** [comment] 2016-10-19 16:22
> Banner is shown if there's no .packages file near pubspec.yaml or if .packages file is older than pubspec.

Ah.  That makes sense.  What's odd is that I can repro this with a project that looks like this:

```
[~] $ ls -alT
total 56
drwxr-xr-x  14 pquitslund  eng   476 Oct 19 09:18:53 2016 .
drwxr-xr-x  12 pquitslund  eng   408 Oct 19 09:18:52 2016 ..
drwxr-xr-x   3 pquitslund  eng   102 Oct 19 09:17:55 2016 .atom
-rw-r--r--   1 pquitslund  eng    84 Oct 19 09:17:55 2016 .gitignore
drwxr-xr-x   8 pquitslund  eng   272 Oct 19 09:18:53 2016 .idea
-rw-r--r--   1 pquitslund  eng  1599 Oct 19 09:17:59 2016 .packages
-rw-r--r--   1 pquitslund  eng   154 Oct 19 09:17:55 2016 README.md
drwxr-xr-x   4 pquitslund  eng   136 Oct 19 09:17:55 2016 android
-rw-r--r--   1 pquitslund  eng    48 Oct 19 09:17:55 2016 flutter.yaml
drwxr-xr-x  10 pquitslund  eng   340 Oct 19 09:17:55 2016 ios
drwxr-xr-x   3 pquitslund  eng   102 Oct 19 09:17:55 2016 lib
-rw-r--r--   1 pquitslund  eng  2290 Oct 19 09:17:59 2016 pubspec.lock
-rw-r--r--   1 pquitslund  eng    99 Oct 19 09:17:55 2016 pubspec.yaml
-rw-r--r--   1 pquitslund  eng   518 Oct 19 09:18:53 2016 untitled6ahaga.iml
```
I would expect this to be OK since `pubspec.yaml` is older than `.packages`?


> I guess you want me to cherry-pick that fix to 162 branch and update the Dart plugin?

If possible that would be awesome!

**Comment by pq** [comment] 2016-10-19 16:25
_(Edited my previous comment for correctness.)_

@eseidelGoogle : could you confirm that there's a `.packages` file next to your pubspec and that it's indeed newer?

**Comment by eseidelGoogle** [comment] 2016-10-19 16:53
@pq I'm not sure what you're asking for?  This is the list from the project I filed this from, but it's been run, etc. since so I'm sure the timestamps are no longer useful to you.  You can just follow the "create a project" flow in intellij to test yourself.

```
drwxr-xr-x  15 eseidel  wheel   510 Oct 19 08:30:17 2016 .
drwxr-xr-x  59 eseidel  wheel  2006 Oct 19 08:24:05 2016 ..
drwxr-xr-x   3 eseidel  wheel   102 Oct 19 08:24:11 2016 .atom
-rw-r--r--   1 eseidel  wheel    84 Oct 19 08:24:11 2016 .gitignore
drwxr-xr-x   8 eseidel  wheel   272 Oct 19 09:09:51 2016 .idea
-rw-r--r--   1 eseidel  wheel  1445 Oct 19 08:24:14 2016 .packages
-rw-r--r--   1 eseidel  wheel   151 Oct 19 08:24:11 2016 README.md
drwxr-xr-x   4 eseidel  wheel   136 Oct 19 08:24:11 2016 android
-rw-r--r--   1 eseidel  wheel   518 Oct 19 08:24:44 2016 dart_summit.iml
-rw-r--r--   1 eseidel  wheel    45 Oct 19 08:24:11 2016 flutter.yaml
drwxr-xr-x   7 eseidel  wheel   238 Oct 19 08:30:23 2016 flutter_build
drwxr-xr-x  12 eseidel  wheel   408 Oct 19 08:30:18 2016 ios
drwxr-xr-x   3 eseidel  wheel   102 Oct 19 08:50:49 2016 lib
-rw-r--r--   1 eseidel  wheel  2305 Oct 19 08:24:14 2016 pubspec.lock
-rw-r--r--   1 eseidel  wheel    96 Oct 19 08:24:11 2016 pubspec.yaml
```

**Comment by pq** [comment] 2016-10-19 16:59
Thanks @eseidelGoogle.  This is actually what I was asking for.  I did the flow locally, had similar timestamps but did _not_ see the broken pub banner (but have in the past).  Investigating further...

**Comment by pq** [comment] 2016-10-19 17:02
@alexander-doroshko : looking at the where this error is created, I wonder if the issue isn't that we're creating the file in a separate process and need to do a file system refresh to pick it up?

In other words,  maybe the `findChild(...)` call here

```
    final VirtualFile dotPackagesFile = pubspecFile.getParent().findChild(DotPackagesFileUtil.DOT_PACKAGES);

    if (dotPackagesFile == null) {
      return createProblemDescriptors(manager, psiFile, pubspecFile, DartBundle.message("pub.get.never.done"));
    }
```

should be replaced with a call to `LocalFileSystem.getInstance().refreshAndFindFileByPath(...)`?

**Comment by alexander-doroshko** [comment] 2016-10-19 17:07
Yes, it looks like a race. Refresh may not help as file may be open in editor when .packages is not created yet. To avoid race after Dart project creation we have `DartPubActionBase.isInProgress()` check but it doesn't work for Flutter. Need to think more.

**Comment by pq** [comment] 2016-10-19 17:16
Great.  Thanks for giving this thought!

**Comment by pq** [comment] 2016-11-02 12:52
@alexander-doroshko : curious if you have any more thoughts on this one?

**Comment by alexander-doroshko** [comment] 2016-11-02 12:59
See `com.jetbrains.lang.dart.ide.inspections.DartOutdatedDependenciesInspection#checkFile` and `com.jetbrains.lang.dart.ide.actions.DartPubActionBase#isInProgress`. Without changes at Dart plugin side I see no way to skip showing `'Pub get' has not been run` while `flutter create` is in progress.

**Comment by pq** [comment] 2016-11-02 13:26
Exactly.  I was thinking this would require some changes in the Dart plugin as well.  I'm curious how you think this would be easiest.  Could we simply disable this test in the case of Flutter modules?  (And defer to Flutter to ensure that pub gets properly run?)

**Comment by alexander-doroshko** [comment] 2016-11-02 13:38
May be introduce setter like `DartPubActionBase#setPubIsInProgress(boolean)` and use it in flutter plugin like:
```
try {
  DartPubActionBase.setPubIsInProgress(true);
  flutterCreate();
}
finally {
    DartPubActionBase.setPubIsInProgress(false);
}
```

**Comment by mit-mit** [comment] 2016-12-08 12:07
Moving to 0.1.7, I hit this again several times today as mentioned in #508

**Comment by mit-mit** [comment] 2016-12-08 12:08
CC @pq would be good to get this one moving.

**Comment by pq** [comment] 2016-12-08 14:14
Thanks for the nudge @mit-mit !

I've got a PR out to update the Dart plugin as @alexander-doroshko suggests: https://github.com/JetBrains/intellij-plugins/pull/452 but as I look at calling this method from the Flutter side I recall that @devoncarew mentioned some classloader issues I may want to consider?

I was planning to do simple reflection like:

    DartPubActionBase.class.getMethod("setIsInProgress");

but now I'm thinking this will just pull in the class defined in the Dart jar (and not the loaded plugin).  Is that right?

/cc @devoncarew @alexander-doroshko

**Comment by alexander-doroshko** [comment] 2016-12-08 14:25
There are no class loader issues with using public classes/methods.
You can't make cross-plugin package-local calls because package-local things are not visible from a different class loader.
No reflection please :)

**Comment by pq** [comment] 2016-12-08 14:35
> No reflection please :)

I was hoping to use reflection so that I could write code that would work with the current plugin and just get better when a new Dart Plugin is available.  (This is such a small feature I didn't think it justified bumping our minimum requirement on the Dart version.)  Not hugely invested either way.

My question was probably a misunderstanding though. I realize now that at runtime we're probably not loading classes from the Dart plugin jars in the Flutter plugin and that those are just there for development.  Or maybe I'm even more confused.  (Very possible without coffee! ☕️ )

**Comment by devoncarew** [comment] 2016-12-13 17:22
We've landed the fix for this in the Dart plugin (we'll then need to make corresponding fixes in the Flutter plugin).

**Comment by devoncarew** [comment] 2016-12-13 17:23
(we need to patch the fix to the dart plugin into the current stable release)

**Comment by pq** [comment] 2016-12-13 18:21
Confirmed that the Dart plugin fixes are *not* in the latest plugin so this is blocked until the next push.

**Comment by pq** [comment] 2016-12-21 18:10
Looks like this didn't make it into `163.10154.19` either but should be in the next one.

**Comment by pq** [comment] 2016-12-21 18:16
WIP: https://github.com/pq/flutter-intellij/tree/pub_set_in_progress --- pending new Dart Plugin.

**Closed** 2017-01-03 23:53 UTC
Labels: bug, dart plugin, high priority, question, usability
