### ISSUE TITLE
Flutter Inspector's "Select Widget" mode not working with CupertinoApp

### ISSUE THREAD

**Issue by RedBrogdon** [flutter/flutter-intellij#2572] opened 2018-08-29 19:47 UTC
I have this code in an otherwise empty project:

```dart
import 'package:flutter/cupertino.dart';

void main() {
  runApp(new DogApp());
}

class DogApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'Test',
      home: HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      color: Color(0xffffffff),
      child: Center(
        child: Text('Hello, world.'),
      )
    );
  }
}
```

When I run the app, it displays as normal. If I open the Flutter Inspector and click the button to turn on Select Widget mode, though, I get a red error screen on the iOS simulator, and this error message in the console:

```
info flutter.tools flutter: The following assertion was thrown building CupertinoTabView:
info flutter.tools flutter: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1304 pos 14:
info flutter.tools flutter: 'observer.navigator == null': is not true.
```

## Version info

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.2.2)
[!] VS Code (version 1.24.1)
[✓] Connected devices (1 available)
```

**Comment by stevemessick** [comment] 2018-08-30 19:53
This is reproducible. @jacob314 can you take a look and determine if the problem is in the inspector or the Flutter code on the device?

**Comment by devoncarew** [comment] 2018-11-06 18:13
re: this:

```
The following assertion was thrown building CupertinoTabView:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1304 pos 14:
'observer.navigator == null': is not true.
```

I suspect this is hitting an assertion because the on-device inspector UI uses parts of flutter/material, and the current app is just using `package:flutter/cupertino.dart`. I suspect a fix here would involve changes to the inspector code in the flutter framework - to make this assert not fire, or to reduce the use of the material components in the inspector.

cc @jacob314

**Comment by jacob314** [comment] 2019-03-28 00:36
This has now been fixed with cupertino appropriate select button.
Proof of life after inspecting a cupertino app.
<img width="288" alt="Screen Shot 2019-03-27 at 5 32 44 PM" src="https://user-images.githubusercontent.com/1226812/55121229-c1f77200-50b6-11e9-9852-279b5e616823.png">

**Closed by jacob314** 2019-03-28 00:36 UTC
Labels: bug
