### ISSUE TITLE
Dartdoc links don't work

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1083] opened 2017-05-29 08:24 UTC
## Steps to Reproduce

1. Create new Flutter project
1. Go-to-decl on `new FloatingActionButton`
1. Place cursor inside `[RaisedButton]` in the top Dartdoc comment, and Go-to-decl

=> Complains 'Cannot find a declaration to go to'

**Comment by pq** [comment] 2017-05-30 22:09
It looks like we're seeing this for vanilla Dart projects as well.

![image](https://cloud.githubusercontent.com/assets/67586/26607019/36baa25e-4549-11e7-958a-0a3904040eeb.png)

@alexander-doroshko @jwren : any thoughts?  Is this a regression?

**Comment by alexander-doroshko** [comment] 2017-05-31 09:35
Not a regression, it never worked. Tracked as https://youtrack.jetbrains.com/issue/WEB-26751. Unfortunately no ETA at the moment. We may get closer to the fix during angular plugin integration work.

**Comment by pq** [comment] 2017-05-31 13:35
Thanks for confirming @alexander-doroshko !

**Comment by alexander-doroshko** [comment] 2017-06-03 07:24
Fixed in the Dart plugin

**Comment by devoncarew** [comment] 2017-06-03 14:17
Thanks!

(eta is the next release of IntelliJ - 2017.1)

**Closed by devoncarew** 2017-06-03 14:17 UTC
Labels: bug, dependency: dart plugin
