### ISSUE TITLE
 Debugger: the stop button does not stop the app #64241 

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter-intellij#4775] opened 2020-08-25 09:07 UTC
## Steps to Reproduce

1. Start-debug any flutter app in Android Studio
2. Click the stop button

**Expected results:** IDE stops debugging and the app terminates

**Actual results:** IDE stops debugging but the app keeps working on the device

Command line `flutter run` and then 'q' works so it has to be an IDE/plugin issue.

<details>

Device: LG H873

  <summary>Logs</summary>

```
C:\dev\pss-mobile-android>flutter doctor -v
[√] Flutter (Channel stable-logcat-fix, v1.17.0-4.0.pre.6, on Microsoft Windows [Version 10.0.18362.959], locale ru-UA)
    • Flutter version 1.17.0-4.0.pre.6 at C:\dev\flutter
    • Framework revision bffffb8cd7 (3 months ago), 2020-06-04 11:58:54 +0300
    • Engine revision b851c71829
    • Dart version 2.8.3


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at c:\tools\Android-SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = c:\tools\Android-SDK
    • Java binary at: C:\tools\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\tools\android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 32-bit edition (version 1.48.0)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • LG H873 • LGH8736bb28167 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

</details>

**Comment by stevemessick** [comment] 2020-08-28 17:07
I cannot reproduce this. I suspect the problem has been fixed in the latest plugin. Please update Android Studio, the plugins, and Flutter SDK. Let us know if the problem is fixed.

It is possible that your Flutter SDK is so old that it does not work with more recent plugins. There have been some changes to the communication protocol used between the plugin and the flutter tool.

**Comment by duzenko** [comment] 2020-08-29 11:10
No, this is device-specific
It works on an emulator, but not with LG H873

**Comment by duzenko** [comment] 2020-08-31 07:18
```
C:\tools\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18362.959], locale ru-UA)
    • Flutter version 1.20.2 at C:\tools\flutter
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at c:\tools\Android-SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = c:\tools\Android-SDK
    • Java binary at: C:\tools\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\tools\android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 32-bit edition (version 1.48.0)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by duzenko** [comment] 2020-08-31 07:20
> 
> 
> I cannot reproduce this. I suspect the problem has been fixed in the latest plugin. Please update Android Studio, the plugins, and Flutter SDK. Let us know if the problem is fixed.
> 
> It is possible that your Flutter SDK is so old that it does not work with more recent plugins. There have been some changes to the communication protocol used between the plugin and the flutter tool.

What command does the plugin use for termination? Is there a 'shell' involved?
https://github.com/flutter/flutter/pull/58670

**Comment by stevemessick** [comment] 2020-08-31 14:45
@jacob314 @devoncarew Can you think of any way a device dependence could cause the IDE to not stop the app after the Stop button is clicked? I suspect this is an issue in the Flutter tool.

**Comment by stevemessick** [comment] 2020-08-31 16:19
@duzenko It's been a while since I looked at the code for the Flutter tool, so I don't know if there is a shell involved, but there might be. The IDE communicates with the tool using a JSON protocol that is enabled by the --machine option used in the `flutter run` command. We may need to make changes similar to what you did to get logcat working.

**Comment by stevemessick** [comment] 2020-08-31 16:24
I re-opened https://github.com/flutter/flutter/issues/64241 with a comment stating why.

**Comment by hacker1024** [comment] 2020-09-02 02:59
Lately, I've been getting the complete opposite - my app is stopping, but IntelliJ is acting like it's not. The run button continues to show a green dot, and nothing happens when I press it again (other than going grey for a second).

Closing and opening the project seems to reset it, but upon closing, I need to press "disconnect", "cancel", and "disconnect" again.

Could this be related, or should I open a new issue here?

**Comment by stevemessick** [comment] 2020-09-30 23:25
@hacker1024 Please open a new issue. If you have a sample project that reproduces the problem please include it. Also include the output of `flutter doctor --verbose` and which device you are using. This sounds like it might also be an issue with the flutter cmd line tool, but it might also be in the IDE.

**Closed by stevemessick** 2020-09-30 23:25 UTC

**Comment by duzenko** [comment] 2020-10-01 12:29
@stevemessick why closed?
