### ISSUE TITLE
Dependencies files are been read by intellij like they were project directories

### ISSUE THREAD

**Issue by danielgomezrico** [flutter/flutter-intellij#5029] opened 2020-11-07 20:19 UTC
There are multiple kinds of search filters but in "Project Files" dependencies are also included:
![image](https://user-images.githubusercontent.com/76348/98450607-f1cc7f80-210b-11eb-81cc-40427fd99913.png) ![image](https://user-images.githubusercontent.com/76348/98451056-5689d900-2110-11eb-934b-c159434483fe.png)

But event having selected only `Project Files` the dependencies/libraries are been read by IntelliJ like project code for some reason, it makes searching on the code harder.

# Versions
- Flutter plugin: `51.0.3`
- Intellij Community: `2020.2` 

# Examples of problematic behavior
## 1
I try to search with "find in path" (cmd + shift + f) results contains dependencies files:

![image](https://user-images.githubusercontent.com/76348/98688722-27a27b80-2339-11eb-9b6c-8926901b11d7.png)

> The only result that belongs to the project is the first one, but I get a big list of files from the project libraries.

## 2
I try to search a class name (cmd + o) I see library classes and the same thing for another kind of searches.

![image](https://user-images.githubusercontent.com/76348/98450576-c053b400-210b-11eb-908a-ed4d8645c818.png)

> The only result that belongs to the project is the 4 and the 5, not even the first results belongs to it.

**Comment by pq** [comment] 2020-11-10 14:29
fyi @alexander-doroshko @jwren

**Comment by alexander-doroshko** [comment] 2020-11-10 16:46
@pq I don't know for sure if the Find In Path result is correct or not as I don't know how the project is configured.

It looks like this issue is not related to Flutter or Dart plugin. It's about core IntelliJ functionality. Such issues are tracked in https://youtrack.jetbrains.com/issues/IDEA. To file an actionable issue there I'd recommend to attach a sample project where the problem could be reproduced.

**Comment by pq** [comment] 2020-11-10 16:59
Sounds good.  Thanks!  @danielgomezrico, I'll close this one.  Feel free to open a fresh issue on the jetbrains tracker.

Thanks again for the report!

**Closed by pq** 2020-11-10 16:59 UTC
