### ISSUE TITLE
Intellij have error. i don't know why. but some time, android app on emulator is frozen.

### ISSUE THREAD

**Issue by chuothungbang9622** [flutter/flutter-intellij#7372] opened 2024-04-22 13:52 UTC
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2024.1` • Flutter plugin `io.flutter 79.0.3` • Dart plugin `241.15845`

Error getting Flutter sdk information.

## Exception

null

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.flutter.run.OpenDevToolsAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.flutter]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**Comment by jacob314** [comment] 2024-04-22 20:49
This is probably a duplicate of https://github.com/flutter/flutter-intellij/issues/7355

**Closed by jacob314** 2024-04-22 20:49 UTC
