### ISSUE TITLE
Stuck at "Syncing files to device" when running the project from "Run" or "Debug" button

### ISSUE THREAD

**Issue by lsalazarm99** [flutter/flutter-intellij#5236] opened 2021-02-02 08:54 UTC
If I run the project from the GUI of the IDE (run or debug button), it will be stuck at "Syncing files to device", making it impossible to test the app because it's just a white screen. Not even the `main()` method is reached. If I run the profiler mode, it will run (I guess because it doesn't need to synchronize files), but the Flutter Performance view won't detect the app.

In any case, if I close the app from my phone, the "runner" will detect it and show that the connection was lost. Then I can normally open the app but of course not hot reload.

If I run the app from the terminal, it works well.

If I try to attach to an instance started from the terminal, it will be stuck again at "Syncing files to device".

Also, each time the process gets stuck, the IDE shows these internal error messages:
<details>
<summary>stacktrace.txt</summary>
<pre>
<code>
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor166.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:246)
	at com.sun.proxy.$Proxy46.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:220)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:154)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:206)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:190)
	at com.intellij.util.io.BaseOutputReader.readAvailableBlocking(BaseOutputReader.java:137)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:68)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:157)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.io.BaseDataReader.lambda$start$0(BaseDataReader.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: de/roderick/weberknecht/WebSocketException
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.sun.proxy.$Proxy235.<clinit>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1022)
	at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1008)
	at com.intellij.util.EventDispatcher.createMulticaster(EventDispatcher.java:77)
	at com.intellij.util.EventDispatcher.getMulticaster(EventDispatcher.java:112)
	at io.flutter.run.daemon.FlutterApp.changeState(FlutterApp.java:557)
	at io.flutter.run.daemon.FlutterAppDaemonEventListener.onAppStarted(FlutterApp.java:866)
	at io.flutter.run.daemon.DaemonEvent$AppStarted.accept(DaemonEvent.java:239)
	at io.flutter.run.daemon.DaemonEvent.dispatch(DaemonEvent.java:52)
	at io.flutter.run.daemon.DaemonApi.dispatch(DaemonApi.java:177)
	at io.flutter.run.daemon.DaemonApi$1.onTextAvailable(DaemonApi.java:148)
	... 23 more
Caused by: java.lang.ClassNotFoundException: de.roderick.weberknecht.WebSocketException PluginClassLoader[PluginDescriptor(name=Flutter, id=io.flutter, path=C:\Users\leozx\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.7148.57.plugins\flutter-intellij, version=52.2.5)] com.intellij.ide.plugins.cl.PluginClassLoader@6ff310c0
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:129)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 40 more
</code>
</pre>
</details>

<details>
<summary>induced.txt</summary>
<pre>
<code>
Following exceptions happened soon after this one, most probably they are induced.

2021-02-02T03:20:10.961
java.lang.NoClassDefFoundError: de/roderick/weberknecht/WebSocketException
	at io.flutter.vmService.DartVmServiceDebugProcess.lambda$scheduleConnect$1(DartVmServiceDebugProcess.java:238)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:270)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: de.roderick.weberknecht.WebSocketException PluginClassLoader[PluginDescriptor(name=Flutter, id=io.flutter, path=C:\Users\leozx\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.7148.57.plugins\flutter-intellij, version=52.2.5)] com.intellij.ide.plugins.cl.PluginClassLoader@6ff310c0
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:129)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 12 more
</code>
</pre>
</details>

Finally, if I press the stop button, the phone will stay in the white screen and the IDE will show these internal errors messages:
<details>
<summary>stacktrace.txt</summary>
<pre>
<code>
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:246)
	at com.sun.proxy.$Proxy46.processWillTerminate(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.fireProcessWillTerminate(ProcessHandler.java:228)
	at com.intellij.execution.process.ProcessHandler.lambda$destroyProcess$0(ProcessHandler.java:122)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:279)
	at com.intellij.execution.process.ProcessHandler.destroyProcess(ProcessHandler.java:120)
	at com.intellij.execution.impl.ExecutionManagerImpl$Companion.stopProcess(ExecutionManagerImpl.kt:110)
	at com.intellij.execution.impl.ExecutionManagerImpl$Companion.stopProcess(ExecutionManagerImpl.kt:87)
	at com.intellij.execution.impl.ExecutionManagerImpl.stopProcess(ExecutionManagerImpl.kt)
	at com.intellij.execution.actions.StopAction.actionPerformed(StopAction.java:197)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:281)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:209)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:177)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:160)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:477)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:911)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sun.proxy.$Proxy235
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1022)
	at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1008)
	at com.intellij.util.EventDispatcher.createMulticaster(EventDispatcher.java:77)
	at com.intellij.util.EventDispatcher.getMulticaster(EventDispatcher.java:112)
	at io.flutter.run.daemon.FlutterApp.changeState(FlutterApp.java:557)
	at io.flutter.run.daemon.FlutterApp.shutdownAsync(FlutterApp.java:568)
	at io.flutter.run.daemon.FlutterAppDaemonEventListener.processWillTerminate(FlutterApp.java:795)
	at io.flutter.run.daemon.DaemonApi$1.processWillTerminate(DaemonApi.java:156)
	... 54 more
</code>
</pre>
</details>

<details>
<summary>induced.txt</summary>
<pre>
<code>
Following exceptions happened soon after this one, most probably they are induced.

2021-02-02T03:22:37.072
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:246)
	at com.sun.proxy.$Proxy46.processTerminated(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.lambda$notifyTerminated$2(ProcessHandler.java:204)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:279)
	at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:187)
	at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:183)
	at com.intellij.execution.process.BaseProcessHandler.onOSProcessTerminated(BaseProcessHandler.java:61)
	at com.intellij.execution.process.OSProcessHandler.onOSProcessTerminated(OSProcessHandler.java:206)
	at com.intellij.execution.process.BaseOSProcessHandler$1.lambda$startNotified$0(BaseOSProcessHandler.java:97)
	at com.intellij.execution.process.ProcessWaitFor.lambda$new$0(ProcessWaitFor.java:55)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.execution.process.ProcessWaitFor.lambda$new$1(ProcessWaitFor.java:33)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sun.proxy.$Proxy235
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1022)
	at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1008)
	at com.intellij.util.EventDispatcher.createMulticaster(EventDispatcher.java:77)
	at com.intellij.util.EventDispatcher.getMulticaster(EventDispatcher.java:112)
	at io.flutter.run.daemon.FlutterApp.changeState(FlutterApp.java:557)
	at io.flutter.run.daemon.FlutterAppDaemonEventListener.processTerminated(FlutterApp.java:808)
	at io.flutter.run.daemon.DaemonApi$1.processTerminated(DaemonApi.java:161)
	... 24 more
</code>
</pre>
</details>

## Steps to Reproduce

To be honest, I have no idea how this happened. It was working well. I just decided to reboot my PC and then the error started. I was in the latest version (53.0). I decided to try the latest dev release and also the second latest stable version (52.2.5) but it still happens. I tried invalidating cache and restarting, changing flutter channels and doing upgrades, doing a lot of  `flutter clean`, restart my PC again, even downgrading IntelliJ. But the error is still present.

I tried in a new "black" project and it still happens, so since the plugin has no configuration I think the following is valid:

1. Create a new project
2. Run the project from the "Run" button.

## Version info
```
C:\tools\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [Version 10.0.19042.746], locale es-PE)
    • Flutter version 1.25.0-8.3.pre at C:\tools\flutter
    • Framework revision 5d36f2e7f5 (3 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\leozx\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Users\leozx\.jdks\openjdk-15.0.1\bin\java
    • Java version OpenJDK Runtime Environment (build 15.0.1+9-18)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Users\leozx\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.7148.57
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[√] Connected device (1 available)
    • Pixel 3a (mobile) • 98FAY14MT6 • android-arm64 • Android 11 (API 30)

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by stevemessick** [comment] 2021-02-02 16:29
`Caused by: java.lang.NoClassDefFoundError: de/roderick/weberknecht/WebSocketException`
The WebSocket library is distributed with the Dart plugin. My guess is that you have a class path configuration problem. The easiest way to fix that probably is to completely uninstall all IntelliJ and Android Studio, then reinstall the latest of whichever you want. Uninstall instructions are here:
https://www.jetbrains.com/help/idea/uninstall.html

I don't know much about Windows but there is probably some system setting that controls where it looks to find applications to run. Make sure that does not include anything you uninstalled, and that it does include the one you are using. Let us know if that helps.

**Comment by lsalazarm99** [comment] 2021-02-02 17:25
Given what you said about the Dart plugin, I tried downgrading it to 203.6803 (current is 203.6912), invalidating cache, and restarting and... it worked! I'm now with:
- IntelliJ 2020.3.2
- Dart Plugin 203.6912
- Flutter Plugin 52.2.5

I'll upgrade the plugins and see if the problem persists.

**Comment by lsalazarm99** [comment] 2021-02-02 17:29
I upgraded those plugins to their latest stable versions (the ones I had when the problem started) and **it's working now**.
Many thanks!

**Comment by stevemessick** [comment] 2021-02-02 21:29
It must have been a combination of finding a new version of the Dart plugin and rebuilding the cache that did it. I'm glad your problem is fixed. I'll close this issue.

**Closed by stevemessick** 2021-02-02 21:29 UTC
