### ISSUE TITLE
Hot reload for multiple devices

### ISSUE THREAD

**Issue by stefandevo** [flutter/flutter-intellij#3111] opened 2019-01-23 16:45 UTC
## Steps to Reproduce

Start debugging your app by running it on multiple devices (ios simulator, android simulator). Upon Save, only the active devices is hot-reloaded. 

Can this be extended that it reloads all running devices?

`flutter run -d all` will hot-reload all devices when started in terminal and pressing "s".

Can this be included in the IDE upon Save.

**Comment by jwren** [comment] 2019-01-23 21:56
Closing, this is a duplicate of https://github.com/flutter/flutter-intellij/issues/956

**Closed by jwren** 2019-01-23 21:56 UTC
