### ISSUE TITLE
Hot reload and restart should cause the Console to scroll to the bottom

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1089] opened 2017-06-01 12:46 UTC
From @floitschG recent getting started log.

Working as expected:

1. Make the console not very tall so that it easily "overflows"
1. Create new app
1. Introduce a runtime error (e.g., add `int x = 42 ~/ 0;` above `_counter++;`)
1. Run app
1. Trigger runtime error (press `+` button)

=> Console scrolls to the botton of the error

1. Trigger runtime error again

=> Console scrolls to the botton of the error

*Not* working as expected:

1. Scroll up a bit in the Console
1. Trigger runtime error again

=> Console no longer scrolls to the botton

**Comment by pq** [comment] 2017-06-01 13:58
@devoncarew

**Comment by devoncarew** [comment] 2017-06-01 16:26
@floitschG, this is likely working as intended from the IntelliJ perspective. There's an option in the console view to toggle 'scroll to the end':

<img width="139" alt="screen shot 2017-06-01 at 9 24 24 am" src="https://cloud.githubusercontent.com/assets/1269969/26689912/3ed639f8-46ac-11e7-8d5f-4d77a8907214.png">

If it's enabled, new output should cause the view to scroll. If this is enabled but is not working for you, we'll need to file a platform bug on the youtrack tracker.

**Comment by floitschG** [comment] 2017-06-01 17:30
I guess it's not enabled.

Either, it should be enabled by default, or (probably better), there should be a visible indication that new output has been added (prompting me to scroll down).
Alternatively, Flutter could, of course, clear the output for every hot reload.

The current behavior is not great (even if "as designed" from intellij's perspective).

**Comment by devoncarew** [comment] 2017-06-01 17:33
Agree that IntelliJ has way too many user options and settings.

> Alternatively, Flutter could, of course, clear the output for every hot reload.

We do do this now (based on your feedback) - this will be in the next milestone release.

**Closed** 2017-06-01 17:33 UTC
Labels: enhancement, topic-debugging
