### ISSUE TITLE
I updated the intellij and got this error

### ISSUE THREAD

**Issue by beautybird** [flutter/flutter-intellij#6987] opened 2023-10-25 13:43 UTC
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

I just updated the intellij to latest version ...and got this error !!

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by jwren** [comment] 2023-10-25 21:39
LMK if it is not this issue:

**Comment by jwren** [comment] 2023-10-25 21:39
Duplicate of https://github.com/flutter/flutter-intellij/issues/6942

**Closed by jwren** 2023-10-25 21:39 UTC
