### ISSUE TITLE
Plugin 'Flutter' (version '81.0.2') is not compatible with the current version of the IDE, because it requires build 241.* or older but the current build is IU-242.20224.300

### ISSUE THREAD

**Issue by sky-train** [flutter/flutter-intellij#7598] opened 2024-08-08 15:36 UTC
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by parlough** [comment] 2024-08-08 18:51
Thanks for reporting this! Closing as a duplicate of https://github.com/flutter/flutter-intellij/issues/7595 to consolidate discussion and tracking there.

I believe the next release of the plugin will support 2024.2, but until then, you can downgrade IntelliJ (or other JetBrains IDE) to 2024.1.

**Closed by parlough** 2024-08-08 18:51 UTC
