### ISSUE TITLE
The run button should be disabled when debugging an app (and vice versa)

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter-intellij#1823] opened 2018-02-24 21:32 UTC
If the developer runs the app not attached to the debugger, then decides to restart the app with debugging enabled by either going to "Run > Debug" or hitting the "Debug" button... nothing happens.

Similarly, if they've already started the app with debugging enabled, and they hit the "Debug" button again, nothing happens.

In the first case, the app should probably be restarted with debugging enabled.  Alternatively, the button and menu option should be disabled.

In the second case, for parity with what happens when you click "Run" when the app is already running, we should probably perform a full restart (with debugging enabled).

**Comment by tvolkert** [comment] 2018-02-25 03:53
> Similarly, if they've already started the app with debugging enabled, and they hit the "Debug" button again, nothing happens.

I definitely saw this at first, but then later, it was triggering a full restart as expected.  Not sure if anyone else can reproduce the behavior I saw at first.

**Comment by branflake2267** [comment] 2018-02-25 14:56
I think this is related. I've found a scenario where I try to debug again and nothing happens. 
https://github.com/flutter/flutter-intellij/issues/1821

**Comment by devoncarew** [comment] 2018-02-25 18:45
This is mostly by design; in previous versions of IntelliJ, it would properly display that we couldn't debug the same app when it was running (or run the same app when we were debugging it). This would allow us to disable the alternate button when executing, so if you hit run:
- the run button stays enabled
- the debug button becomes disabled
- hitting the run button again will issue a 'hot restart' instead of re-running the whole app

the was a good discovery mechanism for performing a hot restart, however I think the platform has regressed here - it no longer shows the disabled state of the toolbar run/debug actions correctly.

**Comment by devoncarew** [comment] 2018-03-19 20:30
Possibly due to a regression in the IntelliJ framework.

**Comment by devoncarew** [comment] 2018-03-22 00:43
This appears to be fixed in IntelliJ 2018.1. It's nearing general release; closing this issue in anticipation of that.

**Closed by devoncarew** 2018-03-22 00:43 UTC
Labels: bug
