### ISSUE TITLE
tests can no longer be run individually (using the gutter run icons)

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#4518] opened 2020-04-28 15:43 UTC
(moved from https://youtrack.jetbrains.com/issue/WEB-45123)

From the above issue:

I am not sure how this came to happen, I was running individual tests using the Run icon at the gutter, right on the left side of the Test, then instead of clicking Run I selected Debug and it debugged all my tests, not the individual one that I had selected. The tests were failing as well. Now the gutter button is not at the test name anymore, but on the next line:

Now I can't Run or Debug individual tests, they are all Run at once.

I am using IntelliJ IDEA Ultimate 2020.1.

EDIT:

I came with some more weird cases:

I tried to add as simple test to reproduce the bug described before:

As you can see the previous test has the gutter Run button on the wrong line and the Simple Test has no gutter button at al. But as soon as I create the Simple Test it had the button, I used it to run it, and after it completed the button just disappeared.

If I just edit the contents of my test (type Enter then Backspace) the IDE fixes it self and shows the gutter buttons:

But as soon as I use them they just disappear again like in reported before on item 1.

Attachments 3
image.png
 image1.png
 image2.png

**Comment by stevemessick** [comment] 2021-01-22 19:26
Fixed in #5199 

It is possible that the change does not actually fix this since I can't reproduce it. If the problem persists then we will re-open this.

**Closed by stevemessick** 2021-01-22 19:26 UTC
Labels: topic-testing
