### ISSUE TITLE
Crash when trying to open Flutter DevTools (Flutter Inspector)

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter-intellij#5928] opened 2022-01-31 20:13 UTC
When I try and open the Flutter Inspector, I get the following crash after it says "Trying to install DevTools". It happens even if I nuke my .idea directory and start clean.  I don' t know if it's only on a new install of dev tools or not, since it crashes every time.

I have to disable "Launch Flutter Inspector on app launch" because otherwise I couldn't use the debugger.
It doesn't appear to happen if I just open the Flutter Performance tab.

```
Running "flutter pub get" in manual_tests...
Launching lib/menu.dart on Linux in debug mode...
Building Linux application...
Debug service listening on ws://127.0.0.1:36831/FSEy51m2ZUw=/ws
Syncing files to device Linux...
Unhandled exception:
type 'DillSetterBuilder' is not a subtype of type 'SourceMemberBuilderImpl?' in type cast
#0      SourceLibraryBuilder.checkMemberConflicts.<anonymous closure> (package:front_end/src/fasta/source/source_library_builder.dart:998:22)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:574:13)
#2      Scope.forEachLocalSetter (package:front_end/src/fasta/scope.dart:424:14)
#3      SourceLibraryBuilder.checkMemberConflicts (package:front_end/src/fasta/source/source_library_builder.dart:974:11)
#4      SourceLibraryBuilder.build (package:front_end/src/fasta/source/source_library_builder.dart:1057:5)
#5      IncrementalCompiler.compileExpression.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:1817:20)
#6      IncrementalCompiler.compileExpression.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:1668:39)
#7      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:46)
#8      new Future.sync (dart:async/future.dart:296:31)
#9      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:19)
#10     _rootRun (dart:async/zone.dart:1426:13)
#11     _CustomZone.run (dart:async/zone.dart:1328:19)
#12     _runZoned (dart:async/zone.dart:1861:10)
#13     runZoned (dart:async/zone.dart:1783:10)
#14     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:117:12)
#15     IncrementalCompiler.compileExpression (package:front_end/src/fasta/incremental_compiler.dart:1668:26)
#16     IncrementalCompiler.compileExpression (package:vm/incremental_compiler.dart:218:23)
#17     FrontendCompiler.compileExpression (file:///b/s/w/ir/cache/builder/sdk/pkg/frontend_server/lib/frontend_server.dart:850:44)
#18     listenAndCompile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/frontend_server/lib/frontend_server.dart:1268:20)
#19     listenAndCompile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/frontend_server/lib/frontend_server.dart:1160:15)
#20     _RootZone.runUnaryGuarded (dart:async/zone.dart:1618:10)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#23     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#24     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#25     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#26     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:170:13)
#27     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:145:5)
#28     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#29     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#30     _RootZone.runUnaryGuarded (dart:async/zone.dart:1618:10)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#33     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#34     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#35     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#36     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#37     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#38     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#39     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#40     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#41     _RootZone.runUnaryGuarded (dart:async/zone.dart:1618:10)
#42     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#43     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#44     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#45     _StreamController._add (dart:async/stream_controller.dart:648:7)
#46     _StreamController.add (dart:async/stream_controller.dart:596:5)
#47     _Socket._onData (dart:io-patch/socket_patch.dart:2314:41)
#48     _RootZone.runUnaryGuarded (dart:async/zone.dart:1618:10)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#51     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#52     _StreamController._add (dart:async/stream_controller.dart:648:7)
#53     _StreamController.add (dart:async/stream_controller.dart:596:5)
#54     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1839:33)
#55     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322:14)
#56     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#57     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#58     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
```

Here are my details:
<details>
<summary>flutter doctor -v</summary>
<pre>
[✓] Flutter (Channel menu_bar_in_progress, 2.10.0-1.0.pre.349, on Debian GNU/Linux rodete 5.10.46-5rodete1-amd64, locale
    en_US.UTF-8)
    • Flutter version 2.10.0-1.0.pre.349 at /usr/local/google/home/gspencer/code/flutter
    • Upstream repository git@github.com:gspencergoog/flutter.git
    • Framework revision 7e4a639f0f (8 minutes ago), 2022-01-31 12:01:08 -0800
    • Engine revision c2bcffb07e
    • Dart version 2.17.0 (build 2.17.0-67.0.dev)
    • DevTools version 2.10.0-dev.1
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /usr/local/google/home/gspencer/Android/Sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /usr/local/google/home/gspencer/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at google-chrome
[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 13.0.0-9+build1
    • cmake version 3.22.1
    • ninja version 1.8.2
    • pkg-config version 0.29.2
[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /opt/idea-IC-212.4746.92
    • Flutter plugin version 63.2.4
    • Dart plugin version 213.5744.122
[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux rodete 5.10.46-5rodete1-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.99
[✓] HTTP Host Availability
    • All required HTTP hosts are available
• No issues found!
</pre>
</details>

**Comment by kenzieschmoll** [comment] 2022-01-31 21:06
this looks like a duplicate of https://github.com/flutter/devtools/issues/3599, and looks like @jensjoha pushed a fix to the SDK 6 hours ago.

**Comment by stevemessick** [comment] 2022-02-01 18:15
Thanks @kenzieschmoll, closing.

**Closed by stevemessick** 2022-02-01 18:15 UTC
