### ISSUE TITLE
**NO SUGGESTION of maching Widget IN latest Plugin**

### ISSUE THREAD

**Issue by kaushiklad55** [flutter/flutter-intellij#3946] opened 2019-10-09 11:23 UTC
![flutterisue](https://user-images.githubusercontent.com/56347527/66476852-383c4e80-eab4-11e9-9bb8-24a80185a5ab.png)

**NO SUGGESTION of maching Widget IN latest Plugin**

card shape ,conatiner decoration and all many widget has this kind of issue in latest android studio 3.5 and plugin 40.1 ...i was expecting to get solved 

image i m sharing is old version android 3.2 and plugin 30.2 wich is old work fine 

hope u solve this isuue

**Comment by devoncarew** [comment] 2019-10-09 15:21
@kaushiklad55, can you provide the version of the Flutter plugin, the version of Android Studio you're using, and the version of Flutter you're on?

It sounds like the image from above is working as expected, but that in the current versions, you're not seeing code completion results as expected? Can you provide a few more details on the issue?

**Comment by alexander-doroshko** [comment] 2019-10-09 21:31
It's probably a known downside caused by switching to `AvailableSuggestions` (which enabled an auto-import feature). Tracked as https://github.com/dart-lang/sdk/issues/38739 and also discussed in many other places in different issue trackers.

**Comment by kaushiklad55** [comment] 2019-10-10 07:26
![flutterisue](https://user-images.githubusercontent.com/56347527/66547462-ed2a4600-eb5c-11e9-8de9-2d60bd7b1355.png)
![flutterisuue2](https://user-images.githubusercontent.com/56347527/66547463-ed2a4600-eb5c-11e9-82d0-fa978a768b3d.png)

its work fine on andorid studio 3.2.1 and flutter pluging 31.3.1 

its not work on android studio 3.5.1 and flutter pluging 40.1

today i try with itellije comunity IDE with latest pluging still same issue 

my flutter version is 1.9 stable hotfix 4

**Comment by kenzieschmoll** [comment] 2019-10-17 21:12
going to close this issue, as the underlying problem is tracked in the sdk repo: https://github.com/dart-lang/sdk/issues/38739

**Closed by kenzieschmoll** 2019-10-17 21:12 UTC
