### ISSUE TITLE
after upgrading IntelliJ displays a "Migrate Project to Gradle?" notification

### ISSUE THREAD

**Issue by bjornbjorn** [flutter/flutter-intellij#1343] opened 2017-09-20 10:20 UTC
After upgrading IntelliJ a while back I started getting this message in my Event Log:

> 20/09/2017
> 10:36	Migrate Project to Gradle?
> 			This project does not use the Gradle build system. We recommend that you migrate to using the Gradle build system.
> 			More Information about migrating to Gradle
> 			Don't show this message again.

I created this Flutter project the 8th of September and I am using Gradle (AFAIK) - I have files like android/build.gradle, gradlew and settings.gradle etc. in the project and when I run it in the Android emulator I see references to Gradle:

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
```
So it seems that the issue here is that IntelliJ is not able to identify that my project is using Gradle.

## Steps to Reproduce

Not sure how to reproduce. When I create a new project using "flutter create" everything seems to work fine and IntelliJ is able to pick up that the project is using Gradle.

I did a diff of the android/ folders on the newly created test project and my old project (the one complaining) and most files were identical. In the files that were not, I didn't see anything that was not related to changes I've made myself (like app class name etc.) but I may have overlooked something of course.

## Version info

flutter doctor:

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-NO, channel alpha)
    • Flutter at /Users/bjorn/bin/flutter
    • Framework revision 701d534ba9 (8 days ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/bjorn/Library/Android/sdk
    • Platform android-26, build-tools 26.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.4)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

adb not responding
```

--- 
IntelliJ version:

```
IntelliJ IDEA 2017.2.4
Build #IU-172.4155.36, built on September 11, 2017
Licensed to IntelliJ IDEA Evaluator
Expiration date: September 27, 2017
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```

**Comment by bjornbjorn** [comment] 2017-09-20 11:49
Actually, after reopening my testproject later I see that this also is complaining about the lack of Gradleness:

![](https://i.imgur.com/WQJoS20.png)

I haven't touched the project after running "flutter create"

**Comment by devoncarew** [comment] 2017-09-21 21:02
Thanks for the report! We do see this issue as well; totally agree that a newly created project shouldn't warn.

**Comment by devoncarew** [comment] 2017-09-21 21:03
From some investigation (/cc @stevemessick), this patch file into the flutter/flutter repo may address the issue:

```
diff --git a/packages/flutter_tools/templates/create/projectName.iml.tmpl b/packages/flutter_tools/templates/create/projectName.iml.tmpl
index dafb00113..4a51e50ba 100644
--- a/packages/flutter_tools/templates/create/projectName.iml.tmpl
+++ b/packages/flutter_tools/templates/create/projectName.iml.tmpl
@@ -1,13 +1,28 @@
 <?xml version="1.0" encoding="UTF-8"?>
 <module type="WEB_MODULE" version="4">
+  <component name="FacetManager">
+    <facet type="android" name="Android">
+      <configuration>
+        <option name="GEN_FOLDER_RELATIVE_PATH_APT" value="/../../{{projectName}}/gen" />
+        <option name="GEN_FOLDER_RELATIVE_PATH_AIDL" value="/../../{{projectName}}/gen" />
+        <option name="MANIFEST_FILE_RELATIVE_PATH" value="/../../{{projectName}}/AndroidManifest.xml" />
+        <option name="RES_FOLDER_RELATIVE_PATH" value="/../../{{projectName}}/res" />
+        <option name="ASSETS_FOLDER_RELATIVE_PATH" value="/../../{{projectName}}/assets" />
+        <option name="LIBS_FOLDER_RELATIVE_PATH" value="/../../{{projectName}}/libs" />
+        <option name="PROGUARD_LOGS_FOLDER_RELATIVE_PATH" value="/../../{{projectName}}/proguard_logs" />
+      </configuration>
+    </facet>
+  </component>
   <component name="NewModuleRootManager" inherit-compiler-output="true">
     <exclude-output />
     <content url="file://$MODULE_DIR$">
+      <sourceFolder url="file://$MODULE_DIR$/gen" isTestSource="false" generated="true" />
       <excludeFolder url="file://$MODULE_DIR$/.idea" />
       <excludeFolder url="file://$MODULE_DIR$/.pub" />
       <excludeFolder url="file://$MODULE_DIR$/build" />
       <excludeFolder url="file://$MODULE_DIR$/packages" />
     </content>
+    <orderEntry type="jdk" jdkName="Android API {{androidSdkVersion}} Platform" jdkType="Android SDK" />
     <orderEntry type="sourceFolder" forTests="false" />
     <orderEntry type="library" name="Dart Packages" level="project" />
     <orderEntry type="library" name="Dart SDK" level="project" />
diff --git a/packages/flutter_tools/templates/package/projectName.iml.tmpl b/packages/flutter_tools/templates/package/projectName.iml.tmpl
index dafb00113..4a51e50ba 100644
--- a/packages/flutter_tools/templates/package/projectName.iml.tmpl
+++ b/packages/flutter_tools/templates/package/projectName.iml.tmpl
@@ -1,13 +1,28 @@
 <?xml version="1.0" encoding="UTF-8"?>
 <module type="WEB_MODULE" version="4">
+  <component name="FacetManager">
+    <facet type="android" name="Android">
+      <configuration>
+        <option name="GEN_FOLDER_RELATIVE_PATH_APT" value="/../../{{projectName}}/gen" />
+        <option name="GEN_FOLDER_RELATIVE_PATH_AIDL" value="/../../{{projectName}}/gen" />
+        <option name="MANIFEST_FILE_RELATIVE_PATH" value="/../../{{projectName}}/AndroidManifest.xml" />
+        <option name="RES_FOLDER_RELATIVE_PATH" value="/../../{{projectName}}/res" />
+        <option name="ASSETS_FOLDER_RELATIVE_PATH" value="/../../{{projectName}}/assets" />
+        <option name="LIBS_FOLDER_RELATIVE_PATH" value="/../../{{projectName}}/libs" />
+        <option name="PROGUARD_LOGS_FOLDER_RELATIVE_PATH" value="/../../{{projectName}}/proguard_logs" />
+      </configuration>
+    </facet>
+  </component>
   <component name="NewModuleRootManager" inherit-compiler-output="true">
     <exclude-output />
     <content url="file://$MODULE_DIR$">
+      <sourceFolder url="file://$MODULE_DIR$/gen" isTestSource="false" generated="true" />
       <excludeFolder url="file://$MODULE_DIR$/.idea" />
       <excludeFolder url="file://$MODULE_DIR$/.pub" />
       <excludeFolder url="file://$MODULE_DIR$/build" />
       <excludeFolder url="file://$MODULE_DIR$/packages" />
     </content>
+    <orderEntry type="jdk" jdkName="Android API {{androidSdkVersion}} Platform" jdkType="Android SDK" />
     <orderEntry type="sourceFolder" forTests="false" />
     <orderEntry type="library" name="Dart Packages" level="project" />
     <orderEntry type="library" name="Dart SDK" level="project" />
```

**Comment by stevemessick** [comment] 2017-09-21 21:39
Actually, that patch was intended to address a different but similar issue. When you create a project you get notified that the Android framework is not configured. The patch fixes that. I don't think it will stop Gradle warnings.

<img width="344" alt="screen shot 2017-09-21 at 2 36 24 pm" src="https://user-images.githubusercontent.com/8518285/30719919-64036fb2-9eda-11e7-85fd-13c0aeacc1dd.png">

It is possible this notification only happens with Android Studio. I haven't created a "standard" IntelliJ Flutter project in a long time, since I'm working on the AS plugin, and I do not see the Gradle warning.

**Comment by devoncarew** [comment] 2017-09-21 21:53
Ah, thanks for the clarification. I'll change this bug back to the original issue.

**Comment by stevemessick** [comment] 2017-10-16 17:54
This is fixed for Android Studio but not other IDEA-based platforms. The reason is that the Android Studio version uses a different project creation pathway, which removes any files created by the IDE before `flutter create` is run. Flutter won't overwrite existing files, and the ones generated by the IDE do not have the "ignore gradle" setting.

**Comment by raveeshtech** [comment] 2017-12-18 09:12
Sorry for the noob question but bottom line: I have to ignore that warning till this is fixed. Right? 
##Using:
IntelliJ IDEA 2017.3.1 (Ultimate Edition)
Build #IU-173.3942.27, built on December 11, 2017
Licensed to Raveesh Agarwal
Subscription is active until May 28, 2018
For educational use only.
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.10.0-42-generic 

I have also observed the same issue

**Comment by Peet-A** [comment] 2018-02-16 20:16
hello all , i have the same issue here , and i can't run the app on android emulator , only ios is working 
so , when i will be able to test it on android emulator ? there is any workaround ?

**Comment by raveesh-me** [comment] 2018-02-16 21:42
Making an avd with SDK 24, installing SDK 24 sources did the trick for us. On 17-Feb-2018 1:46 AM, Peet-A <notifications@github.com> wrote:hello all , i have the same issue here , and i can't run the app on android emulator , only ios is working
so , when i will be able to test it on android emulator ? there is any workaround ?

**Comment by Peet-A** [comment] 2018-02-17 10:48
@raveesh-me , thanks very much it worked for me too - i appreciate your help sir .

**Comment by devoncarew** [comment] 2018-02-25 05:44
closing as a dup of https://github.com/flutter/flutter-intellij/issues/1807

**Closed by devoncarew** 2018-02-25 05:44 UTC
Labels: bug
