### ISSUE TITLE
DevTools Flutter inspector is too big and sharp

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter-intellij#5104] opened 2020-12-07 12:35 UTC
The side window opens up too big and the text isn't smooth

![image](https://user-images.githubusercontent.com/2807712/101351245-9e775980-3890-11eb-81ed-25ad674080b4.png)

## Steps to Reproduce

Run an app on a 4K monitor

## Version info

Plugin is not detected in `flutter doctor -v` but version is `52.0.1`.

```
[✓] Flutter (Channel stable, 1.22.4, on Microsoft Windows [VersiÃ³n 10.0.19042.662], locale es-ES)
    • Flutter version 1.22.4 at C:\src\flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\crist\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\crist\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (1 available)
    • ONEPLUS A5000 (mobile) • f2eb43ee • android-arm64 • Android 10 (API 29)
```

**Comment by stevemessick** [comment] 2020-12-07 14:24
@helin24 Does JxBrowser have scaling options?

**Comment by helin24** [comment] 2020-12-07 18:04
There may be some JxBrowser settings that are relevant here. We may also be able to fix this with sending font size to DevTools (https://github.com/flutter/devtools/pull/2459).

**Comment by lpancho** [comment] 2021-01-06 02:09
@Zazo032 We have encountered this issue today and **temporarily** fixed it by reverting back to IntelliJ theme then back to Dracula theme. Initially we have selected Dracula theme after downloading android studio.
![image](https://user-images.githubusercontent.com/43244009/103720747-07c0c880-5007-11eb-90f4-f8f2150a3d57.png)

**Comment by DenisGL** [comment] 2021-01-13 21:15
I have the same issue. I have a monitor with 3440 x 1440 resolution, and use **125% scaling** (on Windows 10). If I set back the scaling to 100%, every is fine (except that I can read anything because all fonts in Windows are two small). I also noticed that images displayed in the "Tip of the day" suffer from the same issue.

**Comment by mdavidtio** [comment] 2021-01-21 04:59
Please try this, hope it can work: 
File => Settings => Languages & Frameworks => Flutter => Experiments => Unselect 'Enable embedding DevTools in the Flutter Inspector tool window' => Apply => OK => Restart Android Studio for changes to take effect.

**Comment by helin24** [comment] 2021-01-22 20:16
Closing this one as a duplicate of https://github.com/flutter/flutter-intellij/issues/5164

**Closed by helin24** 2021-01-22 20:16 UTC
Labels: enhancement

**Comment by msedawy** [comment] 2021-03-22 12:41
> Please try this, hope it can work:
> File => Settings => Languages & Frameworks => Flutter => Experiments => Unselect 'Enable embedding DevTools in the Flutter Inspector tool window' => Apply => OK => Restart Android Studio for changes to take effect.

IT works thank you alot

**Comment by DenisGL** [comment] 2021-03-30 11:43
Changing the settings (Unselect 'Enable...'), also worked for me. Thanks.
