### ISSUE TITLE
IDE Exception error

### ISSUE THREAD

**Issue by shamylkashif** [flutter/flutter-intellij#7737] opened 2024-10-27 07:21 UTC
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## What happened

I was just waiting for my project to build and doing nothing.
PS. This is my first time reporting an issue, if there is ant mistake in this report please excuse me, I was doing my work and suddenly this window popped up telling me to report this issue, so I did it.

## Version information

Android Studio `Ladybug | 2024.2.1 Patch 1` • Flutter plugin `io.flutter 82.0.3` • Dart plugin `242.22855.32`

Error getting Flutter sdk information.

## Exception

null

```
Error Report: NullPointerException in Flutter Performance View

Error Message: java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.wm.ToolWindow.setAvailable(boolean)" because the return value of "com.intellij.openapi.wm.ToolWindowManager.getToolWindow(String)" is null

Relevant Stack Trace:
at io.flutter.performance.FlutterPerformanceViewFactory.lambda$initPerfView$1(FlutterPerformanceViewFactory.java:43)

Description: This error indicates that a NullPointerException occurred while attempting to set a tool window's availability in the Flutter Performance View.
```

**Comment by jwren** [comment] 2024-11-14 18:34
Batch close for the `com.intellij.openapi.wm.ToolWindow.setAvailable(boolean)` exception out of the Flutter IJ plugin, this is a duplicate of https://github.com/flutter/flutter-intellij/issues/7691 and is resolved in the release of the Flutter plugin, `82.1`.

**Closed by jwren** 2024-11-14 18:34 UTC
