### ISSUE TITLE
Flutter plugin is not compatible with new IntelliJ version.

### ISSUE THREAD

**Issue by applezrock** [flutter/flutter-intellij#7118] opened 2023-12-07 04:03 UTC
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce
1. I updated IntelliJ to IntelliJ IDEA 2023.3 (Ultimate Edition)
Build #IU-233.11799.241, built on December 2, 2023

2. IntelliJ says "Plugin 'Flutter' (version '76.3.4') is not compatible with the current version of the IDE, because it requires build 232.* or older but the current build is IU-233.11799.241"

## Version info
[✓] Flutter (Channel stable, 3.16.2, on macOS 14.1.2 23B92 darwin-arm64, locale en-KR)
    • Flutter version 3.16.2 on channel stable at /Users/applezrock/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (6 days ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/applezrock/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 233.11799.172

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.199

[✓] Network resources
    • All expected network resources are available.

• No issues found!

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by stevenramirezgains** [comment] 2023-12-07 04:22
Can confirm, seeing this on my machine as well.

**Comment by chinnasamymca** [comment] 2023-12-07 06:26
+1 Getting incompatible error with latest Inteliji

**Comment by ArishSultan** [comment] 2023-12-07 06:26
Same here, however I haven't faced this kind of issue before.

**Comment by zcwessels** [comment] 2023-12-07 06:32
Same here

**Comment by omegaui** [comment] 2023-12-07 09:04
Same here

**Comment by Constans** [comment] 2023-12-07 10:36
Got the same problem with IntelJ 2023.3

**Comment by HemanthGowda** [comment] 2023-12-07 10:38
Same here

**Comment by Constans** [comment] 2023-12-07 10:39
This seems a duplicate of https://github.com/flutter/flutter-intellij/issues/7115 . There is a solution"" in the linked issue.

**Comment by jwren** [comment] 2023-12-13 21:11
Duplicate of https://github.com/flutter/flutter-intellij/issues/7115

**Closed by jwren** 2023-12-13 21:11 UTC
