### ISSUE TITLE
Flutter Inspector does not show source code

### ISSUE THREAD

**Issue by a-v-ebrahimi** [flutter/flutter-intellij#6894] opened 2023-09-04 05:21 UTC
In Flutter inspector, when I click on widget tree, it does not sync and show respective source code, this was working properly previously.
___
**DevTools version**: 2.25.0
**Connected Device**:
CPU / OS: ia32 (32 bit) android
Dart Version: 3.1.0
Flutter Version: 3.13.2 / stable
Framework / Engine: ff5b5b5fa6 / b20183e040
Connected app type: Flutter native (debug build)

**Comment by a-v-ebrahimi** [comment] 2023-09-06 05:15
> What IDE are you using?

Android Studio Giraffe | 2022.3.1 Patch 1

**Comment by Likhachev17** [comment] 2023-09-07 20:15
faced the same. Please fix it! :( 
Any beta IntelliJ plugins have it now?

**Comment by sleem2012** [comment] 2023-09-09 14:50
faced same problem and it happen for all of my friends in android studio only
I've thoroughly tested this on multiple devices, including 2 Macs and 2 Windows machines, and the problem persists across all of them. However, I want to emphasize that the same DevTool functionality works flawlessly when using Visual Studio Code (VSCode).
i posted it on google issue tracker but they told me to reopen this issue here
I've thoroughly tested this on multiple devices, including 2 Macs and 2 Windows machines, and the problem persists across all of them. However, I want to emphasize that the same DevTool functionality works flawlessly when using Visual Studio Code (VSCode).

https://issuetracker.google.com/issues/299314637

**Comment by majidempire** [comment] 2023-09-11 14:22
Same issue here and I have done many things but no success, is there anyway to downgrade? 

Android Studio Giraffe | 2022.3.1 Patch 1
Build #AI-223.8836.35.2231.10671973, built on August 17, 2023
Runtime version: 17.0.6+0-17.0.6b829.9-10027231 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8

Non-Bundled Plugins:
    Dart (223.8950)
    com.localizely.flutter-intl (1.18.4-2022.2)
    io.flutter (75.1.2)

**Comment by helin24** [comment] 2023-09-11 20:42
I can offer a couple options for fixing this until we make our next plugin release (hopefully soon).

Easier: downgrade your flutter SDK version to 3.7.0 or earlier (another user mentioned 3.10 works, but I was not able to verify myself).

Or keep an updated flutter SDK and try a dev release of the IntelliJ plugin:
1. Download the appropriate plugin for your version of IJ: https://plugins.jetbrains.com/plugin/9212-flutter/versions/dev
2. Go to plugins > Settings button > Install plugin from disk > choose the downloaded file
3. Go to Settings > Languages and frameworks > Flutter > Check "use JCEF browser to show embedded DevTools"

**Comment by majidempire** [comment] 2023-09-11 21:15
> I can offer a couple options for fixing this until we make our next plugin release (hopefully soon).
> 
> Easier: downgrade your flutter SDK version to 3.7.0 or earlier (another user mentioned 3.10 works, but I was not able to verify myself).
> 
> Or keep an updated flutter SDK and try a dev release of the IntelliJ plugin:
> 
>     1. Download the appropriate plugin for your version of IJ: https://plugins.jetbrains.com/plugin/9212-flutter/versions/dev
> 
>     2. Go to plugins > Settings button > Install plugin from disk > choose the downloaded file
> 
>     3. Go to Settings > Languages and frameworks > Flutter > Check "use JCEF browser to show embedded DevTools"

I tried the second option and it worked for me, thanks

**Comment by Likhachev17** [comment] 2023-09-12 00:18
> > I can offer a couple options for fixing this until we make our next plugin release (hopefully soon).
> > Easier: downgrade your flutter SDK version to 3.7.0 or earlier (another user mentioned 3.10 works, but I was not able to verify myself).
> > Or keep an updated flutter SDK and try a dev release of the IntelliJ plugin:
> > ```
> > 1. Download the appropriate plugin for your version of IJ: https://plugins.jetbrains.com/plugin/9212-flutter/versions/dev
> > 
> > 2. Go to plugins > Settings button > Install plugin from disk > choose the downloaded file
> > 
> > 3. Go to Settings > Languages and frameworks > Flutter > Check "use JCEF browser to show embedded DevTools"
> > ```
> 
> I tried the second option and it worked for me, thanks

I tried second option too but it didn't help. Flutter inspector with beta plugin doesn't event launch. Any advices?
IntelliJ IDEA 2023.2.1 (Community Edition)
Flutter Channel stable, 3.13.3, on macOS 13.3.1

**Comment by duymanhit** [comment] 2023-09-12 03:35
I switch to dev channel and it work well.

**Comment by sleem2012** [comment] 2023-09-12 10:48
i tried second option and it help me for showing code when i open dev tool from browser but android studio dev tool don't open and stuck on installing dev tool
<img width="352" alt="Screenshot 2023-09-12 at 1 45 06 PM" src="https://github.com/flutter/flutter-intellij/assets/31719188/a2a76f3e-c1fd-43d1-aee9-dafcf912d969">

**Comment by sleem2012** [comment] 2023-09-12 13:59
> I ha
> 
> > i tried second option and it help me for showing code when i open dev tool from browser but android studio dev tool don't open and stuck on installing dev tool <img alt="Screenshot 2023-09-12 at 1 45 06 PM" width="352" src="https://user-images.githubusercontent.com/31719188/267303811-a2a76f3e-c1fd-43d1-aee9-dafcf912d969.png">
> 
> use File / Invalidate caches / Invalidate and restart Then restart your OS also
> 
> I did it and fixed to open devTools in embeded browser in Android Studio
> 
> Good Luck

dosent work

**Comment by helin24** [comment] 2023-09-12 17:44
@sleem2012 and @Likhachev17 assuming you both checked the "Enable JCEF" option in settings, can you tell me what OS you are using? It may be that JCEF is not supported for your OS, in which case you could use DevTools in a separate browser instead.

**Comment by sleem2012** [comment] 2023-09-12 17:50
> @sleem2012 and @Likhachev17 assuming you both checked the "Enable JCEF" option in settings, can you tell me what OS you are using? It may be that JCEF is not supported for your OS, in which case you could use DevTools in a separate browser instead.

Iam using macbook air m1 ventura os
It works well in sperated browser but don't work in android studio

**Comment by helin24** [comment] 2023-09-12 17:51
@sleem2012 do you want to send me your logs from using it in Android Studio? Help > Show log in finder > idea.log is hte file to send. You can post here or send to helinx@google.com.

**Comment by majidempire** [comment] 2023-09-12 19:29
> @sleem2012 do you want to send me your logs from using it in Android Studio? Help > Show log in finder > idea.log is hte file to send. You can post here or send to [helinx@google.com](mailto:helinx@google.com).

`java.lang.IllegalStateException: JCEF is not supported in this env or failed to initialize
	at com.intellij.ui.jcef.JBCefApp.getInstance(JBCefApp.java:250)
	at com.intellij.ui.jcef.JBCefBrowserBase.lambda$new$3(JBCefBrowserBase.java:152)
	at com.intellij.util.ObjectUtils.notNull(ObjectUtils.java:124)
	at com.intellij.ui.jcef.JBCefBrowserBase.<init>(JBCefBrowserBase.java:152)
	at com.intellij.ui.jcef.JBCefBrowser.<init>(JBCefBrowser.java:190)
	at com.intellij.ui.jcef.JBCefBrowser.<init>(JBCefBrowser.java:150)
	at io.flutter.view.EmbeddedJcefBrowserTab.<init>(EmbeddedJcefBrowser.java:30)
	at io.flutter.view.EmbeddedJcefBrowser.openEmbeddedTab(EmbeddedJcefBrowser.java:68)
	at io.flutter.view.EmbeddedBrowser.openBrowserTabFor(EmbeddedBrowser.java:126)
	at io.flutter.view.EmbeddedBrowser.openPanel(EmbeddedBrowser.java:73)
	at io.flutter.view.FlutterView.lambda$addBrowserInspectorViewContent$3(FlutterView.java:294)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at io.flutter.view.FlutterView.lambda$addBrowserInspectorViewContent$4(FlutterView.java:294)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
`

here is an error log of mine

**Comment by sleem2012** [comment] 2023-09-12 20:12
[idea.log](https://github.com/flutter/flutter-intellij/files/12590472/idea.log)

@helin24

**Comment by kazbeksultanov** [comment] 2023-09-14 10:16
@helin24  
I have the same error with DevTools in Android studio on MacBook Pro m1 pro chip

Device: 
<img width="210" alt="Screenshot 2023-09-14 at 16 12 16" src="https://github.com/flutter/flutter-intellij/assets/17141647/43bbc52d-7bee-4c51-b7ad-606a30eda2be">

```
Android Studio Giraffe | 2022.3.1 Patch 1

Build #AI-223.8836.35.2231.10671973, built on August 17, 2023
Runtime version: 17.0.6+0-17.0.6b829.9-10027231 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
```

Flutter Doctor

```
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.5.1 22G90 darwin-arm64, locale en-KZ)
    • Flutter version 3.13.3 on channel stable at /Users/kazbek/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (8 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/kazbek/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = /Users/kazbek/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

In setting when 'use JCEF' is disabled, there is no error. Just showing:

<img width="346" alt="Screenshot 2023-09-14 at 16 10 49" src="https://github.com/flutter/flutter-intellij/assets/17141647/eab792c0-dd1f-496c-8ad0-30813887fb70">

When 'use JCEF' is enabled, there is dropping error
```
java.lang.IllegalStateException: JCEF is not supported in this env or failed to initialize
	at com.intellij.ui.jcef.JBCefApp.getInstance(JBCefApp.java:250)
	at com.intellij.ui.jcef.JBCefBrowserBase.lambda$new$3(JBCefBrowserBase.java:152)
	at com.intellij.util.ObjectUtils.notNull(ObjectUtils.java:124)
	at com.intellij.ui.jcef.JBCefBrowserBase.<init>(JBCefBrowserBase.java:152)
	at com.intellij.ui.jcef.JBCefBrowser.<init>(JBCefBrowser.java:190)
	at com.intellij.ui.jcef.JBCefBrowser.<init>(JBCefBrowser.java:150)
	at io.flutter.view.EmbeddedJcefBrowserTab.<init>(EmbeddedJcefBrowser.java:30)
	at io.flutter.view.EmbeddedJcefBrowser.openEmbeddedTab(EmbeddedJcefBrowser.java:68)
	at io.flutter.view.EmbeddedBrowser.openBrowserTabFor(EmbeddedBrowser.java:126)
	at io.flutter.view.EmbeddedBrowser.openPanel(EmbeddedBrowser.java:73)
	at io.flutter.view.FlutterView.lambda$addBrowserInspectorViewContent$3(FlutterView.java:294)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at io.flutter.view.FlutterView.lambda$addBrowserInspectorViewContent$4(FlutterView.java:294)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```

I don't know what to do.

I did not want to switch to VS Code, but seem like there is no problem with this.

**Comment by kazbeksultanov** [comment] 2023-09-15 06:34
@helin24 
I found the solution on this article, how to install `JCEF` on android studio, and it worked for me.
(https://medium.com/tech-takeaways/how-to-fix-the-markdown-plugin-preview-in-android-studio-80e74a160ed4)

Steps are simple:
1. Help -> Find Action (or double tap the `SHIFT` button and select `Action` tab)
2. Select `Choose Boot Java Runtime for the IDE...`

<img width="694" alt="Screenshot 2023-09-15 at 12 29 15" src="https://github.com/flutter/flutter-intellij/assets/17141647/09473fa2-64da-450f-ad31-235fff5804a0">

3. I selected first
<img width="512" alt="Screenshot 2023-09-15 at 12 30 14" src="https://github.com/flutter/flutter-intellij/assets/17141647/90174dc5-c14a-463b-ac28-0e11af4dcde7">
<img width="519" alt="Screenshot 2023-09-15 at 12 30 47" src="https://github.com/flutter/flutter-intellij/assets/17141647/4b3584b4-beda-41c0-84df-ad7c4253c195">

4. After make sure that in Flutter Plugin Settings you selected enable `JCEF`

And finally inspector is working!
<img width="342" alt="Screenshot 2023-09-15 at 12 32 35" src="https://github.com/flutter/flutter-intellij/assets/17141647/02dcf312-160a-4a10-9781-02f6c89b146c">


**More issues are:
Selected widget from widget tree do not show code in IDE.**

**Comment by sleem2012** [comment] 2023-09-15 20:52
> @helin24 
> I found the solution on this article, how to install `JCEF` on android studio, and it worked for me.
> (https://medium.com/tech-takeaways/how-to-fix-the-markdown-plugin-preview-in-android-studio-80e74a160ed4)
> 
> Steps are simple:
> 1. Help -> Find Action (or double tap the `SHIFT` button and select `Action` tab)
> 2. Select `Choose Boot Java Runtime for the IDE...`
> 
> <img width="694" alt="Screenshot 2023-09-15 at 12 29 15" src="https://github.com/flutter/flutter-intellij/assets/17141647/09473fa2-64da-450f-ad31-235fff5804a0">
> 
> 3. I selected first
> <img width="512" alt="Screenshot 2023-09-15 at 12 30 14" src="https://github.com/flutter/flutter-intellij/assets/17141647/90174dc5-c14a-463b-ac28-0e11af4dcde7">
> <img width="519" alt="Screenshot 2023-09-15 at 12 30 47" src="https://github.com/flutter/flutter-intellij/assets/17141647/4b3584b4-beda-41c0-84df-ad7c4253c195">
> 
> 4. After make sure that in Flutter Plugin Settings you selected enable `JCEF`
> 
> And finally inspector is working!
> <img width="342" alt="Screenshot 2023-09-15 at 12 32 35" src="https://github.com/flutter/flutter-intellij/assets/17141647/02dcf312-160a-4a10-9781-02f6c89b146c">
> 
> 
> **More issues are:
> Selected widget from widget tree do not show code in IDE.**
> 

This solution helps me ,thanks

**Comment by AlHasanSony** [comment] 2023-09-24 05:41
Previously, when I ran the app and turned on the widget mode in the Flutter Inspector, if I clicked on any widget in the APP, it would immediately navigate to the code related to that widget element inside the Dart file. But now, when I click, it only selects the widget in the widget tree. However, it doesn't navigate to the related code in the Dart file anymore. What could be the possible solution for this?

My expectation is: If I click on any widget in the app, it will immediately navigate to the code related to that widget element inside the Dart file like previously

**[It works fine in flutter version 3.10.6 and earlier, but in later versions, it doesn't work]**

**Comment by AlHasanSony** [comment] 2023-09-24 05:54
Previously, when I ran the app and turned on the widget mode in the Flutter Inspector, if I clicked on any widget in the APP, it would immediately navigate to the code related to that widget element inside the Dart file. But now, when I click, it only selects the widget in the widget tree. However, it doesn't navigate to the related code in the Dart file anymore. What could be the possible solution for this?

My expectation is: If I click on any widget in the app, it will immediately navigate to the code related to that widget element inside the Dart file like previously

_[It works fine in flutter version 3.10.6 and earlier, but in later versions, it doesn't work]_

**Comment by sleem2012** [comment] 2023-09-24 09:50
> Previously, when I ran the app and turned on the widget mode in the Flutter Inspector, if I clicked on any widget in the APP, it would immediately navigate to the code related to that widget element inside the Dart file. But now, when I click, it only selects the widget in the widget tree. However, it doesn't navigate to the related code in the Dart file anymore. What could be the possible solution for this?
> 
> My expectation is: If I click on any widget in the app, it will immediately navigate to the code related to that widget element inside the Dart file like previously
> 
> **[It works fine in flutter version 3.10.6 and earlier, but in later versions, it doesn't work]**


Check this solution 
https://youtu.be/oHcjiMGG4ic?si=QKAkuisWPZR6vvS_

**Comment by Ankitkj1999** [comment] 2023-09-27 12:15
I am facing the same issue macOs: 13.2 (22D49) Apple M1

Flutter version: 3.7.12

Android Studio Giraffe | 2022.3.1 Patch 1
Build #AI-223.8836.35.2231.10671973, built on August 17, 2023
Runtime version: 17.0.6+1-b653.34 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
external.system.auto.import.disabled=true
ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
com.tao.provider (1.5.3)
com.github.copilot (1.2.22.3129)
com.bloc.intellij_generator_plugin (3.4.0)
Dart (223.8950)
andrasferenczi.dart-data-plugin (0.2.0)
com.mallowigi (85.1.0)
io.flutter (75.1.2)
nix-idea (0.4.0.10)

And the video solution provided above does not work for me!

**Comment by waslost0** [comment] 2023-09-29 09:50
> tion provided above does not work for me!

Android emulator not starting `The emulator process for AVD Pixel_XL_API_34 has terminated.`. Only works on ios sim and real devices

**Comment by waslost0** [comment] 2023-09-29 09:52
> @helin24 I found the solution on this article, how to install `JCEF` on android studio, and it worked for me. (https://medium.com/tech-takeaways/how-to-fix-the-markdown-plugin-preview-in-android-studio-80e74a160ed4)
> 
> Steps are simple:
> 
> 1. Help -> Find Action (or double tap the `SHIFT` button and select `Action` tab)
> 2. Select `Choose Boot Java Runtime for the IDE...`
> 
> <img alt="Screenshot 2023-09-15 at 12 29 15" width="694" src="https://user-images.githubusercontent.com/17141647/268194946-09473fa2-64da-450f-ad31-235fff5804a0.png">
> 3. I selected first
> 
> <img alt="Screenshot 2023-09-15 at 12 30 14" width="512" src="https://user-images.githubusercontent.com/17141647/268195100-90174dc5-c14a-463b-ac28-0e11af4dcde7.png"> <img alt="Screenshot 2023-09-15 at 12 30 47" width="519" src="https://user-images.githubusercontent.com/17141647/268195202-4b3584b4-beda-41c0-84df-ad7c4253c195.png">
> 4. After make sure that in Flutter Plugin Settings you selected enable `JCEF`
> 
> And finally inspector is working! <img alt="Screenshot 2023-09-15 at 12 32 35" width="342" src="https://user-images.githubusercontent.com/17141647/268195626-02dcf312-160a-4a10-9781-02f6c89b146c.png">
> 
> **More issues are: Selected widget from widget tree do not show code in IDE.**

Android emulator not starting The emulator process for AVD Pixel_XL_API_34 has terminated.. Only works on ios sim and real devices

**Comment by a-v-ebrahimi** [comment] 2023-10-19 06:46
> > Previously, when I ran the app and turned on the widget mode in the Flutter Inspector, if I clicked on any widget in the APP, it would immediately navigate to the code related to that widget element inside the Dart file. But now, when I click, it only selects the widget in the widget tree. However, it doesn't navigate to the related code in the Dart file anymore. What could be the possible solution for this?
> > My expectation is: If I click on any widget in the app, it will immediately navigate to the code related to that widget element inside the Dart file like previously
> > **[It works fine in flutter version 3.10.6 and earlier, but in later versions, it doesn't work]**
> 
> Check this solution https://youtu.be/oHcjiMGG4ic?si=QKAkuisWPZR6vvS_

Worked, at last, thank you!

**Comment by muhsinzyne** [comment] 2023-10-19 11:00
> > > Previously, when I ran the app and turned on the widget mode in the Flutter Inspector, if I clicked on any widget in the APP, it would immediately navigate to the code related to that widget element inside the Dart file. But now, when I click, it only selects the widget in the widget tree. However, it doesn't navigate to the related code in the Dart file anymore. What could be the possible solution for this?
> > > My expectation is: If I click on any widget in the app, it will immediately navigate to the code related to that widget element inside the Dart file like previously
> > > **[It works fine in flutter version 3.10.6 and earlier, but in later versions, it doesn't work]**
> > 
> > 
> > Check this solution https://youtu.be/oHcjiMGG4ic?si=QKAkuisWPZR6vvS_
> 
> Worked, at last, thank you!

Please copy your flutter version, android studio version etc.. i am stuck at here

**Comment by jishkln** [comment] 2023-10-20 11:06
i getting the same issue ,  it is not working to me

**Comment by kenzieschmoll** [comment] 2023-10-20 16:40
This appears to be a duplicate of https://github.com/flutter/flutter-intellij/issues/6875. A new release of the Flutter plugin should be shipped next week with a fix for this issue. CC @jwren

**Closed by kenzieschmoll** 2023-10-20 16:40 UTC
Labels: bug, P1

**Comment by MohammadAlieye** [comment] 2023-12-14 06:16
"Hey there! 🚀 Good news! Just update your Flutter to the latest version - Flutter 3.16.2 and Dart 3.2.2. The Flutter team has fixed the issue with the Flutter Inspector not showing source code. 
Get the latest update at https://github.com/flutter/flutter and you'll be good to go!
 Happy coding! 😎👩‍💻

**Comment by Oubi256** [comment] 2024-10-07 16:16
If you do run into this problem like in the video, make sure you don't have space in the project path.

https://github.com/user-attachments/assets/4b1efa13-c7e1-417f-b379-730021e0aea1



**BAD**
`/Users/myprofile/flutter projects/myproject`

**GOOD**
`/Users/myprofile/flutter_projects/myproject`

**Comment by hoangduchuu** [comment] 2025-02-14 03:50
> If you do run into this problem like in the video, make sure you don't have space in the project path.
> 
>  2024-10-07_18.13.16.mp4 
> **BAD** `/Users/myprofile/flutter projects/myproject`
> 
> **GOOD** `/Users/myprofile/flutter_projects/myproject`

Đẹp trai, you save my life
