### ISSUE TITLE
Flutter Plugin v39.0.5: code analysis stops working, 100% CPU

### ISSUE THREAD

**Issue by andreidiaconu** [flutter/flutter-intellij#3853] opened 2019-09-06 08:46 UTC
## Steps to Reproduce

Editing code, not sure what triggers this to happen. It happened twice in 15 minutes, after updating the plugin to 39.0.5. Everything works fine until:

- IntelliJ editor highlights an error (for example, this time it's a final field that I haven't initialized in the constructor, since I'm in the middle of adding this final field to my class)
- IntelliJ code error does not get un-highlighted after fixing the code. Code analysis seems to have stopped and remains in this state.
- `dart` process shows high CPU usage in the MacOS Activity Monitor.
- laptop heats up, can't get much done

Will try to reboot and see if that does anything. If not, will have to figure out how to downgrade to the previous version and see if that works.

## Version info

[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G95, locale en-RO)
    • Flutter version 1.7.8+hotfix.4 at /Users/andrei/Library/Android/flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/andrei/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/andrei/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.6.0.beta.2

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6262.58

[✓] Connected device (1 available)
    • iPhone Xʀ • B7750E9B-926E-4A03-924C-DFF7905E680C • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!

**Comment by jacob314** [comment] 2019-09-10 23:08
Sorry you had this bug. It is likely a bug in the dart analysis server. Let us know if you can reproduce the issue. To solve the problem we would likely need a sample application that reproduces the problem.

**Comment by andreidiaconu** [comment] 2019-09-11 05:34
The system reboot fixed the issue for me. Sorry I can't help reproduce it
anymore.

**Comment by stevemessick** [comment] 2019-09-16 13:04
Thanks for getting back to us @andreidiaconu. I'm going to close this since Flutter is now at 1.9.1, which upgrades Dart to 2.5. It is likely this problem has been fixed, but if it occurs again please re-open this bug.

**Closed by stevemessick** 2019-09-16 13:04 UTC
Labels: bug
