### ISSUE TITLE
Error reported after upgrade to Flutter 3.19 and restart of IntelliJ

### ISSUE THREAD

**Issue by bjorn-eiderback** [flutter/flutter-intellij#7364] opened 2024-04-18 07:43 UTC
## What happened

Restarting the IDE after updating the Flutter plugin to the latest version, the following error message i

## Version information

IntelliJ IDEA `2024.1` • Flutter plugin `io.flutter 79.0.3` • Dart plugin `241.15845`

Flutter 3.19.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 54e66469a9 (12 hours ago) • 2024-04-17 13:08:03 -0700
Engine • revision c4cd48e186
Tools • Dart 3.3.4 • DevTools 2.31.1

## Exception

null

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.flutter.actions.OpenSimulatorAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.flutter]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**Comment by jwren** [comment] 2024-11-20 01:04
Duplicate of https://github.com/flutter/flutter-intellij/issues/7330

**Closed by jwren** 2024-11-20 01:04 UTC
Labels: bug
