### ISSUE TITLE
Debugger doesn't stop at breakpoints in hello_services example on Android

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#471] opened 2016-11-24 08:16 UTC
_From @jsiedentop on November 23, 2016 18:59_

## Steps to Reproduce
1. Open the hello_service example in IntelliJ: `file -> open -> /flutter/examples/hello_services/`
2. Set a breakpoint (for example in line 66 inside of `main()`)
3. Start debugging: `run -> debug`
4. The example app start on the android device, but doesn't stop at breakpoints.

Tested with ``HTC One M8`` and ``Samsung Galaxy Note 3``. An other user in the flutter gitter chat report the same issue.

## Logs
```
Starting device daemon...
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:flutterBuild
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:copyFlutterAssetsDebug
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources
:app:generateDebugSources
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:prePackageMarkerForDebug
:app:transformClassesWithDexForDebug UP-TO-DATE
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:validateDebugSigning
:app:packageDebug
:app:zipalignDebug
:app:assembleDebug
:app:preReleaseBuild UP-TO-DATE
:app:checkReleaseManifest
:app:prepareReleaseDependencies
:app:compileReleaseAidl UP-TO-DATE
:app:compileReleaseRenderscript UP-TO-DATE
:app:generateReleaseBuildConfig UP-TO-DATE
:app:mergeReleaseShaders UP-TO-DATE
:app:compileReleaseShaders UP-TO-DATE
:app:generateReleaseAssets UP-TO-DATE
:app:mergeReleaseAssets UP-TO-DATE
:app:copyFlutterAssetsRelease
:app:generateReleaseResValues UP-TO-DATE
:app:generateReleaseResources UP-TO-DATE
:app:mergeReleaseResources UP-TO-DATE
:app:processReleaseManifest UP-TO-DATE
:app:processReleaseResources
:app:generateReleaseSources
:app:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:app:compileReleaseJavaWithJavac UP-TO-DATE
:app:compileReleaseNdk UP-TO-DATE
:app:compileReleaseSources UP-TO-DATE
:app:lintVitalRelease
:app:prePackageMarkerForRelease
:app:transformClassesWithDexForRelease UP-TO-DATE
:app:mergeReleaseJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:app:processReleaseJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:app:packageRelease
:app:assembleRelease
:app:assemble
:app:compileLint
:app:lint
Ran lint on variant release: 5 issues found
Ran lint on variant debug: 5 issues found
Wrote HTML report to file:///Users/jsi/temp/hello_service/android/app/build/outputs/lint-results-debug.html
Wrote XML report to file:///Users/jsi/temp/hello_service/android/app/build/outputs/lint-results-debug.xml
:app:incrementalDebugUnitTestJavaCompilationSafeguard UP-TO-DATE
:app:preDebugUnitTestBuild UP-TO-DATE
:app:prepareDebugUnitTestDependencies
:app:compileDebugUnitTestJavaWithJavac UP-TO-DATE
:app:processDebugUnitTestJavaRes UP-TO-DATE

:app:compileDebugUnitTestSources UP-TO-DATE
:app:mockableAndroidJar UP-TO-DATE
:app:assembleDebugUnitTest UP-TO-DATE
:app:testDebugUnitTest UP-TO-DATE
:app:incrementalReleaseUnitTestJavaCompilationSafeguard UP-TO-DATE
:app:preReleaseUnitTestBuild UP-TO-DATE
:app:prepareReleaseUnitTestDependencies
:app:compileReleaseUnitTestJavaWithJavac UP-TO-DATE
:app:processReleaseUnitTestJavaRes UP-TO-DATE
:app:compileReleaseUnitTestSources UP-TO-DATE
:app:assembleReleaseUnitTest UP-TO-DATE
:app:testReleaseUnitTest UP-TO-DATE
:app:test UP-TO-DATE
:app:check
:app:build

BUILD SUCCESSFUL

Total time: 22.876 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html
Built android/app/build/outputs/apk/app-debug.apk (10.2MB).
Uninstalling old version...
Running lib/main.dart on HTC One M8...
```
## Flutter Doctor
```
$ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/jsi/Library/flutter
    • Framework revision a0c567f751 (2 days ago), 2016-11-21 20:17:41
    • Engine revision cea5ed2b9b
    • Tools Dart version 1.21.0-dev.6.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /Users/jsi/Library/Android/sdk
    • Platform android-25, build-tools 25.0.0
    • Java(TM) SE Runtime Environment (build 1.8.0_111-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.1, Build version 8B62

[✓] IntelliJ IDEA Community Edition (version 2016.2.5)
    • Dart plugin installed
    • Flutter plugin installed

[✓] Connected devices
    • HTC One M8 • SH46CWM03491 • android-arm • Android 5.0.1 (API 21)
    • SM N9005 • eb53b4f0 • android-arm • Android 5.0 (API 21)
```

_Copied from original issue: flutter/flutter#7003_

**Comment by mit-mit** [comment] 2016-11-24 08:16
_From @eseidelGoogle on November 24, 2016 4:41_

Thanks for the report.

**Comment by mit-mit** [comment] 2016-11-24 08:23
@jsiedentop what version of the Flutter IJ plugin do you have? (Settings/Preferences -> Plugins -> Flutter)

**Comment by mit-mit** [comment] 2016-11-24 08:30
@jsiedentop I think this may be related to https://github.com/flutter/flutter-intellij/issues/466 (and noted your comment that you are on the latest plugin there).

Can you try to see if the following workaround makes it work?

1. Close any open projects you have in IJ with `hello_services` in them
1. Invoke File > New> Project... in IJ
1. Click Next on the Flutter SDK page
1. In the New Project screen, click the `...` button next to Project location, and browse to the folder that has the `hello_services` project
1. Click Finish
1. Say yes when it asks if you want to override an existing .idea or .idl files
1. Now add breakpoint and start Run > Debug

**Comment by eseidelGoogle** [comment] 2016-11-24 15:16
Note that hello_services is typically run differently than simpler flutter apps.  We haven't yet taught `flutter build` and `flutter run` about gradle so you have to call it directly to build the additional custom java code hello_services depends on:
https://github.com/flutter/flutter/blob/master/examples/hello_services/README.md

**Comment by jsiedentop** [comment] 2016-11-24 16:33
@mit-mit: I had the debugging error in one of my projects as I tried to use QR-Code scanning in my own flutter app. To make the error reproducible and eliminate own mistakes, I tried to get the same error with the example code. The first error I've got was #466. After founding the workaround, I could document the second error with debugging. Sorry for the bad report. I should have mentioned that I created the flutter.yaml file manually (My workaround in #466).

I deleted my hello_service example and followed your instructions with a new copy of the example from github. It worked fine. I could start the app without creating the flutter.yaml file manually. So your instructions are the better workaround for opening the example projects. 

Bad news: Anyway, the debugger did't stop at breakpoints. 

@eseidelGoogle: It was not necessary to create the `android/local.properties` file manually. after following the instructions from mit-mit the file was automatically created, the app starts on my android phone after building and the geolocation button also works fine.

**Comment by mit-mit** [comment] 2016-11-29 14:38
@pq did you have a chance to look at this?

**Comment by pq** [comment] 2016-11-29 20:58
Sorry for the slow reply.  I'm in flight and no android device handy.  Maybe @devoncarew can try and repro?  Otherwise, I can try when I'm back in the office on Friday.

**Comment by devoncarew** [comment] 2016-12-13 17:25
We need to verify whether this is a bug or some feature work.

**Comment by pq** [comment] 2017-01-09 18:49
As per our conversation, this looks like feature work that should be coordinated with the work being done in AAR.

cc @mit-mit

**Comment by devoncarew** [comment] 2017-01-30 21:48
Just repro-ing this now - I am able to debug the hello_services project with the flutter plugin. I:

- opened the examples/hello_service project in IntelliJ
- opened the iOS simulator
- set a breakpoint at line 59 (in setState(), `_latitude = reply...`)
- hit the 'debug' icon in the toolbar with the `hello_services` flutter launch config selected
- hit the 'locate' button in the app
- the breakpoint did fire and I could debug

I'm going to close this, but we'll keep an eye on the hello_service project as the interop work progresses.

**Closed by devoncarew** 2017-01-30 21:48 UTC
Labels: bug, high priority, topic-debugging, ▣ platform-android
