### ISSUE TITLE
Flutter plugin is not available on IntelliJ IDEA 2023.3 (Ultimate Edition)

### ISSUE THREAD

**Issue by hugo-rodrigues-hugintech** [flutter/flutter-intellij#7115] opened 2023-12-06 16:46 UTC
## Steps to Reproduce

Flutter plugin is not available on the marketplace to install on:

IntelliJ IDEA 2023.3 (Ultimate Edition)
Build #IU-233.11799.241, built on December 2, 2023
Runtime version: 17.0.9+7-b1087.7 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.1.1
GC: G1 Young Generation, G1 Old Generation
Memory: 10024M
Cores: 16
Metal Rendering is ON

## Version info

[✓] Flutter (Channel stable, 3.16.1, on macOS 14.1.1 23B81 darwin-x64, locale en-PT)
    • Flutter version 3.16.1 on channel stable at /Users/hugorodrigues/opt/flutter/flutter-3.16.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7f20e5d18c (9 days ago), 2023-11-27 09:47:30 -0800
    • Engine revision 22b600f240
    • Dart version 3.2.1
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/hugorodrigues/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 233.11799.172

[✓] VS Code (version 1.84.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1.1 23B81 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.199

[✓] Network resources
    • All expected network resources are available.

**Comment by blasko** [comment] 2023-12-06 17:46
First time I've seen the Flutter plugin incompatible with the latest IntelliJ version. Not good.

**Comment by ibcoleman** [comment] 2023-12-06 18:42
This is a little concerning. One feature that would be extremely helpful--and possibly not a huge effort on JB's end--would be to generate a report of incompatible plugins that would be affected when giving the user the option of updating their IDE.

**Comment by yehorh** [comment] 2023-12-06 19:28
I'm puzzled.

Even the dev builds are silent for IDEA 2023.3
Previous issues with the widget inspector that lasted for more than a few months
Could it be that IDEA is no longer being supported and should I stop paying for it and switch to vscode? I'm just clarifying so I can understand what to do with the subscription, because Dart there is not a priority either
sad...

**Comment by newfantoski** [comment] 2023-12-06 21:24
I couldn't make it work with EAP for some time and I wondered why there still hadn't been an update, but now that's 2023.3 is the **main** version, that's becoming a real problem. 

Does anyone know of a temporary fix, a bypass, to make it work on 2023.3 ?

**Comment by jonathanlermitage** [comment] 2023-12-07 00:01
> Does anyone know of a temporary fix, a bypass, to make it work on 2023.3 ?

You can force compatibility with IDE 2023.3.  
* download the ZIP plugin from https://plugins.jetbrains.com/plugin/9212-flutter/versions/stable
* open the ZIP, open `lib/instrumented-flutter-idea-76.3.4.jar/META-INF/plugin.xml`
* line 18 "<idea-version ...": remove the until variable+value. Save and update the ZIP file.

It will tell the IDE to accept the plugin, as there is no more maximum IDE version.  
Please note that the modified plugin may NOT work, as some IDE APIs may have changed. At least, you can try and see if it works. You can do this for every plugin.  
 
I modified the latest version by removing the `until` value, you can try it at your own risk: 
[flutter-intellij no-until-tag.zip](https://github.com/flutter/flutter-intellij/files/13592887/flutter-intellij.no-until-tag.zip)  
I am new to Flutter, so, for now, I don't know what to test. I simply wanted to learn Flutter from today 😅

**Comment by applezrock** [comment] 2023-12-07 03:58
I have the same problem. I cannot build my project. Please fix this immediately.

**Comment by zcwessels** [comment] 2023-12-07 06:57
> > Does anyone know of a temporary fix, a bypass, to make it work on 2023.3 ?
> 
> You can force compatibility with IDE 2023.3.
> 
> * download the ZIP plugin from https://plugins.jetbrains.com/plugin/9212-flutter/versions/stable
> * open the ZIP, open `lib/instrumented-flutter-idea-76.3.4.jar/META-INF/plugin.xml`
> * line 18 "<idea-version ...": remove the until variable+value. Save and update the ZIP file.
> 
> It will tell the IDE to accept the plugin, as there is no more maximum IDE version. Please note that the modified plugin may NOT work, as some IDE APIs may have changed. At least, you can try and see if it works. You can do this for every plugin.
> 
> I modified the latest version (76.3.4) by removing the `until` value, you can try it at your own risk: [flutter-intellij no-until-tag.zip](https://github.com/flutter/flutter-intellij/files/13592887/flutter-intellij.no-until-tag.zip) I am new to Flutter, so, for now, I don't know what to test. I simply wanted to learn Flutter from today 😅
> 
> Edit: I did some tests and it seems to work. I can build and tests some sample projects.

Thank you

**Comment by hugo-rodrigues-hugintech** [comment] 2023-12-07 10:30
@jonathanlermitage Many many thanks!!!

It works very well! I just compile a massive flutter project!

**Comment by jonathanlermitage** [comment] 2023-12-08 02:07
> This is a little concerning. One feature that would be extremely helpful--and possibly not a huge effort on JB's end--would be to generate a report of incompatible plugins that would be affected when giving the user the option of updating their IDE.

This report actually exists already, and it works super well.  
The issue is: the Flutter plugin sets a compatibility flag with a range of IDE versions: https://github.com/flutter/flutter-intellij/blob/master/resources/META-INF/plugin.xml#L18. Here, the plugin is compatible with 2023.2 IDEs only, not 2023.3 nor EAP.  
A solution would be to set only a minimum IDE version, automate the testing against EAP builds, and fix compatibility with EAP builds asap (this way, we are 99.999% sure it will work fine with the next stable IDE release, especially when an RC has been published). Unfortunately, it can be (very) time-consuming, depending on the APIs the plugin depends on, things like that.

**Comment by xtien** [comment] 2023-12-08 09:26
> First time I've seen the Flutter plugin incompatible with the latest IntelliJ version. Not good.

Flutter usually waits for the release build before updating the plugin. I use the EAP build of intellij, I have seen this issue on the plugins at least twice before.

**Comment by scris** [comment] 2023-12-09 08:47
A version compatible (77.0.1) has now been released: https://plugins.jetbrains.com/plugin/9212-flutter/versions/stable/451792

**Comment by jwren** [comment] 2023-12-13 21:09
Thanks all for filing issues and updating accordingly.  Closing this out with the release.

**Closed by jwren** 2023-12-13 21:09 UTC
