### ISSUE TITLE
Too much CPU consumption after using Android Studio for few mins. 

### ISSUE THREAD

**Issue by iLoveDocs** [flutter/flutter-intellij#4849] opened 2020-09-17 17:35 UTC
This isn't easily reproducible, but I can give you an insight when the problem occurs.

I open the project, start writing code in it. IDE works flawlessly for 10-12 mins, (I don't open any other app or even emulators/simulators in the meantime, simple coding). 

Slowly, I start seeing some high cpu consumption in Activity Monitor. It generally happens because of code suggestions (what we call that smart completion?). After that it becomes so much difficult to code, even a single modifier `var` takes too long to get typed on the editor.  I saw [this](https://stackoverflow.com/questions/19986498/android-studio-using-100-cpu-at-all-times-no-background-processes-appear-to) and [this](https://stackoverflow.com/questions/53075228/dart-consuming-high-cpu), tried everything but nothing made any difference, I thought it could be because of some plugins, so I installed IntelliJ Idea to verify it, it worked fine for some 30-35 mins but it also started showing that lagginess. 

I'm attaching the screenshot of plugins:
![image](https://user-images.githubusercontent.com/40364434/93504980-85f34500-f91a-11ea-9a5e-2834d58b6ef8.png)

Here's a [one min long video](https://imgur.com/usgClZ3) showing the high CPU usage. In the video, I am simply scrolling the class in the background and nothing more, the CPU usage is over 100% most of the time. But when I restart the IDE, and work for around 10 mins, the CPU consumption is actually less than 10%, but as I said it gradually increases over time, which I don't understand why. 

In the video, when I got out of memory error, I set the memory to the recommended figure, invalidated the caches and restarted the AS, but again it didn't much difference. 

**Flutter doctor:**
[✓] Flutter (Channel dev, 1.22.0-12.0.pre, on Mac OS X 10.15.1 19B88, locale en-GB)
    • Flutter version 1.22.0-12.0.pre at /Users/docs/sample/flutter
    • Framework revision a27c242b0e (6 days ago), 2020-09-11 17:46:57 -0400
    • Engine revision fee6f9e533
    • Dart version 2.10.0 (build 2.10.0-110.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/docs/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

**Machine specs:** 

Processor: 3.4 GHz Quad-Core Intel Core i5
Memory: 24 GB 2400 MHz DDR4
macOS Catalina v10.15.1
GPU: Radeon Pro 570 4 GB

**Comment by bernaferrari** [comment] 2020-09-20 18:35
Agreed. It is hard to report, but I've been having the same issue recently.

**Comment by tugayac** [comment] 2020-10-02 20:01
I've encountered this problem as well. The exact same thing happens as shown in the video above. I've tried everything I can think of, including:
* `flutter clean` and clearing all cached packages
* Invalidating Caches and Restarting Android Studio
* Increasing the max memory allocation pool size to 4GB
* Restarting my computer

I've noticed a pattern however, that it only seems to happen in very large Dart files. I have a database connection and initialization file which is ~150 lines long, but the generated file that's part of it is ~3500 lines long. I use [Moor](https://moor.simonbinder.eu/) as the SQLite wrapper so unfortunately I don't have much of a choice here when it comes to breaking down the file into smaller pieces (or perhaps I do and I'm not aware of such a feature?)

For now, I've worked around the problem by writing code in another file and then copying it into the database connection and initialization file. As long as I only spend a few minutes in that file, I can avoid the CPU spike.

**Comment by iLoveDocs** [comment] 2020-10-03 07:58
@tugayac You're absolutely right, even I tried all the four workarounds (found on the internet) and nothing actually worked and it for me it happens in all parts of the code, I think the problem is related to your project length. I've a good big project and the problem persist only for that project. The rest of my projects work without any issue.

**Comment by KlausJokinen** [comment] 2020-10-11 11:01
I'm having the same issue. It usually starts after like 5-10 minutes of coding.

**Comment by ericwindmill** [comment] 2020-10-14 17:17
Just +1ing this. I can work for up to an hour until I get an error message from Intellij about memory usage.

I can't be 100% positive that this is Flutter plug-in, but I only use Intellij for Dart development. Webstorm and Goland work fine

**Comment by iLoveDocs** [comment] 2020-10-15 12:08
@ericwindmill  You forgot to implement your fist line. 

>Just +1ing this

**Comment by jezsung** [comment] 2020-11-21 01:23
I'm experiencing the same issue recently. IDE gets really slow after around 5-10 minutes. For me, especially when editing the Bloc file which is from the bloc & flutter_bloc package.

**Comment by mzdm** [comment] 2020-11-21 16:26
> I'm experiencing the same issue recently. IDE gets really slow after around 5-10 minutes. For me, especially when editing the Bloc file which is from the bloc & flutter_bloc package.

Same is happening to me since I started using bloc (when I edit these files especially long ones) typing is very laggy

**Comment by KlausJokinen** [comment] 2020-11-21 19:37
> > I'm experiencing the same issue recently. IDE gets really slow after around 5-10 minutes. For me, especially when editing the Bloc file which is from the bloc & flutter_bloc package.
> 
> Same is happening to me since I started using bloc (when I edit these files especially long ones) typing is very laggy

Are you guys also using some code generation? Same thing is happening to me with BloC and Freezed.

**Comment by mzdm** [comment] 2020-11-21 19:54
> > > I'm experiencing the same issue recently. IDE gets really slow after around 5-10 minutes. For me, especially when editing the Bloc file which is from the bloc & flutter_bloc package.
> > 
> > 
> > Same is happening to me since I started using bloc (when I edit these files especially long ones) typing is very laggy
> 
> Are you guys also using some code generation? Same thing is happening to me with BloC and Freezed.

Yes - freezed also - but I have don't `watch` for changes to it doesn't automatically generate.

I have this lagging issue for more than about 2 months and it also happened in a project where I didn't have freezed package though. Strange that it happens only within bloc files.



<br>
<br>
Also another weird issue when I declare this:

`final AsyncSnapshot<List<T>> something;` dart analysis laggs and to have red errors fixed I need to restart Android Studio...

**Comment by KlausJokinen** [comment] 2020-11-21 21:27
> > > > I'm experiencing the same issue recently. IDE gets really slow after around 5-10 minutes. For me, especially when editing the Bloc file which is from the bloc & flutter_bloc package.
> > > 
> > > 
> > > Same is happening to me since I started using bloc (when I edit these files especially long ones) typing is very laggy
> > 
> > 
> > Are you guys also using some code generation? Same thing is happening to me with BloC and Freezed.
> 
> Yes - freezed also - but I don't have `watch` for changes to it doesn't automatically generate.
> 
> I have this lagging issue for more than about 2 months and it also happened in a project where I didn't have freezed package though. Strange that it happens only within bloc files.
> 
> 
> 
> Also another weird issue when I declare this:
> `final AsyncSnapshot<List<T>> something;` dart analysis laggs and to have red errors fixed I need to restart Android Studio...

Could you try and see if you can reproduce this issue: https://github.com/dart-lang/sdk/issues/43166

**Comment by jezsung** [comment] 2020-11-22 01:20
@KlausJokinen @mzdm  I'm only using Bloc. I'm not sure what causes this issue. Do you guys use macOS? I didn't experience this issue when I was using Windows but it happens after I switched to macOS. I'm using Macbook Pro 2020 with 16GB RAM i5 8th

**Comment by jezsung** [comment] 2020-11-22 04:31
For those of you who are struggling with this problem, I solved it by just downgrading the VSCode extension. Unfortunately, I couldn't find a way to downgrade the plugin for Android Studio.

Here's the link to how to install the previous version of extensions
https://code.visualstudio.com/updates/v1_30#_extensions

**Comment by KlausJokinen** [comment] 2020-11-22 05:56
> @KlausJokinen @mzdm I'm only using Bloc. I'm not sure what causes this issue. Do you guys use macOS? I didn't experience this issue when I was using Windows but it happens after I switched to macOS. I'm using Macbook Pro 2020 with 16GB RAM i5 8th

Im using Windows so its not OS related.

**Comment by AndriiChuzhynov** [comment] 2020-12-01 20:09
Hi All, 
Is the problem appears with all files or more it's more related to some specific files? 

I found strange analyzer behavior with files that composed using `part ""`, `part of ""`. 
So, if you have composed files, remove it and try to reproduce the issue.

**Comment by iLoveDocs** [comment] 2020-12-02 02:52
@AndriiChuzhynov  I'm not using anything like BLoC/Provider/ScopedModel/Redux etc, simple plain dart code. I had a file with over 10,000 lines, so my IDE already used to freeze in between. I decided to break it in parts and now I'm using `part ''` and `part of''`. And even that is causing the same issue. 

This doesn't happen with other files in the project.

**Comment by jezsung** [comment] 2020-12-02 03:36
@AndriiChuzhynov @iLoveDocs  Bloc files also contain `part` and `part of` keywords. Looks like these cause the problem.

**Comment by KiwiArch** [comment] 2020-12-03 00:31
Also facing this issue, even with blocs that are only a couple of hundred lines of code the analyzer is forever churning and making code suggestions worse than useless.  Removing all the part declarations from my blocs didn't immediately resolve the problem but also deleting the content of .dartServer/.analysis-driver/ did.  Now wish I'd cleaned that folder first to see it that on its own helped as results on whats made the difference are, for now, inconclusive.

**Comment by drekka** [comment] 2020-12-17 04:26
Having massive issues with the current project. Not using bloc or anything like that. Pretty new project with. only 1000 LOC or so. The moment I run the app on a simulator, CPU maxes out and AS become sluggish and unusable. Flutter performance reports poor frame rates in screens that were good previously, and reports constant rebuilds of widgets that should only build once but also reports no increase in build counts. So something really weird going on there.

**Comment by jacksontong** [comment] 2020-12-17 16:25
I'm learning Flutter + Bloc, it's very frustrated with this issue.

**Comment by KiwiArch** [comment] 2020-12-18 00:33
Been two weeks now and haven't had a repeat of this issue since removing all the usage of 'part'  in the blocs.

As Andrii said above you also need to delete ~/.dartServer/.analysis-driver/ and then restart the IDE.

**Comment by drekka** [comment] 2020-12-21 00:51
Um, solved it. :-) PEBCAK. I'd switched to using the integrated GPU on the simulator because of a painting issue with the discrete GPU when running Flutter apps. Solved the painting issue but the performance went to the dogs :-)

**Comment by AAverin** [comment] 2021-01-09 09:16
Can confirm that the issue seems to be related to having `part` and `part of` in the codebase

**Comment by KlausJokisuo** [comment] 2021-01-09 11:45
I believe the analyzer freaks out when there are too many .part files.

**Comment by AAverin** [comment] 2021-01-09 11:56
@KlausJokisuo I had only 1 part file, just started the project. So it's not the reason

**Comment by AndriiChuzhynov** [comment] 2021-01-09 12:37
Fix for parts already merged to Dart SDK 🎉 
https://github.com/dart-lang/sdk/issues/44353

**Comment by stevemessick** [comment] 2021-03-11 22:57
Looks like this was fixed in https://dart-review.googlesource.com/c/sdk/+/177640

If there is another problem please open a separate issue.

**Closed by stevemessick** 2021-03-11 22:57 UTC
