### ISSUE TITLE
Feature request: a way to find method overrides

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter-intellij#950] opened 2017-04-25 17:25 UTC
I find myself frequently right-clicking on a method and looking for a "Find Overrides" option - or wishing that "Find Usages" produced a section that showed overrides.

**Comment by devoncarew** [comment] 2017-04-25 17:29
I think you want the 'down arrow' decoration next to a method, in the editor ruler column:

<img width="383" alt="screen shot 2017-04-25 at 10 28 29 am" src="https://cloud.githubusercontent.com/assets/1269969/25398780/036b4a74-29a2-11e7-9f11-7c9e2d8e1798.png">

there is a feature request for this - it's an analysis server feature.

**Comment by devoncarew** [comment] 2017-04-25 17:31
(I'm not able to locate the issue in the sdk repo right now; @scheglov, this is a request for the overrides search)

**Comment by tvolkert** [comment] 2017-04-25 17:33
Hmm - I don't have a 'down arrow':

![ide](https://cloud.githubusercontent.com/assets/15253456/25398954/9cfd7766-29a2-11e7-923e-80256a5bb387.png)

**Comment by devoncarew** [comment] 2017-04-25 17:34
That's a screenshot from the Java support -

**Comment by alexander-doroshko** [comment] 2017-04-25 17:37
Down arrows are broken since Dart SDK 1.23, the issue is https://github.com/dart-lang/sdk/issues/29113.
You may still use Method Hierarchy (Cmd+Shift+H or Ctrl+Shift+H on method name)

**Comment by tvolkert** [comment] 2017-04-25 17:41
Method Hierarchy is disabled (possibly because it's a getter)

**Comment by alexander-doroshko** [comment] 2017-04-25 17:43
> Method Hierarchy is disabled (possibly because it's a getter)

I guess it could be fixed. Please file an issue in https://youtrack.jetbrains.com/issues/WEB (set Subsystem: Dart).

**Comment by tvolkert** [comment] 2017-04-25 17:51
> Please file an issue

Done - https://youtrack.jetbrains.com/issue/WEB-26607

**Comment by devoncarew** [comment] 2017-04-25 18:25
Closing, since more specific work is tracked in dart-lang/sdk#29113 and https://youtrack.jetbrains.com/issue/WEB-26607.

**Closed by devoncarew** 2017-04-25 18:25 UTC

**Comment by devoncarew** [comment] 2017-06-21 21:29
(implemented recently: https://codereview.chromium.org/2942753002/)
