### ISSUE TITLE
Problem with the Flutter plugin

### ISSUE THREAD

**Issue by bushcravter** [flutter/flutter-intellij#6988] opened 2023-10-25 16:07 UTC
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Start the IDe

## Version info

[✓] Flutter (Channel stable, 3.13.8, on Ubuntu 23.10 6.5.0-9-generic, locale de_DE.UTF-8)
    • Flutter version 3.13.8 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c4930c4ac (vor 7 Tagen), 2023-10-18 10:57:55 -0500
    • Engine revision 767d8c75e8
    • Dart version 3.1.4
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /opt/android-sdk/
    • Platform android-34-ext8, build-tools 34.0.0
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 16.0.6 (15)
    • cmake version 3.27.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2022.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 75.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at /opt/intellij
    • Flutter plugin version 75.1.4
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • SM F936B (mobile) • RFCT8022QVA • android-arm64  • Android 13 (API 33)
    • Linux (desktop)   • linux       • linux-x64      • Ubuntu 23.10 6.5.0-9-generic
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 118.0.5993.117

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by jwren** [comment] 2023-10-25 21:38
Duplicate of https://github.com/flutter/flutter-intellij/issues/6942

**Closed by jwren** 2023-10-25 21:38 UTC
