### ISSUE TITLE
Enforcing non-nullable type on a nullable param in constructor breaks hot reload / hot restart

### ISSUE THREAD

**Issue by Amphaal** [flutter/flutter-intellij#6602] opened 2023-02-03 09:05 UTC
## Steps to Reproduce

Run this:

```
import 'package:flutter/material.dart';

void main() async {
  runApp(
    const Scaffold(
      body: Preview.enforce(title: 'test'),
    ),
  );
}

class Preview extends StatelessWidget {
  const Preview({String? title}) : title = title ?? 'default';
  const Preview.enforce({required String this.title});

  final String? title;

  @override
  Widget build(BuildContext context) {
    return Text(title!);
  }
}
```

... then try to change anything in the file : the hot reload won't work. 

The problem here is **the enforced non-nullable** `this.title` in the alternative constructor, which is correct Dart syntax and should not break anything regarding hot reload / hot restart ; Changing to `const Preview.enforce({required this.title});` fixes the issue. 

Strangely, please note that making an error-free save in any other `.dart` file that does not has this scenario within it makes hot restart / hot reload happen normally.

## Version info

Flutter Plugin: 72.0.2
Dart Plugin: 221.6096

/Users/guillaumevara/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 3.7.1, on macOS 13.1 22C65 darwin-arm64, locale fr-FR)
    • Flutter version 3.7.1 on channel stable at /Users/guillaumevara/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (il y a 2 jours), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/guillaumevara/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_SDK_ROOT = /Users/guillaumevara/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Zulu11.58+23-CA (build 11.0.16.1+1-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by stevemessick** [comment] 2023-02-03 17:01
I can't reproduce this. If I run your code as-is I get the error below, but hot reload seems to work anyway. If I fix the problem by wrapping the `Scaffold` in a `MaterialApp` (running on Pixel 4) then everything works as expected. My SDK, IDE, and plugin versions are all the same as yours. To make sure the hot reload had something to do, I changed the contents of the string "default". Can you give more precise repro steps? Also, does this happen when running from the command line? If so, it is a [framework issue](https://github.com/flutter/flutter/issues).

```dart
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Scaffold(dirty, state: ScaffoldState#6365f(tickers: tracking 2 tickers)):
No MediaQuery widget ancestor found.
Scaffold widgets require a MediaQuery widget ancestor.
The specific widget that could not find a MediaQuery ancestor was:
  Scaffold
The ownership chain for the affected widget is: "Scaffold ← [root]"
No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
This can happen because you have not added a WidgetsApp, CupertinoApp, or MaterialApp widget (those widgets introduce a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.

The relevant error-causing widget was:
  Scaffold Scaffold:file:///Users/messick/tmp/tmp/lib/main.dart:5:11

When the exception was thrown, this was the stack:
#0      debugCheckHasMediaQuery.<anonymous closure> (package:flutter/src/widgets/debug.dart:297:7)
#1      debugCheckHasMediaQuery (package:flutter/src/widgets/debug.dart:312:4)
#2      ScaffoldState.build (package:flutter/src/material/scaffold.dart:2762:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5080:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:863:21)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#12     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:942:7)
#16     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
(elided 3 frames from class _Timer and dart:async-patch)

═══════════════════════════════════════════════════════════════════════════════════════════════════
Performing hot reload...
Reloaded 1 of 640 libraries in 317ms (compile: 57 ms, reload: 142 ms,
reassemble: 77 ms).
```

**Comment by Amphaal** [comment] 2023-02-03 17:21
My bad, I forgot that `MaterialApp` was missing in my example and did not update my ticket once I identified the `No MediaQuery widget ancestor found.` error, which does not prevent auto-reloading indeed.

//
//
//

So, now with my fixed example, with detailed actions to reproduce:

1. Run script below, **preferably on web flutter (Google Chrome)**. It should not produce any Dart Analysis issues in IDE.

```
import 'package:flutter/material.dart';

void main() async {
  runApp(
    const MaterialApp(
      home: Scaffold(
        body: Preview.enforce(title: 'test'),
      ),
    ),
  );
}

class Preview extends StatelessWidget {
  const Preview({String? title}) : title = title ?? 'default';
  const Preview.enforce({required String this.title});

  final String? title;

  @override
  Widget build(BuildContext context) {
    return Text(title!);
  }
}
```
2. Then, do something which will be significant enough on the code above (adding a space, changing `default` default title to something else...)
3. Save file (Command+S)

>>

<img width="1012" alt="Capture d’écran 2023-02-03 à 18 17 59" src="https://user-images.githubusercontent.com/13903151/216666187-c9745c99-c161-4db9-8efa-8faa5dbd0afa.png">

... hot reload / hot restart will not happen.

**FIX** : Turn `const Preview.enforce({required String this.title});` into `const Preview.enforce({required this.title});` re-enable hot reload / hot restart on save.

**Comment by Amphaal** [comment] 2023-02-03 17:27
> I can't reproduce this. If I run your code as-is I get the error below, but hot reload seems to work anyway. If I fix the problem by wrapping the `Scaffold` in a `MaterialApp` (running on Pixel 4) then everything works as expected. My SDK, IDE, and plugin versions are all the same as yours. To make sure the hot reload had something to do, I changed the contents of the string "default". Can you give more precise repro steps? Also, does this happen when running from the command line? If so, it is a [framework issue](https://github.com/flutter/flutter/issues).
> 
> ```dart
> ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY╞═══════════════════════════════════════════════════════════
> The following assertion was thrown building Scaffold(dirty, state: ScaffoldState#6365f(tickers: tracking 2 tickers)):
> No MediaQuery widget ancestor found.
> Scaffold widgets require a MediaQuery widget ancestor.
> The specific widget that could not find a MediaQuery ancestor was:
>   Scaffold
> The ownership chain for the affected widget is: "Scaffold ← [root]"
> No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
> This can happen because you have not added a WidgetsApp, CupertinoApp, or MaterialApp widget (those widgets introduce a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
> 
> The relevant error-causing widget was:
>   Scaffold Scaffold:file:///Users/messick/tmp/tmp/lib/main.dart:5:11
> 
> When the exception was thrown, this was the stack:
> #0      debugCheckHasMediaQuery.<anonymous closure> (package:flutter/src/widgets/debug.dart:297:7)
> #1      debugCheckHasMediaQuery (package:flutter/src/widgets/debug.dart:312:4)
> #2      ScaffoldState.build (package:flutter/src/material/scaffold.dart:2762:12)
> #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5080:27)
> #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968:15)
> #5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
> #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
> #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
> #8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:863:21)
> #9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
> #10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
> #11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
> #12     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:942:7)
> #16     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
> (elided 3 frames from class _Timer and dart:async-patch)
> 
> ═══════════════════════════════════════════════════════════════════════════════════════════════════
> Performing hot reload...
> Reloaded 1 of 640 libraries in 317ms (compile: 57 ms, reload: 142 ms,
> reassemble: 77 ms).
> ```

Running from command line with `flutter run` and triggering hot reload / hot restart with a keystroke on R on the terminal always works as expected, w/ or wo/ `String` specified... Which IMO tends to indicate an issue relative to the Flutter / Dart plugin code parser.

**Comment by stevemessick** [comment] 2023-02-03 18:11
Thanks. I know what the problem is. The Dart plugin has its own parser, and the Flutter plugin uses it to check for errors. It needs to be updated to accept the null-safe syntax. I'll create a YouTrack issue for it, then close this one.

**Comment by stevemessick** [comment] 2023-02-03 18:29
Tracked as https://youtrack.jetbrains.com/issue/WEB-59361/Dart-parser-does-not-recognize-null-safe-syntax

Thanks for the detailed repro steps!

**Closed by stevemessick** 2023-02-03 18:29 UTC

**Comment by Amphaal** [comment] 2023-02-03 21:16
> Tracked as https://youtrack.jetbrains.com/issue/WEB-59361/Dart-parser-does-not-recognize-null-safe-syntax
> 
> Thanks for the detailed repro steps!

Many thanks for your reactivity ! 💯
