### ISSUE TITLE
ide crashes when switching from flutter project to plain dart project

### ISSUE THREAD

**Issue by transmeta01** [flutter/flutter-intellij#2087] opened 2018-04-14 05:17 UTC
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

ide switching from flutter project to plain dart project

## Version info

IntelliJ IDEA `2017.3.4` • Flutter plugin `io.flutter 23.2.2` • Dart plugin `173.4548.30`

No Flutter sdk configured.

## Exception

null

```
java.lang.NullPointerException
	at com.intellij.ui.content.impl.ContentManagerImpl.doAddContent(ContentManagerImpl.java:173)
	at com.intellij.ui.content.impl.ContentManagerImpl.addContent(ContentManagerImpl.java:152)
	at io.flutter.view.FlutterView.displayEmptyContent(FlutterView.java:304)
	at io.flutter.view.FlutterView.access$300(FlutterView.java:64)
	at io.flutter.view.FlutterView$2.lambda$connectionClosed$0(FlutterView.java:272)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by pq** [comment] 2018-04-16 18:27
Not able to reproduce against latest (which has changed a bit since 23.2.2) so closing optimistically.  We can re-open if it recurs.

Thanks again!

**Closed by pq** 2018-04-16 18:27 UTC

**Comment by transmeta01** [comment] 2018-04-16 18:46
to reproduce: 1-open a flutter project, then from file menu -> open a vanilla dart project and select "this window". 
I am running on MacOS

**Comment by pq** [comment] 2018-04-16 18:56
That's perfect.  I was trying exactly that and it works on latest (on OS X) so should be good in the next plugin release.

Thanks for following up!
