### ISSUE TITLE
flutter application compile error

### ISSUE THREAD

**Issue by xieyuhai** [flutter/flutter-intellij#2931] opened 2018-12-08 06:24 UTC
```
Error running Gradle:
ProcessException: Process "/Users/xieyuhai/Downloads/AndroidFlutter/flutter_app/android/gradlew" exited abnormally:
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.1.2.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.1.2.
         > Could not get resource 'https://maven.aliyun.com/repository/google/com/android/tools/build/gradle/3.1.2/gradle-3.1.2.pom'.
            > Could not HEAD 'https://maven.aliyun.com/repository/google/com/android/tools/build/gradle/3.1.2/gradle-3.1.2.pom'.
               > Connect to 127.0.0.1:1086 [/127.0.0.1] failed: Connection refused (Connection refused)
      > Could not resolve com.android.tools.build:gradle:3.1.2.
         > Could not get resource 'https://maven.aliyun.com/repository/jcenter/com/android/tools/build/gradle/3.1.2/gradle-3.1.2.pom'.
            > Could not HEAD 'https://maven.aliyun.com/repository/jcenter/com/android/tools/build/gradle/3.1.2/gradle-3.1.2.pom'.
               > Connect to 127.0.0.1:1086 [/127.0.0.1] failed: Connection refused (Connection refused)
      > Could not resolve com.android.tools.build:gradle:3.1.2.
         > Could not get resource 'http://maven.aliyun.com/nexus/content/groups/public/com/android/tools/build/gradle/3.1.2/gradle-3.1.2.pom'.
            > Could not HEAD 'http://maven.aliyun.com/nexus/content/groups/public/com/android/tools/build/gradle/3.1.2/gradle-3.1.2.pom'.
               > Connect to 127.0.0.1:1086 [/127.0.0.1] failed: Connection refused (Connection refused)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by stevemessick** [comment] 2018-12-08 22:17
> Connect to 127.0.0.1:1086 [/127.0.0.1] failed: Connection refused (Connection refused)

Looks like you have a network configuration problem.

**Comment by xieyuhai** [comment] 2018-12-10 14:48
Using the "hello world" of example in flutter, adding agents or changing the gradle configuration of the project root directory will still report this error, for example
google ()
jcenter ()   or
maven {url'https://maven.aliyun.com/repository/google'}
maven {url'https://maven.aliyun.com/repository/jcenter'}
maven {url'http://maven.aliyun.com/nexus/content/groups/public'}

trying several ways

**Comment by zoechi** [comment] 2018-12-10 14:54
Duplicate of flutter/flutter#22470, #19719

**Comment by cqpaul** [comment] 2019-09-03 16:45
Anybody know how to solve this problem, the same with me...Please help.

**Comment by stevemessick** [comment] 2019-09-03 16:50
As @zoechi said, this is a dup of a flutter issue. See flutter/flutter#22470. This is not something the plugin can help with.

**Closed by stevemessick** 2019-09-03 16:50 UTC
