### ISSUE TITLE
Android studio 4 frozen and thread dumps.

### ISSUE THREAD

**Issue by ashutosh1211** [flutter/flutter-intellij#4606] opened 2020-06-06 18:21 UTC
I Have attached the thread dumps.

[threadDumps-freeze-20200606-234657-AI-193.6911.18.40.6514223.zip](https://github.com/flutter/flutter-intellij/files/4740774/threadDumps-freeze-20200606-234657-AI-193.6911.18.40.6514223.zip)

## Version info
Flutter version:
Flutter 1.19.0-2.0.pre • channel master • https://github.com/flutter/flutter.git
Framework • revision 478d4c9c1a (3 weeks ago) • 2020-05-19 20:22:01 -0700
Engine • revision 2d4e83921d
Tools • Dart 2.9.0 (build 2.9.0-9.0.dev 40f7a11d89)

Android studio version 4.0

```
[√] Flutter (Channel master, 1.19.0-2.0.pre, on Microsoft Windows [Version 10.0.18362.778], locale en-IN)
    • Flutter version 1.19.0-2.0.pre at C:\Projects\flutter\flutter_dev
    • Framework revision 478d4c9c1a (3 weeks ago), 2020-05-19 20:22:01 -0700
    • Engine revision 2d4e83921d
    • Dart version 2.9.0 (build 2.9.0-9.0.dev 40f7a11d89)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\ashut\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\ashut\AppData\Local\Android\sdk
    • Java binary at: C:\android_studio\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.4.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.4.29709.97

[√] Android Studio (version 4.0)
    • Android Studio at C:\android_studio\android-studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\ashut\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[√] Connected device (3 available)
    • Windows    • Windows    • windows-x64    • Microsoft Windows [Version 10.0.18362.778]
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97

• No issues found!

```

**Comment by ashutosh1211** [comment] 2020-06-06 18:28
Seems like flutter debug console writer has some issue.

Logs from idea.log file.

```
2020-06-06 23:43:41,358 [ 749206]   WARN - .diagnostic.PerformanceWatcher - UI freezed for 39367ms, details saved to C:\Users\ashut\.AndroidStudio4.0\system\log\threadDumps-freeze-20200606-234301-AI-193.6911.18.40.6514223-Unsafe.park-39sec 
2020-06-06 23:44:20,798 [ 788646]   WARN - cution.filters.CompositeFilter - FlutterConsoleFilter.applyFilter() took 39465 ms on '''flutter: {"TotalCount":1,"Status":"success","Result":[{"SysUpdated":"06/06/2020 23:26:05","Id":1591466135852,"SysCreated":"06/06/2020 23:26:05","Price":400.0,"TotalDays":4,"Schedule":"[{\"Id\":1591356205872,\"SysCreated\":\"05/06/2020 16:55:31\",\"SysUpdated\":\"05/06/2020 16:55:31\",\"Name\":\"Niruha\\r Basti\",\"Duration\":36.0,\"NoDays\":6.0,\"Price\":600.0,\"DefTherapistName\":\"abc\",\"DefRoomNo\":\"5\",\"Medicine\":\"[{\\\"Id\\\":1591356268768,\\\"MedicineId\\\":1591355466898,\\\"QtyPerServing\\\":412.0,\\\"Unit\\\":1,\\\"Composition\\\":{\\\"Id\\\":1591355466898,\\\"SysCreated\\\":\\\"05/06/2020 16:41:59\\\",\\\"SysUpdated\\\":\\\"05/06/2020 16:41:59\\\",\\\"Name\\\":\\\"Makshik\\\",\\\"Qty\\\":412.0,\\\"QtyUnit\\\":1,\\\"PrepFormula\\\":\\\"[{\\\\\\\"Id\\\\\\\":1591355475794,\\\\\\\"MedicineId\\\\\\\":1590320951003,\\\\\\\"QtyPerServing\\\\\\\":101000.0,\\\\\\\"Unit\\\\\\\":1,\\\\\\\"IsComposition\\\\\\\":false},{\\\\\\\"Id\\\\\\\":1591355488965,\\\\\\\"MedicineId\\\\\\\":1591355478401,\\\\\\\"QtyPerServing\\\\\\\":201.0,\\\\\\\"Unit\\\\\\\":1,\\\\\\\"Composition\\\\\\\":{\\\\\\\"Id\\\\\\\":1591355478401,\\\\\\\"Name\\\\\\\":\\\\\\\"kalka\\\\\\\",\\\\\\\"Qty\\\\\\\":201.0,\\\\\\\"QtyUnit\\\\\\\":1,\\\\\\\"PrepFormula\\\\\\\":\\\\\\\"[{\\\\\\\\\\\\\\\"Id\\\\\\\\\\\\\\\":1591355485415,\\\\\\\\\\\\\\\"MedicineId\\\\\\\\\\\\\\\":1590320951003,\\\\\\\\\\\\\\\"QtyPerServing\\\\\\\\\\\\\\\":101000.0,\\\\\\\\\\\\\\\"Unit\\\\\\\\\\\\\\\":1,\\\\\\\\\\\\\\\"IsComposition\\\\\\\\\\\\\\\":false},{\\\\\\\\\\\\\\\"Id\\\\\\\\\\\\\\\":1591355487742,\\\\\\\\\\\\\\\"MedicineId\\\\\\\\\\\\\\\":1590321461023,\\\\\\\\\\\\\\\"QtyPerServing\\\\\\\\\\\\\\\":100.0,\\\\\\\\\\\\\\\"Unit\\\\\\\\\\\\\\\":4,\\\\\\\\\\\\\\\"IsComposition\\\\\\\\\\\\\\\":false}]\\\\\\\"},\\\\\\\"IsComposition\\\\\\\":true},{\\\\\\\"Id\\\\\\\":1591355516460,\\\\\\\"MedicineId\\\\\\\":1591355506890,\\\\\\\"QtyPerServing\\\\\\\":110.0,\\\\\\\"Unit\\\\\\\":4,\\\\\\\"Composition\\\\\\\":{\\\\\\\"Id\\\\\\\":1591355506890,\\\\\\\"Name\\\\\\\":\\\\\\\"kwatha\\\\\\\",\\\\\\\"Qty\\\\\\\":110.0,\\\\\\\"QtyUnit\\\\\\\":4,\\\\\\\"PrepFormula\\\\\\\":\\\\\\\"[{\\\\\\\\\\\\\\\"Id\\\\\\\\\\\\\\\":1591355511274,\\\\\\\\\\\\\\\"MedicineId\\\\\\\\\\\\\\\":1590321461023,\\\\\\\\\\\\\\\"QtyPerServing\\\\\\\\\\\\\\\":100.0,\\\\\\\\\\\\\\\"Unit\\\\\\\\\\\\\\\":4,\\\\\\\\\\\\\\\"IsComposition\\\\\\\\\\\\\\\":false},{\\\\\\\\\\\\\\\"Id\\\\\\\\\\\\\\\":1591355514090,\\\\\\\\\\\\\\\"MedicineId\\\\\\\\\\\\\\\":1590321519063,\\\\\\\\\\\\\\\"QtyPerServing\\\\\\\\\\\\\\\":10.0,\\\\\\\\\\\\\\\"Unit\\\\\\\\\\\\\\\":5,\\\\\\\\\\\\\\\"IsComposition\\\\\\\\\\\\\\\":false}]\\\\\\\"},\\\\\\\"IsComposition\\\\\\\":true}]\\\"},\\\"IsComposition\\\":true}]\",\"DefObservations\":\"some default observations here.\",\"DefSansarjanKram\":\"some sansarjan karma here\",\"DefInternalNotes\":\"some default internal nots here\",\"DefPatientInstructions\":\"some patient instr here\",\"DefTherapistInstructions\":\"Some therapist instr here\"},{\"Id\":1591359099134,\"SysCreated\":\"05/06/2020 16:55:31\",\"SysUpdated\":\"05/06/2020 17:43:35\",\"Name\":\"Sneha\\r Basti\",\"Duration\":36.0,\"NoDays\":6.0,\"Price\":600.0,\"DefTherapistName\":\"abc\",\"DefRoomNo\":\"5\",\"Medicine\":\"[{\\\"Id\\\":1591356268768,\\\"MedicineId\\\":1591355466898,\\\"QtyPerServing\\\":412.0,\\\"Unit\\\":1,\\\"Composition\\\":{\\\"Id\\\":1591355466898,\\\"SysCreated\\\":\\\"05/06/2020 16:41:59\\\",\\\"SysUpdated\\\":\\\"05/06/2020 16:41:59\\\",\\\"Name\\\":\\\"Makshik\\\",\\\"Qty\\\":412.0,\\\"QtyUnit\\\":1,\\\"PrepFormula\\\":\\\"[{\\\\\\\"Id\\\\\\\":1591355475794,\\\\\\\"MedicineId\\\\\\\":1590320951003,\\\\\\\"QtyPerServing\\\\\\\":101000.0,\\\\\\\"Unit\\\\\\\":1,\\\\\\\"IsComposition\\\\\\\":false},{\\\\\\\"Id\\\\\\\":1591355488965,\\\\\\\"MedicineId\\\\\\\":1591355478401,\\\\\\\"QtyPerServing\\\\\\\":201.0,\\\\\\\"Unit\\\\\\\":1,\\\\\\\"Composition\\\\\\\":{\\\\\\\"Id\\\\\\\":1591355478401,\\\\\\\"Name\\\\\\\":\\\\\\\"kalka\\\\\\\",\\\\\\\"Qty\\\\\\\":201.0,\\\\\\\"QtyUnit\\\\\\\":1,\\\\\\\"PrepFormula\\\\\\\":\\\\\\\"[{\\\\\\\\\\\\\\\"Id\\\\\\\\\\\\\\\":1591355485415,\\\\\\\\\\\\\\\"MedicineId\\\\\\\\\\\\\\\":1590320951003,\\\\\\\\\\\\\\\"QtyPerServing\\\\\\\\\\\\\\\":101000.0,\\\\\\\\\\\\\\\"Unit\\\\\\\\\\\\\\\":1,\\\\\\\\\\\\\\\"IsComposition\\\\\\\\\\\\\\\":false},{\\\\\\\\\\\\\\\"Id\\\\\\\\\\\\\\\":1591355487742,\\\\\\\\\\\\\\\"MedicineId\\\\\\\\\\\\\\\":1590321461023,\\\\\\\\\\\\\\\"QtyPerServing\\\\\\\\\\\\\\\":100.0,\\\\\\\\\\\\\\\"Unit\\\\\\\\\\\\\\\":4,\\\\\\\\\\\\\\\"IsComposition\\\\\\\\\\\\\\\":false}]\\\\\\\"},\\\\\\\"IsComposition\\\\\\\":true},{\\\\\\\"Id\\\\\\\":1591355516460,\\\\\\\"MedicineId\\\\\\\":1591355506890,\\\\\\\"QtyPerServing\\\\\\\":110.0,\\\\\\\"Unit\\\\\\\":4,\\\\\\\"Composition\\\\\\\":{\\\\\\\"Id\\\\\\\":1591355506890,\\\\\\\"Name\\\\\\\":\\\\\\\"kwatha\\\\\\\",\\\\\\\"Qty\\\\\\\":110.0,\\\\\\\"QtyUnit\\\\\\\":4,\\\\\\\"PrepFormula\\\\\\\":\\\\\\\"[{\\\\\\\\\\\\\\\"Id\\\\\\\\\\\\\\\":1591355511274,\\\\\\\\\\\\\\\"MedicineId\\\\\\\\\\\\\\\":1590321461023,\\\\\\\\\\\\\\\"QtyPerServing\\\\\\\\\\\\\\\":100.0,\\\\\\\\\\\\\\\"Unit\\\\\\\\\\\\\\\":4,\\\\\\\\\\\\\\\"IsComposition\\\\\\\\\\\\\\\":false},{\\\\\\\\\\\\\\\"Id\\\\\\\\\\\\\\\":1591355514090,\\\\\\\\\\\\\\\"MedicineId\\\\\\\\\\\\\\\":1590321519063,\\\\\\\\\\\\\\\"QtyPerServing\\\\\\\\\\\\\\\":10.0,\\\\\\\\\\\\\\\"Unit\\\\\\\\\\\\\\\":5,\\\\\\\\\\\\\\\"IsComposition\\\\\\\\\\\\\\\":false}]\\\\\\\"},\\\\\\\"IsComposition\\\\\\\":true}]\\\"},\\\"IsComposition\\\":true}]\",\"DefObservations\":\"some default observations here.\",\"DefSansarjanKram\":\"some sansarjan karma here\",\"DefInternalNotes\":\"some default internal nots here\",\"DefPatientInstructions\":\"some patient instr here\",\"DefTherapistInstructions\":\"Some therapist instr here\",\"ExtractionQty\":12.0,\"ExtractionQtyUnit\":4,\"ExtractionTime\":15.0},{\"Id\":1591356205872,\"SysCreated\":\"05/06/2020 16:55:31\",\"SysUpdated\":\"05/06/2020 16:55:31\",\"Name\":\"Niruha\\r Basti\",\"Duration\":36.0,\"NoDays\":6.0,\"Price\":600.0,\"DefTherapistName\":\"abc\",\"DefRoomNo\":\"5\",\"Medicine\":\"[{\\\"Id\\\":1591356268768,\\\"MedicineId\\\":1591355466898,\\\"QtyPerServing\\\":412.0,\\\"Unit\\\":1,\\\"Composition\\\":{\\\"Id\\\":1591355466898,\\\"SysCreated\\\":\\\"05/06/2020 16:41:59\\\",\\\"SysUpdated\\\":\\\"05/06/2020 16:41:59\\\",\\\"Name\\\":\\\"Makshik\\\",\\\"Qty\\\":412.0,\\\"QtyUnit\\\":1,\\\"PrepFormula\\\":\\\"[{\\\\\\\"Id\\\\\\\":1591355475794,\\\\\\\"MedicineId\\\\\\\":1590320951003,\\\\\\\"QtyPerServing\\\\\\\":101000.0,\\\\\\\"Unit\\\\\\\":1,\\\\\\\"IsComposition\\\\\\\":false},{\\\\\\\"Id\\\\\\\":1591355488965,\\\\\\\"MedicineId\\\\\\\":1591355478401,\\\\\\\"QtyPerServing\\\\\\\":201.0,\\\\\\\"Unit\\\\\\\":1,\\\\\\\"Composition\\\\\\\":{\\\\\\\"Id\\\\\\\":1591355478401,\\\\\\\"Name\\\\\\\":\\\\\\\"kalka\\\\\\\",\\\\\\\"Qty\\\\\\\":201.0,\\\\\\\"QtyUnit\\\\\\\":1,\\\\\\\"PrepFormula\\\\\\\":\\\\\\\"[{\\\\\\\\\\\\\\\"Id\\\\\\\\\\\\\\\":1591355485415,\\\\\\\\\\\\\\\"MedicineId\\\\\\\\\\\\\\\":1590320951003,\\\\\\\\\\\\\\\"QtyPerServing\\\\\\\\\\\\\\\":101000.0,\\\\\\\\\\\\\\\"Unit\\\\\\\\\\\\\\\":1,\\\\\\\\\\\\\\\"IsComposition\\\\\\\\\\\\\\\":false},{\\\\\\\\\\\\\\\"Id\\\\\\\\\\\\\\\":1591355487742,\\\\\\\\\\\\\\\"MedicineId\\\\\\\\\\\\\\\":1590321461023,\\\\\\\\\\\\\\\"QtyPerServing\\\\\\\\\\\\\\\":100.0,\\\\\\\\\\\\\\\"Unit\\\\\\\\\\\\\\\":4,\\\\\\\\\\\\\\\"IsComposition\\\\\\\\\\\\\\\":false}]\\\\\\\"},\\\\\\\"IsComposition\\\\\\\":true},{\\\\\\\"Id\\\\\\\":1591355516460,\\\\\\\"MedicineId\\\\\\\":1591355506890,\\\\\\\"QtyPerServing\\\\\\\":110.0,\\\\\\\"Unit\\\\\\\":4,\\\\\\\"Composition\\\\\\\":{\\\\\\\"Id\\\\\\\":1591355506890,\\\\\\\"Name\\\\\\\":\\\\\\\"kwatha\\\\\\\",\\\\\\\"Qty\\\\\\\":110.0,\\\\\\\"QtyUnit\\\\\\\":4,\\\\\\\"PrepFormula\\\\\\\":\\\\\\\"[{\\\\\\\\\\\\\\\"Id\\\\\\\\\\\\\\\":1591355511274,\\\\\\\\\\\\\\\"MedicineId\\\\\\\\\\\\\\\":1590321461023,\\\\\\\\\\\\\\\"QtyPerServing\\\\\\\\\\\\\\\":100.0,\\\\\\\\\\\\\\\"Unit\\\\\\\\\\\\\\\":4,\\\\\\\\\\\\\\\"IsComposition\\\\\\\\\\\\\\\":false},{\\\\\\\\\\\\\\\"Id\\\\\\\\\\\\\\\":1591355514090,\\\\\\\\\\\\\\\"MedicineId\\\\\\\\\\\\\\\":1590321519063,\\\\\\\\\\\\\\\"QtyPerServing\\\\\\\\\\\\\\\":10.0,\\\\\\\\\\\\\\\"Unit\\\\\\\\\\\\\\\":5,\\\\\\\\\\\\\\\"IsComposition\\\\\\\\\\\\\\\":false}]\\\\\\\"},\\\\\\\"IsComposition\\\\\\\":true}]\\\"},\\\"IsComposition\\\":true}]\",\"DefObservations\":\"some default observations here.\",\"DefSansarjanKram\":\"some sansarjan karma here\",\"DefInternalNotes\":\"some default internal nots here\",\"DefPatientInstructions\":\"some patient instr here\",\"DefTherapistInstructions\":\"Some therapist instr here\"},{\"Id\":1591359099134,\"SysCreated\":\"05/06/2020 16:55:31\",\"SysUpdated\":\"05/06/2020 17:43:35\",\"Name\":\"Sneha\\r Basti\",\"Duration\":36.0,\"NoDays\":6.0,\"Price\":600.0,\"DefTherapistName\":\"abc\",\"DefRoomNo\":\"5\",\"Medicine\":\"[{\\\"Id\\\":1591356268768,\\\"MedicineId\\\":1591355466898,\\\"QtyPerServing\\\":412.0,\\\"Unit\\\":1,\\\"Composition\\\":{\\\"Id\\\":1591355466898,\\\"SysCreated\\\":\\\"05/06/2020 16:41:59\\\",\\\"SysUpdated\\\":\\\"05/06/2020 16:41:59\\\",\\\"Name\\\":\\\"Makshik\\\",\\\"Qty\\\":412.0,\\\"QtyUnit\\\":1,\\\"PrepFormula\\\":\\\"[{\\\\\\\"Id\\\\\\\":1591355475794,\\\\\\\"MedicineId\\\\\\\":1590320951003,\\\\\\\"QtyPerServing\\\\\\\":101000.0,\\\\\\\"Unit\\\\\\\":1,\\\\\\\"IsComposition\\\\\\\":false},{\\\\\\\"Id\\\\\\\":1591355488965,\\\\\\\"MedicineId\\\\\\\":1591355478401,\\\\\\\"QtyPerServing\\\\\\\":201.0,\\\\\\\"Unit\\\\\\\":1,\\\\\\\"Composition\\\\\\\":{\\\\\\\"Id\\\\\\\":1591355478401,\\\\\\\"Name\\\\\\\":\\\\\\\"kalka\\\\\\\",\\\\\\\"Qty\\\\\\\":201.0,\\\\\\\"QtyUnit\\\\\\\":1,\\\\\\\"PrepFormula\\\\\\\":\\\\\\\"[{\\\\\\\\\\\\\\\"Id\\\\\\\\\\\\\\\":1591355485415,\\\\\\\\\\\\\\\"MedicineId\\\\\\\\\\\\\\\":1590320951003,\\\\\\\\\\\\\\\"QtyPerServing\\\\\\\\\\\\\\\":101000.0,\\\\\\\\\\\\\\\"Unit\\\\\\\\\\\\\\\":1,\\\\\\\\\\\\\\\"IsComposition\\\\\\\\\\\\\\\":false},{\\\\\\\\\\\\\\\"Id\\\\\\\\\\\\\\\":1591355487742,\\\\\\\\\\\\\\\"MedicineId\\\\\\\\\\\\\\\":1590321461023,\\\\\\\\\\\\\\\"QtyPerServing\\\\\\\\\\\\\\\":100.0,\\\\\\\\\\\\\\\"Unit\\\\\\\\\\\\\\\":4,\\\\\\\\\\\\\\\"IsComposition\\\\\\\\\\\\\\\":false}]\\\\\\\"},\\\\\\\"IsComposition\\\\\\\":true},{\\\\\\\"Id\\\\\\\":1591355516460,\\\\\\\"MedicineId\\\\\\\":1591355506890,\\\\\\\"QtyPerServing\\\\\\\":110.0,\\\\\\\"Unit\\\\\\\":4,\\\\\\\"Composition\\\\\\\":{\\\\\\\"Id\\\\\\\":1591355506890,\\\\\\\"Name\\\\\\\":\\\\\\\"kwatha\\\\\\\",\\\\\\\"Qty\\\\\\\":110.0,\\\\\\\"QtyUnit\\\\\\\":4,\\\\\\\"PrepFormula\\\\\\\":\\\\\\\"[{\\\\\\\\\\\\\\\"Id\\\\\\\\\\\\\\\":1591355511274,\\\\\\\\\\\\\\\"MedicineId\\\\\\\\\\\\\\\":1590321461023,\\\\\\\\\\\\\\\"QtyPerServing\\\\\\\\\\\\\\\":100.0,\\\\\\\\\\\\\\\"Unit\\\\\\\\\\\\\\\":4,\\\\\\\\\\\\\\\"IsComposition\\\\\\\\\\\\\\\":false},{\\\\\\\\\\\\\\\"Id\\\\\\\\\\\\\\\":1591355514090,\\\\\\\\\\\\\\\"MedicineId\\\\\\\\\\\\\\\":1590321519063,\\\\\\\\\\\\\\\"QtyPerServing\\\\\\\\\\\\\\\":10.0,\\\\\\\\\\\\\\\"Unit\\\\\\\\\\\\\\\":5,\\\\\\\\\\\\\\\"IsComposition\\\\\\\\\\\\\\\":false}]\\\\\\\"},\\\\\\\"IsComposition\\\\\\\":true}]\\\"},\\\"IsComposition\\\":true}]\",\"DefObservations\":\"some default observations here.\",\"DefSansarjanKram\":\"some sansarjan karma here\",\"DefInternalNotes\":\"some default internal nots here\",\"DefPatientInstructions\":\"some patient instr here\",\"DefTherapistInstructions\":\"Some therapist instr here\",\"ExtractionQty\":12.0,\"ExtractionQtyUnit\":4,\"ExtractionTime\":15.0}]","Name":"4 days basti","Description":"contains 4 days basti"}]}
'''
```

**Comment by HugoHeneault** [comment] 2020-06-08 06:05
This might be a duplicate of #4599 :)

**Comment by devoncarew** [comment] 2020-06-08 16:27
Thanks for the triage; closing as a dupe of https://github.com/flutter/flutter-intellij/issues/4599.

We've landed what we think is a fix - this will next be available in the dev channel, w/ availability in the stable channel after that.

**Closed by devoncarew** 2020-06-08 16:27 UTC
