### ISSUE TITLE
Built-in Inspect code throws a lot of warning and errors in the example project

### ISSUE THREAD

**Issue by sashkent3** [flutter/flutter-intellij#4776] opened 2020-08-25 11:02 UTC
As it doesn't affect real application it still seems strange and annoying to me when debugging the non-dart part of the app. Maybe I just use the wrong tool for the job though.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Open it in Intellij IDEA, run `Analyze > Inspect code... > OK`
3. See a lot of warning and errors:
![idea_flutter_bug](https://user-images.githubusercontent.com/33320473/91166382-f5d72c80-e6da-11ea-8b18-285dc2c65d7b.png)

## Version info

```
/opt/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 1.20.2, on Linux, locale ru_RU.UTF-8)
    • Flutter version 1.20.2 at /opt/flutter
    • Framework revision bbfbf1770c (12 дней назад), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /opt/android-sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • SM N960U (mobile) • 28c2c0e2003f7ece • android-arm64 • Android 10 (API 29)

• No issues found!
Process finished with exit code 0
```

**Comment by AAllport** [comment] 2020-08-25 15:08
Duplicate of #2243?

**Comment by stevemessick** [comment] 2020-08-28 17:21
Those errors go away if you open the Android module in Android Studio.
`Tools > Flutter > Open for editing in Android Studio`

I'm not sure anything on the `Analyze` menu is applicable to Dart or Flutter. @alexander-doroshko have you done anything for the `Analyze` menu? I remember we got everything on the `Code` menu implemented but don't recall a focus on the `Analyze` menu.

There may be another way to solve this. If the top-level Flutter project were a Gradle project that included the Android module the issues would probably go away. We can't add the Gradle files for everyone, though, because a lot of people don't want them. If you decide to try that please let us know how it goes. Note, you may need to enable the Experimental option `Enable code completion etc for Java / Kotlin`.

**Comment by AAllport** [comment] 2020-08-28 17:25
@stevemessick, `Enable code completion [...]` is this a flutter specific option?

**Comment by stevemessick** [comment] 2020-08-28 18:10
@AAllport Oops, sorry, it is only available in the Android Studio version of the Flutter plugin. I forgot you are using IntelliJ.

**Comment by alexander-doroshko** [comment] 2020-08-28 18:20
>  @alexander-doroshko have you done anything for the Analyze menu?

`Analyze > Inspect code...` is a general IDE feature. It runs all code annotators and all enabled inspections. It accumulates all problems you would see in the editor if you opened all project files.

**Closed** 2020-09-04 17:59 UTC
Labels: waiting for customer response

**Comment by workerbee22** [comment] 2021-10-11 23:51
@AAllport I've opened a matching issue. Please upvote by hitting the Emoji on the first post here if this still annoys you like it does me: https://github.com/flutter/flutter/issues/91596
