### ISSUE TITLE
Running unit tests from the left gutter breaks debugging unit test

### ISSUE THREAD

**Issue by branflake2267** [flutter/flutter-intellij#1821] opened 2018-02-24 17:53 UTC
## Steps to Reproduce

Running the tests from the left gutter breaks. The only way to run them again is restarting IntelliJ. 
1. Set a break point in the test case
2. Run a unit test from the left gutter run or debug button. (don't stop debugging process)
3. Then click on debug button in the top menu, right of the device selection. (try to start process again)

What I think is happening, when trying to start the debugging process again before it was completed while paused on a break point creates an inconsistent state. I've noticed an exception thrown in IDE log as well but I can't replicate it again. What I'm finding my problem is, I forget to resume past the break point so the unit test finishes. And then I try to start it over while it's paused, the second process doesn't restart. Once I terminate the process, I can no longer launch  another debugging instance from the left gutter button.  

After a third launch of debugging I can no longer run the individual unit test from here.
![screen shot 2018-02-24 at 9 38 40 am](https://user-images.githubusercontent.com/1326504/36633331-8d62414c-1948-11e8-8340-1777f2798b18.png)

How I start it the second time, and it breaks IDE. 
![screen shot 2018-02-24 at 9 56 47 am](https://user-images.githubusercontent.com/1326504/36633372-490babea-1949-11e8-9be0-91dae11c67ea.png)

How I ran it the first time. 
![screen shot 2018-02-24 at 9 45 37 am](https://user-images.githubusercontent.com/1326504/36633330-896affca-1948-11e8-92df-527b50e64ac9.png)

## Version info

```
brandons-mbp:economy branflake2267$ flutter doctor -v
[✓] Flutter (Channel master, v0.1.5-pre.19, on Mac OS X 10.13.3 17D47, locale en-US)
    • Flutter version 0.1.5-pre.19 at /Users/branflake2267/git/flutter
    • Framework revision 37ffb2d730 (3 days ago), 2018-02-21 15:01:46 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at /Users/branflake2267/Library/Android/sdk
    • Android NDK at /Users/branflake2267/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio 3.0.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.3)
    • Flutter plugin version 21.1.3
    • Dart plugin version 173.4301.22

[✓] IntelliJ IDEA Community Edition (version 2017.2.6)
    • Flutter plugin version 21.1.2
    • Dart plugin version 172.4343.25

[✓] VS Code (version 1.20.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.8.2

[✓] Connected devices
    • Nexus 9                   • HT4ATJT00950  • android-arm64 • Android 7.1.1 (API 25)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 8.0.0 (API 26) (emulator)

• No issues found!
```

**Comment by branflake2267** [comment] 2018-02-24 18:14
This may be related. https://github.com/flutter/flutter-intellij/issues/1622

**Comment by devoncarew** [comment] 2018-02-27 00:53
@pq

**Comment by pq** [comment] 2018-02-27 14:02
Thanks for the report!

Which IDEA are you seeing this on? (I see you've got a few installed! 😄)

**Comment by branflake2267** [comment] 2018-02-27 16:53
Oh, good point, I forgot and figured the doctor would be enough. I'm using Android Studio 3.0.1
![screen shot 2018-02-27 at 8 53 05 am](https://user-images.githubusercontent.com/1326504/36742097-aa352f00-1b9b-11e8-9d07-e65e3dc4a1a9.png)
.

**Comment by pq** [comment] 2018-02-27 20:45
Thanks!

**Comment by scheglov** [comment] 2018-04-02 21:51
Just FYI, I was not able to reproduce the problem.
But I can see why https://github.com/flutter/flutter-intellij/issues/1622 happens and will fix it.

**Comment by pq** [comment] 2018-04-16 19:33
I'm unable to reproduce on tip of head either.  Hopefully we should be good with the next release.  Optimistically closing.

**Closed by pq** 2018-04-16 19:33 UTC
Labels: bug, testing
