### ISSUE TITLE
bug when running app in debug mode

### ISSUE THREAD

**Issue by AMDphreak** [flutter/flutter-intellij#7062] opened 2023-11-04 04:10 UTC
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2023.2.4` • Flutter plugin `io.flutter 76.2.4` • Dart plugin `232.10072.19`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.Throwable: Error listening to ToolEvent stream: org.dartlang.vm.service.element.RPCError@6afcb9eb
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at io.flutter.vmService.VmServiceWrapper$2.onError(VmServiceWrapper.java:185)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:633)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:422)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:86)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by AMDphreak** [comment] 2023-11-04 04:15
intellij updated itself and plugins; android sdk updated after the update. the project complained about not being able to find anrdoid sdk 29. there was some button I pressed next to the error banner to change the project to android sdk 33. this got rid of the error banner, but the warning highlighting still shows up in the code text.

**Comment by jwren** [comment] 2023-12-15 19:29
Duplicate of https://github.com/flutter/flutter-intellij/issues/7133

**Closed by jwren** 2023-12-15 19:29 UTC
