### ISSUE TITLE
Colors.* code hint

### ISSUE THREAD

**Issue by mofada** [flutter/flutter-intellij#3202] opened 2019-02-16 08:10 UTC
Every time I use the code prompt Colors.*, it will always be very card, the card is long. Every time I knock on Colors. I get stuck, and then I can show it after a while.

**Comment by stevemessick** [comment] 2019-02-19 21:08
Please append the output of `flutter doctor -v`

This sounds like a performance problem. The first thing we need to do is verify you are using the latest Flutter and IntelliJ releases.

**Comment by mofada** [comment] 2019-02-20 03:38
@stevemessick thinks, Below is my run `flutter doctor -v` , I wonder if it is because the value of the color is too much.

```C:\Users\fada>flutter doctor -v
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.316], locale zh-CN)
    • Flutter version 1.0.0 at D:\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at D:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\Android\android-sdk
    • Java binary at: D:\Android\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at D:\Android\android-studio
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at D:\JetBrains\IntelliJ IDEA
    • Flutter plugin version 31.3.4
    • Dart plugin version 183.4886.3

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.```

**Comment by mofada** [comment] 2019-02-20 04:00
![qxky26sk3b](https://user-images.githubusercontent.com/22286246/53065513-e8018380-3506-11e9-9eec-cea63bd66a8d.gif)
Most of the time is when you use it for the first time, occasionally not the first time.

**Comment by stevemessick** [comment] 2019-02-20 23:40
@mofada Including that animation is great, thanks! There are updates available but I don't think any recent changes would help with this problem.

@scheglov Does locale affect code completion? I notice this is using simplified Chinese. I do observe a slight delay when completing colors but it isn't anything like this (if I understand the animation correctly).

@alexander-doroshko I think this animation is showing the UI becoming non-responsive during completion. Do you have any guesses what could cause that?

**Comment by scheglov** [comment] 2019-02-21 01:36
It looks to me that completion pop-up windows with color names shows up fast. By the time it shows, DAS work is done. The slowness happens in the client, given that these are colors, maybe something is rendered in the even loop.

**Comment by alexander-doroshko** [comment] 2019-02-21 07:57
@mofada Please reproduce the problem once again, then click Help -> Compress Logs and Show in Explorer, and attach the corresponding zip file here. I expect it to contain thread dumps showing the cause of the problem. Thanks!

**Comment by mofada** [comment] 2019-02-21 08:04
@alexander-doroshko Ok, I uploaded it.
[logs-20190221-160210.zip](https://github.com/flutter/flutter-intellij/files/2888226/logs-20190221-160210.zip)

**Comment by alexander-doroshko** [comment] 2019-02-21 08:44
@mofada Thank you!
This looks like https://youtrack.jetbrains.com/issue/IDEA-199409. It's fixed in 2018.3 builds. Can you please check if the problem is gone in any of the following IDEs: IntelliJ IDEA 2018.3.x, Android Studio 3.4 Beta or Android Studio 3.5 Canary?

**Comment by mofada** [comment] 2019-02-22 01:14
@alexander-doroshko  But my Android Studio version is 3.3.1. I'll try to upgrade, thank you

**Comment by alexander-doroshko** [comment] 2019-02-22 07:46
Android Studio 3.3 is based on IntelliJ 2018.2. Upgrading should help.

**Comment by stevemessick** [comment] 2019-02-22 17:39
The beta version of Android Studio will probably solve your problem, if you can use it. Please let us know if that solves your problem.

**Comment by mofada** [comment] 2019-02-24 12:53
Ok, thank you, but I haven't planned to upgrade yet, because Android Studio 3.4 is still a beta version.

**Comment by stevemessick** [comment] 2019-02-25 13:50
Closing since the problem is fixed in upstream builds.

**Closed by stevemessick** 2019-02-25 13:50 UTC
