### ISSUE TITLE
compatibility error with build 232.*

### ISSUE THREAD

**Issue by jcarvalhogo** [flutter/flutter-intellij#7120] opened 2023-12-07 11:14 UTC
I'm very upset with the last intellij update, right after updating the flutter plugin it stopped working

![image](https://github.com/flutter/flutter-intellij/assets/5593817/58afced4-6f16-43c5-80e6-1f7303b89e18)

**Comment by Ajaay7** [comment] 2023-12-07 11:56
Same Issue, had to roll back to previous version, any workarounds?

**Comment by ekremkenter** [comment] 2023-12-07 12:14
Duplicate of https://github.com/flutter/flutter-intellij/issues/7115

**Closed** 2023-12-13 21:11 UTC
