### ISSUE TITLE
Tooltip covers the source being observed

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter-intellij#398] opened 2016-11-02 15:13 UTC
In the attached video I'm trying to navigate to the source of declaration of MaterialApp.

The type display tooltip covers the source that I'm trying to click on.

![jump to declaration ui problem](https://cloud.githubusercontent.com/assets/2978182/19934525/c78ab11e-a10e-11e6-8519-16a86ac5386f.gif)

**Comment by alexander-doroshko** [comment] 2016-11-02 15:48
Looks like IntelliJ Platform issue. Reproducible when tooltip width is bigger than the IDE frame width.

**Comment by pq** [comment] 2016-11-02 18:32
@alexander-doroshko is there a corresponding platform issue or should Luke file one?

**Comment by alexander-doroshko** [comment] 2016-11-02 19:31
Didn't find in 30 sec. You can file new one in 'IntelliJ IDEA' YouTrack project if you do not find one. This is a documentation tooltip on Cmd+hover.

**Comment by pq** [comment] 2016-11-02 19:40
Thanks.  Closing for now here --- @lukechurch if you want to open one for the platform that'd be awesome.

🍻

**Closed by pq** 2016-11-02 19:40 UTC
Labels: bug, dart plugin, usability
