### ISSUE TITLE
NullPointerException: Cannot invoke "com.intellij.openapi.wm.ToolWindow.setAvailable(boolean)" - Flutter Plugin in Android Studio

### ISSUE THREAD

**Issue by hamster336** [flutter/flutter-intellij#7732] opened 2024-10-24 11:59 UTC
[bug-report_2.md](https://github.com/user-attachments/files/17506383/bug-report_2.md)
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by jwren** [comment] 2024-11-14 18:33
Batch close for the `com.intellij.openapi.wm.ToolWindow.setAvailable(boolean)` exception out of the Flutter IJ plugin, this is a duplicate of https://github.com/flutter/flutter-intellij/issues/7691 and is resolved in the release of the Flutter plugin, `82.1`.

**Closed by jwren** 2024-11-14 18:33 UTC
