### ISSUE TITLE
Stuck at loading device

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter-intellij#4662] opened 2020-06-26 17:15 UTC
<img width="395" alt="Screen Shot 2020-06-27 at 12 14 12 AM" src="https://user-images.githubusercontent.com/52562340/85883503-4cbfa300-b80b-11ea-9396-74c0c848bc52.png">

**Comment by liyiwei979621500** [comment] 2020-06-27 04:25
try #4642

**Comment by tbm98** [comment] 2020-06-27 04:36
same issue with https://github.com/flutter/flutter-intellij/issues/4642#issuecomment-649462151

but how to switch to use dev channel plugin. my flutter sdk is beta channel

**Comment by helin24** [comment] 2020-06-30 00:08
Duplicate of https://github.com/flutter/flutter-intellij/issues/4642

**Closed by helin24** 2020-06-30 00:08 UTC

**Comment by helin24** [comment] 2020-06-30 00:09
@tbm98 [How to change channels](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels) may be helpful for you.

**Comment by tbm98** [comment] 2020-06-30 00:11
@helin24.
It is flutter sdk. My flutter sdk already is dev channel

**Comment by helin24** [comment] 2020-06-30 00:21
Ah I see, I think you want to go to an earlier channel. This problem occurs after flutter `1.18.0-11.1.pre`, and the current flutter stable channel is earlier than that.

**Comment by tbm98** [comment] 2020-06-30 00:25
Yes. I'll try it.
Thanks !
