### ISSUE TITLE
A plug exception

### ISSUE THREAD

**Issue by Profssh** [flutter/flutter-intellij#7043] opened 2023-10-31 01:22 UTC
## What happened

Install app to emulator while run flutter project.

## Version information

IntelliJ IDEA `2022.3.3` • Flutter plugin `io.flutter 76.1.2` • Dart plugin `223.8977`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.Throwable: Error listening to ToolEvent stream: org.dartlang.vm.service.element.RPCError@536e03c5
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at io.flutter.vmService.VmServiceWrapper$2.onError(VmServiceWrapper.java:185)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:633)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:422)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:86)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by jwren** [comment] 2023-12-15 19:29
Duplicate of https://github.com/flutter/flutter-intellij/issues/7133

**Closed by jwren** 2023-12-15 19:29 UTC
