### ISSUE TITLE
NPE in FlutterView on first app launch

### ISSUE THREAD

**Issue by robertoscaramuzzi** [flutter/flutter-intellij#789] opened 2017-03-07 23:07 UTC
## What happened

In each session, when first running or debugging my Flutter App a message with IDE error appears in the bottom right of Intellij. The App launches/debugs correctly after this.

Also, this only happens the first time after I start Intellij. Further app launches don't display the exception.

## Version information

Flutter plugin `0.1.11.1`

No Flutter sdk configured.

## Exception

null

```
java.lang.NullPointerException
	at io.flutter.view.FlutterView.lambda$updateIcon$0(FlutterView.java:143)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by devoncarew** [comment] 2017-03-08 07:37
Fixed in https://github.com/flutter/flutter-intellij/commit/10c6c1898083bb808ddeeb207867adfe9ce3b26b; this fix is not yet in the shipping version.

**Comment by devoncarew** [comment] 2017-03-09 07:57
dupe of #794

**Closed by devoncarew** 2017-03-09 07:57 UTC
Labels: bug
