### ISSUE TITLE
Deep links tool window "hide" button does not work

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter-intellij#7321] opened 2024-04-04 15:25 UTC
Clicking this should close the tool window, but nothing happens:
![Screenshot 2024-04-04 at 8 25 00 AM](https://github.com/flutter/flutter-intellij/assets/43759233/9ae77a57-b401-4436-95f1-816d19a8ac3b)

@helin24

**Comment by helin24** [comment] 2024-04-05 23:00
Do you recall if this was when this tab was empty?

**Comment by kenzieschmoll** [comment] 2024-04-08 22:27
> Do you recall if this was when this tab was empty?

I don't recall whether it was empty.. if you can't repro maybe it was related to one of the bugs you already fixed.

**Comment by helin24** [comment] 2024-05-02 20:18
This seems to have been fixed by https://github.com/flutter/flutter-intellij/pull/7325 (I am unable to reproduce). We can reopen if it appears again.

**Closed by helin24** 2024-05-02 20:18 UTC
Labels: bug, devtools-integration, flutter-deep-links
