### ISSUE TITLE
IntelliJ crashed while trying to run emulator

### ISSUE THREAD

**Issue by lucalves** [flutter/flutter-intellij#3929] opened 2019-10-03 13:27 UTC
---

## What happened

When this exception occurred, I was using the emulator and constantly pressing a button in the application that returned a print () method.

Following IDE guidelines, I am opening this pull request to analyze what may have happened.

## Version information

IntelliJ IDEA `2019.2.3` • Flutter plugin `io.flutter 40.0.4` • Dart plugin `192.6817.14`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.NullPointerException
	at io.flutter.vmService.VMServiceManager.getFlutterViewsList(VMServiceManager.java:662)
	at io.flutter.vmService.VMServiceManager.getFlutterViewId(VMServiceManager.java:647)
	at io.flutter.vmService.VMServiceManager.getDisplayRefreshRate(VMServiceManager.java:607)
	at io.flutter.vmService.VMServiceManager.lambda$onFrameEventReceived$1(VMServiceManager.java:372)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:824)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:412)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:411)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by kenzieschmoll** [comment] 2019-10-03 14:15
Dupe of https://github.com/flutter/flutter-intellij/issues/3925

**Closed by kenzieschmoll** 2019-10-03 14:15 UTC
