### ISSUE TITLE
Ctrl+Space Suggestions include non-imported files

### ISSUE THREAD

**Issue by Karthick-Ramanathan** [flutter/flutter-intellij#3118] opened 2019-01-24 09:43 UTC
On working with java and kotlin files, when ctrl+space pressed, suggestions list contains classes of non imported files that contains in the project and dependencies. But in flutter suggestions of classes only contains imported classes.

Every new class in working need to be imported first or type class name and then click import that file.

**Comment by lambdabaa** [comment] 2019-01-28 17:03
I'm working on this issue in https://github.com/dart-lang/sdk/issues/35680 FYI.

**Comment by terrylucas** [comment] 2019-01-28 18:08
.Close duplicate of dart-lang/sdk#35680

**Closed by terrylucas** 2019-01-28 18:08 UTC
