### ISSUE TITLE
make the inspector `recomputeTreeRoot` call tolerant to errors

### ISSUE THREAD

**Issue by YograjSolanke** [flutter/flutter-intellij#2893] opened 2018-11-28 09:51 UTC
## What happened

(please describe what you were doing when this exception occurred)
I run the application, and then made some changes and re-run app then hot reloading applied and application crashed by throwing following error

## Version information

Android Studio `3.2.1` • Flutter plugin `io.flutter 30.0.1` • Dart plugin `181.5656`

Error getting Flutter sdk information.

## Exception

java.util.concurrent.CompletionException: java.io.IOException: Application terminated

```
java.lang.Throwable: java.util.concurrent.CompletionException: java.io.IOException: Application terminated
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:126)
	at io.flutter.view.InspectorPanel.lambda$recomputeTreeRoot$5(InspectorPanel.java:575)
	at io.flutter.inspector.InspectorService$ObjectGroup.lambda$null$69(InspectorService.java:880)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by jacob314** [comment] 2018-11-28 22:03
Which version of package:flutter were you using?
Can you see if you can reproduce with v0.11.11?
Thanks,
Jacob

**Comment by stevemessick** [comment] 2018-12-05 17:20
Even better, try Flutter 1.0 with plugin M31.1.

I think this is one of a class of problems that was fixed in the last month.

**Comment by YograjSolanke** [comment] 2018-12-06 05:12
ok. thanks, I will try this.
Thanks & Regards,
*Yograj Balu Solanke*
Mob: *7841023392*

**Comment by YograjSolanke** [comment] 2018-12-12 15:10
sorry for late reply... but sometimes it throws same error.

**Comment by devoncarew** [comment] 2018-12-12 15:48
It looks like this happens in `recomputeTreeRoot` after the app has shut down. We should likely make that call tolerant to most classes of errors, and in many or most cases just silently ignore them.

**Comment by YograjSolanke** [comment] 2018-12-12 15:59
so what changes we have to do??

**Comment by jacob314** [comment] 2018-12-12 16:01
Just ignore the error for now. It is harmless. We will hide the error if the app has shut down.

**Comment by YograjSolanke** [comment] 2018-12-12 16:04
ok . thanks

**Comment by YograjSolanke** [comment] 2018-12-14 10:40
I/SurfaceView(13314): updateWindow -- setFrame, this = io.flutter.view.FlutterView{9c455bc VFE...... .F....I. 0,0-720,1184}
F/libc    (13314): Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 13377 (package name)
Lost connection to device.
Exited (sigterm)

**Comment by YograjSolanke** [comment] 2018-12-14 10:41
> 
> 
> I/SurfaceView(13314): updateWindow -- setFrame, this = io.flutter.view.FlutterView{9c455bc VFE...... .F....I. 0,0-720,1184}
> F/libc (13314): Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 13377 (package name)
> Lost connection to device.
> Exited (sigterm)

when app crashes above error prints in console.

**Closed** 2019-01-17 20:01 UTC
Labels: inspector
