### ISSUE TITLE
Intellij fights with itself over iml files

### ISSUE THREAD

**Issue by abarth** [flutter/flutter-intellij#302] opened 2016-10-14 04:05 UTC
I tried setting the iml files to a reasonable value, but each of my machines has a different idea what it wants these files to hold.

```diff
diff --git a/examples/flutter_gallery/flutter_gallery.iml b/examples/flutter_gallery/flutter_gallery.iml
index 802d866..3a913c2 100644
--- a/examples/flutter_gallery/flutter_gallery.iml
+++ b/examples/flutter_gallery/flutter_gallery.iml
@@ -4,7 +4,7 @@
     <exclude-output />
     <content url="file://$MODULE_DIR$">
       <excludeFolder url="file://$MODULE_DIR$/build" />
-      <excludeFolder url="file://$MODULE_DIR$/packages/flutter_gallery" />
+      <excludeFolder url="file://$MODULE_DIR$/packages" />
       <excludeFolder url="file://$MODULE_DIR$/test/calculator/packages" />
       <excludeFolder url="file://$MODULE_DIR$/test/packages" />
     </content>
diff --git a/examples/hello_world/hello_world.iml b/examples/hello_world/hello_world.iml
index 2258678..8b7ff15 100644
--- a/examples/hello_world/hello_world.iml
+++ b/examples/hello_world/hello_world.iml
@@ -5,7 +5,7 @@
     <content url="file://$MODULE_DIR$">
       <excludeFolder url="file://$MODULE_DIR$/.pub" />
       <excludeFolder url="file://$MODULE_DIR$/build" />
-      <excludeFolder url="file://$MODULE_DIR$/packages/hello_world" />
+      <excludeFolder url="file://$MODULE_DIR$/packages" />
       <excludeFolder url="file://$MODULE_DIR$/test/packages" />
     </content>
     <orderEntry type="inheritedJdk" />
diff --git a/packages/flutter/flutter.iml b/packages/flutter/flutter.iml
index b6bfb1c..0510f57 100644
--- a/packages/flutter/flutter.iml
+++ b/packages/flutter/flutter.iml
@@ -5,7 +5,7 @@
     <content url="file://$MODULE_DIR$">
       <excludeFolder url="file://$MODULE_DIR$/.pub" />
       <excludeFolder url="file://$MODULE_DIR$/bin/packages" />
-      <excludeFolder url="file://$MODULE_DIR$/packages/flutter" />
+      <excludeFolder url="file://$MODULE_DIR$/packages" />
       <excludeFolder url="file://$MODULE_DIR$/test/animation/packages" />
       <excludeFolder url="file://$MODULE_DIR$/test/cassowary/packages" />
       <excludeFolder url="file://$MODULE_DIR$/test/engine/packages" />
diff --git a/packages/flutter_driver/flutter_driver.iml b/packages/flutter_driver/flutter_driver.iml
index 5bca37d..1fa9806 100644
--- a/packages/flutter_driver/flutter_driver.iml
+++ b/packages/flutter_driver/flutter_driver.iml
@@ -4,7 +4,7 @@
     <exclude-output />
     <content url="file://$MODULE_DIR$">
       <excludeFolder url="file://$MODULE_DIR$/.pub" />
-      <excludeFolder url="file://$MODULE_DIR$/packages/flutter_driver" />
+      <excludeFolder url="file://$MODULE_DIR$/packages" />
       <excludeFolder url="file://$MODULE_DIR$/test/packages" />
       <excludeFolder url="file://$MODULE_DIR$/test/src/packages" />
     </content>
diff --git a/packages/flutter_markdown/flutter_markdown.iml b/packages/flutter_markdown/flutter_markdown.iml
index 162f9c5..2ae0251 100644
--- a/packages/flutter_markdown/flutter_markdown.iml
+++ b/packages/flutter_markdown/flutter_markdown.iml
@@ -5,7 +5,7 @@
     <content url="file://$MODULE_DIR$">
       <excludeFolder url="file://$MODULE_DIR$/.pub" />
       <excludeFolder url="file://$MODULE_DIR$/example/packages" />
-      <excludeFolder url="file://$MODULE_DIR$/packages/flutter_markdown" />
+      <excludeFolder url="file://$MODULE_DIR$/packages" />
       <excludeFolder url="file://$MODULE_DIR$/test/packages" />
     </content>
     <orderEntry type="inheritedJdk" />
diff --git a/packages/flutter_test/flutter_test.iml b/packages/flutter_test/flutter_test.iml
index 216a82f..a2f4fdd 100644
--- a/packages/flutter_test/flutter_test.iml
+++ b/packages/flutter_test/flutter_test.iml
@@ -4,7 +4,7 @@
     <exclude-output />
     <content url="file://$MODULE_DIR$">
       <excludeFolder url="file://$MODULE_DIR$/.pub" />
-      <excludeFolder url="file://$MODULE_DIR$/packages/flutter_test" />
+      <excludeFolder url="file://$MODULE_DIR$/packages" />
       <excludeFolder url="file://$MODULE_DIR$/test/packages" />
     </content>
     <orderEntry type="inheritedJdk" />
diff --git a/packages/flutter_tools/flutter_tools.iml b/packages/flutter_tools/flutter_tools.iml
index a4712ec..2ccd7bc 100644
--- a/packages/flutter_tools/flutter_tools.iml
+++ b/packages/flutter_tools/flutter_tools.iml
@@ -5,7 +5,7 @@
     <content url="file://$MODULE_DIR$">
       <excludeFolder url="file://$MODULE_DIR$/.pub" />
       <excludeFolder url="file://$MODULE_DIR$/bin/packages" />
-      <excludeFolder url="file://$MODULE_DIR$/packages/flutter_tools" />
+      <excludeFolder url="file://$MODULE_DIR$/packages" />
       <excludeFolder url="file://$MODULE_DIR$/test/packages" />
       <excludeFolder url="file://$MODULE_DIR$/test/src/ios/packages" />
       <excludeFolder url="file://$MODULE_DIR$/test/src/packages" />
```

**Comment by devoncarew** [comment] 2016-10-14 06:32
Does running `flutter update-packages --upgrade` normalize it at all? I would expect that some (all?) of those packages dirs should go away with `pub upgrade --no-packages-dir`.

**Comment by abarth** [comment] 2016-10-14 06:45
I'll need to run some experiments.

**Comment by alexander-doroshko** [comment] 2016-10-14 09:57
This is actually caused by the Dart plugin. Exclusion list depends on the Dart SDK version configured in the IDE (even if Dart support is disabled for the current project). Difference happens because in case of SDK older than 1.12 root `packages` folder is not excluded, but some of its subfolders should. In case of SDK 1.12+ root `packages` is excluded. Dart plugin treated no SDK the same as 1.11-. I'll fix it at Dart plugin side, since we are not interested too much in older SDKs support.

So 'the correct' IML is where `"file://$MODULE_DIR$/packages"` is excluded, the incorrect one is with `"file://$MODULE_DIR$/packages/flutter_tools"` and similar.

**Comment by abarth** [comment] 2016-10-14 14:48
Thanks!

**Comment by pq** [comment] 2016-10-14 16:39
@devoncarew : it looks like the IML files can be safely updated in the repo.  Tentatively bouncing to you since you did the first round.  Feel free to reassign as you see fit!

**Comment by abarth** [comment] 2016-10-14 16:59
I pushed the updated IML files to flutter.git.

**Comment by pq** [comment] 2016-10-14 17:04
Awesome.  Thanks @abarth !

Optimistically closing...

**Comment by abarth** [comment] 2016-10-15 04:53
Now we're fighting over `.pub` folders.

```diff
diff --git a/examples/hello_world/hello_world.iml b/examples/hello_world/hello_world.iml
index 78a245f..8b7ff15 100644
--- a/examples/hello_world/hello_world.iml
+++ b/examples/hello_world/hello_world.iml
@@ -3,6 +3,7 @@
   <component name="NewModuleRootManager" inherit-compiler-output="true">
     <exclude-output />
     <content url="file://$MODULE_DIR$">
+      <excludeFolder url="file://$MODULE_DIR$/.pub" />
       <excludeFolder url="file://$MODULE_DIR$/build" />
       <excludeFolder url="file://$MODULE_DIR$/packages" />
       <excludeFolder url="file://$MODULE_DIR$/test/packages" />
diff --git a/packages/flutter/flutter.iml b/packages/flutter/flutter.iml
index e50331f..0510f57 100644
--- a/packages/flutter/flutter.iml
+++ b/packages/flutter/flutter.iml
@@ -3,6 +3,7 @@
   <component name="NewModuleRootManager" inherit-compiler-output="true">
     <exclude-output />
     <content url="file://$MODULE_DIR$">
+      <excludeFolder url="file://$MODULE_DIR$/.pub" />
       <excludeFolder url="file://$MODULE_DIR$/bin/packages" />
       <excludeFolder url="file://$MODULE_DIR$/packages" />
       <excludeFolder url="file://$MODULE_DIR$/test/animation/packages" />
diff --git a/packages/flutter_driver/flutter_driver.iml b/packages/flutter_driver/flutter_driver.iml
index c88753f..1fa9806 100644
--- a/packages/flutter_driver/flutter_driver.iml
+++ b/packages/flutter_driver/flutter_driver.iml
@@ -3,6 +3,7 @@
   <component name="NewModuleRootManager" inherit-compiler-output="true">
     <exclude-output />
     <content url="file://$MODULE_DIR$">
+      <excludeFolder url="file://$MODULE_DIR$/.pub" />
       <excludeFolder url="file://$MODULE_DIR$/packages" />
       <excludeFolder url="file://$MODULE_DIR$/test/packages" />
       <excludeFolder url="file://$MODULE_DIR$/test/src/packages" />
diff --git a/packages/flutter_markdown/flutter_markdown.iml b/packages/flutter_markdown/flutter_markdown.iml
index cbcc56c..2ae0251 100644
--- a/packages/flutter_markdown/flutter_markdown.iml
+++ b/packages/flutter_markdown/flutter_markdown.iml
@@ -3,6 +3,7 @@
   <component name="NewModuleRootManager" inherit-compiler-output="true">
     <exclude-output />
     <content url="file://$MODULE_DIR$">
+      <excludeFolder url="file://$MODULE_DIR$/.pub" />
       <excludeFolder url="file://$MODULE_DIR$/example/packages" />
       <excludeFolder url="file://$MODULE_DIR$/packages" />
       <excludeFolder url="file://$MODULE_DIR$/test/packages" />
diff --git a/packages/flutter_test/flutter_test.iml b/packages/flutter_test/flutter_test.iml
index 20208e6..a2f4fdd 100644
--- a/packages/flutter_test/flutter_test.iml
+++ b/packages/flutter_test/flutter_test.iml
@@ -3,6 +3,7 @@
   <component name="NewModuleRootManager" inherit-compiler-output="true">
     <exclude-output />
     <content url="file://$MODULE_DIR$">
+      <excludeFolder url="file://$MODULE_DIR$/.pub" />
       <excludeFolder url="file://$MODULE_DIR$/packages" />
       <excludeFolder url="file://$MODULE_DIR$/test/packages" />
     </content>
```

**Comment by alexander-doroshko** [comment] 2016-10-15 09:20
It's ok to commit excluded .pub folders

**Comment by pq** [comment] 2016-10-15 14:30
Thanks @alexander-doroshko.

cc @devoncarew

**Comment by devoncarew** [comment] 2016-10-16 08:24
Fixed here https://github.com/flutter/flutter/commit/9cab64a72c1e09d8c87e7ff8ef6f75701e42cbe3 I believe.

**Closed by devoncarew** 2016-10-16 08:24 UTC
Labels: task, usability

**Comment by alexander-doroshko** [comment] 2016-10-17 10:26
I've found one more possible case when there may be conflicts related to excluded folders in the `*.iml`. This is what Dart plugin does:
- excludes ALL `packages` folders, even if they do not exist by iterating all places where these folders can be potentially created
- excludes `.pub` folder, but only if it exists
- excludes `build` folder, but only if it exists

**Example 1:** you add new `web/foo` folder to the project and do `pub get`. Since this moment IDE also adds one more potential folder to the exclude list: `web/foo/packages`, `*.iml` file becomes locally changed.
**Required action:** you need to commit changed `*.iml` together with added files from the newly added `web/foo/packages` folder. Your colleagues won't have any conflicts with locally chaged `*.iml` after updating. So no problems in this case.

**Example 2:** You do `pub build`. IDE adds `.pub` and `build` folders to the exclude list in the `.iml`. You commit `*.iml`. Your colleague checks out the project but doesn't do `pub build`. 
**Problem:** In this case your colleague has locally changed `*.iml` because `build` folder is excluded in committed `*.iml`, but not excluded in his/her local copy (because `build` folder doesn't exist yet).
**Suggestion:** I suggest that Dart plugin should exclude `.pub` and `build` folders always, even if they do not exist. In this case you'll commit `*.iml` with excluded `.pub`, `build` and numerous `packages`, and colleagues won't have local changes in `*.iml`.

I'm going to include this logic in the Dart plugin 2016.3, let me know in case of any objections.
