### ISSUE TITLE
Consider nesting stacktrace entries

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#2485] opened 2018-07-16 18:57 UTC
It would be great to nest stack trace frames under log entries so they can be easily collapsed and hidden.

![image](https://user-images.githubusercontent.com/67586/42777364-b2c28b98-88ee-11e8-8751-0e1eb1b0ca1d.png)

/cc @quangson91

**Comment by quangson91** [comment] 2018-09-09 03:16
@pq, I'm trying to working on this issue.
But for now, do you have any suggestion to determine the log entry is Stacktrace ?

For me, I think we can determine the log is entry by check some first characters contain `#NUMBER`.

// cc @devoncarew

**Comment by quangson91** [comment] 2018-09-09 06:45
I just create an WIP pr for this one: https://github.com/flutter/flutter-intellij/pull/2594/files
(Still thinking about: how do we enable collapse for the FlutterLogTree)

**Comment by pq** [comment] 2018-09-11 21:02
Looking at the PR now.  I think in the medium term we'll want to introduce a structured format for entries coming from the Flutter framework itself so that nesting is something explicit.  FWIW: a bit of relevant conversation is going on in https://github.com/flutter/flutter/issues/21504 and https://github.com/flutter/flutter/pull/21505.

Thanks for pitching in!

**Comment by DanTup** [comment] 2018-09-20 16:02
We do have a structured way of getting stack traces, it's in the VM service :-)

It would be great if we could support breaking and let the user use all the debugging tools we have (eg. https://github.com/flutter/flutter/issues/17007). I don't know what the scale of work for it is though (or who could advise). The problem is that Flutter wants to catch the exceptions, but as a user I want them to break.

**Comment by pq** [comment] 2018-11-06 18:06
Another angle to consider is to use the new details pane:

![image](https://user-images.githubusercontent.com/67586/48084014-7e55a780-e1ab-11e8-8c18-c78619a20338.png)

So far this is just showing json "data" but could easily be used to show stack traces and that may be a nice alternative to nesting.

**Comment by devoncarew** [comment] 2020-01-07 20:37
Closing as this is related to the experimental logging view.

**Closed by devoncarew** 2020-01-07 20:37 UTC
Labels: enhancement, logging
