### ISSUE TITLE
Project Structure item is missing from the File menu

### ISSUE THREAD

**Issue by fnicastri** [flutter/flutter-intellij#4756] opened 2020-08-11 08:07 UTC
I know it is already reported in the announcement mailing list
but I cant' find a reference here.

## Steps to Reproduce

Install Android Studio 4.1 Beta
install flutter plugin
create a new project

## expected behavior

Project structure in  File menu and toolbar

## what's happening

Project structure is missing

### Studio:
```
Android Studio 4.1 RC 1
Build #AI-201.8743.12.41.6719854, built on July 29, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: undo.documentUndoLimit=1000, ide.new.welcome.screen.force=true, undo.globalUndoLimit=100
Non-Bundled Plugins: Dart, io.flutter
```
### Flutter plugin:
```
48.1.3 Stable channel
```
__same happens with the dev 48.0.3-dev.6 version__

### Flutter:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2020.2)
```

Everything is working with Studio Stable, Canary and Idea CE

**Comment by jacob314** [comment] 2020-08-24 17:25
We don't add or remove the product structure item from the File menu. That is a general IntelliJ feature.
If you would like to file a bug on IntelliJ you can do it here.
https://youtrack.jetbrains.com/issues/IDEA

**Comment by jacob314** [comment] 2020-08-24 17:30
This is a dupe of.
https://github.com/flutter/flutter-intellij/issues/4736

**Closed by jacob314** 2020-08-24 17:30 UTC

**Comment by fnicastri** [comment] 2020-08-25 08:50
> This is a dupe of.
> #4736

not entirely, the issue is present on Studio created projects too
