### ISSUE TITLE
Format on Save

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1293] opened 2017-08-24 17:24 UTC
This has come up in discussion a few times; would be great to have a 'Reformat code on save' option in Flutter preferences.

**Comment by alexander-doroshko** [comment] 2017-08-24 17:39
Dupe of #1205.

There are already 2 ways to achieve this.
First is to record a macro as @mit-mit  wrote in comments of #1205.
Second is to install 3rd party [Save Actions](https://plugins.jetbrains.com/plugin/7642-save-actions) plugin and check 'Reformat on Save' there.

In JetBrains we think that we do not want to provide such a feature out-of-the-box. Standard 'Reformat Code' action has a standard keybinding and most of users are used to it. Whereas 'Save' action is from a different world and we believe that experienced users very rarely do save whatever manually (unless a special 3rd party tool requires saving).

**Comment by devoncarew** [comment] 2017-08-30 06:55
@alexander-doroshko, thanks for the reminder! Closing as a dup of #1205.

**Closed by devoncarew** 2017-08-30 06:55 UTC
Labels: enhancement
