### ISSUE TITLE
flutter 3.13.3 - jump to source in select widget mode does not jumps to source

### ISSUE THREAD

**Issue by vasilich6107** [flutter/flutter-intellij#6905] opened 2023-09-14 15:25 UTC
# ON FLUTTER 3.10.6 - IT WORKS FINE

# ON FLUTTER 3.13.3 - DOES NOT WORK
Issues in console.

```
======== Exception caught by Flutter framework =====================================================
The following assertion was thrown during a service extension callback for "ext.flutter.inspector.getDetailsSubtree":
Id does not exist.

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49  throw_
packages/flutter/src/widgets/widget_inspector.dart 1369:7                     toObject
packages/flutter/src/widgets/widget_inspector.dart 1796:28                    [_idToDiagnosticsNode]
packages/flutter/src/widgets/widget_inspector.dart 1954:35                    [_getDetailsSubtree]
packages/flutter/src/widgets/widget_inspector.dart 1198:21                    <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5            _async
packages/flutter/src/widgets/widget_inspector.dart 1194:38                    <fn>
packages/flutter/src/foundation/binding.dart 958:32                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
dart-sdk/lib/async/zone.dart 1661:54                                          runUnary
dart-sdk/lib/async/future_impl.dart 156:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 840:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 869:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 632:7                                     [_complete]
dart-sdk/lib/async/future.dart 424:15                                         <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19       internalCallback
====================================================================================================
```

## Steps to Reproduce

Use latest Intelij IDEA Community Edition and try to select widget mode.

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

```
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.5.1 22G90 darwin-arm64 (Rosetta), locale en-UA)
    • Flutter version 3.13.3 on channel stable at /Users/vasilich/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (8 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/vasilich/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2022.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 71.1.5
    • Dart plugin version 222.4459.16

[✓] IntelliJ IDEA Community Edition (version 2023.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE 2.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] VS Code (version 1.82.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0
```

**Comment by ocakliemre** [comment] 2023-09-15 19:53
I'm having the same problem too. While it works normally on VsCode, it does not work on Android Studio.

**Comment by fourman-alex** [comment] 2023-09-20 07:32
Has this been picked up by the team yet? This is the "bread and butter" of Flutter, those of us who prefer IntelliJ are forced to use VS Code for this feature alone (while it is broken). Can we help by providing more info?

**Comment by 7AveNooN7** [comment] 2023-09-20 11:36
Up.

**Comment by helin24** [comment] 2023-09-20 18:50
Duplicate of https://github.com/flutter/flutter-intellij/issues/6894

You can try out the options here to fix until our next release: https://github.com/flutter/flutter-intellij/issues/6894#issuecomment-1714549150

**Closed by helin24** 2023-09-20 18:50 UTC
