### ISSUE TITLE
Flutter Inspector - Not Found

### ISSUE THREAD

**Issue by politebarista** [flutter/flutter-intellij#6406] opened 2022-11-24 08:18 UTC
Hi! I get the following window (see screenshot) when opening Flutter Inspector. The bug is reproduced only if the "Enable embedding DevTools in the Flutter Inspector tool window" option is selected in the framework settings in Android Studio preferences. If you remove the selection from it, the inspector starts.

<details><summary>Screenshot of Flutter inspector</summary>

![Screenshot 2022-11-24 at 15 07 44](https://user-images.githubusercontent.com/63463572/203727414-095918b6-8c47-4a72-b1fa-3e9e88de8603.png)

</details>

Yes, the flutter version is already outdated, but I don't think it's the case, since I've been using it for some time, and the problem has just appeared.

Using "Invalidate caches and restart" did not help, as did restarting the studio or the computer as a whole.

## Version info

Android Studio version - Android Studio Dolphin | 2021.3.1 Patch 1.

<details><summary>Version of Android Studio plugins</summary>

![Screenshot 2022-11-24 at 15 12 29](https://user-images.githubusercontent.com/63463572/203728355-d99ffc24-1109-421d-945e-83d545d7a2e8.png)

</details>

<details><summary>flutter doctor -v</summary>

[✓] Flutter (Channel unknown, 3.0.3, on macOS 13.0 22A380 darwin-arm, locale en-RU)
    • Flutter version 3.0.3 at /Users/user/flutter
    • Upstream repository unknown
    • Framework revision 676cefaaff (5 months ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/user/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/user/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • iPhone 14 (mobile) • 4A83F57A-AADA-4E10-A7D6-2ECD45931583 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 13.0 22A380 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
</details>

**Comment by stevemessick** [comment] 2022-11-28 23:51
@helin24 Could you take a look at this?

**Comment by helin24** [comment] 2022-11-29 00:09
@politebarista could you send along your IntelliJ logs? A file like `idea.log` should be available if you go to Help > Show Log in finder.

**Comment by politebarista** [comment] 2022-12-01 03:33
Yes, of course, but I may need time for this, since the log contains a lot of sensitive information 🤗

**Comment by helin24** [comment] 2022-12-05 17:19
@politebarista sorry I didn't mention this earlier - feel free to send to my email (helinx@google.com).

**Comment by helin24** [comment] 2022-12-12 20:36
@politebarista are you able to run `dart devtools` in the terminal and open DevTools successfully in a browser outside of IntelliJ?

**Comment by politebarista** [comment] 2022-12-13 03:33
Yes, I entered this command and DevTools opened successfully. I entered the command while in the project directory, as well as while the project was running in Android Studio.

<details><summary>Screenshot of DevTools in a browser</summary>

<img width="1440" alt="Screenshot 2022-12-13 at 10 31 38" src="https://user-images.githubusercontent.com/63463572/207220116-65aa84ce-ab78-450a-8ed0-a062872645e0.png">

</details>

**Comment by samirgezalov** [comment] 2023-01-16 09:50
same issue, flutter 3.0.4

**Comment by helin24** [comment] 2023-01-23 19:26
@samirgezalov I'm hoping someone who's having this issue can provide more detailed logs. Could you try the steps in https://github.com/flutter/flutter-intellij/issues/6493#issuecomment-1371332999?

**Comment by samirgezalov** [comment] 2023-01-24 14:27
> @samirgezalov I'm hoping someone who's having this issue can provide more detailed logs. Could you try the steps in [#6493 (comment)](https://github.com/flutter/flutter-intellij/issues/6493#issuecomment-1371332999)?

Thanks for answer, seems that it's undead now. If you need logs with 'corrupted' version please let me know, and instruct me please where those logs are, so i could find them, because when i open corrupted version, no mistake given, apart of inspector tab itself.

**Comment by helin24** [comment] 2023-01-26 17:19
@samirgezalov okay, sounds good. If you end up back at a corrupted version, please send logs using the instructions (https://github.com/flutter/flutter-intellij/issues/6493#issuecomment-1371332999) - your log file will be in a file called `idea.log` found from Help > Show logs in finder.

**Comment by helin24** [comment] 2023-02-02 00:16
@politebarista and @samirgezalov could you see if the problem is fixed in this custom plugin? We suspect there could be a caching issue or an issue with using an incompatible DevTools URL. (Even better if you can use the custom plugin and also follow the updated logging steps in https://github.com/flutter/flutter-intellij/issues/6493#issuecomment-1371332999, if you continue to see a failure)

Install this by going to Settings > Plugins > Settings gear to the right of "Installed" > Install plugin from disk:
[flutter-intellij.zip](https://github.com/flutter/flutter-intellij/files/10563239/flutter-intellij.zip) - this is for AS 2021.3. If your version of the IDE now differs, I'll upload another file for you to try.

**Comment by politebarista** [comment] 2023-02-07 15:01
@helin24 I really apologize for the very long answer. After updating the plugin, I no longer observe this problem. Thank you very much!

**Comment by DanTup** [comment] 2023-02-08 11:37
I don't know if it's the same issue, but when I tried to repro this I get this:

<img width="590" alt="Screenshot 2023-02-08 at 11 23 46" src="https://user-images.githubusercontent.com/1078012/217516622-2e5eb574-0a8c-4a23-8945-62af5f171105.png">

@helin24 is there a way I can attach Chrome DevTools to this JxBrowser instance?

I don't know if all these steps are important, but here's what I did:

- use Flutter latest stable
- open Android Studio
- run counter app
- click Flutter Inspector - everything loaded fine
- closed Android Studio
- `git checkout 3.0.0 && flutter doctor` in the Flutter SDK dir
- re-open Android Studio
- run counter app
- click Flutter Inspector

I don't know whether this is the same issue and "not found" just isn't rendering. My theory was going to be that the index html / javascript was being cached from the new SDK version and being used after switching back to the older version. This would cause the DevTools script to redirect from `?page=inspector&...` to `/inspector?...` which the older SDK's DevTools server would not handle.

I was trying to verify if JxBrowser was doing any caching. I found https://www.teamdev.com/downloads/jxbrowser/javadoc/com/teamdev/jxbrowser/chromium/CacheStorage.html but it's not clear if this is enabled by default. I do have a bunch of Chrome profile data at `/Users/danny/Library/Application Support/Google/AndroidStudio2021.2/plugins/flutter-intellij/jxbrowser/user-data/Default` but I don't know how to verify if any might be a cache.

I think if there's a way we can connect Chrome DevTools (from `chrome://inspect`) to it, it may be easier to track down what's happening.

**Closed** 2023-02-10 17:47 UTC
Labels: P1
