### ISSUE TITLE
On Linux, installing Flutter plugin in AS creates infinite loop

### ISSUE THREAD

**Issue by LarkAscending** [flutter/flutter-intellij#1518] opened 2017-11-21 02:06 UTC
## Steps to Reproduce
1. From AS Welcome screen>Configure>Plugins
1. Select Browse repositories.
1. Search for Flutter plugin and select it. Click Install.
1. Select Yes in OK-to-install-Dart-plugin prompt.

Dart plugin is downloaded and installed. Flutter plugin Install button is enabled, but clicking it just displays the OK-to-install-Dart-plugin prompt again. 

## Version info

```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /usr/local/google/home/eastrue/flutter
    • Framework revision 1c372c6803 (3 months ago), 2017-08-31 15:54:45 -0700
    • Engine revision f9e00a7c72
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /usr/local/google/home/eastrue/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /opt/android-studio-3.0/jre/bin/java
    • Java version    16363

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio-2.3
    • Java version    16146

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio-with-blaze-2.3
    • Java version    16168

[✓] Android Studio (version 2.2)
    • Android Studio at /usr/local/google/home/eastrue/android-studio
    • Java version    16190

[✓] Android Studio (version 3.0)
    • Android Studio at /opt/android-studio-3.0
    • Java version    16250

[-] IntelliJ IDEA Community Edition (version 2017.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 171.4694.29
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices
    • Nexus 5X • 0048fc9b7c76b7a2 • android-arm • Android 6.0.1 (API 23)

```

**Comment by stevemessick** [comment] 2017-11-21 15:05
On the AS Welcome screen, to the left of the Configure button, you should see an Events button. Does it get annotated with a red bubble? If so, that might help diagnose the problem. After restarting AS is either the Dart or Flutter plugin installed?

I am pretty sure this is a problem with the plugin manager since neither the Dart nor Flutter plugins are functional until AS has been restarted.

**Comment by stevemessick** [comment] 2017-11-21 15:25
One more thing: Could you try this with IntelliJ? The `flutter doctor` output shows you have the CE version handy (although it needs updating). If it works there then the problem is probably specific to AS, assuming no Events point to a plugin issue.

**Comment by stevemessick** [comment] 2017-12-11 16:40
@LarkAscending Did that linux box ever get rebooted?

**Comment by LarkAscending** [comment] 2017-12-11 18:40
Yes but according to IT it needed an upgrade. Post-upgrade there are other issues that are causing it to be non-functional. It's sitting cold and dark right now... have not forgotten about this issue though.

**Comment by stevemessick** [comment] 2018-02-08 17:48
I'd like to resolve this soon. Any progress?

**Comment by stevemessick** [comment] 2018-02-08 17:54
I'm closing this since we cannot reproduce it. Please re-open if you see this behavior again. Thanks!

**Closed** 2018-02-08 17:55 UTC
Labels: platform-android-studio, ui
