### ISSUE TITLE
Cannot override missing methods on newly created StatefulWidget

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter-intellij#2228] opened 2018-05-08 21:24 UTC
## Steps to Reproduce

If I type this:
```dart
class StatefulTest extends StatefulWidget {
}
```
Into a dart file, I get an analyzer error on the "StatefulTest":
![image](https://user-images.githubusercontent.com/8867023/39783798-0bbd949a-52cb-11e8-9115-e44bd2bed8c8.png)

This makes sense.  But when I select "Generate...>Override Methods...", or hit "Ctrl-O", (with my cursor on the class name), I get this:
![image](https://user-images.githubusercontent.com/8867023/39783779-030b847e-52cb-11e8-874c-5b3a9a7625a1.png)

I'd really like to be able to easily create a new widget by just typing the class declaration, and then making skeletons of all the missing overrides.

## Version info

```
[✓] Flutter (Channel switcher_perf, v0.4.1-pre.32, on Linux, locale en_US.UTF-8)
    • Flutter version 0.4.1-pre.32 at /usr/local/google/home/gspencer/code/flutter
    • Framework revision 7cc7263ef8 (4 days ago), 2018-05-04 09:23:45 -0700
    • Engine revision 20b286dd42
    • Dart version 2.0.0-dev.53.0.flutter-e6d7d67f4b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at /usr/local/google/home/gspencer/Android/Sdk
    • Android NDK at /usr/local/google/home/gspencer/Android/Sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.2
    • ANDROID_HOME = /usr/local/google/home/gspencer/Android/Sdk
    • Java binary at: /opt/android-studio-with-blaze-3.0/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /opt/my-intellij-ce-2018.1
    • Flutter plugin version 24.1.2
    • Dart plugin version 181.4892.1

[✓] Connected devices (1 available)
    • Nexus 6P • 84B7N15A07007628 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by scheglov** [comment] 2018-05-09 05:47
`Generate... > Override Methods...` is implemented in Java in Dart plugin and is old code.
Ideally we should replace it with requesting members data from Analysis Server.
@jwren have you started working on this, or I can steal it? :-)

For you using Quick Assist (Cmd + Enter) might be a  better choice.
It will do exactly what you need - add all missing overrides.

![image](https://user-images.githubusercontent.com/384794/39797587-9da56ca2-5311-11e8-9ce5-bf59b4640a4b.png)

![image](https://user-images.githubusercontent.com/384794/39797607-bcafc4da-5311-11e8-858f-f820258889e2.png)

**Comment by jwren** [comment] 2018-05-09 15:39
@scheglov - Go for it.  Integration from DAS into the generator wasn't obvious to me into the Generator IJ framework.  Alt+Enter on the error from the DAS, does the right thing so it hasn't been prioritized.

**Comment by gspencergoog** [comment] 2018-08-13 17:42
One difference between the Ctrl/Cmd-I and Alt/Cmd-Enter way is that I have to actually have the cursor on the class name to have the context menu appear, as opposed to anywhere inside of the class declaration.

**Comment by AylanBoscarino** [comment] 2020-05-20 12:56
This issue wasn't fixed yet.

A problem that is quite common to me when I extend a custom created class (like BaseViewModel for example) and want to override any specific method (Ctrl + O) the IDE says that no method where found to override.

**Comment by crtl** [comment] 2020-07-28 09:03
This issue still exists in 2020?
When is it going to be fixed?

**Comment by AhmedElshimy1998** [comment] 2022-05-16 01:26
issue still in 2022

**Comment by NanoMichael** [comment] 2022-06-23 11:26
Any progress? It's really annoying and lowers the work efficiency. 😢 

And I've found this issue: #1110, but with no luck.

**Comment by gspencergoog** [comment] 2022-06-23 15:45
Yeah, I'm not able to get suggestions for overrides still.

If I'm in a class decl between declarations and hit Ctrl-Space, I get a bunch of suggested class names, but no suggested overrides.  Command-O always gives "No methods were found to override". Typing the first few letters of what I want to override and then hitting Ctrl-Space does give me some override suggestions, but then I have to know the exact name (or at least the beginning) of the override, and often I just want to see what is overridable before I pick one.

It would be really nice if Ctrl-Space in a blank area would give me a list of all the possible overrides, and that Command-O was wired up to do the right thing instead of trying to complete a Java method or whatever it is doing.

Additionally, I would like to suggest that the templates that the overrides place do NOT include the comment that says "// TODO: implement <function>", since 99.9% of the time I just immediately delete it, making it more work to do.  I guess I kind of feel the same way about the "throw UnimplementedError" lines too: I'd rather it insert non-functional code than make me delete it every single time.  Alternatively, once inserted, it could automatically select the body of the function so I could just immediately hit delete or start typing to delete the `throw` line. I still wouldn't want the TODO comments though.

**Comment by gspencergoog** [comment] 2022-06-23 17:06
I filed https://github.com/flutter/flutter-intellij/issues/6239 for the "TODO" part of my previous comment.

**Comment by gspencergoog** [comment] 2022-06-24 19:02
@stevemessick Should we file a separate Dart issue about the Command-O behavior?

**Comment by stevemessick** [comment] 2022-06-27 14:54
Yes, it seems to be a regression.

**Comment by stevemessick** [comment] 2022-06-28 23:13
This is a problem in the Dart plugin, and an issue has already been created:
https://youtrack.jetbrains.com/issue/WEB-40469/Dart-Ctrl-O-Override-Methods-does-not-show-Super-class-instance-methods-Dart-Plugin

I'm closing this issue. Whether it will be fixed using the suggestion by @scheglov (above) or by debugging the existing code, the work will be done in the Dart plugin, not the Flutter plugin.

**Closed by stevemessick** 2022-06-28 23:13 UTC
