### ISSUE TITLE
Use ⌃↑ and ⌃↓ keys to quickly move between methods in the editor not working

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter-intellij#3678] opened 2019-07-18 12:33 UTC
## Steps to Reproduce

> Use ⌃↑ and ⌃↓ keys to quickly move between methods in the editor

It doesn't work in Flutter

## Version info
```
[✓] Flutter (Channel dev, v1.8.0, on Mac OS X 10.14 18A389, locale en-GB)
    • Flutter version 1.8.0 at /flutter
    • Framework revision 2fefa8c731 (2 weeks ago), 2019-07-01 11:33:22 -0700
    • Engine revision 45b66b722e
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/chocolate/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.2

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by devoncarew** [comment] 2019-07-18 14:54
cc @jwren 

I can trigger this on the Mac (for Java code) using the the find actions dialog, but not via the keyboard (the ctrl-arrow keys are bound to mac's spaces).

**Comment by dark-chocolate** [comment] 2019-07-18 14:58
@devoncarew I am also able to do it in Java code using exact ⌃↑ and ⌃↓ keys, but it doesn't work in Dart.

**Comment by jwren** [comment] 2019-07-18 20:29
The actions are called "Next Method" and "Previous Action" . I have never used or noticed the behavior myself as the Mac overrides the keybinding with the MacOs Mission Control and other actions.

Created https://youtrack.jetbrains.com/issue/WEB-40081 to track on the JetBrains side.

**Comment by jwren** [comment] 2019-07-18 22:12
@dark-chocolate

I went to go see what it would take to implement this feature and found that is already implemented.  I made sure that the actions worked in both directions and with methods and functions.

Make sure that you don't have any parsing errors in your Dart file.  If you can't get it working with the keys, or with the menu bar, Navigate > Next Method / Navigate > Previous Method either, attach a sample piece of Dart source so we can reproduce the issue.

**Comment by dark-chocolate** [comment] 2019-07-19 01:32
@jwren I tried both  `⌃↑` and `⌃↓` and `Navigate > Next Method / Navigate > Previous Method` and still it failed, there are absolutely no errors in my dart file and in complete flutter project, here is the screenshot of the full file.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/40364434/61502811-0656a700-a9f3-11e9-8307-5147fd393f3f.gif)

**Comment by jwren** [comment] 2019-07-22 18:28
I reproduced this in v2019.1 of the IJ platform, with and without the Flutter plugin installed, so the issue is with the Dart Plugin (and/or the underlying IDEA platform.)

I was **not** able to reproduce it on the 2019.2 version of IJ launching from Dart plugin source, with the above Dart source.  I suspect that this was an issue in IntelliJ platform that has been resolved.  The rolled Flutter plugin version doesn't yet allow me to install the Flutter plugin in the latest launched intellij-community/ source to confirm that the action works with Flutter Dart source.

I was not able to find any resolved issue in https://youtrack.jetbrains.com. @alexander-doroshko 

This can be closed as soon someone else confirms that these actions work with IJ 2019.2

**Comment by alexander-doroshko** [comment] 2019-07-23 12:17
I'm not sure when the feature was implemented / broken / fixed, but I can confirm it works for me in 2019.2.

**Closed** 2019-07-23 15:52 UTC
Labels: dependency: dart plugin

**Comment by dark-chocolate** [comment] 2019-07-25 09:59
@jwren  So what's the final solution, do I need to wait for the coming update in Android studio?

**Comment by jwren** [comment] 2019-07-25 16:34
Yes.  If it was a lower-risk change in the Dart or Flutter plugin we'd push out a change for all IJ platforms being used, but unfortunately it was some change in the platform itself.

**Comment by GanZhiXiong** [comment] 2020-03-02 04:09
Hello, everyone. I have also encountered this problem. Is there any solution?

**Comment by GanZhiXiong** [comment] 2020-03-02 04:13
@dark-chocolate   
How is this problem solved? Why is it closed?  😂
