### ISSUE TITLE
Windows support disabled despite running Flutter 3 with config enabled

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter-intellij#6174] opened 2022-05-17 19:46 UTC
The Windows checkbox is grayed out even though it's enabled in `flutter config`: 

## Steps to Reproduce
Installed Android Studio Chipmunk (2022.2.1). 
Created a new project. 
Note that Windows is grayed out in the dialog below:
![image](https://user-images.githubusercontent.com/2319867/168897259-8e587f96-f2df-4c42-8e98-64af34d85cec.png)

### Flutter Doctor
```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.753, on Microsoft Windows [Version 10.0.19044.1706], locale en-US)
    • Flutter version 3.1.0-0.0.pre.753 at C:\src\flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 9651f1d717 (59 minutes ago), 2022-05-17 14:45:05 -0400
    • Engine revision 8ab1720293
    • Dart version 2.18.0 (build 2.18.0-123.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\timsneath\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.2.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.2.32505.173
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.67.1)
    • VS Code at C:\Users\timsneath\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1706]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.54
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.47

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Flutter Config
```
Settings:
  enable-android: true
  enable-web: true
  enable-linux-desktop: false
  enable-macos-desktop: false
  enable-windows-desktop: true
```

**Comment by stevemessick** [comment] 2022-05-17 22:42
I can't reproduce this on a Mac.

**Comment by timsneath** [comment] 2022-05-17 22:52
Well, obviously not: I wouldn't expect you to create a Windows solution on a macOS workstation :) 

Are you saying that the macOS checkbox _is_ available on a macOS machine running Flutter 3?

**Comment by stevemessick** [comment] 2022-05-17 23:41
> Are you saying that the macOS checkbox is available on a macOS machine running Flutter 3?

Yes. All platforms should be available. It's like creating an Android app on a Mac, in a way.

The code that runs the platform selection is complex, due to `flutter config` being how you enable them. It's probably got some silly platform-specific thing that needs special-casing. I'll look into next week when I'm working on the monthly release (and have my Windows machine in use). Meantime, you can use `flutter create ...` -- sorry about all the stuff you have to type!

**Comment by timsneath** [comment] 2022-05-18 00:47
No worries! Thank you!

**Comment by timsneath** [comment] 2022-05-20 00:33
Looks like someone else is running into this issue: https://github.com/flutter/website/issues/6811

**Comment by stevemessick** [comment] 2022-05-25 22:53
This is fixed in the June release.

**Closed by stevemessick** 2022-05-25 22:53 UTC
Labels: investigate, ❖ platform-windows
