### ISSUE TITLE
Breakpoint is ignored after hot reload

### ISSUE THREAD

**Issue by turnidge** [flutter/flutter-intellij#434] opened 2016-11-10 22:00 UTC
Steps to reproduce:

1. User sets a breakpoint in the demo app on "_counter++;"

![screen shot 2016-11-10 at 1 35 50 pm](https://cloud.githubusercontent.com/assets/4804200/20196028/b63ea448-a74d-11e6-8ca1-0d6423442ee8.png)

2. When the (+) button is pressed, the breakpoint works at this point.

![screen shot 2016-11-10 at 1 48 10 pm](https://cloud.githubusercontent.com/assets/4804200/20196040/c2f7fa18-a74d-11e6-9e48-35724dea9dbf.png)

3. Hit "hot reload".  We have not edited the code.

![screen shot 2016-11-10 at 1 58 59 pm](https://cloud.githubusercontent.com/assets/4804200/20196063/dcf26660-a74d-11e6-9ab6-05dff7bbaa65.png)

EXPECTED: Program stops at breakpoint
ACTUAL: Program ignores breakpoint

Cc'ing @johnmccutchan

**Comment by mit-mit** [comment] 2016-11-11 09:13
Dupe of https://github.com/flutter/flutter-intellij/issues/305

**Closed by mit-mit** 2016-11-11 09:13 UTC
