### ISSUE TITLE
Autocompletion not working optimally

### ISSUE THREAD

**Issue by szakarias** [flutter/flutter-intellij#876] opened 2017-04-04 10:55 UTC
## Steps to Reproduce

`flutter create`, then in `main.dart` take the `Text` widget in the `Center` widget, wrap it in a `Row` widget so that the `Text` widget is the only element in the `children` list like so:
    
    body: new Center(
        child: new Row(
          children: <Widget>[
            new Text(
              'Button tapped $_counter time${ _counter == 1 ? '' : 's' }.',
            ),
          ],
        ),
      ), 

Now try to add a new element in the beginning of the list, for instance by typing to "new T" . Here no suggestions are provided. If a "," is typed after "new T" or the element is added as the last element in the list we get the suggestions.

**Comment by pq** [comment] 2017-05-08 02:44
cc @danrubel

**Comment by pq** [comment] 2017-05-10 17:47
AI (@pq): investigate.  This may be a limitation of how we're dealing with what we're seeing from the parser.

**Comment by pq** [comment] 2017-05-10 19:10
Confirmed no completions.

![screen shot 2017-05-10 at 12 08 45 pm](https://cloud.githubusercontent.com/assets/67586/25916445/7c900ff6-3579-11e7-9013-bccffbc0a55f.png)

even w/ `new` cue:

![screen shot 2017-05-10 at 12 08 57 pm](https://cloud.githubusercontent.com/assets/67586/25916446/7c91dd22-3579-11e7-8aa2-3b1bb2b7c952.png)


@danrubel : maybe we can look together at the AST and see what case we need to provision for?

**Comment by mit-mit** [comment] 2018-01-04 14:25
This is super annoying, and something you hit whenever you edit the first element in a list of widgets. @pq any news?

@devoncarew I'd like to nominate this for M21.

**Comment by mit-mit** [comment] 2018-01-04 14:33
Btw, this works in vsCode, so I assume this is somehow an IJ issue?

**Comment by pq** [comment] 2018-01-04 14:43
> Btw, this works in vsCode, so I assume this is somehow an IJ issue?

This is surprising.  I'd expect the behavior to be the same unless we don't send requests from IntelliJ in some cases?

cc @danrubel @alexander-doroshko

**Comment by mit-mit** [comment] 2018-01-04 14:55
Here are a couple of illustrations. Looks like maybe code completions don't work in IJ when the separating comma is missing?

*vsCode*:

![ij2](https://user-images.githubusercontent.com/13644170/34568882-7c8f488c-f167-11e7-8c28-77bf6bcdbaf4.gif)

*IntelliJ*:

![ij3](https://user-images.githubusercontent.com/13644170/34568962-a88756c8-f167-11e7-8d3c-155310b1c2cb.gif)

**Comment by alexander-doroshko** [comment] 2018-01-05 15:37
This is a bug in the Dart plugin, it filters out all the received completion variants for this case. It should be easy to fix, thanks for letting me know! I'll fix it as soon as I'm back in the office next week.

**Comment by devoncarew** [comment] 2018-01-05 15:44
Awesome, thanks Alex!

**Comment by pq** [comment] 2018-01-05 15:52
Excellent, thanks @alexander-doroshko !

**Comment by danrubel** [comment] 2018-01-05 16:04
@alexander-doroshko It would be great to know when the Dart plugin changes or filters out code completion suggestions. Those situations probably indicate areas where the analysis server code completion returns (or used to return) poor results. Could you provide us a list of when code completion suggestions are filtered out? Or point us to the code where this filtering occurs?

**Comment by alexander-doroshko** [comment] 2018-01-05 16:18
@danrubel It's filtering by prefix. 
If `foo` is typed before the caret then `fooBar` matches, `FooBar` doesn't match if case-sensitive frst letter check is enabled, `bazFoo` matches if middle-matching is enabed, but `qwerty` is always filtered out.
The problem with this example is that prefix is calculated incorrectly. There should be no prefix at all, but IDE thinks it is `<Widget>[ new` and filters out everything.
I don't think you may use this knowledge to test analysis server :).

**Comment by alexander-doroshko** [comment] 2018-01-09 12:14
Fixed in 2018.1 branch. EAPs will start soon.

**Comment by danrubel** [comment] 2018-01-09 13:24
@alexander-doroshko Thanks!

**Comment by pq** [comment] 2018-01-09 15:16
Awesome. Thank you!

**Comment by pq** [comment] 2018-03-22 19:25
Confirmed this works w/ the latest Dart Plugin in 2017.3+.

![mar-22-2018 12-22-42](https://user-images.githubusercontent.com/67586/37793455-fbe254d0-2dcb-11e8-9659-a4de31509b14.gif)

🎉

**Closed by pq** 2018-03-22 19:25 UTC
Labels: P1, bug, completion, dependency: dart plugin, topic-editing, validate-next-dart-plugin
