### ISSUE TITLE
Suggestions are not working properly

### ISSUE THREAD

**Issue by bhanuka96** [flutter/flutter-intellij#6177] opened 2022-05-18 15:26 UTC
Type **color**, there aren't display any suggestions but type the exact same word, then suggestions are displayed.

![Screenshot 2022-05-18 at 8 52 09 PM](https://user-images.githubusercontent.com/34953062/169080715-5b4168f8-dbdb-465f-90bb-45206a2047b0.png)
![Screenshot 2022-05-18 at 8 52 32 PM](https://user-images.githubusercontent.com/34953062/169080733-253d30d5-62e1-4842-a757-f648979fe091.png)

**Comment by stevemessick** [comment] 2022-05-18 23:36
This is an issue with the Dart analyzer. See https://github.com/dart-lang/sdk/issues/49054

**Comment by scheglov** [comment] 2022-05-20 17:23
What did you expect to see here for `colo` typed?
Do you have a named parameter named `color`? Or `colorFoo`?
Something else?

**Comment by bhanuka96** [comment] 2022-05-22 14:51
@scheglov Previously, it showed 'textColor' when typing 'color'. Now I have to type the exact word to get the suggestions list

**Comment by Anfet** [comment] 2022-05-23 09:33
Upping.

Right now made a stateful widget.
Typing `disp` does not  yield a `dispose` methond suggestion


in Studio logbar is being displayed
```Class '_AppVideoPlayerState' can't define field 'dispose' and have method 'State.dispose' with the same name. Expected to find ';'. Variables must be declared using the keywords 'const', 'final', 'var' or a type name. ```

And there are many more such issues, when code suggestion ignores overridable methods;

**Comment by stevemessick** [comment] 2022-05-23 17:41
This is fixed in https://dart-review.googlesource.com/c/sdk/+/245623, but not released yet.

**Comment by helin24** [comment] 2022-05-23 22:12
Closing as duplicate of https://github.com/flutter/flutter-intellij/issues/6176

**Closed by helin24** 2022-05-23 22:12 UTC

**Comment by stevemessick** [comment] 2022-07-13 23:34
The new Flutter 3.0.5 has the fix for this problem.
