### ISSUE TITLE
Setting Flutter SDK path for default project does not set properly

### ISSUE THREAD

**Issue by marcusljx** [flutter/flutter-intellij#1018] opened 2017-05-14 14:33 UTC
## Steps to Reproduce
1. Open IntelliJ IDE (with Flutter + Dart plugins already installed)
1. Close all existing projects (ie. you should only see IntelliJ project management window, with `Create New Project`, etc.)
1. Click Configure > Settings > Languages & Frameworks > Flutter
1. Input/Browse for the Flutter SDK Path
1. Click `Apply` or `OK`

### Expected
Path should remain in Flutter SDK path text box

### Actual
Path disappears from Flutter SDK path text box

## Version info
```
[✓] Flutter (on Linux, channel alpha)
    • Flutter at /home/marcusljx/REPO/flutter
    • Framework revision dc4ca8db83 (3 days ago), 2017-05-11 15:33:29 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /home/marcusljx/Android/Sdk
    • Platform android-25, build-tools 25.0.0
    • Java binary at: /home/marcusljx/.local/share/umake/android/android-studio/jre/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/marcusljx/.local/share/umake/android/android-studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Ultimate Edition (version 2016.2)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[-] WebStorm (version 2016.3)
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.1

[-] WebStorm (version 2017.1)
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] Connected devices
    • None
```

**Comment by pq** [comment] 2017-05-15 19:48
Repro'ed on that mac.  Thanks for the report!

**Comment by alexander-doroshko** [comment] 2017-05-15 20:03
If you decide not to show the Flutter page for the template project at all, adding `nonDefaultProject="true"` to the plugin.xml will do the trick.

**Comment by pq** [comment] 2017-05-15 20:16
Thanks @alexander-doroshko .  I think that's exactly right.

**Comment by skybrian** [comment] 2017-05-16 01:16
I agree that we don't need this setting. The combo box for Flutter SDK will soon default to the most recent one you used (fixed in #1006, not released yet).

**Closed** 2017-05-16 04:06 UTC
Labels: bug, ⌘‬ platform-mac

**Comment by strootaay** [comment] 2017-08-17 18:04
Same issue with me. Installed Flutter and IntelliJ IDEA Version 2017.2.2 on Windows 7 64-Bit, today. Installed the Flutter and Dart plugins. However, Flutter is not listed under Languages and Frameworks, nor is Dart. Unable to specify the Flutter SDK path as advised in the Flutter guidelines. Any help would be appreciated.

**Comment by devoncarew** [comment] 2017-08-17 18:09
> nor is Dart

That seems like the underlying issue - without that the Flutter plugin can't run. I would open the Plugins preference, and see if there's any issue listed with the Dart plugin. You could also check the IntelliJ log file (available from the help menu) for issues.

**Comment by strootaay** [comment] 2017-08-18 02:37
Hi Devon,

Both Flutter and Dart plugins are installed.

Log says this:

[   1243]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins:
Dart (172.3757.55), Flutter (16.0)
2017-08-17 23:12:01,128

No visible error for the Flutter/Dart plugin. Restarts didn't help.


On 17-Aug-2017 11:39 pm, "Devon Carew" <notifications@github.com> wrote:

nor is Dart

That seems like the underlying issue - without that the Flutter plugin
can't run. I would open the Plugins preference, and see if there's any
issue listed with the Dart plugin. You could also check the IntelliJ log
file (available from the help menu) for issues.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/flutter/flutter-intellij/issues/1018#issuecomment-323150900>,
or mute the thread

**Comment by rmirabelle** [comment] 2017-10-08 11:16
I'm experiencing this issue as well.  WebStorm 2017.2 is failing to store the Flutter SDK Path and therefore creating a new Flutter project simply fails miserably (by creating the selected directory, but doing nothing else). Any word on a fix?

**Comment by devoncarew** [comment] 2017-10-11 20:14
@rmirabelle, I think this is the same issues as https://github.com/flutter/flutter-intellij/issues/1384, which we're looking at now.

In the meantime, you can create the project from the command line (flutter create) and open it in WebStorm, or use something like IntelliJ Community Edition. Thanks!

**Comment by calimbadevs** [comment] 2018-10-01 16:50
Is there any fix to this yet? I'm having a similar issue: Whenever I pull a flutter-project from git Android Studio tells me that my "Dart SDK is not configured". Then I have to go to my preferences and reset the Flutter SDK Path. But for some time now , after pressing "apply", the path just disappears and i can't go on. 
Any help would be really appreciated! This is on Mac, of course, on Windows it works just fine.

**Comment by suyxx** [comment] 2018-12-07 05:50
open local.properties in android folder and see if it is location right sdk or not

**Comment by mrinvicto** [comment] 2019-02-14 09:23
The issue is pretty common. Please refer to [LINK](https://ladwhocodes.blogspot.com/2019/02/fix-flutter-sdk-not-found-in-specified-location.html) to solve this issue.

**Comment by jack773** [comment] 2020-06-02 15:53
**Hi, this not helpful to me as I am on Windows and I am using Android Studio, could you please give an explanation for my needs?**

**Comment by yulkin2002** [comment] 2020-08-05 14:20
File -> Invalidate caches and restart fixed it for me
