### ISSUE TITLE
Debugger doesn't open the correct source file when stopping on a breakpoint

### ISSUE THREAD

**Issue by kaqqao** [flutter/flutter-intellij#7458] opened 2024-05-27 11:24 UTC
## Steps to Reproduce

1. Add a breakpoint to any Dart source file
2. Start the app in debug mode and hit the breakpoint

**Expected result:** When the debugger stops at a breakpoint, the corresponding source file is opened.

**Actual result:** A strange read-only copy of the file opens instead. This copy can not be interacted with at all: the text can not be edited, elements can not be Cmd+clicked, breakpoints can not be added etc. Only **started happening after upgrading** to Jellyfish.

## Version info

Flutter doctor:

```
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale en-NL)
    • Flutter version 3.22.1 on channel stable at /Users/kaqqao/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (5 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/kaqqao/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/kaqqao/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2023.3)
    • Android Studio at /Users/kaqqao/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.2)
    • IntelliJ at /Users/kaqqao/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554         • android-arm64 • Android 14 (API 34) (emulator)
    • macOS (desktop)                 • macos                 • darwin-arm64  • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin        • macOS 14.5 23F79 darwin-arm64

[✓] Network resources
    • All expected network resources are available.
```

General:

```
Build: AI-233.14808.21.2331.11842104, 202405150249

AI-233.14808.21.2331.11842104, JRE 17.0.10+0-17.0.10b1087.21-11572160x64 JetBrains s.r.o., OS Mac OS X(aarch64) v14.5, screens 3456.0x2234.0; Retina

AS: Jellyfish | 2023.3.1 Patch 1
Kotlin plugin: 233.14808.21.2331.11842104-AS
Android Gradle Plugin: (plugin information not found)
Gradle: (gradle version information not found)
Gradle JDK: JetBrains Runtime version 17.0.10
NDK: from local.properties: (not specified), latest from SDK: (not found)
CMake: from local.properties: (not specified), latest from SDK: (not found), from PATH: (not found)
```

**Comment by alexander-doroshko** [comment] 2024-05-27 11:43
Duplicate of #7449. See the workaround there (the first comment).

**Closed** 2024-05-28 09:24 UTC
