### ISSUE TITLE
At least one platform must be selected

### ISSUE THREAD

**Issue by kwabynah** [flutter/flutter-intellij#5249] opened 2021-02-08 11:13 UTC
New to flutter and I keep getting this pop-up anytime I launch the intellij. Any fixes ?
![issue](https://user-images.githubusercontent.com/73634146/107212034-47ac0e80-69fe-11eb-93b7-febdb7b7b5c8.JPG)
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by devoncarew** [comment] 2021-02-08 16:18
Thanks for the report! I believe this will be addressed by https://github.com/flutter/flutter-intellij/pull/5246; cc @stevemessick .

**Comment by devoncarew** [comment] 2021-02-08 16:20
Dupe of https://github.com/flutter/flutter-intellij/issues/5245.

**Closed by devoncarew** 2021-02-08 16:20 UTC
