### ISSUE TITLE
No 'Flutter' menu option on android module

### ISSUE THREAD

**Issue by niamh-power** [flutter/flutter-intellij#3873] opened 2019-03-02 23:13 UTC
## Steps to Reproduce

This is an issue in both Android Studio and IntelliJ. I've tried previous versions of both and still have the same issue.

Basically I'm wanting to do the Android X migration for our Flutter app in order to use the latest plugins, and I was having the issues detailed here https://stackoverflow.com/questions/54395491/unable-to-migrate-to-androidx/54618207 I then go to open just the android module in Android Studio rather than the whole project, and find that the `Flutter` option when right clicking is greyed out. To note when I do the same on the root project folder or the ios module, I get the option `Open iOS module in Xcode` under the non-greyed out Flutter menu item.

<img width="581" alt="screenshot 2019-03-02 at 20 51 31" src="https://user-images.githubusercontent.com/17346045/53688778-f474b000-3d40-11e9-9135-a20ef8e1b5c4.png">

<img width="689" alt="screenshot 2019-03-02 at 09 38 15" src="https://user-images.githubusercontent.com/17346045/53688781-fa6a9100-3d40-11e9-95a7-58862329bd14.png">

## Logs

flutter doctor output:

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14 18A391, locale en-GB)
    • Flutter version 1.2.1 at /Users/niamhpower/development/flutter
    • Framework revision 8661d8aecd (2 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/niamhpower/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/niamhpower/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 3.4 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b22)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 10.2, Build version 10P99q
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0.beta.2

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.4 Preview.app/Contents
    • Flutter plugin version 33.3.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b22)

[✓] IntelliJ IDEA Community Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5215

[!] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

**Comment by PiN73** [comment] 2019-09-14 16:17
Updating Android Studio to latest version seems solve the problem

**Comment by PStoner3** [comment] 2019-09-20 14:40
Updated to Android Studio 3.5 Build number 191.5791312 Build date 8/8/2019. The problem still persists. The work-around stated above worked once. The flutter menu was enabled after I clicked on it, though the issue returned

**Comment by Eluny** [comment] 2019-09-23 11:28
![image](https://user-images.githubusercontent.com/8575422/65422139-39287b80-de38-11e9-96da-07355e552029.png)
![image](https://user-images.githubusercontent.com/8575422/65422151-42194d00-de38-11e9-8272-337473e46d60.png)

**Comment by furkanvatandas** [comment] 2019-09-24 07:40
I have the same issue. Flutter button is still disabled.

**Comment by dhimant1990** [comment] 2019-09-27 13:50
I have the same issue with Android Studio 3.5

**Comment by dhimant1990** [comment] 2019-09-27 13:52
I have the same issue with Android Studio 3.5

![Screenshot 2019-09-27 at 7 17 43 PM](https://user-images.githubusercontent.com/12906391/65774522-080fba00-e15c-11e9-9b5f-2110173bf4e6.png)

**Comment by Sheharyar566** [comment] 2019-09-27 18:00
I recently downgraded my android studio from 3.5 to 3.4.1, and the issue is still there; but the dart and flutter plugins are the of latest version. So, I think it has to do something with the plugins themselves.

**Comment by devoncarew** [comment] 2019-09-30 05:39
@stevemessick - is this something that will be addressed by https://github.com/flutter/flutter-intellij/pull/3909?

**Closed as completed** 2019-10-01 14:56 UTC

**Comment by rockingdice** [comment] 2019-10-27 04:13
@devoncarew 
I think I found the issue - it's quite simple, please check my answer at SO:
https://stackoverflow.com/a/58576562/9545222

**Comment by BaranMichal25** [comment] 2019-12-03 09:07
> I think I found the issue - it's quite simple, please check my answer at SO:
https://stackoverflow.com/a/58576562/9545222

It worked for me, but the `.iml` file must end up with `android`, so eg. "your_app_name_android.iml"

**Comment by rockingdice** [comment] 2019-12-03 21:49
@BaranMichal25 Yes, it's the point.

**Comment by Kuan-Wei** [comment] 2019-12-06 02:11
Try this 

got **File** -> **Open Recent** project and select your flutter project.

**Comment by Drkjr92** [comment] 2020-01-16 14:55
> I tried something that worked for me:
> got **File -> open project** and select the android sub folder of your flutter project.
> 
> Your project will oad and you will have a pop up that tells you to update the Gradle plugin, click on **Update**.
> 
> In Android Studio click on the **Tools -> SDK Manager -> SDK Tools** menu and verify that you have selected the **Google Play Services option**. In case the box is empty, they click on it and then install it.
> 
> Go for the android folder then the app folder inside it and open the **gradle.build** file, search for the property **compileSdkVersion** and change the value to **28**.
> 
> Open the **gradle.properties** file and add the following lines:
> **android.useAndroidX=true android.enableJetifier=true**
> 
> Then in the file tree on the left panel, at the top change the Android mode by Project, right click on the android folder and select the **Migrate to AndroidX** option under **Refactor**. A window appears to inform you that it will make a backup if we want, then click the **Migrate** button.
> 
> Execute **flutter clean** after it.
> 
> It worked for me I hope it will for you !

It Worked! Thank you!

**Comment by phyoeieibo2016** [comment] 2020-02-20 08:15
when I create the project, then i face this issue
[image1.docx](https://github.com/flutter/flutter-intellij/files/4229543/image1.docx)

**Comment by aswins24** [comment] 2020-05-01 06:18
I had the same issue, found a solution that worked for me. Pasting the link here.
[https://stackoverflow.com/questions/54364690/flutter-open-android-module-in-android-studio-is-disabled](https://stackoverflow.com/questions/54364690/flutter-open-android-module-in-android-studio-is-disabled)

**Comment by heqingbao** [comment] 2020-07-23 03:19
Because you lost the `xxx_android.iml` file in android directory, it cannot be recognized as an android project.
So you only need to copy a `xxx_android.iml` file from other projects to the android directory.
Note, replace `xxx` with your project name

**Comment by AshrafLP** [comment] 2020-07-26 09:39
> I solved it. What I did is deleted the modules from my project and specify them again:
> 
> **1.- File >> Project Structure...**
> ![image](https://user-images.githubusercontent.com/11686712/56867514-944e6300-69ab-11e9-8b94-1f17eec9db20.png)
> 
> **2.- Delete all the modules**
> Take care here, check all the set-ups before delete them all.
> ![image](https://user-images.githubusercontent.com/11686712/56867538-ebecce80-69ab-11e9-9347-33e148090e4e.png)
> 
> **3.- Create a Flutter "New Module", in the same project root**
> Click the "+" symbol, and in the next screen pick up "Flutter" >> "Next" button.
> ![image](https://user-images.githubusercontent.com/11686712/56867587-6ddcf780-69ac-11e9-88a5-17a6d8705c45.png)
> 
> **4.- Choose the project root**
> Don't change the "module name", just target the content root to your project root, and check that all it's fine.
> ![image](https://user-images.githubusercontent.com/11686712/56867648-3753ac80-69ad-11e9-86b6-64efb9ab8a8e.png)
> 
> **5.- It's done**
> Check if the "Flutter" option is enabled now. Don't forget to import the **Android module**.
> ![image](https://user-images.githubusercontent.com/11686712/56867627-dd52e700-69ac-11e9-8e64-8ce44a696c7a.png)

it works for me thank you

**Comment by AshrafLP** [comment] 2020-07-26 09:40
it works for me thank you

**Comment by aldk98** [comment] 2020-08-18 09:59
Apologize for posting another comment on closed issue, but since no one mentioned it, running the command below may help

`flutter create .`

Take note of the flutter SDK version though, different versions might produce different results.

also works when project name is changed in pubspec.yaml, directory change, etc.
In fact, running the command can help other missing file related issue as it (re)creates all necessary file for flutter to work.

**Comment by andreasrothballer** [comment] 2020-09-07 13:33
**This worked for me:**

Go to the Android-Studio Terminal

Then type:

flutter clean
flutter upgrade
flutter pub get
fluter create . <- Don't forget the space between the "e" and the "."

After these steps you will see the flutter register on the top right side.

Then move to android->tasks->android->signingReport <-double tap on it.

Now at the Bottom you will find the SHA1 Key.

**Comment by feel2174** [comment] 2020-11-03 08:23
https://stackoverflow.com/questions/54364690/flutter-open-android-module-in-android-studio-is-disabled


Because you lost the xxx_android.iml file in android directory, it cannot be recognized as an android project.

So you only need to copy a xxx_android.iml file from other projects to the android directory.

Note, replace xxx with your project name

**Comment by LiuJQ** [comment] 2020-12-22 06:59
> **This worked for me:**
> 
> Go to the Android-Studio Terminal
> 
> Then type:
> 
> flutter clean
> flutter upgrade
> flutter pub get
> fluter create . <- Don't forget the space between the "e" and the "."
> 
> After these steps the Flutter Symbole is available.
> 
> Then move to it and click "Open for editing in Android Studios".
> 
> You will see the flutter register on the top right side.
> 
> Then go to it and move to android->tasks->android->signingReport <-double tap on it.
> 
> Now at the Bottom you will find the SHA1 Key.

Work like a charm !

**Comment by fernando-s97** [comment] 2021-05-20 17:16
Just delete the <your-project-name>.iml and the .idea folder inside your project root folder.

**Comment by tandacedric** [comment] 2021-11-20 21:48
Simply create in your Android module folder the file "yourFlutterProjectName_android.iml" (Even if the content of the file is empty, there is no problem). The option will appear immediately

**Comment by alejorom** [comment] 2022-02-07 19:18
> **This worked for me:**
> 
> Go to the Android-Studio Terminal
> 
> Then type:
> 
> flutter clean flutter upgrade flutter pub get fluter create . <- Don't forget the space between the "e" and the "."
> 
> After these steps the Flutter Symbole is available.
> 
> Then move to it and click "Open for editing in Android Studios".
> 
> You will see the flutter register on the top right side.
> 
> Then go to it and move to android->tasks->android->signingReport <-double tap on it.
> 
> Now at the Bottom you will find the SHA1 Key.

2022:  with same problem.... but this solution works 1A

**Comment by alejorom** [comment] 2022-02-07 19:20
> Simply create in your Android module folder the file "yourFlutterProjectName_android.iml" (Even if the content of the file is empty, there is no problem). The option will appear immediately

2022: still the same problem but this solution works 1A.

**Comment by Kartmax13** [comment] 2023-07-30 21:58
> **This worked for me:**
> 
> Go to the Android-Studio Terminal
> 
> Then type:
> 
> flutter clean flutter upgrade flutter pub get flutter create . <- Don't forget the space between the "e" and the "."
> 
> After these steps the Flutter Symbole is available.
> 
> Then move to it and click "Open for editing in Android Studios".
> 
> You will see the flutter register on the top right side.
> 
> Click on it and move to android->tasks->android->signingReport <-double tap on it.
> 
> Now at the Bottom you will find the SHA1 Key.

2023 update -> This worked for me at immediately. Thanks!

**Comment by Zhuinden** [comment] 2024-05-27 08:04
`flutter create .` then even a `git reset --hard HEAD` fixed the menu option.
