### ISSUE TITLE
com.intellij.diagnostic.PluginException about ActionUpdateThread.OLD_EDT

### ISSUE THREAD

**Issue by wxd79** [flutter/flutter-intellij#7388] opened 2024-04-25 03:57 UTC
## What happened

I normally use Flutter for project development.
Intellij reports errors frequently. It happens every day. You can ignore the exceptions and continue to use it usually, but once it caused the whole Intellij to crash.

## Version information

IntelliJ IDEA `2024.1` • Flutter plugin `io.flutter 79.0.3` • Dart plugin `241.15845`

Flutter 3.19.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 300451adae (4 weeks ago) • 2024-03-27 21:54:07 -0500
Engine • revision e76c956498
Tools • Dart 3.3.3 • DevTools 2.31.1

## Exception

null

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.flutter.actions.OpenSimulatorAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.flutter]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**Comment by jwren** [comment] 2024-05-14 19:56
Duplicate of https://github.com/flutter/flutter-intellij/issues/7330

**Closed by jwren** 2024-05-14 19:56 UTC
