### ISSUE TITLE
No Android Tools like Logcat or Device File Explorer

### ISSUE THREAD

**Issue by Jaykocha** [flutter/flutter-intellij#4994] opened 2020-10-23 16:50 UTC
Hello I have a problem which occured in Android Studio 3.6.1 and now still persists with 4.1!

## Steps to Reproduce

I created a flutter project on a different machine (my laptop) and now on my PC at home I cannot access the Android Tools like 'Device File Explorer' or 'Logcat'.

Now since 4.1 it shows me that Dart and Flutter Plugin are not installed, even though they are! The Flutter app runs normally!

## Version info
C:\Users\janne\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.1139], locale en-US)
    • Flutter version 1.17.5 at C:\Users\janne\flutter
    • Framework revision 8af6b2f038 (4 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\janne\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\janne\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.43.1)
    • VS Code at C:\Users\janne\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • SM G390F • 4200cc96d22d65d3 • android-arm • Android 9 (API 28)

! Doctor found issues in 3 categories.

**Comment by helin24** [comment] 2020-10-26 17:08
Those tools aren't surfaced currently but we may be able to add them in the future.

For the Dart and Flutter plugin installations not showing up from `flutter doctor`, you can try some of the notes here: https://github.com/flutter/flutter/issues/67986. This isn't related to the tools missing, though.

**Comment by stevemessick** [comment] 2020-10-26 17:24
Android Studio has four facet-dependent tools:
- Build Variants
- Device File Explorer
- Device Manager
- Logcat

These are configured as `facet.toolWindow` extension points in android-plugin.xml.

It might be possible to support some of them for Flutter projects. The issue is that we don't even have a facet in Flutter projects, so it won't be straightforward. And for the device file explorer we'd have to be careful it was only enabled for Android devices.

**Comment by tremp-m** [comment] 2021-06-07 16:40
@stevemessick, thx for direct.
And i have one questions (clarifications). 
Because in old projects such problem absent (there is device explorer present) - can i make some changes in files manually for turn on DE?

**Comment by stevemessick** [comment] 2021-06-07 23:26
@tremp-m I don't recall ever seeing the Device File Explorer in a Flutter project. However, you could make a sample Android project and open it from there.

**Comment by tremp-m** [comment] 2021-06-08 18:32
Of course, I could be wrong, but I don't remember doing something special in order for DE to appear in the project a year ago ...
Well, OK.
Now I have found such a solution
![image](https://user-images.githubusercontent.com/48671789/121238522-3dfdbf00-c8a9-11eb-92e9-ae74019ebc61.png)

**Comment by tremp-m** [comment] 2021-08-12 11:09
on Arctic Fox does not work any more (

**Comment by tremp-m** [comment] 2021-08-20 13:29
on Arctic fox 2020.3.1 patch 1 work again

**Comment by stevemessick** [comment] 2021-09-03 18:53
This has different symptoms but the same root cause as #5464.

**Comment by bukunmialuko** [comment] 2021-09-20 09:13
> Of course, I could be wrong, but I don't remember doing something special in order for DE to appear in the project a year ago ...
> Well, OK.
> Now I found such solution
> ![image](https://user-images.githubusercontent.com/48671789/121238522-3dfdbf00-c8a9-11eb-92e9-ae74019ebc61.png)



I invalidated the cache and restarted the IDE.

**Comment by stevemessick** [comment] 2021-10-04 16:33
Closing, since this is caused by the same problem as #5464, which is actually requires a change to the Flutter SDK.

**Closed by stevemessick** 2021-10-04 16:33 UTC
Labels: enhancement
