### ISSUE TITLE
App hangs on unhandled exception like it is in debug mode

### ISSUE THREAD

**Issue by JFixby** [flutter/flutter-intellij#1271] opened 2017-08-08 17:29 UTC
Hello, can you please check this one: https://github.com/dart-lang/sdk/issues/30369

Thank you.

**Comment by devoncarew** [comment] 2017-08-08 17:39
Thanks for the remote! I think this is a dupe of https://github.com/flutter/flutter-intellij/issues/1164.

**Closed by devoncarew** 2017-08-08 17:39 UTC
