### ISSUE TITLE
Hot reload on Save doesn't work

### ISSUE THREAD

**Issue by te8uekm12** [flutter/flutter-intellij#7040] opened 2023-10-30 10:26 UTC
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Hot reload on Save doesn't work 

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

IDE
Android Studio Giraffe | 2022.3.1 Patch 2
Build #AI-223.8836.35.2231.10811636, built on September 14, 2023
Runtime version: 17.0.6+0-b2043.56-10027231 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 16
Registry:
    external.system.auto.import.disabled=true
    debugger.watches.in.variables=false
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    Batch Scripts Support (1.0.13)
    Dart (223.8977)
    com.tao.getx (3.3.2)
    pl.pszklarska.pubversionchecker (1.3.5)
    io.flutter (76.1.2)

Flutter plugin: 76.1.2
Dart plugin: 223.8977

**Comment by friedScotch** [comment] 2023-10-30 11:05
I was wondering the same till I found this issue. I manually downgraded the version for now

**Comment by petodavid** [comment] 2023-10-30 20:19
Same issue here

**Comment by andrefedev** [comment] 2023-10-31 07:19
For God's sake, I spent two hours trying to see if it was an Android Studio problem. But then apparently I updated the Flutter plugin and it didn't work anymore.

**Comment by stefangaller** [comment] 2023-10-31 07:53
https://github.com/flutter/flutter-intellij/issues/6996

**Comment by MariuszMilka** [comment] 2023-11-01 12:16
Same here. But to clarify:

1. Both save all and hot reload work separately.
2. Their keyboard shortcuts ctrs+s and ctrl + \ also work.
3.  What does not work is the option "Perform hot reload on save". It just does not perform hot reload atuomatically, so I have to do it manually.

**Comment by billliyu** [comment] 2023-11-01 14:30
Same issue, why has it taken so long to fix the problem

**Comment by Sahilbhayani** [comment] 2023-11-02 14:03
same issuse, Hot reload is not working in a specific file. It only working in main.dart file.

**Comment by Sahilbhayani** [comment] 2023-11-06 13:07
It spend me several hours to figure out the reason, so I hope this would help to save your time

Downloading the 76.0.x or earlier zip file from this link
https://plugins.jetbrains.com/plugin/9212-flutter/versions/stable

And install the plugin manually from file, which will make the hot reload works again

for Android studio : 
![Screenshot from 2023-11-06 18-34-10](https://github.com/flutter/flutter-intellij/assets/77524691/d26806aa-6108-466c-b69c-550823247484)

**Comment by reidbaker** [comment] 2023-11-08 20:04
This looks related to https://github.com/flutter/flutter-intellij/issues/6996 which just had someone confirm that the latest version was fixed for them. Can you update and try again?

**Comment by jwren** [comment] 2023-11-08 21:56
This is duplicate, closing this issue out. If there is still a regression for some platform version, open a new issue and tag me to escalate.

**Closed by jwren** 2023-11-08 21:56 UTC
