### ISSUE TITLE
Flutter Plugin Exception

### ISSUE THREAD

**Issue by kevindmoore** [flutter/flutter-intellij#7500] opened 2024-06-08 15:58 UTC
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_
While editing the Android portion of a Flutter plugin that I am building, I am having lots of problems. I've filed a bug with the Android Studio team but there is also an exception with the Flutter plugin.
I've tried this on AS JellyFish and Koala.

## Version information

Android Studio `Jellyfish | 2023.3.1 Patch 1` • Flutter plugin `io.flutter 80.0.1` • Dart plugin `233.15271`

No Flutter sdk configured.

## Exception

null

```
com.intellij.diagnostic.PluginException: Cannot invoke "com.intellij.openapi.actionSystem.AnAction.getTemplatePresentation()" because "this.myAction" is null [Plugin: io.flutter]
        at com.intellij.ui.EditorNotificationsImpl$updateEditors$job$1.invokeSuspend(EditorNotificationsImpl.kt:251)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.actionSystem.AnAction.getTemplatePresentation()" because "this.myAction" is null
        at io.flutter.editor.NativeEditorNotificationProvider$NativeEditorActionsPanel.<init>(NativeEditorNotificationProvider.java:123)
        at io.flutter.editor.NativeEditorNotificationProvider.createPanelForAction(NativeEditorNotificationProvider.java:63)
        at io.flutter.editor.NativeEditorNotificationProvider.createPanelForFile(NativeEditorNotificationProvider.java:56)
        at io.flutter.editor.NativeEditorNotificationProvider.createNotificationPanel(NativeEditorNotificationProvider.java:49)
        at io.flutter.editor.NativeEditorNotificationProvider.createNotificationPanel(NativeEditorNotificationProvider.java:25)
        at com.intellij.ui.EditorNotifications$Provider.lambda$collectNotificationData$0(EditorNotifications.java:73)
        at com.intellij.ui.EditorNotificationsImpl$updateEditors$job$1$2.invokeSuspend(EditorNotificationsImpl.kt:243)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:194)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
        at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
        at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
        at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
        at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1436)
        at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
        at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
        at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
        at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
        at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
        at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
        at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
        at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
        at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```
Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.1.1 23B81 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] Android Studio (version 2023.3)
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.2)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.

**Comment by bcspain** [comment] 2024-06-10 02:15
Downgrading  Android Studio  to  Iguana Patch 1 is a temporary fix that worked for me.

**Comment by Code-Remote** [comment] 2024-06-12 10:53
The same issue but older is mentioned here, https://github.com/flutter/flutter-intellij/issues/7488.

Maybe it's a good idea to close this issue and up-vote the mentioned issue.

Btw, i've tried downgrading to Iguana and even hedge hedgehog but also don't work

**Comment by jwren** [comment] 2024-06-17 20:50
Duplicate of https://github.com/flutter/flutter-intellij/issues/7488

**Closed by jwren** 2024-06-17 20:50 UTC
