### ISSUE TITLE
"Hot reload on save" works only occasionally

### ISSUE THREAD

**Issue by Gieted** [flutter/flutter-intellij#6510] opened 2022-12-26 15:08 UTC
## Steps to Reproduce
1. Use IntelliJ Idea 2022.3.1
2. Make sure hot reload on save and autosave is enabled in settings
3. Create a new app using project wizard
4. Change something in code
5. Switch window to trigger autosave
6. Repeat steps 4 and 5 for some time
7. See hot reload no longer triggering automatically

The hot reload will still work as expected when you press a lighting icon, it just won't happen automatically on save.

Stacktrace from IntelliJ logs:
```
java.lang.Throwable: Template presentations must not be used directly
	at com.intellij.openapi.actionSystem.Presentation.assertNotTemplatePresentation(Presentation.java:465)
	at com.intellij.openapi.actionSystem.Presentation.setEnabled(Presentation.java:438)
	at io.flutter.actions.FlutterAppAction$1.stateChanged(FlutterAppAction.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:120)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:85)
	at jdk.proxy13/jdk.proxy13.$Proxy205.stateChanged(Unknown Source)
	at io.flutter.run.daemon.FlutterApp.transitionStartingHotReload(FlutterApp.java:426)
	at io.flutter.run.FlutterReloadManager.handleSaveAllNotification(FlutterReloadManager.java:235)
	at io.flutter.run.FlutterReloadManager$2.lambda$beforeAllDocumentsSaving$1(FlutterReloadManager.java:191)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:429)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

## Version info

```
[✓] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.22000.1335], locale pl-PL)
    • Flutter version 3.3.10 on channel stable at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (11 days ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33205.214
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at C:\Users\Gieted\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\223.8214.52
    • Flutter plugin version 71.2.6
    • Dart plugin version 223.8214.16

[✓] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.1335]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
```

**Comment by stevemessick** [comment] 2023-01-03 23:10
This needs to be investigated. I just wanted to quickly mention that I don't think the author of hot-reload-on-save imagined it being triggered by switching windows. It was intended to be triggered by saving the file (menu `File > Save` or keyboard short cut). For now, try using the keyboard short cut to save before switching windows.

**Comment by stevemessick** [comment] 2023-01-05 00:46
From looking at the code referenced in the stack trace (above) I think `FlutterAppAction` needs to be updated. It currently has a listener that changes its enablement whenever the listener's state changes. IntelliJ is now logging a warning that we should not do that. Instead, we should save the enablement state then set it during `update()`.

However, the warning doesn't stop the code from working, so I suspect it has nothing to do with the problem. I suspect the hot-reload-on-save is being triggered in such a way that it cannot get write-mode or some other situation that depends on the window state.

@Gieted This may seem obvious, but please tell me if there are any Dart analysis errors in your program when hot-reload-on-save stops working. If there are, then it is working as intended (but I suspect that's not the problem).

**Comment by Gieted** [comment] 2023-01-05 01:28
Hi,
Thanks for your response.

No, I don't have any analysis errors. I'm having troubles finding any pattern for when the problems start/stops appearing, so far I've noticed:
- The on-save reload could work when making changes in a particular file, but not in the others.
- Sometimes on-save reload stops working for some exact file contents.
- Changing file contents to that, which cause on-save reload to stop working, also cause a noticeable lag in the syntax coloring (syntax is incorrectly colored for some seconds):
![obraz](https://user-images.githubusercontent.com/35242233/210679626-747146ee-3d54-4a8d-a8f1-1675e771ad4f.png)

-------------
> I don't think the author of hot-reload-on-save imagined it being triggered by switching windows

It shouldn't make much difference, because switching the window triggers an auto-save. This is a default setting most likely used by most of IntelliJ users

**Comment by stevemessick** [comment] 2023-01-05 16:14
Thanks for the response. That screen shot looks like a mess. If you'd like to help get that cleaned up then creating an issue in [dart-lang/sdk](https://github.com/dart-lang/sdk/issues) would be appropriate. It would be helpful to include that screen shot and the actual code (as text, so people can repro the problem).

> It shouldn't make much difference, because switching the window triggers an auto-save.

The difference is that switching windows causes a huge change in the state of the IDE. Certain window state is required to perform hot reload. I'll look into whether that is a real problem; it may be something else entirely.

**Comment by stevemessick** [comment] 2023-01-05 22:17
That syntax highlighting problem is probably unrelated to the Dart analyzer. I just found this issue, which looks very similar, and has already been fixed in theDart plugin:
https://youtrack.jetbrains.com/issue/WEB-56916/Dart-syntax-highlighting-may-become-incorrect-after-save.

**Closed** 2023-01-05 23:11 UTC
