### ISSUE TITLE
Installation freezes at "Unzipping Dart SDK" in android studio

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1961] opened 2018-03-21 03:39 UTC
_From @puttapravinkumar0 on March 13, 2018 16:17_

Recently I had installed flutter plugin in android studio. And when I went for new project, it asked me flutter sdk. I chosen "Install SDK". And it was freezes at ""Unzipping Dart SDK". I kept as it is for more than 3hrs, but was there is no any response.
Please can any one help me to continue....

![image](https://user-images.githubusercontent.com/25848532/37355093-2645be52-2709-11e8-99db-d04c98aa1d33.png)

_Copied from original issue: flutter/flutter#15485_

**Comment by devoncarew** [comment] 2018-03-21 03:39
_From @Hixie on March 13, 2018 23:35_

cc @devoncarew

**Comment by devoncarew** [comment] 2018-03-21 03:39
_From @hanzhida on March 21, 2018 2:57_

same problem. Seems many people met this, it's not a new one. I met this when run "flutter dector" in cmd, it just hung at Unzipping Dart SDK... forever.
I work on Windows

**Comment by devoncarew** [comment] 2018-03-21 03:40
@pq, can you look at what this step is doing that it might fail at? Is this after we've cloned? Is this message coming from flutter_tools?

**Comment by devoncarew** [comment] 2018-03-21 03:43
@hanzhida, re:

> Seems many people met this, it's not a new one

Do you have references to other issues? I'm wondering if they might have some additional details, like if we're hitting issues with a virus checker.

**Comment by hanzhida** [comment] 2018-03-21 06:05
https://github.com/flutter/flutter/issues/11698
Seems some people also met this. It's better if it showing more detailed information.

**Comment by pq** [comment] 2018-03-21 13:24
@devoncarew: 👍 Looking now.

@hanzhida : thanks for the report and the extra context!

**Comment by IkhlasMemon** [comment] 2018-03-22 05:27
I'm also facing the same issue and nothing is happening.

**Comment by hanzhida** [comment] 2018-03-22 06:29
Followed the instructions by c-born in [flutter/flutter#11698](https://github.com/flutter/flutter/issues/11698), , I solved this problem. Great!!

> I installed the latest 7Zip and added its directory (C:\Program Files\7-Zip) to my PATH
> I also installed the latest PowerShell from https://www.microsoft.com/en-us/download/details.aspx?id=54616


But, it showed another crash:(

E:\workspace\flutter\flutter>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[âˆš] Flutter (Channel master, v0.2.4-pre.64, on Microsoft Windows [Version 6.1.7601], locale zh-CN)

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: b4642fa3a13e651f)
Unhandled exception:
NoSuchMethodError: The getter 'isMacOS' was called on null.
Receiver: null
Tried calling: isMacOS
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      IOSDevices.supportsPlatform (package:flutter_tools/src/ios/devices.dart:34)
#2      DeviceManager._platformDiscoverers.<anonymous closure> (package:flutter_tools/src/device.dart:85)
#3      WhereIterator.moveNext (dart:_internal/iterable.dart:439)
#4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:90)
<asynchronous suspension>
#5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:560)
<asynchronous suspension>
#6      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:71)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:128)
<asynchronous suspension>
#8      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:237)
#9      AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#10     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#11     _rootRun (dart:async/zone.dart:1126)
#12     _CustomZone.run (dart:async/zone.dart:1023)
#13     runZoned (dart:async/zone.dart:1501)
#14     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#15     _doctorText (package:flutter_tools/runner.dart:237)
<asynchronous suspension>
#16     _createLocalCrashReport (package:flutter_tools/runner.dart:212)
<asynchronous suspension>
#17     _handleToolError (package:flutter_tools/runner.dart:167)
<asynchronous suspension>
#18     run.<anonymous closure> (package:flutter_tools/runner.dart:94)
<asynchronous suspension>
#19     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#20     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#21     _rootRun (dart:async/zone.dart:1126)
#22     _CustomZone.run (dart:async/zone.dart:1023)
#23     runZoned (dart:async/zone.dart:1501)
#24     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#25     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#26     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#27     main (file:///E:/workspace/flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

**Comment by pq** [comment] 2018-03-22 13:48
Thanks for all the follow-ups.  While the issue is coming up out of flutter_tools (and should be fixed there), I'm looking at our installation logic to see how we can harden it a little.

**Comment by pq** [comment] 2018-04-16 20:17
Closing in favor of tracking in https://github.com/flutter/flutter/issues/11698.

**Closed by pq** 2018-04-16 20:17 UTC
Labels: topic-getting-started, ❖ platform-windows
