### ISSUE TITLE
Show breadcrumbs for dart

### ISSUE THREAD

**Issue by jianzhongli** [flutter/flutter-intellij#4039] opened 2019-10-31 04:16 UTC
![image](https://user-images.githubusercontent.com/5278523/67918600-f183d500-fbd7-11e9-9330-c9e81e2e9898.png)

Dart codes in the flutter framework often come with multiple classes in the same file. Most of them have deep nesting structures, it would be really helpful if we can show breadcrumbs when browsing dart code.

**Comment by devoncarew** [comment] 2019-10-31 15:02
cc @jwren

**Comment by jwren** [comment] 2019-10-31 17:47
Closing out since this is a duplicate of https://github.com/flutter/flutter-intellij/issues/3576.

This is tracked in YouTrack as https://youtrack.jetbrains.com/issue/WEB-33823

**Closed by jwren** 2019-10-31 17:47 UTC
