### ISSUE TITLE
No usages found for enum despite being used

### ISSUE THREAD

**Issue by crtl** [flutter/flutter-intellij#4881] opened 2020-09-24 12:32 UTC
When using an enum the usage will not be reported when showing usage for type (CTRL + Click).

## Steps to Reproduce

1. `flutter create bug`
2. Create a simple enum in a sperate file `enum Test{First, Second, Third}`
3. Reference one of the enum values in `main.dart` like `print(Test.First)`
4. Showing usages for `Test` shows `No usages found`.

## Version info

```
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18363.1082], locale en-DE)
    • Flutter version 1.20.4 at D:\dev\flutter\sdk
    • Framework revision fba99f6cf9 (10 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
```

**Comment by pq** [comment] 2020-09-24 17:41
Thanks for the report!

I'm unable to reproduce on the Flutter dev channel.  Maybe this was fixed in a more recent Dart SDK?

@scheglov, @bwilkerson : does a fix here ring a bell?

**Comment by scheglov** [comment] 2020-09-24 18:05
Indeed, search for `Test` (not for `First`) does not produce any results.

**Comment by scheglov** [comment] 2020-09-24 18:20
https://dart-review.googlesource.com/c/sdk/+/164363

**Comment by pq** [comment] 2020-09-25 15:34
Thanks @scheglov!  Since this is an analysis issue and a fix is on the way, I'll close this out.  Thanks for the report @crtl !

**Closed by pq** 2020-09-25 15:34 UTC

**Comment by lzhuor** [comment] 2020-11-17 17:52
Hi @scheglov can we have a cherry pick of this for patch? or release it to stable? 

The stable channel v1.22.4 doesn't include this fix. Thank you!

cc: @pcsosinski

**Comment by scheglov** [comment] 2020-11-17 18:07
I'm not sure about releasing and stuff, I will let Patrick to decide.

**Comment by pcsosinski** [comment] 2020-11-17 18:34
@franklinyow for stable CP potential

**Comment by franklinyow** [comment] 2020-11-17 18:50
@devoncarew PTAL if it is worthy of a stable CP

**Comment by devoncarew** [comment] 2020-11-17 20:11
@lzhuor - thanks for the inquiry about a cherry pick. We're cautious about cherry-picks into our stable releases as they can themselves introduce instability. I think in this instance - while the behavior is incorrect - it doesn't rise to the level of a cherry pick. An example of something that might would be an issue that prevented all find references operations from working.
