### ISSUE TITLE
Flutter package template doesn't have example folder

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter-intellij#3131] opened 2019-01-26 14:58 UTC
When I choose new flutter project -> Flutter package, I getting a template for the package and tests, but it doesn't contain anything about an example app. From the description `Select package when creating a pure Dart component, like a new Widget` so if I'm creating a new widget, I would like to have an example app to at least test it during development. 
Might worth having a checkbox `generate example app` that will generate it for us if it's not by default

**Comment by terrylucas** [comment] 2019-01-28 14:13
Duplicate of #2975

I think a subclass widget would be a great idea I'll add it to the original bug.  Thanks.

**Closed by terrylucas** 2019-01-28 14:13 UTC
