### ISSUE TITLE
New line after break in switch statement doesn't return the caret to the right place

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter-intellij#698] opened 2017-02-01 15:57 UTC
Expected behaviour: After typing ```break;``` the only thing that can come next is a new case, so the caret should be indented to align with the previous case statement.

Current behaviour: The caret on new line returns to the same indentation as the break statement.

![screen shot 2017-02-01 at 16 55 46](https://cloud.githubusercontent.com/assets/2978182/22514369/5fc7dc36-e89f-11e6-9eca-469a8f9ccc3c.png)

**Comment by alexander-doroshko** [comment] 2017-02-01 16:17
Yes, statements like `break` and `return` are special in this context and could be handled specially.

@lukechurch Note that as soon as you type the next `case`, on `:` char the whole line will be reindented correctly:
![case](https://cloud.githubusercontent.com/assets/4499789/22515292/11fe868a-e8b3-11e6-8603-8b01e068297b.gif)

**Comment by mit-mit** [comment] 2017-02-08 17:38
Closing working as intended. From what we can see, this is indeed a bit weird but also seems like that is what most IDEs do.

**Closed by mit-mit** 2017-02-08 17:38 UTC
Labels: dart plugin, topic-editing
