### ISSUE TITLE
DevTools not loading properly

### ISSUE THREAD

**Issue by jamesrw94** [flutter/flutter-intellij#5564] opened 2021-06-10 17:28 UTC
## Steps to Reproduce

Using Android Studio, run flutter web app with target as Chrome.

I then attempt to launch DevTools via the button "Open Flutter DevTools" on the console of Android Studio. The Flutter inspector page fails to load (simply get the blue loading circle)
<img width="867" alt="Screenshot 2021-06-10 at 18 05 17" src="https://user-images.githubusercontent.com/52331558/121570037-5f7db880-ca19-11eb-85d2-411c5755bb27.png">

The debugger page does not show the entry point to my application (i.e. main.dart).
<img width="867" alt="Screenshot 2021-06-10 at 18 05 29" src="https://user-images.githubusercontent.com/52331558/121570096-6f959800-ca19-11eb-8725-49289d2a06ac.png">

 However, the widget tree is present in the Flutter Inspector within Android Studio (although only shows the tree and no frames).
<img width="388" alt="Screenshot 2021-06-10 at 18 05 59" src="https://user-images.githubusercontent.com/52331558/121570121-791f0000-ca19-11eb-8157-99fd1128f55d.png">

The same thing happens when manually launching DevTools from the command line.

I am on the Flutter channel beta.

I have also disabled "Enable embedding DevTools in the Flutter Inspector window".

## Version info

[✓] Flutter (Channel beta, 2.2.0, on macOS 11.0.1 20B50 darwin-x64, locale en-GB)
    • Flutter version 2.2.0 at /Users/jameswilson/development/flutter
    • Framework revision b22742018b (4 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jameswilson/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 57.0.3
    • Dart plugin version 203.8173

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77

• No issues found!

**Comment by kenzieschmoll** [comment] 2021-06-10 17:40
Looks like a duplicate of https://github.com/flutter/devtools/issues/3105#

**Comment by helin24** [comment] 2021-06-11 16:27
Closing as a duplicate

**Closed by helin24** 2021-06-11 16:27 UTC
