### ISSUE TITLE
The generated 'flutter create' template project isn't gradle based, and doesn't know how to resolve Java code in consumed native plugins

### ISSUE THREAD

**Issue by arieosdmin** [flutter/flutter-intellij#2089] opened 2018-04-16 06:51 UTC
Fresh installation on MAC/Windows (both same problem) of 
- GIT
- Flutter
- Android Studio
- Intelij Idea
- JAVA

All I do is add a new plugin, like firebase or webview or any other plugin and I get an error in .../android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java

[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.3 17D47, locale nl-IN)
    • Flutter version 0.2.8 at /Users/osdm/flutter
    • Framework revision b397406561 (13 days ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/osdm/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ Brew not installed; use this to install tools for iOS device development.
      Download brew at https://brew.sh/.

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 23.2.3
    • Dart plugin version 181.4445.29

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by pq** [comment] 2018-04-16 19:13
Do you have a module SDK setup for your project?  What errors are you seeing?

**Comment by arieosdmin** [comment] 2018-04-16 22:35
Yes I have set the flutter/dart sdk on this project. Basically I set up a fresh everything as described on flutter.io and created a new standard project. "Flutter Demo Home Page". All I change is adding a plugin (any) and I get this error:
https://user-images.githubusercontent.com/37406301/37550330-1a98dd0c-29d7-11e8-939d-a8bc1691e43c.png
(This is not my image, but I saw it in issue 1929)
I feel there is just a setting mistake that I have to change somewhere. The plugins are not being installed in the location it shows.

**Comment by stevemessick** [comment] 2018-04-17 16:13
@pq Nope, I had no problems when I was helping out with the code lab. Sorry, no time to investigate now.

**Comment by bowojori7** [comment] 2018-04-20 18:10
Hello, I have the same problem. @arieosdmin have you fixed yours?

**Comment by arieosdmin** [comment] 2018-04-20 23:11
It is a real problem that I don't understand as I am very new with flutter and app development. There is another thread that they gave a solution, maybe it helps you it did not help me.
https://github.com/flutter/flutter-intellij/issues/1929

The way I solved it is someone else who create a git for me and I imported that in Intelij IDEA. And I used that project to create my app. Then there is no problem with this plugin. Why? Don't have any idea.

**Comment by bowojori7** [comment] 2018-04-21 23:47
@arieosdmin  thank you. I tried to follow the instructions on the thread but intellij idea shows an error when i try the flutter -> Open Android module in Android Studio. Says it's unable to locate android studio. I have android studio though so i dunno what the problem is. Maybe theres a way to tell itellij idea where android studio is located?

**Comment by devoncarew** [comment] 2018-04-22 21:06
@arieosdmin :

> The way I solved it is someone else who create a git for me and I imported that in Intelij IDEA. And I used that project to create my app. Then there is no problem with this plugin. 

Can you share that project with us? You cam PM me at `devoncarew@google.com`; thanks!

**Comment by arieosdmin** [comment] 2018-04-22 22:59
https://github.com/fmatosqg/flutter_problem

**Comment by devoncarew** [comment] 2018-04-23 03:34
Thanks! Just to clarify:

- this is the working repo (the repo that was shared with you that doesn't have issues)
- it was shared ~like this? I note that it doesn't have any `.idea/` directory files committed (which they're normally not committed, but I would think that things like the `.idea/modules.xml` file would be useful in a full repro)

**Comment by bowojori7** [comment] 2018-04-29 22:00
So I played around a little with the project @arieosdmin shared.
Turns out You have to: 
- delete the android.iml file if you have it, only iml files you should be left with are projectname.iml and projectname_android.iml
- Open project structure in intellij (ctrl-alt-shift-s)
- Delete the Flutter for Android library from libraries
- If your project has two modules in the module tab: one with the "projectname" and one with the "projectname_android", delete the module with the android suffix.
- Try rebuilding your project, any errors that come up now should be very straightforward to fix .
- That should fix the problem. 

It fixed mine. Thanks for all the help

**Comment by stevemessick** [comment] 2018-11-16 18:33
There have been a lot of changes in the Android portion of a Flutter project. I can't reproduce any of the issues reported here with the current release. I'm closing this but feel free to re-open if the problem recurs.

**Closed by stevemessick** 2018-11-16 18:33 UTC
Labels: question, topic-getting-started
