### ISSUE TITLE
Syntax highlighting does not work nicely with icon package in Android Studio

### ISSUE THREAD

**Issue by cirediew** [flutter/flutter-intellij#6373] opened 2022-10-26 12:54 UTC
When using this package https://pub.dev/packages/material_design_icons_flutter the syntax highlighting stops working. I've made a video to show you what I mean.

After uncommenting the MdiIcon and commenting other widgets they do not change the highlighting to the comment syntax. When changing the MdiIcon to a comment it all seems to work again.

https://user-images.githubusercontent.com/9058616/198029216-818b2654-787f-45b5-97eb-50c17e941a64.mov

## Version info

```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.5.1 21G83 darwin-arm, locale en-NL)
    • Flutter version 3.3.4 on channel stable at /Users/user/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (3 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/user/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/user/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.8913347/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/user/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 11 Pro (mobile) • 00000000-0000-0000-8091-E3EE396D0000 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by stevemessick** [comment] 2022-10-27 22:21
This is either a problem in the Dart plugin or the Dart analysis server. Since it is triggered by an external package, I'd suspect the analyzer. That package has a huge number of icons! It is possible this is just a performance problem.

I suggest creating an issue in https://github.com/dart-lang/sdk/issues. If you can include a sample project that demonstrates the same behavior as in your video it would help. Link me the issue and I'll add a comment.

**Comment by asashour** [comment] 2022-11-03 18:12
Please close this, as a duplicate of https://github.com/dart-lang/sdk/issues/50328, which is closed.

**Comment by stevemessick** [comment] 2022-11-03 20:37
Thanks @asashour. I see the problem is caused by another plugin.

**Closed by stevemessick** 2022-11-03 20:37 UTC
Labels: waiting for customer response
