### ISSUE TITLE
After upgrading Flutter3, the code prompts are not smart anymore

### ISSUE THREAD

**Issue by ilgnefz** [flutter/flutter-intellij#6176] opened 2022-05-18 03:15 UTC
Flutter2.10.5
![2](https://user-images.githubusercontent.com/58471330/168949873-5e5f805b-86c5-4bc7-a3a4-846d7e34715a.gif)

Flutter3
![1](https://user-images.githubusercontent.com/58471330/168949913-281b51be-e9df-45df-9f98-2bb143272fb7.gif)

**Comment by Gridzzle** [comment] 2022-05-18 17:39
i'm having the same issue, its really annoying coz im used to code quicker before, now i have to write the whole syntax

**Comment by stevemessick** [comment] 2022-05-18 23:36
This is an issue with the Dart analyzer. See https://github.com/dart-lang/sdk/issues/49054

**Comment by stevemessick** [comment] 2022-05-23 17:42
This is fixed in https://dart-review.googlesource.com/c/sdk/+/245623, but not released yet.

**Comment by scheglov** [comment] 2022-05-23 23:35
There are a few regressions because of the new completion protocol.
1. The feature that Steve referenced is for completion in `import` directives: https://dart-review.googlesource.com/c/sdk/+/245623
2. The feature that you experience is suggesting static fields, to be fixed as https://dart-review.googlesource.com/c/sdk/+/229324
3. And there is also override on completion, which already landed into the master branch, and I filled a PR to cherry pick it into stable. https://github.com/dart-lang/sdk/issues/49086

**Closed** 2022-05-24 00:57 UTC

**Comment by stevemessick** [comment] 2022-07-13 23:34
The new Flutter 3.0.5 has the fix for this problem.
