### ISSUE TITLE
Flutter DevTools unavailable in new Flutter projects

### ISSUE THREAD

**Issue by ViktorVoloshko** [flutter/flutter-intellij#7875] opened 2024-12-20 19:53 UTC
## Steps to Reproduce
1) Create new Flutter project.
2) Open View > Tool Windows
3) Search for Flutter DevTools (no Flutter DevTools)
4) Switch to Dart project and to new Flutter project again
5) Search for Flutter DevTools (they should be available now)

![bug1](https://github.com/user-attachments/assets/43d11b63-c127-422e-a3e3-e827ec41c72e)
![bug2](https://github.com/user-attachments/assets/d16b6647-77d9-4c38-bb49-47be494545b9)

## Version info
Build: AI-242.23339.11.2421.12700392, 202411221916
AS: Ladybug | 2024.2.1 Patch 3
AI-242.23339.11.2421.12700392, JRE 21.0.3+-12282718-b509.11x64 JetBrains s.r.o., OS Windows 11(amd64) v10.0 , screens 1920x1080 (125%)
Android Gradle Plugin: (plugin information not found)
Gradle: (gradle version information not found)
Gradle JDK: Eclipse Temurin 21.0.5
NDK: from local.properties: (not specified), latest from SDK: (not found)
CMake: from local.properties: (not specified), latest from SDK: (not found), from PATH: (not found)

## Flutter Doctor
C:\Users\ViktorVoloshko\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 3.27.1, on Microsoft Windows [Version 10.0.26100.2605], locale en-001)
    • Flutter version 3.27.1 on channel stable at C:\Users\ViktorVoloshko\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (4 days ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\ViktorVoloshko\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Eclipse Adoptiu
m\jdk-21.0.5.11-hotspot\bin\java
    • Java version OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS)

    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.12.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.12.35527.113
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[√] VS Code (version 1.96.0)
    • VS Code at C:\Users\ViktorVoloshko\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.102.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.26100.2605]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 131.0.6778.110

[√] Network resources
    • All expected network resources are available.

• No issues found!
Process finished with exit code 0

I mistakenly reported issue to AS bugtracker first. there's zip with logs from IDE: https://issuetracker.google.com/382786779

**Comment by jwren** [comment] 2024-12-23 22:28
Marking this as a duplicate of https://github.com/flutter/flutter-intellij/issues/7430 and prioritizing.

**Closed by jwren** 2024-12-23 22:28 UTC
