### ISSUE TITLE
IllegalStateException: Cannot add two modules with the same name

### ISSUE THREAD

**Issue by ToH2002** [flutter/flutter-intellij#6019] opened 2022-03-04 22:57 UTC
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

--- Started AndroidStudio with an existing project. I've tried recreating the project from scratch using just the lib
directory and pubspec.yaml (plus android/build.gradle, android/app/build.gradle, and  android/app/src/main/AndroidManifest)

Keeps recreating this problem

## Version information

Android Studio `Bumblebee | 2021.1.1 Patch 2` • Flutter plugin `io.flutter 65.1.2` • Dart plugin `211.7808`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.IllegalStateException: Module name 'liveprompter_android' already exists. Trying to load module: D:/Users/Torsten/Studio Projects/LivePrompter 2/liveprompter/android/liveprompter_android.iml
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModifiableModuleModelBridgeImpl.loadModule(ModifiableModuleModelBridgeImpl.kt:156)
	at io.flutter.module.FlutterModuleBuilder.addAndroidModule(FlutterModuleBuilder.java:211)
	at io.flutter.FlutterInitializer.runActivity(FlutterInitializer.java:150)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.java:335)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:309)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivities$3(StartupManagerImpl.java:245)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:403)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:395)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:66)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:787)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:325)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:787)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by stevemessick** [comment] 2022-03-06 23:29
This problem was supposed to be fixed in 65.1, but that obviously did not work. I'm having trouble building a debuggable Android Studio today, so I'll have to get back to this when everyone gets back to work tomorrow (Monday). Sorry, I hoped to push a new point release today, but I need to make sure it works first.

**Comment by stevemessick** [comment] 2022-03-07 19:48
@ToH2002 @medst @sanyakuznezov @singhguru84 and anyone else seeing this error:

I cannot reproduce this problem. If possible, could you share your project with us? If not, could you take a screen shot from the `Tools > Project Structure...` dialog, similar to this:

<img width="346" alt="Screen Shot 2022-03-07 at 11 46 52 AM" src="https://user-images.githubusercontent.com/8518285/157106957-e731b4fb-ffcd-4991-b063-1dcdce5eb724.png">

Then add that image here?

**Comment by rayk** [comment] 2022-03-08 00:00
@stevemessick I am also getting this in intellij


## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2021.3.2` • Flutter plugin `io.flutter 65.1.4` • Dart plugin `213.5744.122`

Flutter 2.11.0-0.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision b101bfe32f (3 weeks ago) • 2022-02-16 07:36:54 -0800
Engine • revision e355993572
Tools • Dart 2.17.0 (build 2.17.0-69.2.beta) • DevTools 2.10.0-dev.1

## Exception

null

```
java.lang.IllegalStateException: Module name 'noldor_android' already exists. Trying to load module: /Users/rayk/Projects/noldrepo/apps/packages/noldor/android/noldor_android.iml
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModifiableModuleModelBridgeImpl.loadModule(ModifiableModuleModelBridgeImpl.kt:148)
	at io.flutter.module.FlutterModuleBuilder.addAndroidModule(FlutterModuleBuilder.java:211)
	at io.flutter.FlutterInitializer.runActivity(FlutterInitializer.java:150)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.kt:312)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:293)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration$default(StartupManagerImpl.kt:288)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$2.run(StartupManagerImpl.kt:256)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:395)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:387)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:66)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
<img width="1365" alt="Screen Shot 2022-03-08 at 10 59 25 am" src="https://user-images.githubusercontent.com/349890/157138712-bb6ee39e-7f9d-485d-b980-3502c3a7bc8a.png">

The project was created with via new project in intellij and here are the problems intellij detected
<img width="819" alt="Screen Shot 2022-03-08 at 10 59 58 am" src="https://user-images.githubusercontent.com/349890/157138837-d225ba3a-41d1-4921-bdbd-dd4045d94d19.png">

**Comment by stevemessick** [comment] 2022-03-08 00:45
Thanks for the additional details @rayk !

**Comment by ToH2002** [comment] 2022-03-08 09:47
Happy to share,

to avoid email clutter, here's a Dropbox link:
https://www.dropbox.com/s/lf3dgbjiproszg2/Test%20Project.zip?dl=0

Steps to reproduce:

  * Create new Flutter project - Title "Test Project", project folder
    "Test Project", module name "test_project"
  * Standard Flutter inital project is generated
  * Close Android Studio, re-start Android Studio
  * Error message is shown

Here's the requested screenshot:

Cheers,

Torsten


Am 07.03.2022 um 20:48 schrieb stevemessick:

**Comment by stevemessick** [comment] 2022-03-08 18:15
Thanks @ToH2002 for the detailed repro steps. That really helped.

**Closed** 2022-03-08 18:27 UTC
Labels: P0
