### ISSUE TITLE
compatibility error with build 232.*

### ISSUE THREAD

**Issue by HudsonAfonso** [flutter/flutter-intellij#7123] opened 2023-12-07 21:22 UTC
compatibility error with build 232.*

**Comment by wagner1343** [comment] 2023-12-07 22:02
Maybe duplicate of #7118

**Comment by jwren** [comment] 2023-12-13 21:09
Duplicate of https://github.com/flutter/flutter-intellij/issues/7115

**Closed by jwren** 2023-12-13 21:09 UTC
