### ISSUE TITLE
java.lang.Throwable: Error listening to ToolEvent stream: org.dartlang.vm.service.element.RPCError

### ISSUE THREAD

**Issue by simonecaf** [flutter/flutter-intellij#7102] opened 2023-12-02 17:57 UTC
On latest Intellij Idea on Sonoma 14.0, I got this error:

```
java.lang.Throwable: Error listening to ToolEvent stream: org.dartlang.vm.service.element.RPCError@63ed7be6
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at io.flutter.vmService.VmServiceWrapper$2.onError(VmServiceWrapper.java:185)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:633)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:422)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:86)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)

```

Please note: everything works smoothly with previous versions of Idea.

## Steps to Reproduce

Just running the iOS Simulator, using the App as normal and the Simulator freezes and I need to restart it. 

## Version info

[✓] Flutter (Channel stable, 3.3.2, on macOS 14.0 23A344 darwin-arm, locale en-IT)
    • Flutter version 3.3.2 on channel stable at /applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (1 year, 3 months ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✗] Android toolchain - develop for Android devices
    • Android SDK at /Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2023.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10248

[✓] Connected device (3 available)
    • New sim (mobile) • 9F89DF04-9999-47DC-A227-EA43BA3EB4F9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)  • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm
    • Chrome (web)     • chrome                               • web-javascript • Google Chrome 119.0.6045.199
    ! Error: Browsing on the local area network for Apple Watch di S. Ensure the device is unlocked and discoverable via Bluetooth. (code -27)
    ! Error: Browsing on the local area network for iPhone di S. Ensure the device is unlocked and attached with a cable or associated with the same local area network as
      this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by jwren** [comment] 2023-12-15 19:30
Duplicate of https://github.com/flutter/flutter-intellij/issues/7133

**Closed by jwren** 2023-12-15 19:30 UTC
