### ISSUE TITLE
Error can't open devtool in Android Studio

### ISSUE THREAD

**Issue by LeQuangTho** [flutter/flutter-intellij#6151] opened 2022-05-04 07:47 UTC
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

Error can't open devtool in Visual Studio

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

Flutter 2.13.0-0.0.pre.887 • channel master • https://github.com/flutter/flutter.git
Framework • revision b3838eb3de (19 minutes ago) • 2022-05-04 03:24:08 -0400
Engine • revision 84d3539062
Tools • Dart 2.18.0 (build 2.18.0-82.0.dev) • DevTools 2.12.2

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.13.0-0.0.pre.887, on Microsoft Windows [Version 10.0.19044.1645], locale vi-VN)
    • Flutter version 2.13.0-0.0.pre.887 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b3838eb3de (23 minutes ago), 2022-05-04 03:24:08 -0400
    • Engine revision 84d3539062
    • Dart version 2.18.0 (build 2.18.0-82.0.dev)
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Users\Admin\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\211.7628.21.2111.8309675\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32414.318
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Users\Admin\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\211.7628.21.2111.8309675
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.66.2)
    • VS Code at C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1645]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 100.0.4896.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.36

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by AndreyBondarew** [comment] 2022-05-04 11:32
To fix this error on Linux you need to create an alias in /usr/bin/ for /bin/cache/dart-sdk/bin/dart
After that the Flutter inspector works.
In windows, I think you can solve the same.

**Comment by Nightfright** [comment] 2022-05-05 06:44
I have the same problem with Android Studio and Flutter plugin 67.0.1, if I go to plugin homepage and download 66.0.1 and install plugin from disk it works again. So seems latest plugin is broken.

**Comment by stevemessick** [comment] 2022-05-05 17:57
I believe this problem only occurs when using the master channel of the Flutter SDK. You can switch to the stable or beta channel to fix the problem until we can get a patch for the plugin ready.

**Comment by Nightfright** [comment] 2022-05-05 18:39
> I believe this problem only occurs when using the master channel of the Flutter SDK. You can switch to the stable or beta channel to fix the problem until we can get a patch for the plugin ready.

I use stable Android studio and stable flutter and get this problem. so I will hang on with the previous plugin version until there is another release. 👍

**Comment by helin24** [comment] 2022-05-06 20:20
I believe this is a duplicate of https://github.com/flutter/flutter-intellij/issues/6149, so closing this one.

**Closed by helin24** 2022-05-06 20:20 UTC
