### ISSUE TITLE
Android Studio folder named "flutter" creates an empty project folder

### ISSUE THREAD

**Issue by EmpireJones** [flutter/flutter-intellij#2049] opened 2018-04-04 01:05 UTC
## Steps to Reproduce
1. Create a flutter project in a folder called "flutter" using the android studio flutter plugin
2. No files are created

## Version info
Plugin version 23.1.2

## Flutter doctor output
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.2.3, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[!] Connected devices
   ! No devices available

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by jwren** [comment] 2018-04-04 15:41
@stevemessick 

@EmpireJones Do other non-"flutter" tokens work fine, or could this be a duplicate of something like https://github.com/flutter/flutter-intellij/issues/1923: Flutter hangs for new Flutter project if not internet

**Comment by devoncarew** [comment] 2018-04-04 15:55
I think we allow the name, but that causes problems later in the toolchain. We should add it to our list of problematic names (packages that we'll collide with) - in FlutterConstants.FLUTTER_PACKAGE_DEPENDENCIES.

**Comment by stevemessick** [comment] 2018-04-04 16:13
As @devoncarew said, that name is not allowed.
```bash
$ flutter create flutter
Invalid project name: 'flutter' - this will conflict with Flutter package dependencies.
```

**Comment by jwren** [comment] 2018-04-04 16:15
Adding it to the current Milestone.

**Comment by stevemessick** [comment] 2018-04-04 16:17
Oops, I should have done more checking. We already test for disallowed project names. The problem is that if someone edits the location directory it changes the name of the project to whatever the final directory name of the location is. This is a dup of #2035.

**Closed by stevemessick** 2018-04-04 16:17 UTC
Labels: usability
