### ISSUE TITLE
Android Studio Flutter Test Coverage Crash

### ISSUE THREAD

**Issue by NonymousMorlock** [flutter/flutter-intellij#6680] opened 2023-03-14 23:40 UTC
## Steps to Reproduce
1. Right-Click on the test folder in flutter porject
2. Choose "Run 'tests  in test' with Coverage" option
3. Wait for tests to complete and expect coverage reports on your project files

_What I was doing and what went wrong_
I ran the coverage tests on my flutter project and after all tests completed successfully, instead of displaying the coverage results on the project files tree view, it crashed

## Version info

Android Studio `Electric Eel | 2022.1.1 Patch 2` • Flutter plugin `io.flutter 72.1.2` • Dart plugin `221.6103.1`

Flutter 3.7.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 12cb4eb7a0 (13 days ago) • 2023-03-01 10:29:26 -0800
Engine • revision ada363ee93
Tools • Dart 2.19.3 • DevTools 2.20.1

## Exception

null

```
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at io.flutter.run.coverage.LcovInfo.readInto(LcovInfo.java:58)
	at io.flutter.run.coverage.FlutterCoverageRunner.doLoadCoverageData(FlutterCoverageRunner.java:37)
	at io.flutter.run.coverage.FlutterCoverageRunner.loadCoverageData(FlutterCoverageRunner.java:30)
	at com.intellij.coverage.BaseCoverageSuite.loadProjectInfo(BaseCoverageSuite.java:261)
	at com.intellij.coverage.BaseCoverageSuite.getCoverageData(BaseCoverageSuite.java:232)
	at com.intellij.coverage.CoverageSuitesBundle.getCoverageData(CoverageSuitesBundle.java:99)
	at com.intellij.coverage.SimpleCoverageAnnotator.createRenewRequest(SimpleCoverageAnnotator.java:295)
	at com.intellij.coverage.BaseCoverageAnnotator.renewCoverageData(BaseCoverageAnnotator.java:38)
	at com.intellij.coverage.CoverageDataManagerImpl.renewCoverageData(CoverageDataManagerImpl.java:455)
	at com.intellij.coverage.CoverageDataManagerImpl.updateCoverageData(CoverageDataManagerImpl.java:332)
	at com.intellij.coverage.CoverageDataManagerImpl.chooseSuitesBundle(CoverageDataManagerImpl.java:303)
	at com.intellij.coverage.CoverageDataManagerImpl.lambda$coverageGathered$0(CoverageDataManagerImpl.java:392)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by stevemessick** [comment] 2023-03-15 16:39
Please attach your `lcov.info` file, from the `coverage` directory.

**Comment by NonymousMorlock** [comment] 2023-03-17 12:50
it won't let me attach it, says it doesn't support that file type, but here it is

[](https://github.com/NonymousMorlock/error_logs/blob/main/lcov.info)

**Comment by stevemessick** [comment] 2023-03-17 16:04
That link gives me a 404. It probably doesn't matter; I think I know what the problem is.

**Comment by NonymousMorlock** [comment] 2023-03-17 16:10
my bad, I left the repo on private

> That link gives me a 404. It probably doesn't matter; I think I know what the problem is.

**Comment by stevemessick** [comment] 2023-03-17 16:53
Thanks. It's just as I thought. I have a bug that doesn't allow for files with no coverage. It'll be fixed in the next release, at the beginning of April.

**Comment by NonymousMorlock** [comment] 2023-03-17 21:49
Thanks a lot, I'll be anticipating the next release

**Closed** 2023-03-30 17:59 UTC
