### ISSUE TITLE
Flutter hot reload not compatible with new AS Hedgehog UI

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter-intellij#7137] opened 2023-12-13 09:49 UTC
## Steps to Reproduce

- Using latest stable version of Android Studio (Android Studio Hedgehog | 2023.1.1), Flutter plugin version, latest Flutter stable version (3.16.3).
- Enable new UI for AS:
  - IDE and Project settings (top-right settings icon) > Enable New UI
- Run a Flutter app
- Hot reload icon is missing:
![image](https://github.com/flutter/flutter-intellij/assets/2807712/ef331d06-9feb-481b-a2d6-5e6767c6b9cd)

## Version info

```
[✓] Flutter (Channel stable, 3.16.3, on Microsoft Windows [Versi¢n 10.0.22631.2792], locale es-ES)
    • Flutter version 3.16.3 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (7 days ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\crist\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[✓] VS Code (version 1.83.1)
    • VS Code at C:\Users\crist\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 120.0.6099.71
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 120.0.2210.61

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by jwren** [comment] 2023-12-13 20:40
This is a duplicate of https://github.com/flutter/flutter-intellij/issues/6595

**Closed by jwren** 2023-12-13 20:40 UTC
