### ISSUE TITLE
[Bug] flutter Cannot find declaration to go

### ISSUE THREAD

**Issue by AhhhhDong** [flutter/flutter-intellij#6829] opened 2023-07-21 08:20 UTC
## Steps to Reproduce

![bug](https://github.com/flutter/flutter-intellij/assets/19795775/3561b223-727d-42a0-ab25-96729b60757c)

the useless "required" will make this bug...

## Version info

[✓] Flutter (Channel stable, 3.7.0, on macOS 13.4.1 22F770820d darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.7.0 on channel stable at /Users/wjd/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (6 months ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/wjd/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/wjd/Library/Android/sdk
    • Java binary at: /Users/wjd/Library/Java/JavaVirtualMachines/azul-15.0.10/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Zulu15.46+17-CA (build 15.0.10+5-MTS)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9161.14

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.98

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by stevemessick** [comment] 2023-07-21 18:47
I cannot reproduce this problem. It looks like you are not using Dart 3. You might want to upgrade. Even if I could reproduce the problem, it isn't something that can be fixed in the Flutter plugin. "Go to Declaration" is implemented in the Dart plugin.

**Closed by stevemessick** 2023-07-21 18:47 UTC
