### ISSUE TITLE
Create Flutter Application with Sample Application

### ISSUE THREAD

**Issue by mofada** [flutter/flutter-intellij#3492] opened 2019-05-13 15:46 UTC
Hello, when I created the Flutter project, the Sample application option was empty.
![TIM图片20190513234115](https://user-images.githubusercontent.com/22286246/57634998-ecef4400-75d8-11e9-8e98-60717c43f459.png)

## Version info
Android Studio version 
![TIM图片20190513234115](https://user-images.githubusercontent.com/22286246/57635198-48213680-75d9-11e9-9bb1-51a4daeb1617.png)

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.
```
C:\Users\fada>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.475], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by stevemessick** [comment] 2019-05-13 16:28
Duplicate of #3429

Two things to check. Make sure your SDK is at least 1.3.10. If it is, then sometimes restarting the wizard will populate the dropdown.

**Closed by stevemessick** 2019-05-13 16:28 UTC

**Comment by mofada** [comment] 2019-05-14 03:27
@stevemessick my flutter version is 1.5.4
![TIM图片20190513234115](https://user-images.githubusercontent.com/22286246/57668807-34a6b780-763b-11e9-8e20-6497a902d0d9.png)

**Comment by sambitraze** [comment] 2019-09-15 12:15
i dont have a sample content dropdown wat should i do
