### ISSUE TITLE
Android Studio 4.1.2 Built-In Emulator not always available

### ISSUE THREAD

**Issue by ehabelnahas** [flutter/flutter-intellij#5669] opened 2021-07-23 13:45 UTC
Hello,
I have Android Studio 4.1.2, I realised that the studio built-in emulator is available if I open certain ones of my flutter projects, but not available for new ones I created. Also the option to view the emulator from the view menu -> Tool windows -> Emulator is not there !!
(In all projects, I checked from Android Studio Settings "Launch Emulator in Tool Windows" is checked) !!

In all cases I can run my apps on external Android Studio Emulator without problems.

Please check the attached screenshots.

My question is, for sure there is something or some setting controlling Android Studio Emulator to be available or not.
![126169188-06e394c5-d5a1-4e81-933a-45cad2ee674f](https://user-images.githubusercontent.com/43919279/126790961-9e3ddfeb-1091-4dfd-b58b-22c70d102ceb.jpg)
![126169195-9fd7849d-4068-47f8-8b4a-d61dcc2fc6ae](https://user-images.githubusercontent.com/43919279/126790964-ecf5981d-2646-47e7-aab1-0a100696cec0.jpg)

**Comment by stevemessick** [comment] 2021-07-23 16:45
For now, you can work around this problem by using the menu `View > Tool Windows > Emulator` then launching the emulator from the AVD Manager.

See https://github.com/flutter/flutter-intellij/issues/5464#issuecomment-836857485 for instructions to get the Emulator and AVD Manager tool windows listed in the menu.

I'm closing this issue since it is a duplicate of #5464.

**Closed by stevemessick** 2021-07-23 16:45 UTC
