### ISSUE TITLE
IntelliJ 2018.2 constantly re-indexing when Android Support turned on.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter-intellij#2511] opened 2018-07-31 05:29 UTC
Tonight I updated to:

```
IntelliJ IDEA 2018.2 (Community Edition)
Build #IC-182.3684.101, built on July 24, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
```

And IntelliJ now continuously indexes (once a second), causing a lot of things to not work, and interrupting interaction with the UI.

It's similar to https://github.com/flutter/flutter-intellij/issues/1735, but invalidating caches/restarting or even nuking the .idea directory doesn't help. 

**What does help is disabling the "Android Support" plugin** (with the obvious down side. :-)). That seems to fix the problem, but only until I turn it on again.

The log says repeatedly (once per second):
2018-07-30 21:19:54,241 [ 212868]   INFO - pl.ProjectRootManagerComponent - project roots have changed 
2018-07-30 21:19:54,252 [ 212879]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 4ms; general responsiveness: ok; EDT responsiveness: ok 
2018-07-30 21:19:54,285 [ 212912]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 33ms; general responsiveness: ok; EDT responsiveness: ok 

## Version info

```
[✓] Flutter (Channel curve_animations, v0.5.8-pre.184, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.5.8-pre.184 at /Users/gspencer/code/flutter
    • Framework revision 4c4e7554d3 (7 days ago), 2018-07-23 11:25:48 -0700
    • Engine revision af855e063a
    • Dart version 2.0.0-dev.69.4.flutter-08f59e5de3

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/gspencer/Library/Android/sdk
    • Android NDK at /Users/gspencer/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = /Users/gspencer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 26.0.3
    • Dart plugin version 182.3569.4

[✓] Connected devices (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.1.1 (API 25) (emulator)

• No issues found!
```

Here's my current log file: 
[idea.log](https://github.com/flutter/flutter-intellij/files/2243867/idea.log)

**Comment by alexander-doroshko** [comment] 2018-07-31 16:47
The problem is probably caused by [this issue](https://youtrack.jetbrains.com/issue/IDEA-196167). Could you please try [IntelliJ IDEA 2018.2.1 RC](https://confluence.jetbrains.com/display/IDEADEV/IDEA+2018.2+EAP) where the problem should be fixed? (You may switch to EAP update channel in Preferences | Appearance & Behavior | System Settings | Updates and check for updates).

**Comment by jwren** [comment] 2018-07-31 18:52
@stevemessick for FYI

Reopen if you suspect that you are hitting something else.

**Comment by devoncarew** [comment] 2018-07-31 19:00
@jwren, this issue is severe enough that we may want to consider keeping it open until the fix rolls into the stable version of 2018.2, and / or updating our known issues list on the readme and mentioning something in the release notes.

**Comment by devoncarew** [comment] 2018-08-03 16:51
I updated the readme to reference this issue (https://github.com/flutter/flutter-intellij/commit/109e9f3f0a9a931cdf0ea7c4f2558418b7179e14); we expect the fix to be in the stable version of 2018.2 ~next week.

**Comment by rvowles** [comment] 2018-08-04 08:11
It is worth keeping this issue open so people like me can more find it and find a resolution. It was driving me bonkers :-)

**Comment by devoncarew** [comment] 2018-08-07 20:45
IntelliJ IDEA 2018.2.1 is out, and this does look fixed.

**Closed by devoncarew** 2018-08-07 20:45 UTC
