### ISSUE TITLE
[Infra] Built artifacts are not for Windows

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter-intellij#6650] opened 2023-02-28 13:21 UTC
Which cannot be run on Windows since those binaries are not executable (not Win32 applications).

![image](https://user-images.githubusercontent.com/15884415/221866128-aed1aaff-87c9-4773-a718-3ee026db339d.png)
![image](https://user-images.githubusercontent.com/15884415/221866440-6e6d15cb-9a90-4a1b-bd2e-87c9f3939bcf.png)

Can we download artifacts for Windows if applicable?

**Comment by stevemessick** [comment] 2023-02-28 16:31
The `flutter-intellij/artifacts` directory is only used for compilation. Currently, we use it for building the plugin (`bin/plugin make`, which has no OS dependencies) and for compiling the plugin in order to run the debugger from IntelliJ (`bin/plugin setup` causes the correct version to be unpacked, and is automatically run after every build).

> Can we download artifacts for Windows if applicable?

We generally use the Linux version because those tend to be the smallest downloads. Sometimes, I use the Mac version, but that requires some special handling. You can use the Windows version if you want to locally. You'd need to repackage it as a zip file, though, or modify the `plugin` tool to unpack a windows executable (PRs welcome).

**Comment by AlexV525** [comment] 2023-02-28 22:45
> Sometimes, I use the Mac version, but that requires some special handling. You can use the Windows version if you want to locally. You'd need to repackage it as a zip file, though, or modify the `plugin` tool to unpack a windows executable (PRs welcome).

Could you suggest with more specific steps and modifications to do that?

**Comment by stevemessick** [comment] 2023-02-28 23:05
Sorry, I don't know much about Windows.

Thinking about it a bit more, I think this is working as intended. The content of `artifacts` is not intended to be executed.

**Comment by AlexV525** [comment] 2023-03-01 01:24
> Sorry, I don't know much about Windows.

How about with macOS, so I can take it as a reference.

> Thinking about it a bit more, I think this is working as intended. The content of `artifacts` is not intended to be executed.

The issue happened when I was executing `runIde`, which tried to use the Java in the built artifacts. So I think it's intended to be executed.

**Comment by stevemessick** [comment] 2023-03-01 16:13
> The issue happened when I was executing runIde, which tried to use the Java in the built artifacts. So I think it's intended to be executed.

Check your Project Structure. When Gradle imports the module it usually sets the Compiler Output path incorrectly. It should be inherited, not specified, for ALL modules. If you see a group named `flutter-studio` then you can remove all its child modules if there are any problems.

<img width="583" alt="Screenshot 2023-03-01 at 8 03 59 AM" src="https://user-images.githubusercontent.com/8518285/222195183-c8048f6a-da52-47d0-af43-f16895a88b06.png">

Since I use the Linux artifacts I can confirm that they are not intended to be executed.

I thought this bug was fixed but it is keeping me from using `runIde` now: https://github.com/JetBrains/gradle-intellij-plugin/issues/1246, or at least the same symptoms appear.

You should be able to avoid that problem by not pulling in #6496, which I committed yesterday.

**Comment by stevemessick** [comment] 2023-03-01 21:54
Actually, after looking into things a bit more, you are correct. If we're doing `runIde` the path to the IDE is what's used. We'll have to find another way to configure it. I think we can add the IDE path to `gradle.properties` and use it when we need to run. For building the plugin, nothing needs to change. For your local Windows setup, you can just provide the path to the IDE you use. For the unit tests on the bots, I think I'll change to run on Linux, since the Linux IDE is easy to install. It might also be possible to stop setting `intellij.localPath` in the Gradle script, and just rely on having the correct IDE on the PATH.

I'm not going to get to this right away. I need to investigate a P1 bug first.

**Comment by stevemessick** [comment] 2023-03-15 16:31
Rather than making artifacts runnable I changed it to eliminate the need for artifacts. The build script now uses the standard artifacts provided by the IntelliJ plugin for Gradle. This was done in #6681.

I have not tested it on Windows. If you have git for Windows (aka gitbash) installed, it might work.

**Closed by stevemessick** 2023-03-15 16:31 UTC
