### ISSUE TITLE
'Bad state: No element' exception from the InspectorPanel

### ISSUE THREAD

**Issue by fmatosqg** [flutter/flutter-intellij#2248] opened 2018-05-15 03:33 UTC
---

## What happened

Debugging issue with hot reload. Console panel is stuck at "Performing hot reload", and I was fiddling with the flutter inspector panel.

![image](https://user-images.githubusercontent.com/5360753/40035235-2e0c939c-5844-11e8-8f0e-3f339e47a05f.png)

If I stop app and launch again everything goes back to normal.

## Version information
OS X Sierra.
Android Studio `3.1.1` • Flutter plugin `io.flutter 24.0.1` • Dart plugin `173.4700`

Flutter 0.3.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 44b7e7d3f4 (4 weeks ago) • 2018-04-20 01:02:44 -0700
Engine • revision 09d05a3891
Tools • Dart 2.0.0-dev.48.0.flutter-fe606f890b

## Exception

java.util.concurrent.CompletionException: java.io.IOException: unexpected response: {"id":9,"error":"Bad state: No element"}

```
com.intellij.openapi.diagnostic.Logger$EmptyThrowable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:140)
	at io.flutter.view.InspectorPanel.lambda$recomputeTreeRoot$5(InspectorPanel.java:574)
	at io.flutter.inspector.InspectorService$ObjectGroup.lambda$null$67(InspectorService.java:868)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by devoncarew** [comment] 2018-05-23 21:06
Possible dupe of https://github.com/flutter/flutter-intellij/issues/2240

**Comment by jacob314** [comment] 2018-06-25 16:53
Dupe of 2240. The dartvm fix for this issue has landed in the flutter master branch.

**Closed by jacob314** 2018-06-25 16:53 UTC
Labels: bug
