### ISSUE TITLE
Stop button appears to hang UI

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter-intellij#349] opened 2016-10-20 11:16 UTC
- Start a minimal flutter app using the iOS simulator
- Press stop

The stop button appears depressed for multiple seconds before the UI responds, giving the appearance that the UI has hung.

**Comment by pq** [comment] 2016-10-20 13:19
cc @stevemessick

**Comment by stevemessick** [comment] 2016-10-20 13:36
@lukechurch Which version of the flutter plugin are you using? How far along had the flutter process gotten before you clicked Stop? More specifically, did flutter print "Application running" to the console or was it still initializing?

**Comment by lukechurch** [comment] 2016-10-20 13:43
I was running 0.1 when this occurred. yes, the app was running before I hit stop. 

I've now updated to 0.1.2 - the stop button now appears to be immediate :) however the app doesn't appear to stop, it just keeps running.

**Comment by stevemessick** [comment] 2016-10-20 14:59
That's a bug in the daemon: https://github.com/flutter/flutter/issues/6208

I think we can close this one.

**Comment by pq** [comment] 2016-10-20 15:36
Assigning to @mit-mit to capture in known issues before closing.

**Comment by stevemessick** [comment] 2016-10-20 19:37
Actually, this is intended behavior. Once the flutter daemon (or flutter tool) starts an app in release mode (i.e. Run button launch) then it is done with the app. It cannot stop it.

What we really should do here is disable the Stop and Pause buttons (along with Hot Reload, Restart, Observatory).

@mit-mit There are a few known issues regarding buttons and keystrokes that should be disabled but are not yet getting disabled. I believe all of them are blocked on flutter/flutter#6400 and will not be fixed before the release. That includes #332 and #334 and this one. I think it would be good to add a paragraph to the known issues doc informing customers that they need to wait a bit after clicking a button, or pressing a keystroke that does the same thing as clicking a button, in order to give flutter time to finish the action before attempting something else. Just say we know that's not ideal and are working on it.

**Comment by stevemessick** [comment] 2016-10-20 19:38
@devoncarew Anything to add?

**Comment by lukechurch** [comment] 2016-10-21 06:02
@stevemessick 
> What we really should do here is disable the Stop and Pause buttons (along with Hot Reload, Restart, Observatory). 

If we do that, can we make the hover text explain why? I.e. that if the developer wants these functions, they should launch in dev mode?

**Comment by pq** [comment] 2016-10-21 13:04
> If we do that, can we make the hover text explain why? I.e. that if the developer wants these functions, they should launch in dev mode?

👍

**Comment by devoncarew** [comment] 2016-10-21 23:19
@stevemessick I'm working on a fix to allow the IDE to stop an app started in release mode. We should determine the best behavior for the run and debug buttons as well - I started an issue to discuss that. I also hope to make some progress on https://github.com/flutter/flutter/issues/6400 as well, in terms of improving the events that flutter tools creates that an IDE could key off to know more about the state of a launch.

**Comment by mit-mit** [comment] 2016-10-31 08:27
I discussed this with Eric, and we arrived at the following:

1. Map the Debug action to Debug mode, i.e. `flutter run`
1. Map the Run action to Release mode, i.e. `flutter run --release`
1. Disable the Run action when the current target device is a simulator, and state in the tooltip that release mode currently only works on physical devices

**Comment by devoncarew** [comment] 2016-11-07 18:28
Obsolete once we have https://github.com/flutter/flutter-intellij/issues/407.

**Closed by devoncarew** 2016-11-07 18:28 UTC
Labels: needs-known-issue-docs, usability
