### ISSUE TITLE
Flutter inspector doesn't select running app by default.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter-intellij#2194] opened 2018-05-03 18:25 UTC
## Steps to Reproduce
In the below screen shot of a newly created flutter app (using `flutter create`), I had just clicked the "Run" icon, and the app built and ran.

Notice that the Flutter inspector says "no running applications".  There is an active application, so that's not accurate, but also, it should switch to the active application when it adds a tab to the inspector. Clicking on the "Nexus 6P" tab does switch to the inspector for that run.

I do have "Open flutter inspector at app launch" turned off, but that's only because I hate it re-configuring my UI every time I launch an app.  I don't want it opening spontaneously, but if I have the inspector open, it should switch its tab to any running app that I just started (and at the least shouldn't be wrong about not having any apps running).

![screenshot from 2018-05-03 11-17-43](https://user-images.githubusercontent.com/8867023/39595293-e324a092-4ec3-11e8-86b8-157ed0cce8b0.png)

## Version info
```
[✓] Flutter (Channel chip_perf, v0.3.6-pre.103, on Linux, locale en_US.UTF-8)
    • Flutter version 0.3.6-pre.103 at /usr/local/google/home/gspencer/code/flutter
    • Framework revision fb1628789b (19 hours ago), 2018-05-02 16:30:13 -0700
    • Engine revision ae0d3a5536
    • Dart version 2.0.0-dev.52.0.flutter-2765fcf2ae

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at /usr/local/google/home/gspencer/Android/Sdk
    • Android NDK at /usr/local/google/home/gspencer/Android/Sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.2
    • ANDROID_HOME = /usr/local/google/home/gspencer/Android/Sdk
    • Java binary at: /opt/android-studio-with-blaze-3.0/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at /opt/intellij-ce-2017.3
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700

[✓] Connected devices (1 available)
    • Nexus 6P • 84B7N15A07007628 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by devoncarew** [comment] 2018-05-04 05:04
I _believe_ you're hitting https://github.com/flutter/flutter-intellij/issues/2029; that shows up in Android Studio 3.1 (and likely 2017.3, which AS 3.1 is based on).

 In the screen shot above, there should be a small blank tab to the left of the `Nexus 6P` one.

You can fix this by using 2018.1; we could also put a workaround in for 2017.3/AS 3.1.

Thanks for the report! I'm going to close as a dupe of https://github.com/flutter/flutter-intellij/issues/2029.

**Closed by devoncarew** 2018-05-04 05:04 UTC
