### ISSUE TITLE
Unable to rename a field.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter-intellij#1465] opened 2017-11-02 18:12 UTC
## Steps to Reproduce
Select a member getter name, hit F6 to rename.

Then I get this.  It happens for renames of public member functions and getter/setters, but not for private member variables.  It happens every time for the ones that it doesn't work for.

![screenshot from 2017-11-02 10 42 54](https://user-images.githubusercontent.com/8867023/32342493-bec62e54-bfbd-11e7-8a13-8ddaa91a1cff.png)

It's likely that this is in the Dart plugin for IntelliJ or the analysis server, but I thought I'd start here in case there are interactions with Flutter.

I've tried "Invalidate Caches and Restart", and I've exited IntelliJ and made sure that no flutter or dart daemons are left running, and then restarted it.  Neither one helped.

I was using the Community Edition, and I recently switched from the Ultimate Edition, and imported my prefs from there for CE.

## Version info
```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel unknown)
    • Flutter at /usr/local/google/home/gspencer/code/flutter
    • Framework revision 7784f2a5ec (3 weeks ago), 2017-10-10 16:44:56 -0700
    • Engine revision 88cf09ffe6
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /usr/local/google/home/gspencer/Android/Sdk
    • Platform android-26, build-tools 26.0.1
    • Java binary at: /opt/android-studio-with-blaze-2.3/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio-with-blaze-2.3
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Flutter plugin version 18.2
    • Dart plugin version 171.4694.29

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • Flutter plugin version 18.2
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • Nexus 5 • 06adc85c0069a8ad • android-arm • Android 6.0.1 (API 23)
```

**Comment by devoncarew** [comment] 2017-11-02 18:26
Thanks for the report!

@gspencergoog, can you try forcing dart to a later version, and re-verify that this still happens? That would be editing `bin/internal/dart-sdk.version` to something like 2.0.0-dev.6.0, then running bin/internal/update_dart_sdk.sh.

@scheglov, do you mind taking a look at this?

**Comment by scheglov** [comment] 2017-11-02 18:56
OK, I can reproduce this on Flutter code when rename `Container.debugFillProperties` (just a random public method).

**Comment by gspencergoog** [comment] 2017-11-02 19:25
Updating the Dart sdk to `2.0.0-dev.6.0` fixes the problem.

**Comment by scheglov** [comment] 2017-11-02 22:03
The update should not fix anything, because there was a bug in Analysis Server :-)

https://dart-review.googlesource.com/c/sdk/+/18426 should fix it.

**Comment by devoncarew** [comment] 2017-11-03 20:29
Closing this - the fix should land with the next roll of the dart sdk into flutter.

**Closed by devoncarew** 2017-11-03 20:29 UTC
