### ISSUE TITLE
[Android Studio] Flutter inspector jump to source is not working

### ISSUE THREAD

**Issue by wtrungvu** [flutter/flutter-intellij#3937] opened 2019-10-04 13:03 UTC
![Screen Shot 2019-10-04 at 19 58 23](https://user-images.githubusercontent.com/33633989/66209614-eb3a3000-e6e1-11e9-8f9e-d84390ff8faf.png)
![Screen Shot 2019-10-04 at 19 57 49](https://user-images.githubusercontent.com/33633989/66209620-ef664d80-e6e1-11e9-95d3-f01ac72e04c0.png)

**Comment by jacob314** [comment] 2019-10-09 16:08
This is a new problem.

**Comment by abduqodirov** [comment] 2020-05-26 12:36
Isn't fixed yet?

**Comment by Tusar-a4aero** [comment] 2020-07-11 04:44
is there any solution???

**Comment by ehsan-mrt** [comment] 2020-07-19 13:08
You should move your project into the default android studio projects folder. I'm using linux and in my case the folder name is "/home/napo/AndroidStudioProjects". In windows, it's probably something like "C:\Users\$username\AndroidStudioProjects" if you haven't changed the default configuration.

**Comment by ehsan-mrt** [comment] 2020-07-19 19:07
You should move your project to the default android studio project folder. For linux it's "/home/USER/AndroidStudioProjects/". It works for me.

**Comment by jwren** [comment] 2024-05-15 08:20
This issue is now obsolete, marking as closed.  Please re-open if it is still reproducible.

**Closed by jwren** 2024-05-15 08:20 UTC
