### ISSUE TITLE
Autoformat causes an exception

### ISSUE THREAD

**Issue by alekskuzmin** [flutter/flutter-intellij#3462] opened 2019-05-07 09:33 UTC
## Steps to Reproduce

Pressed Ctrl + L to reformat the code in a freshly open project

## Version information

Android Studio `3.4` • Flutter plugin `io.flutter 35.2.1` • Dart plugin `183.6270`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.IndexOutOfBoundsException: Index out of range: 5373
	at com.intellij.util.text.ImmutableText.findLeaf(ImmutableText.java:234)
	at com.intellij.util.text.ImmutableText.charAt(ImmutableText.java:226)
	at com.intellij.openapi.editor.impl.DocumentImpl$1.charAt(DocumentImpl.java:101)
	at io.flutter.editor.WidgetIndentsHighlightingPass.computeLocation(WidgetIndentsHighlightingPass.java:682)
	at io.flutter.editor.WidgetIndentsHighlightingPass.buildWidgetDescriptors(WidgetIndentsHighlightingPass.java:709)
	at io.flutter.editor.WidgetIndentsHighlightingPass.buildWidgetDescriptors(WidgetIndentsHighlightingPass.java:742)
	at io.flutter.editor.WidgetIndentsHighlightingPass.buildWidgetDescriptors(WidgetIndentsHighlightingPass.java:742)
	at io.flutter.editor.WidgetIndentsHighlightingPass.buildWidgetDescriptors(WidgetIndentsHighlightingPass.java:742)
	at io.flutter.editor.WidgetIndentsHighlightingPass.buildWidgetDescriptors(WidgetIndentsHighlightingPass.java:742)
	at io.flutter.editor.WidgetIndentsHighlightingPass.setOutline(WidgetIndentsHighlightingPass.java:547)
	at io.flutter.editor.WidgetIndentsHighlightingPass.run(WidgetIndentsHighlightingPass.java:523)
	at io.flutter.editor.WidgetIndentsHighlightingPassFactory.runWidgetIndentsPass(WidgetIndentsHighlightingPassFactory.java:299)
	at io.flutter.editor.WidgetIndentsHighlightingPassFactory.lambda$createHighlightingPass$4(WidgetIndentsHighlightingPassFactory.java:270)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by jacob314** [comment] 2019-05-07 15:22
If you have a source code file that reproduces the issue that would be very helpful.

**Comment by alekskuzmin** [comment] 2019-05-07 15:27
Sure, please provide some contact information, I can send it to you.

**Comment by jacob314** [comment] 2019-05-07 15:41
Unfortunately the repro would need to be included on the github bug for me to be able to view it. Let me try creating a custom intellij plugin build with the likely fix and then you can test if the fix works.

**Comment by jacob314** [comment] 2019-05-07 18:11
[flutter-intellij.zip](https://github.com/flutter/flutter-intellij/files/3153976/flutter-intellij.zip)
Please try this IntelliJ plugin build for Android Studio. I believe it fixes the issue along with related cases where guides could look strange after a large code edit.

**Comment by harounhajem** [comment] 2019-05-07 18:18
We should merge our [issues,](https://github.com/flutter/flutter-intellij/issues/3455) I've now got the same exception 
![bild](https://user-images.githubusercontent.com/17148955/57322958-1144af80-7105-11e9-8dd6-fd3f151b421a.png)

**Comment by alekskuzmin** [comment] 2019-05-07 20:19
> 
> 
> [flutter-intellij.zip](https://github.com/flutter/flutter-intellij/files/3153976/flutter-intellij.zip)
> Please try this IntelliJ plugin build for Android Studio. I believe it fixes the issue along with related cases where guides could look strange after a large code edit.

A different exception appears:

## Version information

Android Studio `3.4` • Flutter plugin `io.flutter SNAPSHOT` • Dart plugin `183.6270`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.Throwable: Incorrect offsets: startOffset=6142, endOffset=6143, text length=6000
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:137)
	at com.intellij.openapi.editor.impl.DocumentImpl.createRangeMarker(DocumentImpl.java:523)
	at com.intellij.openapi.editor.Document.createRangeMarker(Document.java:243)
	at io.flutter.editor.OutlineLocation.track(OutlineLocation.java:101)
	at io.flutter.editor.WidgetIndentGuideDescriptor.trackLocations(WidgetIndentGuideDescriptor.java:69)
	at io.flutter.editor.WidgetIndentsHighlightingPass$WidgetCustomHighlighterRenderer.<init>(WidgetIndentsHighlightingPass.java:111)
	at io.flutter.editor.WidgetIndentsHighlightingPass.createHighlighter(WidgetIndentsHighlightingPass.java:772)
	at io.flutter.editor.WidgetIndentsHighlightingPass.lambda$doApplyIndentInformationToEditor$2(WidgetIndentsHighlightingPass.java:659)
	at com.intellij.util.DocumentUtil.executeInBulk(DocumentUtil.java:48)
	at io.flutter.editor.WidgetIndentsHighlightingPass.doApplyIndentInformationToEditor(WidgetIndentsHighlightingPass.java:657)
	at io.flutter.editor.WidgetIndentsHighlightingPass.setOutline(WidgetIndentsHighlightingPass.java:555)
	at io.flutter.editor.WidgetIndentsHighlightingPass.run(WidgetIndentsHighlightingPass.java:526)
	at io.flutter.editor.WidgetIndentsHighlightingPassFactory.runWidgetIndentsPass(WidgetIndentsHighlightingPassFactory.java:307)
	at io.flutter.editor.WidgetIndentsHighlightingPassFactory.lambda$createHighlightingPass$4(WidgetIndentsHighlightingPassFactory.java:272)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by jacob314** [comment] 2019-05-07 20:34
I really wish I could see a repro of this issue to understand why the outline we are generating is going past the end of the document.
Here's a new build that should fix your issue. Let me know whether the UI guides look right with this fix or if it seems like some indent guides are in the wrong location.
[flutter-intellij.zip](https://github.com/flutter/flutter-intellij/files/3154460/flutter-intellij.zip)

**Comment by alekskuzmin** [comment] 2019-05-07 20:44
Seems like the exception is resolved but some indent guides look weird:
![изображение](https://user-images.githubusercontent.com/6849426/57331735-a356b300-7119-11e9-85bc-25ad7b275ac7.png)

**Comment by jacob314** [comment] 2019-05-07 21:04
Ah. Your code is using very non-standard formatting.
What you are seeing is actually intended.
Notice that `child: Column` is indented 2 more spaces than its properties which I assume isn't what you intended. Once you fix your indentation the guides will look good.  You can either indent content until the guides are to the left of their content or use dartfmt.
I would suggest adding trailing commas after every closing `)` in your build method and then run dartfmt. That should make your indenting look great without requiring any manual work on your part.

**Comment by alekskuzmin** [comment] 2019-05-07 21:12
Thanks, I'll try your suggestions, but this is already the result of the automatic formatting (didn't expect it to rely on commas that much).

**Comment by jacob314** [comment] 2019-05-07 21:14
<img width="296" alt="Screen Shot 2019-05-07 at 2 13 20 PM" src="https://user-images.githubusercontent.com/1226812/57333660-500d4200-70d2-11e9-981c-eb357c854e29.png">
Make sure you format with dartfmt instead of the IntelliJ code formatter which is much more limited in what it will try to do.

**Comment by alekskuzmin** [comment] 2019-05-07 21:20
> 
> 
> <img alt="Screen Shot 2019-05-07 at 2 13 20 PM" width="296" src="https://user-images.githubusercontent.com/1226812/57333660-500d4200-70d2-11e9-981c-eb357c854e29.png">
> Make sure you format with dartfmt instead of the IntelliJ code formatter which is much more limited in what it will try to do.

Thanks! Also no exception after reformatting with dartfmt.

**Comment by jacob314** [comment] 2019-05-07 21:23
How do the guides look now that your code has gone through dartfmt?

**Comment by alekskuzmin** [comment] 2019-05-07 21:25
![изображение](https://user-images.githubusercontent.com/6849426/57334191-54ac1780-711f-11e9-886a-3152fb7c30b8.png)
Everything looks fine.

**Comment by jacob314** [comment] 2019-05-08 16:22
Fix has landed in master and will be available in the next bug fix release.

**Closed by jacob314** 2019-05-08 16:22 UTC
Labels: bug
