### ISSUE TITLE
Exception in Plugin Flutter (79.1.3)

### ISSUE THREAD

**Issue by Johannes-Schiel** [flutter/flutter-intellij#7427] opened 2024-05-14 18:46 UTC
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

When i start my app, the run start but i dont see anything in the debug window an i get the following IDE Internal Errors

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.flutter.run.OpenDevToolsAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.flutter]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:200)

```
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.flutter.run.OpenDevToolsAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.flutter]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:200)
```

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

```
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale en-DE)
    • Flutter version 3.19.6 on channel stable at /opt/homebrew/Caskroom/flutter/3.19.6/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (4 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/johannesschiel/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 79.0.3
    • Dart plugin version 241.15989.9

[✓] Connected device (4 available)            
    • iPhone 15 Pro (mobile)     • A2B27C33-5200-47A2-AA76-756B3980DA7C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by helin24** [comment] 2024-05-14 18:47
Duplicate of #7330 

This should be fixed in the next release.

**Comment by Johannes-Schiel** [comment] 2024-05-14 18:48
Ah ok, when is this planned?

**Comment by jwren** [comment] 2024-05-14 19:02
I am pushing out a point release in a few hours that has this fix and a bunch of other fixes, it will be `79.1`, I will mark it as hidden for Iguana (2023.2) and Jellyfish (2023.3) in the JB marketplace, but marked as available for Koala.

**Comment by Johannes-Schiel** [comment] 2024-05-15 07:38
@jwren there was a update notification for a new version but i still get the same error?

Plugin Version 79.1.3

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.flutter.run.FlutterPopFrameAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.flutter]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:200)

```

**Comment by helin24** [comment] 2024-05-15 22:55
It looks like I missed updating this one. Reopening

**Comment by Johannes-Schiel** [comment] 2024-05-16 04:56
Thx, if you need more information i will try to help :)

**Comment by Johannes-Schiel** [comment] 2024-05-21 07:53
Are there any kind of informaitons when the fix is merged an a new version is released?

**Comment by helin24** [comment] 2024-05-21 15:44
I can update here when we release a new version with the fix

**Closed** 2024-05-21 17:49 UTC

**Comment by Johannes-Schiel** [comment] 2024-05-25 07:27
@helin24 sadly i still have this issue, but only when i use the "new" Flutter version. On one of my notebooks i have Flutter 3.19.5 and the same Plugin & IDE Version on this pc everything works fine. On my other notebook i habe flutter 3.22.1 there i cant see the console when i run the app.


<img width="1104" alt="Screenshot 2024-05-25 at 08 58 52" src="https://github.com/flutter/flutter-intellij/assets/23320610/473f5a80-c08a-446b-9491-e6d4622ce87a">

```
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale en-DE)
    • Flutter version 3.22.1 on channel stable at /opt/homebrew/Caskroom/flutter/3.22.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (3 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/johannesschiel/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 79.2.3
    • Dart plugin version 241.17502

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (5 available)
    • iPhone 15 Pro Max (mobile)      • ED7BC28F-3CA5-4D56-A4AF-9ED53322F69D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 125.0.6422.76

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
Do you or someone have an idear what the problem could be? Because i did not get any error message or something. Also i uninstalled IntelliJ and Flutter on that pc and installed the version displayed in the flutter doctor results with the same error. Currently on both notebooks MacOs in Version 14.5 (23F79) is running and both notebooks use M1 Pro.

sry for the comment again but the problem must have a souse :D

**Comment by helin24** [comment] 2024-05-28 15:48
Ah okay, sorry - I was focused on the error messages you were receiving before and not on the fact that you have nothing in the debug console! (which seems unrelated to the error messages you were getting)

Can you send me your logs to helinx@google.com? If you go to Help > Show log in finder, that should take you to a file called `idea.log`. Maybe there will be some additional info in there about why there's no output, as I'm unable to reproduce the problem on my system.

**Comment by Johannes-Schiel** [comment] 2024-05-29 13:09
@helin24 i send you an email with the log file, thx for the help. If i can help with more informations just ask :)

**Comment by helin24** [comment] 2024-05-29 19:02
Nothing looks wrong to me in the logs, but I'm wondering what setting you have for verbose logging now - is it on or off? In Settings > Languages & Frameworks: Flutter > Enable verbose logging.

If you switch it to the other state, do you get a different result?

**Comment by Johannes-Schiel** [comment] 2024-05-30 00:21
Hello sadly no, even if i disable everything this dont work. I also have nothing else on this mac (i use this device to test new versions for your team) so there is not much that can create problem 😅

**Comment by helin24** [comment] 2025-09-26 21:58
Sorry to have dropped checking on this issue. @Johannes-Schiel is this still a problem for you? We could potentially add some logging to check why the debug window is blank for you.
